### ISSUE TITLE
Gas load on pro server doesn't load

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1002]
In the LES test gas (https://moses.energytransitionmodel.com/testing_grounds/480) the gas load doesn't load. After scaling down an ETM scenario I opened this as a LES, used the default topology and market model, agreed with the technologies and then tried to view the gas load. But it doesn't load.

**Comment by antw** [comment]
@Sanne512 I fixed these LES' for you. It's the same issue we had last time (#980). I'll try again to reproduce this and figure out why it happens.

**Comment by Sanne512** [comment]
The gas load loads now :)
