### ISSUE TITLE
Deficit caused by pipes or stations?

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1005]
Is it possible to see if deficits are caused by the pipes or by the stations at a certain pressure level? 

(CC @JeroenvdLogt )

**Comment by ChaelKruip** [comment]
> Is it possible to see if deficits are caused by the pipes or by the stations at a certain pressure level?

Because pipes don't have capacities, they cannot be the limiting factor. Pipes don't have capacities because it depends on their topology if this would be limiting and we don't model that.
