### ISSUE TITLE
Are deficits included in the business case? 

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1006]
When there's a deficit the customer doesn't receive their gas. In practice this influences the business case, but with the electricity business cases if a station is congested this isn't included in the business case. How does this work with gas? 

(CC @JeroenvdLogt )

**Comment by ChaelKruip** [comment]
> How does this work with gas?

This works similarly with gas. Deficits should be dealt with by building more capacity or removing demand. To put a price on deficits would be very complex as the commodity price is never going to be the limiting factor. Consumers might be compensated for 'blackouts' in a variety of manners. 

We can think about including a new measure like 'number of blackout events' to include in the market models but this requires careful thinking. For example: if a station is congested for 2 time-steps, is that 1 or 2 congestion events? Another one: if a station is congested, how do we determine which customers are affected?
