### ISSUE TITLE
Apply button doesn't work

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1007]
Different day, same LES, different problem. 

In the LES Test gas https://moses.energytransitionmodel.com/testing_grounds/480/edit , when you edit the Gas asset list and click on Apply it doesn't apply and save the changes. I'm not sure if it's connected to the last problem.

**Comment by Sanne512** [comment]
CC @JeroenvdLogt

**Comment by grdw** [comment]
Could you be more specific, do you do anything out of the ordinary or edited a specific field, removed a row, added a row?

Steps I performed
1. Opened your LES
2. Changed the quantity of the last OS to 0.0952
3. Hit apply
4. Refreshed the page to see if it changed (and it did)
5. Put the quanity back to 0.095

**Comment by Sanne512** [comment]
On the first rule i changed the pressure level from 0,1 bar to 40 and hit apply. It didn't werk.

**Comment by grdw** [comment]
I see what is happening here. The gas asset list sorts itself on the pressure level. So if you change the pressure level of a certain gas asset from 0.1 bar to 40 bar the gas asset itself (the row) moves all the way to the bottom. Could you validate that that is what's happening?

This is a bit of hard to detect, so maybe we should give the changed rows (or cells) a yellow background color? @ChaelKruip 

Also there's a different problem happening here. When changing the pressure level of a certain gas asset the default selected technology can become blank, resulting in an incomplete calculation. I'll look into why that is happening .. 😕

**Comment by Sanne512** [comment]
I just retraced my steps and this is what happened: 

1. I change the pressure level of the first line from 0.1 bar to 40 bar
2. Change the quantity to GOS
3. Change the stakeholder to producer
4. Click on apply

Then it discards all changes...

**Comment by grdw** [comment]
I looked into it again but I can't seem to exactly reproduce this. What does happen is as described when refreshing the page the GOS connector appears at the bottom of the list instead of the top where you might expect it to be.

**Comment by ChaelKruip** [comment]
> I looked into it again but I can't seem to exactly reproduce this. What does happen - is as described: when refreshing the page the GOS connector appears at the bottom of the list instead of the top where you might expect it to be.

This is still very confusing but not a bug as such. Let's open a new issue for this.
