### ISSUE TITLE
Efficiency of neighbourhood battery

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1011]
When you change the COP/efficiency of the neighbourhood battery does this affect the calculations?

**Comment by ChaelKruip** [comment]
@antw can you answer this?

**Comment by antw** [comment]
Efficiency and loss is not currently modelled in any battery technology, including the neighbourhood battery. Currently, the only technologies to model CoP are "Heat pumps for space heating" and "Heat pumps for hot water".

I'm curious where you see an option to change the neighbourhood battery CoP/efficiency?

**Comment by Sanne512** [comment]
On the page where you can edit the technologies of the LES, if you click Toggle advanced there is a field with COP/efficiency which is automatically set to 1.0

![etmoses cop efficiency neighbourhood battery](https://cloud.githubusercontent.com/assets/17741822/15772004/dd2ce180-296e-11e6-8634-cc3512e14aa0.PNG)

**Comment by ChaelKruip** [comment]
Closing as this question has been answered. There already is a ticket for adding losses: https://github.com/quintel/etmoses/issues/805
