### ISSUE TITLE
[Airbrake] [Staging] comparison of Float with Float failed

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1016]
**Airbrake error:** [#3713](https://quintel.airbrake.io/projects/111227/groups/1697790612560393713)
**Airbrake project:** ETMoses

**Error type:** `ArgumentError`
**Error message:** `` comparison of Float with Float failed ``
**Where:** `testing_grounds#data`
**Occurred at:** May 31, 2016 12:05:53 UTC
**First seen at:** May 31, 2016 12:05:53 UTC
**Occurrences:** 1 (1 since last deploy on May 30, 2016 14:52:13 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/143/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/143/data.json)
**File:** `[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb:25:in each
[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb:25:in max_by
[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb:25:in block in downsample
[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb:21:in each
```

**Comment by antw** [comment]
Super old LES. Probably returning a `NaN` somewhere due to the old-style (standalone) heat pump which has zero units and no buffer volume.

I'll look into it at some point, but I think this is low priority, and not likely to be an issue for any LES created in the past few months.
