### ISSUE TITLE
Typical numbers for central heat network needed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1018]
The central heat network is subdivided into two non-existing (in the ETM) technologies:

* households_heat_network_connection_steam_hot_water (excess heat/must-run)
* households_heat_network_connection_steam_hot_water (dispatchable)

Investment costs, technical lifetime and yearly O&M cost  for these two 'ghost converters' are not easy to determine. One approach could be to take all must-run technologies that feed the central network in the ETM and make a weighted average of these attributes. This turns out to be very involved and likely leads to little insight for the user.

I propose to use the following typical values for Investment costs, technical lifetime and yearly O&M cost for these technologies (as found in the ETM):

## Must-run part of the central heat network
Because this part of the heat network is 'must-run', the most sensible way to quantify cost is *per MWh heat produced*. So, the suggested defaults are:

* investment costs: 800 [EUR/MWh]
* yearly (fixed) operation and maintenance costs: 25 [EUR/MWh]
* technical lifetime: 30 [year]
* marginal costs: 0.0 [EUR/MWh]   \(we assume that this part is free)

## Dispatchable part of the central heat network
Because this part of the heat network is dispatchable, the most sensible way to quantify cost is *per MW installed output capacity*. So, the suggested defaults are:

* investment costs: 100 [kEUR/MW]
* yearly (fixed) operation and maintenance costs: 1 [kEUR/MW]
* technical lifetime: 30 [year]
* marginal costs: 30 [EUR/MWh]

Including @jorisberkhout @AlexanderWirtz @grdw

**Comment by AlexanderWirtz** [comment]
I have no idea what these costs are. @ChaelKruip what are these costs based on?

**Comment by ChaelKruip** [comment]
> I have no idea what these costs are. @ChaelKruip what are these costs based on?

These numbers are very rough and based on the typical costs of the technologies included in the ETM which feed the heat network. 

@Sanne512 can you ask around if these numbers are satisfactory as the defaults? If you can find more accurate numbers, please let me know.

**Comment by Sanne512** [comment]
> yearly (fixed) operation and maintenance costs: 1 [kEUR/MW]<

Shoudn't this be 1 [kEUR/MW_h_]

And I'm asking around. When I know more I'll update you.

**Comment by ChaelKruip** [comment]
> Shoudn't this be 1 [kEUR/MW_h_]

For dispatchable plants it is customary to express the *fixed* O&M costs in EUR/MW. We don't take the variable O&M costs into account currently in ETMoses.

**Comment by Sanne512** [comment]
@ChaelKruip Is this issue still relevant? If so, are there still specific numbers you need from Alliander, besides the issue addressed in https://github.com/quintel/etmoses/issues/1097?

**Comment by ChaelKruip** [comment]
> @ChaelKruip Is this issue still relevant? If so, are there still specific numbers you need from Alliander, besides the issue addressed in #1097?

No. Closing this.
