### ISSUE TITLE
Gas load never loads?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1021]
To reproduce:
1. https://moses.energytransitionmodel.com/testing_grounds/480/gas_load
2. it takes on my laptop more than 40 seconds to load.

![Uploading image.png…]()

**Comment by ChaelKruip** [comment]
I don't know why this would take so long. Is this because the gas-load calculation also triggers the electricity load calculation?

Possibly related to https://github.com/quintel/etmoses/issues/1017

Assigning @antw

**Comment by antw** [comment]
> Is this because the gas-load calculation also triggers the electricity load calculation?

This is correct. #1017 is related.

**Comment by antw** [comment]
I think I'll close this in favour of #1017. Being able to reuse the cached loads is likely the only way we'll improve this. The gas calculation itself is reasonably fast.
