### ISSUE TITLE
Business cases sends many requests to the server?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1022]
![image](https://cloud.githubusercontent.com/assets/104830/15743532/834e10a6-28c6-11e6-8375-0b3abc2afbb6.png)

**Comment by ChaelKruip** [comment]
Assigning @antw

**Comment by antw** [comment]
That's expected. The business case is being calculated and [JS is polling](https://github.com/quintel/etmoses/blob/c42b09907fc22680ba54f6f93ac8731007a0b8c2/app/assets/javascripts/poller.js) to find out if it has finished. Once the server returns the calculated business case, the requests will stop.
