### ISSUE TITLE
X-axis labels of electricity all of a sudden reduced to just 7?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1023]
![image](https://cloud.githubusercontent.com/assets/104830/15743544/a71ed1f0-28c6-11e6-865b-f344d565f4c2.png)

**Comment by dennisschoenmakers** [comment]
https://moses.energytransitionmodel.com/testing_grounds/480

**Comment by ChaelKruip** [comment]
@dennisschoenmakers what did you do to get this effect?

Assigning @grdw

**Comment by dennisschoenmakers** [comment]
1. press 'gas load' tab
2. wait until everything is loaded
3. press 'load' again
4. voila!

![image](https://cloud.githubusercontent.com/assets/104830/15744196/d766b6bc-28ca-11e6-8308-2834a6f93ca9.png)

**Comment by dennisschoenmakers** [comment]
Also, then, it is broken when you select another period: 😭 

![image](https://cloud.githubusercontent.com/assets/104830/15744222/feaa486a-28ca-11e6-8190-1f617c8f6730.png)

**Comment by dennisschoenmakers** [comment]
I also got it with another LES when I didn't even touch the gas load:

![image](https://cloud.githubusercontent.com/assets/104830/15744387/f2a28dce-28cb-11e6-9da6-289a8c86135b.png)

**Comment by grdw** [comment]
Can reproduce locally. Will see what this Javascript sorcery is...

**Comment by grdw** [comment]
I think it somehow switches resolution from `high` to `low` when you toggle tabs. Don't know why exactly yet.

**Comment by grdw** [comment]
Allright, I won't go into much Javascript detail here but the problem was that the Object that kept all the view options was in the `prototype` of the `D3Chart` object and not in an instance of the Object itself. Yeah... gotta love Javscript. 🙀
