### ISSUE TITLE
Business cases take forever to load

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1025]
https://moses.energytransitionmodel.com/testing_grounds/427/business_cases/191

It takes longer than I need to write this ticket and then some... 😒 

![image](https://cloud.githubusercontent.com/assets/104830/15743759/0497ba12-28c8-11e6-872a-9cde17f7efd7.png)

**Comment by ChaelKruip** [comment]
Assigning @antw

**Comment by antw** [comment]
Closing for the more general issue #1031.
