### ISSUE TITLE
Weekly load cache sometimes has one or more missing nodes

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1028]
**Airbrake error:** [#7998](https://quintel.airbrake.io/projects/111227/groups/1699243736076627998)
**Airbrake project:** ETMoses

**Error type:** `Errno::ENOENT`
**Error message:** `` No such file or directory @ rb_file_s_mtime - /var/www/etmoses/releases/20160531130127/tmp/networks/production/476/basic/electricity/49a08c0e397826d795e50f9a6a16b08f35708bd965875a2b22d9bb1db5e25bc6.load.current_week.tmp ``
**Where:** `testing_grounds#data`
**Occurred at:** Jun 02, 2016 12:13:01 UTC
**First seen at:** Jun 02, 2016 12:13:01 UTC
**Occurrences:** 1 (1 since last deploy on May 31, 2016 13:02:06 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/476/data.json](https://moses.energytransitionmodel.com/testing_grounds/476/data.json)
**File:** `[PROJECT_ROOT]/app/services/network_cache/validator.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/network_cache/validator.rb:43:in mtime
[PROJECT_ROOT]/app/services/network_cache/validator.rb:43:in block (2 levels) in cache_time
[PROJECT_ROOT]/app/services/network_cache/validator.rb:42:in map
[PROJECT_ROOT]/app/services/network_cache/validator.rb:42:in block in cache_time
```

**Comment by grdw** [comment]
I just removed the cache for this LES ...
