### ISSUE TITLE
Download curve renders an empty file

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1030]
Reproduce:
1. https://moses.energytransitionmodel.com/testing_grounds/476
2. Click options > download curve

![image](https://cloud.githubusercontent.com/assets/104830/15744455/565cbc4a-28cc-11e6-9e18-35d1197b6c5f.png)

**Comment by antw** [comment]
Almost certainly related to #1028. Probably a cache issue.

**Comment by antw** [comment]
This is still an issue. Might need to be updated to include a heat curve also:

<img width="325" alt="screen shot 2016-06-30 at 14 25 08" src="https://cloud.githubusercontent.com/assets/4383/16488011/85ad38a4-3ece-11e6-9dfd-d397b8557d07.png">
