### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1038]
What's the definition of a clone, for example what does a cloned market model mean?

**Comment by ChaelKruip** [comment]
> What's the definition of a clone, for example what does a cloned market model mean?

If you 'save as' a LES, the new LES consists of copies or *clones* of the topology,  market model, technology matrix etc. This is to ensure that if you edit those clones, the original (parent) LES does not change.

In the future, I would like to simplify the above by storing it as one entity. So, there would be no separate market model and topology but only one thing, the LES.

**Comment by Sanne512** [comment]
> In the future, I would like to simplify the above by storing it as one entity. So, there would be no separate market model and topology but only one thing, the LES.

I'm including this in our wish list for the next sprint.

**Comment by antw** [comment]
#839
