### ISSUE TITLE
Numbers not readable when they are large

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1039]
Source: https://beta-moses.energytransitionmodel.com/testing_grounds/509/gas_load

![image](https://cloud.githubusercontent.com/assets/104830/15772369/0b4069e6-2971-11e6-97ea-43e6a0056c71.png)

**Comment by grdw** [comment]
I'm going to draw a line in the sand at 1.000.000.000. I think we should switch to scientific notation in order for these numbers to become somewhat readable. I remember there being an issue about this problem already...

**Comment by dennisschoenmakers** [comment]
> I'm going to draw a line in the sand at 1.000.000.000. I think we should switch to scientific notation in order for these numbers to become somewhat readable. I remember there being an issue about this problem already...

Couldn't we reproduce the solution that we utilize in etmodel? I like what we did there.

**Comment by grdw** [comment]
https://github.com/quintel/etmoses/issues/139

**Comment by dennisschoenmakers** [comment]
@grdw and @ChaelKruip can we pick this up? Yesterday, a chart was unreadable. (Yes, I am quoting GOT)

**Comment by antw** [comment]
> #139 or the fast way

I prefer #139; scientific notation is ugly. The "modern" ETModel solution to this is [Quantity](https://github.com/quintel/etmodel/blob/d5136eae5183e433e2ba7f4c0881167471ce044b/app/assets/javascripts/lib/models/quantity.coffee), and while it would need some changes (to replace calls to ETModel's `Metric`) it would likely get us 90% of the way there...

**Comment by grdw** [comment]
![screen shot 2016-07-20 at 16 40 01](https://cloud.githubusercontent.com/assets/2676542/16990538/a0946014-4e98-11e6-9b69-2453a4c716dc.png)

First attempt is looking good. 😄 This is a LES with (500_000_000) EV's.

**Comment by grdw** [comment]
Charts to fix still
- [ ] Yearly gas load chart
- [ ] Gas load chart
- [ ] Heat load chart
- [ ] Clean up what is there to clean

**Comment by ChaelKruip** [comment]
What is the status of this @grdw?

**Comment by grdw** [comment]
This is already fixed and deployed. I did found a strange bug though when testing out #1386 but that's fixed in that PR (I also think that that bug is only relevant because of the changes that were made for that PR). I'll close this issue therefor.
