### ISSUE TITLE
Date picker is cut off too low?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1041]
I selected the 'stacked' option:

![image](https://cloud.githubusercontent.com/assets/104830/15772537/e78e46b6-2971-11e6-8139-4afb983cb782.png)

**Comment by grdw** [comment]
This is only in the stacked view. I thought it was happening because the domain isn't changing properly but that's not it. It's calculated correctly but it doesn't quiet 'fit' in the height of the box... hmm, I need to look into it a bit better before I can fix this.

**Comment by grdw** [comment]
Fixed by this line: https://github.com/quintel/etmoses/blob/master/app/assets/javascripts/les/topology_load_charts/d3_load_chart.js#L283

**Comment by dennisschoenmakers** [comment]
:+1:

Sent from my iPhone

On 15 jun. 2016, at 16:21, Gerard <notifications@github.com> wrote:

Closed #1041 <https://github.com/quintel/etmoses/issues/1041>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quintel/etmoses/issues/1041#event-693310071>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAGZfq30jYhDb8RbqP04qzEUnzlKHJ6cks5qMApwgaJpZM4ItSsh>
.
