### ISSUE TITLE
When capacity is selected it does not show up in the chart

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1042]
![image](https://cloud.githubusercontent.com/assets/104830/15772578/2753c19a-2972-11e6-8ba8-cf99f604533e.png)

source: https://beta-moses.energytransitionmodel.com/testing_grounds/509

**Comment by dennisschoenmakers** [comment]
Red line seems to be at 0?

**Comment by grdw** [comment]
It's 51.. but considering your highest load to be 6.000.000 it looks as it is 0.

**Comment by dennisschoenmakers** [comment]
> It's 51 or 17.25 depending on the end-point, but considering your highest load to be 6.000.000 it looks as it is 0.

Fair enough!
