### ISSUE TITLE
Date picker doesn't change when you change legend

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1043]
It start of well, but when you change the legend, the date picker does **not** change. That's a bit unfortunate, because you loose track of 'where you are'.

![image](https://cloud.githubusercontent.com/assets/104830/15772689/e24765ce-2972-11e6-8a9c-455e7dfc2790.png)

**Comment by ChaelKruip** [comment]
I can't reproduce this. @antw @grdw is this still relevant?

**Comment by antw** [comment]
I believe what @dennisschoenmakers means is that if you hide one of the series in the main chart, that series is still shown in the smaller "brush chart". I guess that a hidden series should not be visible there.

**Comment by ChaelKruip** [comment]
> I believe what @dennisschoenmakers means is that if you hide one of the series in the main chart, that series is still shown in the smaller "brush chart". I guess that a hidden series should not be visible there.

Right! Thanks for pointing that out @antw!

**Comment by grdw** [comment]
Fixed as by PR https://github.com/quintel/etmoses/pull/1088
