### ISSUE TITLE
Gas load is not consistent between weeks and sometimes hangs

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1044]
Unfortunately, I don't have the screenshots to 'prove' it, but this is what I did:

I changed the strategies for https://beta-moses.energytransitionmodel.com/testing_grounds/509

![image](https://cloud.githubusercontent.com/assets/104830/15773123/86c94e3a-2975-11e6-87f7-705ae765f0d3.png)

I go to the next week

There the gas load seems to be **very** different and inconsistent with the other week.

![image](https://cloud.githubusercontent.com/assets/104830/15773150/a1ef66cc-2975-11e6-86f9-cdc3e1d1bd4a.png)

I back to a week earlier

I get console log errors:

![image](https://cloud.githubusercontent.com/assets/104830/15773195/e3f90352-2975-11e6-9301-b2d29273f85c.png)

Then I hit refresh:

It keeps hanging, nothing happens for > 2 minutes

**Comment by dennisschoenmakers** [comment]
Also observed on live:

![image](https://cloud.githubusercontent.com/assets/104830/15773610/31a64a9a-2978-11e6-8e00-14698336f687.png)

next week:

![image](https://cloud.githubusercontent.com/assets/104830/15773619/3e17f1a2-2978-11e6-92f4-346e6d5cb077.png)

Going back one week:

![image](https://cloud.githubusercontent.com/assets/104830/15773628/4a3e2582-2978-11e6-8e47-cea7b40294da.png)

Console log error 

![image](https://cloud.githubusercontent.com/assets/104830/15773644/5de77a8e-2978-11e6-9511-3dfd626a8829.png)

**Comment by antw** [comment]
This appears to be a cache issue; the numbers coming out of the gas calculation are fine, and the bug is not present locally when the cache is disabled.

I'm investigating...

**Comment by grdw** [comment]
I'm also watching with this issue... I enabled caching and started testing:
I don't see the errors in the log though (in Firefox), what I do see. Is when you select the first week:

<img width="617" alt="screen shot 2016-06-03 at 11 33 40" src="https://cloud.githubusercontent.com/assets/2676542/15774884/0f26680e-297f-11e6-978c-0985a26f8052.png">

Than select a random week in the future:
<img width="600" alt="screen shot 2016-06-03 at 11 34 21" src="https://cloud.githubusercontent.com/assets/2676542/15774914/3a62b6ee-297f-11e6-8503-91c218e356ee.png">

And than go back again to the first week:

<img width="620" alt="screen shot 2016-06-03 at 11 34 53" src="https://cloud.githubusercontent.com/assets/2676542/15774918/43293014-297f-11e6-9f63-3ddbf697dd63.png">

It's messed up.

It's only the case if you calculate loose weeks. If you first calculate the full year and than start to switch weeks - all is fine.

**Comment by grdw** [comment]
[Relevant line](https://github.com/quintel/etmoses/blob/master/app/services/network_cache/fetcher.rb#L21) ?

**Comment by antw** [comment]
@grdw Those screenshots are interesting. It kind-of looks like the "Gas (with strategies)" load lags behind by one request. The second screenshot still has the gas-strategies load from the first request, and the third screenshot has the load from the second. It's harder to tell if the same is true of electricity.

**Comment by grdw** [comment]
Wait I'm starting to think that it's related to strategies. So the featured cache ... because the normal load is actually correct but the strategies cache is the one you saw before. So it looks like the cache for strategies is not clearing correctly?
