### ISSUE TITLE
Another console error.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1045]
![image](https://cloud.githubusercontent.com/assets/104830/15773404/fa6f1382-2976-11e6-9d80-200262c05c3a.png)

**Comment by grdw** [comment]
[Related](https://stackoverflow.com/questions/22608564/neterr-incomplete-chunked-encoding-in-chrome-only)

**Comment by grdw** [comment]
How do you reproduce this bug?
