### ISSUE TITLE
How do I determine the costs of a heat technology in the source list?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1047]
Is it:

````ruby
(total_initial_investment + om_costs_per_year + marginal_costs) * units * distance 
````

Or is it a bit more complex than my initial thought?

**Comment by ChaelKruip** [comment]
> Or is it a bit more complex than my initial thought?

Yes 😄 

## For dispatchable sources
 
The `depreciation_costs` (what is shown on the diagonal of the business case matrix) is defined as follows:
```
depreciation_costs = initial_investment / technical_lifetime + om_costs_per_year
```
where the initial_investment is defined as:
```
initial_investment = total_initial_investment_per_mw * heat_capacity_per_unit * units
```
and the 
```
om_costs_per_year = om_costs_per_year_per_mw * heat_capacity_per_unit * units
```

## For must-run sources
 
The `depreciation_costs` (what is shown on the diagonal of the business case matrix) is **again** defined as follows:
```
depreciation_costs = initial_investment / technical_lifetime + om_costs_per_year
```
where the initial_investment is defined as:
```
initial_investment = total_initial_investment_per_mwh * heat_production_in_mwh
```
and the 
```
om_costs_per_year = om_costs_per_year_per_mwh * heat_production_in_mwh
```

**Comment by grdw** [comment]
Great. So why do we import `marginal_costs`?

**Comment by ChaelKruip** [comment]
> Great. So why do we import marginal_costs?

The marginal costs are there to help the user (or the calculator) to assign priorities. The cheapest source should come first. 

Also, if the user would like to create a new `transaction` in the Market Model the marginal costs provides a good typical number for what is would cost to produce a kWh of heat.

**Comment by grdw** [comment]
> for what it would cost to produce a kWh of heat.

So it's not really used in any of the business case/financial calculations but we import it nontheless. Will it be used in any of the calculations in the future though? Or is this like said, merely to check if the `marginal_costs` are a good price for a kWh of heat in a Markt Model transaction? 

If so, it's a bit weird that the `marginal_costs` are present in the `heat_sources` list. Couldn't we import the `marginal_costs`, save them with the heat sources. And in the front-end don't display any of the `marginal_costs` to the user (or as a disabled field) and whenever somebody adds a transaction (related to a kWh of heat) to the market model, determine a default based from the average (?) of marginal costs found in the heat sources table. And we could also repeat this trick for `gas` and `electricity` I guess.

**Comment by ChaelKruip** [comment]
@grdw the `marginal_heat_costs` method is available in ETE now. You can use that instead of the `marginal_costs`.

**Comment by ChaelKruip** [comment]
@grdw can this be closed?

**Comment by grdw** [comment]
Yes it can.
