### ISSUE TITLE
The heat infra assets should be editable by the user

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1049]
As described in https://github.com/quintel/etmoses/issues/962, the cost of heat infrastructure is separated into 
* Primary (transmission) infrastructure. This contains one or more pipes from the source to the secondary network.
* Secondary infrastructure. This contains the distribution pipes and the connections to the households including heat exchangers.

I think we should have a page for heat infra similar to the assets page for gas infra:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/15889220/8b81f56e-2d6a-11e6-862d-f9205a2ead99.png)

There should be separate tables for primary and secondary infra though (as they have different requirements, see below).

**Comment by ChaelKruip** [comment]
## Primary infrastructure

When specifying the sources, the user has already submitted a 'distance' to the LES as shown in this (indicative) table:
<img width="796" alt="20150513_etmoses_sprint3_v7_pptx" src="https://cloud.githubusercontent.com/assets/1303760/15249787/ccd1af80-1921-11e6-8f12-9ffefdfda6bd.png">

These distances need to be multiplied by costs (per km) for the pipe between LES and source:

The cost of primary infrastructure consists of the sum of
* depreciation costs: investment_cost_per_km * distance / lifetime
* yearly O&M costs: yearly_om_costs_per_km * distance

I think it makes sense to create the following type of table:

| type of pipe| distance [km] \(from source table)|associated with source|  investment [kEUR/km]|O&M [EUR/y/km]| lifetime [y]| cost per year [EUR]|stakeholder|
|---|---|---|---|---|---|---|---|
|25cm_X_200| 10 | gas CHP | 20 | 200| 50 | 4200|system operator|

**Comment by ChaelKruip** [comment]
## Secondary infrastructure

The cost of secondary infrastructure depends largely on location and type of house. We have chosen the following combinations of these two characteristics:

- rural_detached
- rural_terraced
- village_detached
- village_terraced
- village_apartment
- city_terraced
- city_apartment
- city_flat

Because the secondary infra depends on the number of connections (see https://github.com/quintel/etmoses/issues/970), 
I imagine we could use sliders (sorry about the alignment) to determine how to divide the connection over the types:
![20150608_etmoses_sprint3_v10_pptx](https://cloud.githubusercontent.com/assets/1303760/15890557/7eddcf80-2d70-11e6-8dfb-41febab3151f.png)

**Comment by ChaelKruip** [comment]
At second thought, the table shown above should be extended a bit to give the user the ability to change attributes for the costs:

| type |  investment [kEUR] | O&M [EUR/y] | lifetime [y] | stakeholder | units |
|---|---|---|---|---|---|
| rural_detached | 7 |  20 | 50 | system operator | 20 |
| village_terraced | 8 |  30 | 50 | system operator | 30 |

**Comment by grdw** [comment]
None of these attributes need to be imported from et-engine, right?
And to follow up on that question, what is the default primary and secondary infrastructure? Is this going to be generated? If so: how exactly? 

I'm now at a stage where I created all the views/models/controllers and necessary STI to make this a bit more smoother.

**Comment by ChaelKruip** [comment]
> None of these attributes need to be imported from et-engine, right?

True!

> what is the default primary and secondary infrastructure?

Excellent question! I think we have to make up something until @Sanne512 tells us more.

**Comment by ChaelKruip** [comment]
> what is the default primary and secondary infrastructure?

I propose to use `city_apartment` as the default for all connections. @Sanne512 let me know if you disagree.
