### ISSUE TITLE
New measures and a new stakeholder need to be added for heat

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1051]
The new stakeholder: 
* heat_producer

The new measures:
* number_of_connections_to_heat_network
* kWh_of_heat_consumed
* kWh_of_heat_produced (only available for heat_producer)

**Comment by antw** [comment]
I have pushed these, but the measure for heat production is temporarily disabled. In isolation, the code works and passes the tests, but in a real network the measure never gets applied due to the lack of a "Heat Network" node in the electricity network. I'll deal with setting the correct heat buffering volume first, then come up with a workaround for this.

In the short-term, you can work around this by measuring heat *consumption* on the endpoints. Of course this won't work once buffering and loss are enabled.

**Comment by antw** [comment]
> kWh_of_heat_produced (only available for heat_producer)

Is it genuinely useful to have a measure which says "stakeholder one" pays "stakeholder two" for heat produced by technologies owned by "stakeholder three"? Or does it suffice to price the heat by the marginal cost of the producer, and show that as a cost for the associated stakeholder (much like other costs which aren't explicitly defined in the market model)?

The reason I ask is that this measure does not fit well at all with the way the market model currently works, which measures things happening at the level of *nodes* and not technologies. It is not impossible to change this, but I think I have to be reassured that it really *is* worth rewriting half the market model code to do it...

**Comment by ChaelKruip** [comment]
> Is it genuinely useful to have a measure which says "stakeholder one" pays "stakeholder two" for heat produced by technologies owned by "stakeholder three"? 

I'm afraid so yes. We need to be able to give subsidies to a stakeholder based on its heat production for example. 

> The reason I ask is that this measure does not fit well at all with the way the market model currently works, which measures things happening at the level of nodes and not technologies.

Could we not add some 'virtual nodes' to the topology: one for every source of heat? 

We could even show them in the topology and make them clickable at some point (show the load of that source):
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16831288/7a18d9a4-49a4-11e6-987e-3e9362573543.png)

**Comment by antw** [comment]
> I'm afraid so yes. We need to be able to give subsidies to a stakeholder based on its heat production for example.

Thanks for that, I'll get to work on the changes.

> Could we not add some 'virtual nodes' to the topology: one for every source of heat?

While our graph library is perfectly capable of that, much of Moses is predicated on the network being a tree. Orphaned nodes will likely cause problems elsewhere, and would require extra book-keeping during the calculation (to duplicate the load of the heat producers onto these nodes).
