### ISSUE TITLE
User should be able to select carriers in load chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1056]
This button is 'frozen'/'disabled but I don't think it should be:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/15929111/3cfac9a2-2e4b-11e6-9d72-383db1a102f5.png)

**Comment by grdw** [comment]
I think you mentioned this before. But you can toggle them with the legend items.

**Comment by ChaelKruip** [comment]
> So maybe we should hide it when a user is in the total view?

👍
