### ISSUE TITLE
After clicking "save all and view LES" without editing anything, the LES fails to calculate

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1064]
[This LES](https://moses.energytransitionmodel.com/testing_grounds/482) just stopped working... 😭

**Comment by antw** [comment]
Weekly caching bug *again*. I don't understand how it's still happening after af9810fb. 😧

**Comment by ChaelKruip** [comment]
It seems to happen if I save stuff without actually changing anything...

**Comment by ChaelKruip** [comment]
👍 👍
