### ISSUE TITLE
Adding a district heating connection gives an error

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1065]
In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/521/edit):
<img width="1412" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15991788/996e89b6-30bd-11e6-8fb8-1ee7ed339289.png">

**Comment by grdw** [comment]
I am aware of this problem. The PR #1061 should fix this.
