### ISSUE TITLE
Heat sources should be able to belong to stakeholders that are not in the electricity topology

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1068]
Now only these stakeholders are available:
<img width="1202" alt="screen shot 2016-06-12 at 21 39 54" src="https://cloud.githubusercontent.com/assets/1303760/15993431/675297a0-30e6-11e6-81d8-099c1683a095.png">

**Comment by grdw** [comment]
Fixed by: https://github.com/quintel/etmoses/commit/854b582ffd04553d4cf1e1dd7185351d5dbbc9d7#diff-36d5c149182cfc95143456f5662e7bf2R61
