### ISSUE TITLE
Numbers in sources list should be consistent

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1069]
Some costs are divided by 1000 for all but for the central network:
<img width="1149" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15993471/a4be2c48-30e7-11e6-896b-382ff6fbb47f.png">

Also, some numbers are not rounded to 1 digit after the decimal.

**Comment by grdw** [comment]
This is already fixed

![screen shot 2016-08-22 at 10 58 51](https://cloud.githubusercontent.com/assets/2676542/17849085/7002609e-6857-11e6-9fa4-5a1770d0d9f1.png)
