### ISSUE TITLE
[Airbrake] [Production] key not found: "default"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1070]
**Airbrake error:** [#2786](https://quintel.airbrake.io/projects/111227/groups/1706751260057122786)
**Airbrake project:** ETMoses

**Error type:** `KeyError`
**Error message:** `` key not found: "default" ``
**Where:** `testing_grounds#data`
**Occurred at:** Jun 12, 2016 20:49:03 UTC
**First seen at:** Jun 12, 2016 20:49:03 UTC
**Occurrences:** 1 (1 since last deploy on Jun 12, 2016 15:59:55 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/366/data.json](https://moses.energytransitionmodel.com/testing_grounds/366/data.json)
**File:** `[PROJECT_ROOT]/app/models/calculation/technology_load.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:82:in fetch
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:82:in block in comps_for
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each_with_object
```

**Comment by grdw** [comment]
Water heating buffers dind't have profile's assinged to them. Added them manually.
