### ISSUE TITLE
[Airbrake] [Staging] undefined method `marginal_heat_costs' for #<InstalledHeatSource:0x007f674ad3f500>

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1078]
**Airbrake error:** [#4669](https://quintel.airbrake.io/projects/111227/groups/1707317994170334669)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `marginal_heat_costs' for #<InstalledHeatSource:0x007f674ad3f500> ``
**Where:** `testing_grounds#edit`
**Occurred at:** Jun 13, 2016 15:35:01 UTC
**First seen at:** Jun 13, 2016 15:35:01 UTC
**Occurrences:** 1 (1 since last deploy on Jun 13, 2016 15:27:46 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/528/edit](https://beta-moses.energytransitionmodel.com/testing_grounds/528/edit)
**File:** `[PROJECT_ROOT]/app/views/heat_source_lists/_must_run_table.html.haml`

**Backtrace:**
```
[PROJECT_ROOT]/app/views/heat_source_lists/_must_run_table.html.haml:45:in block in _app_views_heat_source_lists__must_run_table_html_haml___4099859659731822186_70040831311340
[PROJECT_ROOT]/app/views/heat_source_lists/_must_run_table.html.haml:19:in each
[PROJECT_ROOT]/app/views/heat_source_lists/_must_run_table.html.haml:19:in _app_views_heat_source_lists__must_run_table_html_haml___4099859659731822186_70040831311340
[GEM_ROOT]/gems/actionview-4.1.8/lib/action_view/template.rb:145:in block in render
```

**Comment by grdw** [comment]
Fixed by: b584d44
