### ISSUE TITLE
Is the capacity of dispatchable central heat network every non-zero?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1079]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16013905/7c9bc51a-318f-11e6-80a2-2e5c0fc97ff2.png)

**Comment by ChaelKruip** [comment]
This could point to a bug...

**Comment by grdw** [comment]
Well this currently had to do with rounding ... 

The GQL's return: 

0.00033 for central heat network must-run production and
0.0533 for central heat network disp. capacity

for scenario 515515 on beta.

**Comment by ChaelKruip** [comment]
> The GQL's return:

Which GQL's are used for the capacity per unit and the number of units for the dispatchable part?

**Comment by antw** [comment]
> Which GQL's are used for the capacity per unit and the number of units for the dispatchable part?

* [Capacity](https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_dispatchable_capacity_for_households_from_central_heat_network.gql)

I can't find where the number of units is set. Yesterday I found that number of units [wasn't set for the must-run](https://github.com/quintel/etmoses/commit/9233b00290ba5612eb5efa9f4f016d1596e933db), perhaps that is also true for the dispatchable? I'll investigate.

**Comment by antw** [comment]
I can't find any sign of the number of units being set for the dispatchable. Is it meant to be set to 1.0 by the app?

**Comment by ChaelKruip** [comment]
> Yesterday I found that number of units wasn't set for the must-run,

For the must-runs, the only thing that matters is the yearly production. Number of units or capacity per unit are irrelevant and often unknown. Think of it as a swimming pool that has some excess heat which can be used in the neighbouring houses. Nobody knows what the capacity or units of the swimming pool is but rather how much heat is coming from there every year.

For the dispatchables, the installed capacity (capacity_per_unit * number_of_units) *is* relevant, however. You want to know how much can the thing is expected to make if needed. For the dispatchable part of the central heat network, it is less clear how to 'split' installed capacity into number_of_units and capacity_per_unit as it represents a [group of technologies](https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_dispatchable_sources_central_heat_network.gql).

I suggest we use the [gquery for the total installed capacity of the dispatchable part of the central heat network](https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_dispatchable_capacity_for_households_from_central_heat_network.gql) to set the 'capacity_per_unit' and set 'number_of_units' to 1.0.

**Comment by antw** [comment]
> For the must-runs, the only thing that matters is the yearly production. Number of units or capacity per unit are irrelevant and often unknown.

Number of units does matter, albeit [only internally](https://github.com/quintel/etmoses/blob/bfe224ed9ac1e98b98eb7e099cc49bc8b21e7f45/app/models/installed_heat_source.rb#L57). It's set to 1.0 anyway, so it should make no difference to the end-user.

> I suggest we use the gquery for the total installed capacity of the dispatchable part of the central heat network to set the 'capacity_per_unit' and set 'number_of_units' to 1.0.

Done.
