### ISSUE TITLE
Load chart is only showing zeros for solar_pv profiles in 'whole year' view

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#108]
I created a new testing ground with only Residential PV panels. In the 'whole year' view I see a flat profile load chart with only zeros. @ChaelKruip explained that this is due to the fact that the load chart displays the maximum value for every 12 hours to limit the number of datapoints. Since the PV panels introduce negative loads, this approach returns only zeros in this case.

I would suggest to replace the maximum value in 12 hours by the largest deviation from zeros in these 12 hours, which should cover the case for the PV panels.

**Comment by antw** [comment]
Oh, good catch! I'll get this fixed.

**Comment by jorisberkhout** [comment]
:+1:
