### ISSUE TITLE
Chart colors for a converter should be specified in the technologies YML

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1080]

**Comment by grdw** [comment]
@ChaelKruip if you could find some time to think about which technology should need what color, that'd be great. You can edit the colors in the yml files on the branch: `issues/technologies-yml-should-hold-the-color`.

**Comment by ChaelKruip** [comment]
Current colours for electricity technologies:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16043283/322d5254-323f-11e6-9802-22e3dee298b8.png)
For gas technologies:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16043303/4bcf70a2-323f-11e6-9b23-db438768d96b.png)
Heat network:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16043319/5d1a3cac-323f-11e6-8b20-f170359d8a98.png)

**Comment by grdw** [comment]
I like it - color wise - but I think we're stumbling accross the same problem with the merit order hourly supply chart of ETModel. That because there are that many colors, the meaning of the color is a bit gone.

**Comment by ChaelKruip** [comment]
> I like it - color wise - but I think we're stumbling accross the same problem with the merit order hourly supply chart of ETModel. That because there are that many colors, the meaning of the color is a bit gone.

These are the *current* colours (the ones you picked!) 😆 
I intend to bring this set back to fewer colours with easily distinguishable shades of brightness.

**Comment by ChaelKruip** [comment]
For gas I have found these:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16045360/5f704ec0-3248-11e6-83d3-c8f1ce2fde64.png)

**Comment by ChaelKruip** [comment]
For heat:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16045472/d9402950-3248-11e6-9485-b68f4a296e2e.png)

**Comment by grdw** [comment]
> These are the current colours (the ones you picked!)

I didn't really picked them by hand in all honesty 😶 
But I like the improved colors! 👍

**Comment by ChaelKruip** [comment]
And for electricity:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16046452/d1e0f9a6-324c-11e6-88d6-521095f0a4b2.png)
