### ISSUE TITLE
It should not be possible to add a micro CHP to the technology matrix

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1084]
This is not implemented but occurs in the list of technologies.

**Comment by ChaelKruip** [comment]
Same for fuel cells

**Comment by ChaelKruip** [comment]
I'm also confused about the option to add three "parts" of the hybrid heat pump (I understand that you need an electric and a gas-part):
![screen shot 2016-06-14 at 14 27 17](https://cloud.githubusercontent.com/assets/1303760/16042712/52337554-323c-11e6-8c71-e06fc63b3b54.png)

**Comment by grdw** [comment]
hmm.. turns out that all invisble technologies appear in the list ...
