### ISSUE TITLE
[Airbrake] [Production] undefined method `symbolize_keys' for #<Array:0x007f1c6ab5e3d8>

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1086]
**Airbrake error:** [#0031](https://quintel.airbrake.io/projects/111227/groups/1707957968137860031)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `symbolize_keys' for #<Array:0x007f1c6ab5e3d8> ``
**Where:** `topologies#update`
**Occurred at:** Jun 14, 2016 12:46:31 UTC
**First seen at:** Jun 14, 2016 12:46:31 UTC
**Occurrences:** 1 (1 since last deploy on Jun 12, 2016 15:59:55 UTC)

**URL:** [https://moses.energytransitionmodel.com/topologies/506](https://moses.energytransitionmodel.com/topologies/506)
**File:** `[PROJECT_ROOT]/app/models/topology.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/topology.rb:39:in map
[PROJECT_ROOT]/app/models/topology.rb:39:in each_node
[PROJECT_ROOT]/app/models/topology.rb:74:in validate_node_names
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in block in make_lambda
```

**Comment by grdw** [comment]
I'm closing this. It looks as though somebody made a typo in the edit screen.
Topology edit form needs to be improved: https://github.com/quintel/etmoses/issues/596
