### ISSUE TITLE
The business case table should show a breakdown of the number in each cell on mouse-over

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1090]
Right now it is very difficult to see what the origin of outcomes of the cost calculation are.

**Comment by ChaelKruip** [comment]
I think that we should support mouse-over break down of numbers for the business case summary shown in the results section:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17971773/81c1faf6-6adc-11e6-8064-ac44a770115c.png)
Perhaps we can also support mouse-over break down for the matrix in the edit section.

**Comment by ChaelKruip** [comment]
I am still unsure to what level of detail we break down the costs. My first guess would be to identify:

* Depreciation costs of [carrier] infra
* O&M costs of [carrier] infra
* Depreciation costs of district heat sources
* O&M costs of district heat sources
* Result of every relevant row (transaction) of the Market Model

The results could perhaps be displayed as follows:

```
* Depreciation costs of gas infra              = 12345.6 EUR
* O&M costs of gas infra                       = 78.9 EUR
* Payed by [payer] for [measure] with [tariff] = 1234.5 EUR
------------------------------------------------------------- + 
 TOTAL                                         = xxxx EUR
```

**Comment by ChaelKruip** [comment]
@grdw @dennisschoenmakers @antw @MarjoleinSchwachofer @ThomBuijs what do you think would be useful?

**Comment by MarjoleinSchwachofer** [comment]
I think this indeed would be a useful breakdown.

Another nice to have would be if you could export the businesscase and breakdown in an Excel or something and not only see them in the mouseover. So that you can copy them easily.

**Comment by grdw** [comment]
![screen shot 2016-09-01 at 10 07 20](https://cloud.githubusercontent.com/assets/2676542/18160119/1aa0add6-702c-11e6-8a2b-b7820b06692f.png)

Right now it shows the breakdown of the total numbers. It does not yet know if the calculated number came from O&M costs or were depreciation costs etc.
