### ISSUE TITLE
[Airbrake] [Production] undefined method `default_demand' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1091]
**Airbrake error:** [#0466](https://quintel.airbrake.io/projects/111227/groups/1709363318036610466)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `default_demand' for nil:NilClass ``
**Where:** `testing_grounds#render_template`
**Occurred at:** Jun 16, 2016 11:18:10 UTC
**First seen at:** Jun 16, 2016 11:18:10 UTC
**Occurrences:** 1 (1 since last deploy on Jun 12, 2016 15:59:55 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/render_template.js?scenario_id=295723](https://moses.energytransitionmodel.com/testing_grounds/render_template.js?scenario_id=295723)
**File:** `[PROJECT_ROOT]/app/services/testing_ground/technology_builder.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/testing_ground/technology_builder.rb:22:in default_attributes
[PROJECT_ROOT]/app/services/testing_ground/technology_builder.rb:17:in installed_attributes
[PROJECT_ROOT]/app/services/testing_ground/technology_builder.rb:11:in build
[PROJECT_ROOT]/app/controllers/testing_grounds_controller.rb:156:in render_template
```

**Comment by grdw** [comment]
The whole attribute `default_demand`  does not exist anymore. It seems impossible that this error will ever re-occur.
