### ISSUE TITLE
BUG: Units and capacity do not multiply correctly in capacity chart

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1095]
The default topology contains "customers" both a capacity (17.25) and units (33). These two inputs do not multiply, leading to a capacity of just 17.25 kW.

Images are shown below

### Default topology
![image](https://cloud.githubusercontent.com/assets/19907658/16120156/df0ba728-33de-11e6-8a57-b6c485f69d4b.png)

### Capacity shown in graph
![image](https://cloud.githubusercontent.com/assets/19907658/16120297/43c24082-33df-11e6-884d-02192d0d5df8.png)

@grdw @ChaelKruip 
@antw ??

**Comment by grdw** [comment]
Related: https://github.com/quintel/etmoses/issues/336

**Comment by antw** [comment]
I'm guessing this is a display issue only, because the electricity network builder *does* [multiply the capacity by the number of units](https://github.com/quintel/etmoses/blob/master/app/models/network/builders/electricity.rb#L54).

**Comment by DorinevanderVlies** [comment]
Thanks @antw! @grdw can you fix this?

**Comment by ChaelKruip** [comment]
It seems that the capacity is sufficient for [my LES](https://beta-moses.energytransitionmodel.com/testing_grounds/647) but the node is still red:

![etmoses](https://cloud.githubusercontent.com/assets/1303760/17103045/96e77ec4-527c-11e6-9a16-28d40e47cd56.png)
