### ISSUE TITLE
Clarify and check O&M costs for dispatchable sources

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1097]
There is some confusion about the numbers provided by Alliander:

![screenshot_17_06_16_15_25](https://cloud.githubusercontent.com/assets/1303760/16151961/c5732bda-349f-11e6-926b-99281449c978.png)

* Are the investment costs given in EUR/MW or EUR/MWh? The latter (as it is written in the Excel) does not make sense as the capacity factor the dispatchables is unknown
* Are the yearly O&M costs quoted *fixed* or *variable* (or the sum)? 
  * If they are fixed, should the unit not be EUR/MW?
  * If they are variable/sum: could we also get a specification of *fixed* O&M costs in EUR/MW?

**Comment by ChaelKruip** [comment]
The new 'correction' by Machiel has resulted in the following values:
![vragen_van_quintel_-_chael_kruip_quintel_com_-_quintel_intelligence_mail](https://cloud.githubusercontent.com/assets/1303760/16198128/10ae40b4-3705-11e6-9300-e4ec2f702587.png)

I am still confused about the EUR/MW unit for investment costs and O&M costs of must-run (altijd aan) sources. I think that EUR/MWh would be more useful/logical.

**Comment by Sanne512** [comment]
Update: Machiel is on holiday untill 10th of July. I forwarded the question to him, but getting the answer will take a while.

**Comment by Sanne512** [comment]
Machiel's answer: the fact that a heat source is always turned on does not mean that the heat it produces is always being used (completely). So the biggest part of the investment and O&M costs are independent of the use of the heat of the must-run heat sources. The costs that are strongly related to the heat use of the must-run source these can be added in the marginal costs.

**Comment by Sanne512** [comment]
@ChaelKruip rang me about this. I forwarded the question to a heat expert at Liandon and included Chael in that e-mail so the heat expert and Chael can communicate directly about this issue. 

Including @MarjoleinSchwachofer

**Comment by ChaelKruip** [comment]
Machiel has provided us with numbers for the must-run part of the central heat network:
* Investment costs: 0.016 -- 0.50 €/kWh
* Yearly O&M costs: 0.00032 -- 0.02  €/kWh
* Marginal costs: 0 -- 0.025 €/kWh

**Comment by ChaelKruip** [comment]
I will take the upper limit for the numbers quoted above as not to paint a picture for heat networks which is too optimistic by default. 

 With  https://github.com/quintel/etmoses/commit/e9e5492e536e24f4bd40079085badbc091be9eab I close this issue.
