### ISSUE TITLE
ETMoses doesn't display the Residential PV panel power

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1104]
When running a simple grid with residential PV panels, the power of the PV panels is not shown when displaying the individual components. It only shows the power of the households.

![not displaying residential pv power](https://cloud.githubusercontent.com/assets/20039533/16189410/866699da-36da-11e6-86b0-b92d2ed2ac69.png)
![not displaying residential pv power 2](https://cloud.githubusercontent.com/assets/20039533/16189418/8fe06888-36da-11e6-8320-7447d30602e7.png)
![not displaying residential pv power 3](https://cloud.githubusercontent.com/assets/20039533/16189423/921ac5a8-36da-11e6-96b3-3f7e90fbc5a9.png)

In the case where the whole year is displayed, the effect of the PV panels is visible. I guess it would be helpful to compare the solar profile with the load profile.

@ChaelKruip 

https://moses.energytransitionmodel.com/testing_grounds/485

**Comment by ChaelKruip** [comment]
This issue is already described in: https://github.com/quintel/etmoses/issues/1063. Closing this.
