### ISSUE TITLE
Revisiting export page

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1107]
<img width="720" alt="screen shot 2016-06-20 at 15 08 37" src="https://cloud.githubusercontent.com/assets/2676542/16195226/e689f0c8-36f8-11e6-9bc3-e0c9337a9aa0.png">

- Export page buttons need to be at the bottom of the page
- Remove the ASCII-arrows
- The list has to align with the text (also make the text non bold) and keep the numbers bold?

**Comment by ChaelKruip** [comment]
Also, we need add all new technologies that we recently added to ETMoses (hybrid heat pumps for example)

**Comment by ChaelKruip** [comment]
Can this be closed @grdw?
