### ISSUE TITLE
Rescale gas assets to gas connections does not blank/reset the quantities

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1110]

**Comment by ChaelKruip** [comment]
@grdw @antw what is the status of this?

**Comment by grdw** [comment]
This is already merged; this can be closed.

**Comment by ThomBuijs** [comment]
Okay, I clicked on something by accident. I didn't want to modify anything here. I cannot figure out how to undo this. Sorry for the inconvenience.

**Comment by ChaelKruip** [comment]
> Okay, I clicked on something by accident. I didn't want to modify anything here. I cannot figure out how to undo this. Sorry for the inconvenience.

You can click on the "clear this milestone" button to undo what you did:

![rescale_gas_assets_to_gas_connections_does_not_blank_reset_the_quantities_ _issue__1110_ _quintel_etmoses](https://cloud.githubusercontent.com/assets/1303760/17589038/bd30b59c-5fd2-11e6-8270-df37cb91f232.png)
