### ISSUE TITLE
We need a legend for the gas assets

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1112]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16196061/a57b8746-36fc-11e6-9af0-f3bdafc9835c.png)

**Comment by ChaelKruip** [comment]
These terms are very specialistic and not explained yet.

**Comment by ChaelKruip** [comment]
@MarjoleinSchwachofer could you provide an explanation text for these technical terms? We could add that to the documentation and provide the user with a link.

**Comment by ChaelKruip** [comment]
Assigning @MarjoleinSchwachofer

**Comment by Sanne512** [comment]
![image](https://cloud.githubusercontent.com/assets/17741822/16553329/4e6b203e-41c8-11e6-945a-4610c7bbff3a.png)
Not in the same order, I grouped similar terms: 

- pe_lp: a gas pipe at 100 mbar made out of PE
- pvc_lp: a gas pipe at 100 mbar made out of PVC
- steel_lp: a gas pipe at 100 mbar made out of steel
These three are the most common used materials at the 100 mbar level. 

- pe_hp: a gas pipe at 4 or 8 bar made out of PE
- ductile_iron_hp: a gas pipe at 4 or 8 bar made out of ductile iron
These together with the steel pipes are the most common used materials for gas pipes at 4 and 8 bar. 

- as: afleverstation = delivery station
- has: hoofd afleverstation = main delivery station
For an explanation see this issue: https://github.com/quintel/etmoses/issues/984 

- drs: drukregelstation = pressure control station
The connector betweeon 8 bar and 4 bar. 

I didn't research the compressors, so I can't help you with that.

**Comment by ChaelKruip** [comment]
Thanks @Sanne512, assigning @jorisberkhout to add this to the documentation.

**Comment by jorisberkhout** [comment]
I have included the legend in the [documentation](https://github.com/quintel/etmoses/wiki/Gas-network#user-interface). Closing.
