### ISSUE TITLE
Micro CHP cannot be added assigned to a buffer and ligths up red

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#1125]
As noticed in LES 452 on the Live server.

I can add a micro CHP to my LES, but cannot assign a buffer to it. No matter what other attributes of the micro CHP I change, it keeps lighting up red to tell me I am doing something wrong. Can you shine some light on this, @ChaelKruip ?

<img width="1118" alt="screen shot 2016-06-22 at 14 58 54" src="https://cloud.githubusercontent.com/assets/4669028/16267421/f5ed985c-3889-11e6-81ce-b533e044212b.png">

**Comment by ChaelKruip** [comment]
Micro CHPs are not supported yet and should not be available in the menu. Assigning @antw

**Comment by antw** [comment]
Can't reproduce this myself. The micro CHP does not appear in the menu:

<img width="399" alt="screen shot 2016-06-29 at 17 01 48" src="https://cloud.githubusercontent.com/assets/4383/16457281/324c80ba-3e1b-11e6-909e-59029373a0d4.png">

**Comment by jorisberkhout** [comment]
I see these technologies in a somewhat older LES (#452) on the LIVE server.

<img width="1158" alt="screen shot 2016-06-29 at 17 09 05" src="https://cloud.githubusercontent.com/assets/4669028/16457666/930e4d56-3e1c-11e6-85d0-2d1a7f45d320.png">

**Comment by antw** [comment]
> on the LIVE server 

My bad, I wasn't paying attention. 😞
