### ISSUE TITLE
Why can I not log in into my ET Moses account?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1128]
I tried with two different accounts to log in today using Chrome and Explorer but it seems I am unable to log in. Why is this the case? 

Kind regards,

Thom

**Comment by ThomBuijs** [comment]
It is also impossible for me to assign someone and to use labels.

**Comment by ThomBuijs** [comment]
Okay Sanne solved my problem with not loggin in on ET Moses. I was on the Beta version.

**Comment by dennisschoenmakers** [comment]
Hi Thom, thank you for your message. Considering the privacy of your account, could you send us an email to support@quintel.com?

**Comment by dennisschoenmakers** [comment]
> Okay Sanne solved my problem with not loggin in on ET Moses. I was on the Beta version.

Thank you for the update!
