### ISSUE TITLE
Banner on beta should tell users different warning

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1129]
Banner was introduced with 9bed4fc0406431dc220644b9fbecba1e25347706. Currently, the message reads: 

> ETMoses is currenty undergoing maintenance and may not be completely reliable during this process. We hope to have the application restored to full service soon.

I suggest the message should warn users when they are using the *beta* server. And keep the message above for when we are in a deploy, right @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> I suggest the message should warn users when they are using the beta server. And keep the message above for when we are in a deploy, right @ChaelKruip ?

👍
