### ISSUE TITLE
Freeform is not working anymore?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1132]
I entered `10.000` in https://beta-moses.energytransitionmodel.com/testing_grounds/525/edit in business case:

![image](https://cloud.githubusercontent.com/assets/104830/16295753/da44d85a-3928-11e6-8dc5-89ebdaf627c5.png)

Then it hangs and keeps saying 'loading' forever:

![image](https://cloud.githubusercontent.com/assets/104830/16295772/fd202da2-3928-11e6-860c-f20c4f8887c4.png)

If I refresh, the `10.000` has disappeared:

![image](https://cloud.githubusercontent.com/assets/104830/16295788/0e377dac-3929-11e6-9c19-50f347ca456d.png)

**Comment by ChaelKruip** [comment]
Can this be closed @grdw @antw?

**Comment by ChaelKruip** [comment]
Can this be closed @grdw @antw?

**Comment by antw** [comment]
> Can this be closed @grdw @antw?

If it works, sure. I didn't notice any problems with it when working on #1360 last week...
