### ISSUE TITLE
Beta server does currently not assign hybrid heatpumps when present in ETM scenario. 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1133]
**Summary**
When creating a LES on the beta server that contains other technologies for space heating than just combi heating the other technologies are not represented in the technology profile.
The number of units for combi heating is decreased proportionally, but the remaining part of the heating demand is not represented in the technology profile.

On the live server hybrid technologies are assigned in ETMoses when they are present in ETModel.
_The following might be a different issue:_
However, when I select a technology that is not present in ETMoses (for example 50% Micro-CHP). The number of units of "combined network gas" goes down, but no other technology pops up.

**Example**
My scenario has 1657 households.

When I assign for space heating 100% "Condensing combi boiler" and for Hot water 100% Condensing combi boiler my technology profile contains 
- 1657 units "Households water heater combined network gas"
- 1657 units "Households space heater combined network gas"

When I assign in beta ETModel for space heating 50% Condensing combi boiler and 50% hybrid heatpump and for hot water 100% condensing condensing combi boiler
I get:
- 1657 units "Households water heater combined network gas" 
- 828 units "Households space heater combined network gas" 
- and no other heating technologies. 

When I assign in ETModel for heating 50% Condensing combi boiler and 50% hybrid heatpump
And for Hot Water 50% condensing combi boiler and 50% fuel cells 
- 828 units "Households water heater combined network gas" 
- 828 units "Households space heater combined network gas" 
- and no other heating technologies. 
So, the hybrid electrical and gas were not assigned.
And the fuel cells were not assigned

CC: @dennisschoenmakers

**Comment by ChaelKruip** [comment]
@antw can you look into this?
