### ISSUE TITLE
Secondary heat infra table needs some TLC

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1134]
* The new lines should have a '0.0' share of the connections
* The default stakeholder should be the system operator (same goes for primary heat infra)
<img width="1176" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/16337180/a0cc59ae-3a13-11e6-9b78-87b45fb1730b.png">

**Comment by grdw** [comment]
> The new lines should have a '0.0' share of the connections

But shouldn't the percentages be replace by sliders? I'm ok with finding a way to do this. But if someone specifies the first row percentage as 0.5. The second should also have 0.5. And the third one should have zero etc. I'm going to investigate a little and let you know if it's easy or hard to fix.

**Comment by ChaelKruip** [comment]
> But shouldn't the percentages be replace by sliders? I'm ok with finding a way to do this. But if someone specifies the first row percentage as 0.5. The second should also have 0.5. And the third one should have zero etc. I'm going to investigate a little and let you know if it's easy or hard to fix.

Yes! If that is not too hard to do sliders would have my strong preference. @antw has a lot of experience with sliders he might be able to help :)

**Comment by grdw** [comment]
The stakeholder defaults are fixed by: https://github.com/quintel/etmoses/blob/master/app/services/heat_asset_lists/asset_list_generator.rb#L37 

The percentage of heat connections will be replaced by sliders.
