### ISSUE TITLE
stacked and individual curve does not include residential PV panel

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1148]
### Problem
Residential PV is shown in the _total electricity_ curve, but not in the _stacked_ and _individual_ curve.

### Example 
This is shown clearly in a node where just residential PV is present: the _PV plant_ node of scenario 
[554](https://beta-moses.energytransitionmodel.com/testing_grounds/554).

**Total electricity**
![image](https://cloud.githubusercontent.com/assets/19907658/16411714/c3cd0580-3d28-11e6-9979-7be9d2787771.png)

**Stacked  electricity**
![image](https://cloud.githubusercontent.com/assets/19907658/16411720/ca17ca56-3d28-11e6-8a8e-3182426cffc8.png)

@dennisschoenmakers

**Comment by antw** [comment]
This is reported in #1063 so I'll close this. It had been my intention to look at solving it last week, but other things came up. However, it remains high on the priority list.
