### ISSUE TITLE
Base load EDSN is currently missing from permitted technologies select in load profile form

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1150]
As spotted while helping @DorinevanderVlies the `base_load_edsn` or "Aggregated households" is currently missing from the technologies dropdown on beta. 

I manually edited her Ameland `load_profile` so it would accept `base_load_edsn` technologies.

**Comment by ChaelKruip** [comment]
> technologies dropdown on beta.

I am confused. When you assign more than 30 units to the households-technology, the profiles should change to 'aggregated' ones automatically right @grdw? Are the EDSN profiles not selectable for such > 30 unit technologies?

**Comment by antw** [comment]
> When you assign more than 30 units to the households-technology, the profiles should change to 'aggregated' ones automatically right @grdw?

Yes, and it does appear to work correctly:

| 30 households | 31 households |
| --- | --- |
| <img width="413" alt="screen shot 2016-06-29 at 12 18 29" src="https://cloud.githubusercontent.com/assets/4383/16448799/a0839488-3df3-11e6-9b3f-7657c95c0f23.png"> | <img width="411" alt="screen shot 2016-06-29 at 12 18 35" src="https://cloud.githubusercontent.com/assets/4383/16448805/a50c045e-3df3-11e6-864e-e5e45a64a3f7.png"> |

I think this is just a misunderstanding and can be closed.

**Comment by grdw** [comment]
> Are the EDSN profiles not selectable for such > 30 unit technologies?

I'm sorry for specifying this problem this vaguely. But I'm talking about the technologies select boxes at the load profiles form:

<img width="624" alt="screen shot 2016-06-29 at 13 11 05" src="https://cloud.githubusercontent.com/assets/2676542/16450015/f88a5ae8-3dfa-11e6-83ea-d5f4d197a452.png">
