### ISSUE TITLE
Documentation needed for heat assets

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1154]
The primary and secondary infrastructure for heat networks should be explained:
* Where do the numbers come from?
* What is the difference between the two etc.

This can be done in the documentation wiki first. Later we can link to the documentation from the interface.

Assigning @MarjoleinSchwachofer

**Comment by MarjoleinSchwachofer** [comment]
I do not know the details of heat. The difference between primary and secondary infrastructure is explained elswhere: 
https://github.com/quintel/etmoses/issues/962
and heat overall: 
https://github.com/quintel/etmoses/issues/862
@jorisberkhout , @ChaelKruip:  Is this enough or do you have questions for a heat expert?

I will check the source details for the numbers with Sanne @Sanne512 .

**Comment by ChaelKruip** [comment]
> I will check the source details for the numbers with Sanne @Sanne512 .

Thanks @MarjoleinSchwachofer!

**Comment by jorisberkhout** [comment]
I gave the het network documentation a big push. The results can be reviewed [here](https://github.com/quintel/etmoses/wiki/Heat-network).

Closing this issue. Please open a new issue if you have more specific questions that need answering in the documentation.
