### ISSUE TITLE
When is the electrical boost of the hybrid heat pump activated?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1159]
### Situation

Say I have 100 households, 90 of which have space heater combined network gas, 10 have hybrid heat pump space heating. In my technology profile I assign:

- 90 units Households space heater combined network gas, buffering
- 10 units Hybrid heat pump space heating (electricity), buffering
- 10 units Hybrid heat pump space heating (gas), boosting

### Question
Are the 10 units belonging to the hybrid heat pump space heating gas and electricity coupled? 
 
What I would like to happen is this:
When my electrical heat pump cannot fulfil the demand for that 10 units the gas heat pump should be activated for the demand of that 10 units.

Is this indeed how ETMoses handles this situation? 
Or, are all the buffers on the same end node coupled? So my gas heat pump is only active when both the electrical heat pump and the combined network gas heater cannot supply the current demand of all 100 units.

@dennisschoenmakers FYI

**Comment by antw** [comment]
> Or, are all the buffers on the same end node coupled? So my gas heat pump is only active when both the electrical heat pump and the combined network gas heater cannot supply the current demand of all 100 units.

This is correct. If you have a space heating buffer with annual demand of 1000kWh and volume of 3kWh **and 10 units**, then we model that as a single buffer with demand of 10000kWh and volume of 30kWh.

It's the same with technologies: if you have a combined gas heater with capacity of 20kW **and 10 units**, we model that as a single heating technology with 200kW of capacity.

In your example above, I expect the 90 combined heaters to be used first, followed by the 10 electrical hybrid heat pump components. If there is still unsatisfied demand, the gas components of the HHPs would be used.

--

If you want to model a scenario where you have 90 households with combined heaters, and 10 with hybrid heat pumps, you'd need to use separate endpoints for each case.

**Comment by DorinevanderVlies** [comment]
Thanks for you answer!

> If you want to model a scenario where you have 90 households with combined heaters, and 10 with hybrid heat pumps, you'd need to use separate endpoints for each case.

As a user this strategy feels a bit complicated. I think, for example, that looking at my load vs capacity is much more difficult if I have two end nodes in my topology that are one end node in reality.

I think my problem can also be solved by creating a separate buffer for the hybrid heat pumps (within the same end node). @antw, do you agree?

@jorisberkhout, I think the documentation of hybrid heat pumps should at least include the above described problem and preferably also a strategy for a solution.

**Comment by antw** [comment]
> I think my problem can also be solved by creating a separate buffer for the hybrid heat pumps (within the same end node). @antw, do you agree?

Indeed, that's a better idea than mine. :grinning:

**Comment by ChaelKruip** [comment]
Can we close this @DorinevanderVlies?

**Comment by DorinevanderVlies** [comment]
Yes, I shall open another issue about the documentation
