### ISSUE TITLE
Heat chart needs some TLC and improvements

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1161]
* [x] Add a drop-down so that the visitor may choose which week to display.
* [x] Deficit and separate producers need to be added to the heat chart
* [x] To limit the number of series in the chart I would like to group all local production (heat pumps, combi boilers etc.) into one series (currently the black one). Other series I think should have separate colours:
  * Buffers
  * Deficit
  * Every source for the heat network as specified in the heat sources table
* [x] The vertical axis should be labeled 'kW'
* [ ] The legend should allow 'toggling' of the series

**Comment by ChaelKruip** [comment]
And the vertical axis should be labeled 'kWh':
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16561374/219685a4-41f9-11e6-8bf1-8f2df8f79a7e.png)

**Comment by antw** [comment]
Also:

* Add a drop-down so that the visitor may choose which week to display.

**Comment by ChaelKruip** [comment]
Closing this as the toggling is not such a great idea anyways.
