### ISSUE TITLE
Documentation regarding the implementation of hybrid heat pumps should be more clear

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1162]
As discussed in #1159 hybrid heatpumps should be assigned their own buffer.
Currently this is not clear in the documentation. 

@jorisberkhout can you add this?

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etmoses/wiki/Buffers/870d9b1c8dab6fdaf219bccb7ab356d845f6a380.
