### ISSUE TITLE
Stakeholders gas assets

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1164]
In the following LES: https://moses.energytransitionmodel.com/testing_grounds/506/edit I deleted the stakeholders in the electricity topology and added a market model so I could just view the costs involved with the gas infrastructure. However, after deleting the stakeholders in the electricity topology there are no more stakeholders available in the drop down menu at the gas assets.

**Comment by ChaelKruip** [comment]
Assigning @grdw to fix this. All stakeholders (not just those in the topology) should be selectable in the gas-asset list.

**Comment by grdw** [comment]
On beta all stakeholders are available for selection in the gas asset list. At the end of this week we will synchronize the beta server with the production server.

**Comment by ChaelKruip** [comment]
> At the end of this week we will synchronize the beta server with the production server.

@Sanne512 is that soon enough for your purposes? Let me know if not and we will find another solution. 

Closing this for now.
