### ISSUE TITLE
Gas connections

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1167]
Is it possible to adjust the number of gas connections?

**Comment by ChaelKruip** [comment]
> Is it possible to adjust the number of gas connections?

Yes. The number of gas connections is given by the sum of the numbers of base-load profiles on end-points of the electricity network which have at least one gas technology attached.

Also see this comment: https://github.com/quintel/etmoses/issues/851#issuecomment-206347194

**Comment by ChaelKruip** [comment]
Re-open if this does not answer your question @Sanne512

**Comment by Sanne512** [comment]
So checking if I understand this correctly: when you have selected gas technologies in the ETM these technologies are divided over the different endpoints from the electricity topology in the LES? So it is not possible for the user to select the amount of connections used in the LES?

**Comment by ChaelKruip** [comment]
> So it is not possible for the user to select the amount of connections used in the LES?

You can move the gas-technologies to other end-points and/or change the number of base-loads of an end-point. Both change the number of gas-connections. 

There is currently no option to hard-code the number of gas-connections per end-point of the electricity topology (the same goes for electricity by the way). This could be added in principle in the next sprint if needed.

**Comment by Sanne512** [comment]
When referencing from https://github.com/quintel/etmoses/issues/851 @antw stated that 

>  If there are no gas technologies installed, the number of gas connections is zero. If an endpoint does have one or more gas technologies, the number of gas connections is equal to the number of electricity connections.

So this means that if you have ten electricity connections on an endpoint and 3 of them have heat pumps and 7 are connected to the gas network for their heat and warm water supply. All ten endpoints are connected to the gas infrastructure? Or only the 7 without the heat pump?

**Comment by ChaelKruip** [comment]
> So this means that if you have ten electricity connections on an endpoint and 3 of them have heat pumps and 7 are connected to the gas network for their heat and warm water supply. All ten endpoints are connected to the gas infrastructure?

Yes. If you want to have all-electric connections you would in this example have to make two end-points: one with gas technologies attached and 7 electricity base-loads (which is used to count the number of connections) and one end-point with 3 base-loads and the (electric) heat pumps.

**Comment by Sanne512** [comment]
Could this be added to the wiki?

**Comment by ChaelKruip** [comment]
> Could this be added to the wiki?

@jorisberkhout can you expand the documentation about number of connections?

**Comment by jorisberkhout** [comment]
> @jorisberkhout can you expand the documentation about number of connections?

I have added a description of how the number of electricity, gas and heat connections are determined [here](https://github.com/quintel/etmoses/wiki/Networks#number-of-connections).

Closing this issue. Re-open if anything is still unclear.

**Comment by MarjoleinSchwachofer** [comment]
I added the eaxmple above to the wiki of how to deal with all-electric connections
