### ISSUE TITLE
Calculation gas load

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1171]
In the following LES: https://moses.energytransitionmodel.com/testing_grounds/506/gas_load I made the gas demand humongous and the gas infrastructure very little. This doesn't seem to influence the outcome of the gas load..

**Comment by ChaelKruip** [comment]
@Sanne512 could this be a duplicate of https://github.com/quintel/etmoses/issues/1050?

**Comment by Sanne512** [comment]
Yes, that could definately be the case..

**Comment by ChaelKruip** [comment]
Closing this as it is a duplicate of #1050.
