### ISSUE TITLE
[Airbrake] [Staging] undefined method `round' for "-8,9":String

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1172]
**Airbrake error:** [#7301](https://quintel.airbrake.io/projects/111227/groups/1723165705964597301)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `round' for "-8,9":String ``
**Where:** `testing_grounds#show`
**Occurred at:** Jul 05, 2016 12:21:26 UTC
**First seen at:** Jul 05, 2016 12:21:26 UTC
**Occurrences:** 1 (1 since last deploy on Jul 05, 2016 10:34:45 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/577](https://beta-moses.energytransitionmodel.com/testing_grounds/577)
**File:** `[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml`

**Backtrace:**
```
[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml:79:in block (2 levels) in _app_views_testing_grounds_show_html_haml___2863853698922015541_70251869660580
[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml:74:in each
[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml:74:in block in _app_views_testing_grounds_show_html_haml___2863853698922015541_70251869660580
[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml:62:in _app_views_testing_grounds_show_html_haml___2863853698922015541_70251869660580
```

**Comment by antw** [comment]
@grdw Unless you had some sort of quick fix in mind when you self-assigned this, I think we should close this issue. It falls under the category of the ["Input Validation" milestone](https://github.com/quintel/etmoses/milestones/Input%20Validation) and I don't think we need more issues describing incorrect inputs.

**Comment by grdw** [comment]
Not really. I just self-assign myself to these airbrake issues, because otherwise it doesn't turn up in anyone's filter.

**Comment by antw** [comment]
Let's close it then. I want to try something with [dry-validation](http://dry-rb.org/gems/dry-validation/) as soon as we have time, but in the short-term we will have to do without. I'll look into this LES and fix the broken value.
