### ISSUE TITLE
Should the priority of the plant types for heat change automatically when deleting one?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1174]
When deleting some of the plant types, should the priority change accordingly? So if you have 5 types with priority 1 till 5 and delete the plant type with priority 3, I guess it would be better if 4 changed to 3 and 5 changed to 4.

**Comment by ChaelKruip** [comment]
Good point @ThomBuijs! We already have an issue for this: https://github.com/quintel/etmoses/issues/1062 

The most elegant solution would be to 'drag' the various options into order, eliminating the need for explicit priorities. Closing this.
