### ISSUE TITLE
Is the demand for heat met when deleting a plant type?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1175]
When you delete a plant type is the demand for heat still met? This should mean that the production of the remaining plant types should increase. Is this the case?

**Comment by ChaelKruip** [comment]
> Is this the case?

I think so. @antw can you clear this up?

Plotting a possible deficit of heat production in the heat chart is already described here: https://github.com/quintel/etmoses/issues/1161

**Comment by antw** [comment]
Provided the other dispatchable plants have sufficient capacity, their production will increase.

**Heat load with lots of geothermal:**

<img width="594" alt="screen shot 2016-07-05 at 13 58 54" src="https://cloud.githubusercontent.com/assets/4383/16585424/b402abce-42b8-11e6-8d2b-7632ba8d565f.png">

**Heat load with geothermal removed:**

<img width="596" alt="screen shot 2016-07-05 at 13 58 19" src="https://cloud.githubusercontent.com/assets/4383/16585427/b8a4f326-42b8-11e6-851a-ab94f1ca496c.png">

*(I appreciate that the colours for different plants need to be made distinct).*
