### ISSUE TITLE
Cannot scale heat load to a yearly overview

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1176]
I cannot display a yearly overview of the heat load (this is also not possible when I go to the electricity tab).

**Comment by ChaelKruip** [comment]
> I cannot display a yearly overview of the heat load (this is also not possible when I go to the electricity tab).

You mean an overview such as we have for gas?
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16588147/0e5887b4-42ce-11e6-8418-b9e1a7093f81.png)

That is not planned or implemented as part of any sprint. Removing label "Bug".

**Comment by ChaelKruip** [comment]
> I mean that the x-axis is from 1 januari till 7 januari instead of 1 januari till 31 december.

OK, clear. This should be a relatively easy fix right @antw?

**Comment by antw** [comment]
> This should be a relatively easy fix right @antw?

I'm not too familiar with the chart code, but I'm hoping so.

Last week we discussed adding drop-downs for this and the gas load chart to allow visitors to choose which *week* they want to view, but would likely not support a full annual view (at least not until the caching improvements are in place [see: #1152, #1083]). Would that suffice for now?

I have added this request to the chart TLC issue: https://github.com/quintel/etmoses/issues/1161#issuecomment-230503960

**Comment by ChaelKruip** [comment]
> Would that suffice for now?

I think so. @ThomBuijs do you agree?

**Comment by ThomBuijs** [comment]
I think it would, what do you think @Sanne512?

**Comment by Sanne512** [comment]
I agree as well!
