### ISSUE TITLE
It should be possible to clone a public LES and edit it yourself

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1179]
Instead of creating a whole new LES by going through ETM, we would like to be able to clone an existing LES and make some minor changes and see the results and compare this. Currently you can only see a public case and see the electricity load, gas load and businesscase. Bu you cannot see the gas assets and the like and change one item or just add one node.

**Comment by ChaelKruip** [comment]
> Instead of creating a whole new LES by going through ETM, we would like to be able to clone an existing LES and make some minor changes and see the results and compare this. 

This is problematic if any part of the original LES contains private information. Currently several parts of the LES (say, the Market Model, the Topology, the Gas-Assets etc.) can be either public or private. Only if a LES is completely public, would it be possible to 'clone' it and save it as your own new LES.

In [this issue](https://github.com/quintel/etmoses/issues/839) we discuss the idea of 'merging' the various parts of a LES (Market Model, the Topology, the Gas-Assets etc.) to alleviate the issue of having to keep track of all these components. 

Moreover, we suggest to make three or more 'default' lesses which the user can open, explore, clone and re-use easily to help them make a quick start.

**Comment by MarjoleinSchwachofer** [comment]
ik voeg jullie toe aan de discussie ter info: @Sanne512 @ThomBuijs @JeroenvdLogt

**Comment by ChaelKruip** [comment]
> ik voeg jullie toe aan de discussie ter info: @Sanne512 @ThomBuijs @JeroenvdLogt

Friendly reminder: please use English as we are working with an international crowd here :)

**Comment by grdw** [comment]
About duplicating a LES:

A les can be duplicated if the LES is public, the accompanied Market Model is public and the Topology is public. The duplication will duplicate all parts (gas asset list, heat asset list, heat source list, business case and the selected strategy). The duplication will point to the same Topology and the Market Model as the original LES.

````
LES       DUPLICATED LES
|          /
|         /
TOPOLOGY
MARKET_MODEL
````

When somebody makes a change to either the Topology or the Market model the following will happen.

````
LES       DUPLICATED LES
| |       |        \
| |       |          \
|TOPOLOGY |   TOPOLOGY CHANGED
|         |
MARKET_MODEL
````

LES and DUPLICATED LES are interchangeable in the above example, as in, if someone makes a change to a Topology or Market Model that's already in use with another LES (which is the case when it's duplicated for both the duplicated LES adn the original) the Topology and the Market Model will clone themselves when edited.
