### ISSUE TITLE
Name of measure "Annual maximum kW load ("contracted")" is misleading

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#1181]
As discussed with @MarjoleinSchwachofer , the name of the measure `Annual maximum kW load ("contracted")` is misleading. As discussed in https://github.com/quintel/etmoses/issues/333, this measure simply determines the maximum annual load and assigns a price to this maximum load as described by

> For now, we can use a fixed tariff but in real life this measure is a 'stepped tariff'.

However, "contracted" means something different than what is described here as described in this text sent to me by @MarjoleinSchwachofer:

> Onder gecontracteerd transportvermogen wordt verstaan dat vermogen dat een verbruiker redelijkerwijs verwacht maximaal op enig moment in het jaar nodig te hebben voor zijn aansluiting. Iedere verbruiker met een aansluiting groter dan 3*80 A is verplicht om aan de netbeheerder een waarde voor het gecontracteerde transportvermogen op te geven. Deze waarde is gelijk of kleiner dan de waarde van de gewenste aansluitcapaciteit.

Our preferred solution would be to remove the `("contracted")` from the name of the name, but I would be happy to hear how @ChaelKruip and @dennisschoenmakers feel about this. And @antw , but unfortunately most information in this issue is in Dutch 😄

**Comment by jorisberkhout** [comment]
Assigning @ChaelKruip . Re-assign at will.

**Comment by ChaelKruip** [comment]
> Our preferred solution would be to remove the ("contracted") from the name of the name, but I would be happy to hear how @ChaelKruip and @dennisschoenmakers feel about this. 

I'm fine with this solution! 

Assigning @jorisberkhout to add this to the documentation. I'll open an issue for the renaming in the front-end.

**Comment by jorisberkhout** [comment]
I updated the documentation to reflect the changes in https://github.com/quintel/etmoses/commit/dbf4c13ddb10e6fe9472a73e3771f356bc3112b0 (renaming the measure to `Annual maximum kW load `).

Closing.
