### ISSUE TITLE
Scaling up to a national scenario

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1183]
Which technologies are taken into account when scaling up to a national scenario? All of them? Because when scaling up the neighbourhood battery it doesn't seem to be included in the national scenario. 

And how about the technologies from gas en heat?

**Comment by jorisberkhout** [comment]
@ChaelKruip , can you provide the answer to these question? I'll leave myself assigned to include the answer in the documentation.

**Comment by ChaelKruip** [comment]
The list of technologies which is currently exported is found here: https://github.com/quintel/etmoses/issues/1107

That ticket also describes that we need to include some other more recently added technologies.

**Comment by jorisberkhout** [comment]
I have included a short description of the technologies that are currently exported in https://github.com/quintel/etmoses/wiki/Quick-start-guide#scale-the-testing-ground-scenario-up-to-national-size. I also added a link to issue #1107 , such that the readers of the documentation can keep track of the current status. Considering the documentation part of this done. Closing.
