### ISSUE TITLE
The capacities of the heat network are not visible in the heat load chart

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1187]
When viewing the heat load chart, the capacities (maximum temperatures) of the primary and secondary network are not visible. Will this be added?

**Comment by ChaelKruip** [comment]
> Will this be added?

The heat network is modelled purely energetically. So, temperature is not calculated at the moment. Moreover, as far as I understand, the infrastructure is not likely to be the limited factor for a heat network but rather the rate at which extracted heat can be replaced (leading to possible deficits). This is what the heat chart communicates to the user.

**Comment by ChaelKruip** [comment]
If this does not answer your question, please re-open.
