### ISSUE TITLE
Integrate assets, topology and market model into one object: LES

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1188]
Also see the discussion in https://github.com/quintel/etmoses/issues/1038

**Comment by antw** [comment]
To be clear: the proposal is not to merge the three objects or database tables into one, but rather to make the association between LES, market model, topology, and assets simpler for visitors. With that in mind, does this differ from #839?

**Comment by ChaelKruip** [comment]
> With that in mind, does this differ from #839?

No. Closing this as a duplicate.
