### ISSUE TITLE
Add a summary to documentation regarding buffers 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1189]
This part of the documentation is very elaborate.
For me it took quite a while to understand how to implement the buffers and heating technologies in my LES. I think a summary, with a diagram and maybe typical settings would help to understand buffers more quickly.

@dennisschoenmakers

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etmoses/wiki/Buffers/870d9b1c8dab6fdaf219bccb7ab356d845f6a380.
