### ISSUE TITLE
Persistence needed between editing table view and other pages

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#119]
When editing the local energy solution (LES),
![ivy](https://cloud.githubusercontent.com/assets/1303760/7636252/6645074c-fa66-11e4-813e-ed0c40fdf307.png)
I would like to be able to visit the profiles page (for instance) and be able to return to editing the table somehow.

**Comment by grdw** [comment]
There's only a single nice way to do this. And that's to make all the links on this page go to a 'new tab'.

Another nice solution is to use `localStorage` to store the profile temporarily, so whenever you hit the back button your changes will still be available on your machine only.

**Comment by antw** [comment]
> I would like to be able to visit the profiles page (for instance) and be able to return to editing the table somehow.

Sounds like this issue really masks a usability problem: that it's hard to remember the names of nodes, technology types, and profile names; often you have to go and look them up. Drop-downs, which are pre-filled with all the available values, might prevent the need to visit another page while editing a testing ground.

**Comment by grdw** [comment]
> Drop-downs, which are pre-filled with all the available values, might prevent the need to visit another page while editing a testing ground.

Yes and no. If you know what - for instance - a certain profile looks like: yes. If you don't know than people will still bounce off the form page. It depends on who uses it basically (which is usually the case). :)

**Comment by grdw** [comment]
With the dropdowns that are available right now, it becomes a little easier to check which profiles are available for a specific technology. Does that also imply that you don't need to visit the profiles page anymore or? Could you shine your light on this @ChaelKruip

**Comment by ChaelKruip** [comment]
> Does that also imply that you don't need to visit the profiles page anymore or? Could you shine your light on this @ChaelKruip

The profiles page is still useful to browse, inspect, download and edit profiles. I see no reason to get rid of it. You do suggest to get rid of it right @grdw ?

**Comment by grdw** [comment]
> You do suggest to get rid of it right @grdw ?

No, just validating whether or not this issue is still 'open' :smile:  
But considering that it still might be an issue, the most easy solution would be to open all urls in another tab in order to keep the table 'maintained'.
