### ISSUE TITLE
The gas network documentation is still a bit unclear

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1191]
What I'm missing in the documentation regarding the gas network is some practical information/tips.

- What do the basic settings mean? Can I use the default settings as a start?
- Maybe some examples of typical changes to the basic settings.

@dennisschoenmakers FYI

**Comment by jorisberkhout** [comment]
I have updated the gas network documentation to answer your first two question.

I like the idea of stating some examples, but considering it very low priority given the other areas of the documentation that need some improvement.

Closing. Re-open if the documentation is still unclear.
