### ISSUE TITLE
Why is in the gas network 125 mbar used instead of 100 mbar?

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1201]
Could the answer to this question also be put in the documentation so that other people also have the answer directly?

**Comment by jorisberkhout** [comment]
Good question, @MarjoleinSchwachofer . The following image seems to suggest `100 mbar`. Do you now why we use `125 mbar` instead, @ChaelKruip ?

![0bfba1b0-e6b5-11e5-8f8d-08b131a2ba1f](https://cloud.githubusercontent.com/assets/4669028/16649015/047c71e6-4437-11e6-9b5a-906bac7a6cb0.png)

**Comment by ChaelKruip** [comment]
> Do you now why we use 125 mbar instead, @ChaelKruip ?

This was suggested by @Sanne512 and @JeroenvdLogt at the time. Nothing changes in the calculations if we rename it to 100mbar so let me know if that is indeed desirable.

**Comment by JeroenvdLogt** [comment]
As far as I know the pressure in low pressure pipes is 125 mbar. Of course the pressure is allways between a range. I don't know whether 125 mbar is the maximum and 100mbar the minimum.

**Comment by JeroenvdLogt** [comment]
![image](https://cloud.githubusercontent.com/assets/7781037/16680792/7322da94-44f1-11e6-9993-b23e180a4a58.png)
https://www.enexis.nl/Documents/kwaliteit-en-capaciteit/enexis-kwaliteit-en-capaciteit-2012-2021-g-deel-1.pdf
Overview from Enexis document about quality and capacity of their networks

**Comment by JeroenvdLogt** [comment]
Seems to be a bit fuzzy to me. Let's see what the "Aansluit en transportcode gas RNB" says:
"2.1.1.9
Leidingen ten behoeve van de aansluiting voldoen aan de volgende technische normen:

a. NEN 1059:2010 “Nederlandse editie op basis van NEN-EN 12186 en NEN-EN 12279 – Gasvoorzieningssystemen – Gasdrukregelstations voor transport en distributie”;
b. NEN-EN 1594:2009 “Gasvoorziening – Leidingsystemen voor maximale bedrijfsdruk groter dan 16 bar – Functionele eisen”;
c. NEN 3650-1:2012 “Eisen voor buisleidingsystemen – Deel 1: Algemeen”;
NEN 3650-2:2012 “Eisen voor buisleidingsystemen – Deel 2: Staal”;

NEN 3650-3:2012 “Eisen voor buisleidingsystemen – Deel 3: Kunststoffen”;

NEN 3650-4:2012 “Eisen voor buisleidingsystemen – Deel 4: Beton”;

NEN 3650-5:2012 “Eisen voor buisleidingsystemen – Deel 5: Gietijzer”;

d. NEN 7244-1:2003 “Nederlandse editie op basis van NEN-EN 12007-1 – Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 1: Algemene functionele aanbevelingen”;
NEN 7244-2:2004 “Nederlandse editie op basis van NEN-EN 12007-2 – Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 2: Specifieke functionele aanbevelingen voor polyethyleen (MOP tot en met 10 bar)”;

NEN 7244-3:2004 “Nederlandse editie op basis van NEN-EN 12007-3 – Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 3: Specifieke functionele aanbevelingen voor staal”;

NEN 7244-4:2004 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 4: Specifieke functionele eisen voor nodulair gietijzeren leidingen met een maximale bedrijfsdruk van 8 bar”;

NEN 7244-5:2004 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 5: Specifieke functionele eisen voor slagvaste PVC- leidingen met een maximale bedrijfsdruk van 200 mbar”;

NEN 7244-6:2005 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 6: Specifieke functionele eisen voor aansluitleidingen”;

NEN 7244-7:2005 en NEN 7244-7/A1:2009 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 7: Specifieke functionele eisen voor sterkte- en dichtheidsbeproeving en voor het in bedrijf en buiten bedrijf stellen van gasdistributieleidingen”.

NEN 7244-9:2008 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 9: Specifieke functionele eisen voor de afhandeling van gasmeldingen en periodiek gaslek zoeken”.

NEN 7244-10:2010 “Gasvoorzieningsystemen – Leidingen voor maximale druk tot en met 16 bar – Deel 10: Specifieke functionele eisen voor opstellingsruimten en meteropstellingen met een maximale inlaatdruk van 100 mbar en een maximale ontwerpcapaciteit van 650mn3/h”."

http://wetten.overheid.nl/BWBR0037926/2016-05-12#Hoofdstuk1

**Comment by JeroenvdLogt** [comment]
"Deel 5" is about pipes up to 200 mbar. So it's a maximum and says nothing about operation.
"Deel 10" is about metering and not in consideration within the issue we're talking about right now.

As far as I can oversee whe should use 125 mbar.

**Comment by JeroenvdLogt** [comment]
I will adress this issue at our internal gasexperts and let you know when I have some answer.

**Comment by Sanne512** [comment]
The numbers for the low pressure infrastructure are based on pipes ranging between 100 and 200 mbar. In Liander 100 mbar is used for aggregating these pressure levels, while at Enexis 125 mbar is being used. Since Liander uses 100 mbar this has my preference, but both ways are correct as long as it is documented clearly.

**Comment by ChaelKruip** [comment]
I don't really have an opinion but it would be easiest to leave it at 125 mbar as this is what we currently use in the interface. The value is not used for calculation so it doesn't affect the outcomes anyway.

**Comment by jorisberkhout** [comment]
I have updated the documentation to reflect the fact that we use `125 mbar` for now (see https://github.com/quintel/etmoses/wiki/Gas-network/5381a346a8d10eb48e9d50bce6258f412778adbb). I am closing this issue because I think the question is answered.

Please open a new, actionable issue, if you that the value needs to be changed to `100 mbar`.
