### ISSUE TITLE
Importing default technologies, minimizing concurrency for all technologies

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1203]
Found out when testing things for #1145 

*Import all technologies of scenario 515515:*
Minimizing concurrency for all technologies becomes a pain at that moment 😞 my browser freezes for a moment, than when it does come back you can't seem to be able to save your results. It will give a [HTTP/1.1 413 Request Entity Too Large 5027ms]. 

This issue is also related to the new interface (since your browser freezes). But it might still be a problem after that, when there will be a newer interface. I guess we need to rethink how we are storing technologies in the database. 

Issue is not super urgent but might be when there are going to be more technologies introduced in the back-end of ETMoses.

**Comment by grdw** [comment]
This won't be a problem anymore when #1322 is merged.

**Comment by ChaelKruip** [comment]
Closing this as https://github.com/quintel/etmoses/pull/1322 has been merged
