### ISSUE TITLE
question about local gas production 

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1206]
In the documentation it states: Local production of gas can be fed into the network at the lowest (125 millibar) level by using a power-to-gas (P2G) installation. 
Power-to-gas in ETmoses produces hydrogen, correct? Than it cannot be just fed into the grid. (e.g. It should be mixed in the right concentration). So is this correctly been taken into account in the model and described  in the documentation?

Is this the only source that can feed into the network (no green gas producer)?
@Sanne512 Is this correct with your experience?

 @JeroenvdLogt; @ThomBuijs FYI

 @jorisberkhout For documentation on this

**Comment by ChaelKruip** [comment]
> Power-to-gas in ETmoses produces hydrogen, correct? 

Yes.

> Than it cannot be just fed into the grid. (e.g. It should be mixed in the right concentration). So is this correctly been taken into account in the model and described in the documentation?

As discussed with @Sanne512 and in the sprint meeting for sprint 2, we treat hydrogen (and other gas) purely energetically at this moment. The mixing fraction, Wobbe index etc. are not taken into account right now. 

Assigning @jorisberkhout to put this in the documentation (perhaps we can have an 'assumptions' section in the 'modelling' section of the gas-network page).

**Comment by jorisberkhout** [comment]
Added to the documentation in https://github.com/quintel/etmoses/wiki/Gas-network/c44e7f2c348b208d1ed655ea9a74f31960495eee. Closing.
