### ISSUE TITLE
What is meant with locally produced heat?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1207]
When changing the technologies from everybody uses district heating to everybody uses the gas network for warm water, the locally-produced heat is increased. Can someone explain why this is the case?

**Comment by ChaelKruip** [comment]
> Can someone explain why this is the case?

Locally produced heat is all the heat that is produced by technologies inside the households. Heat pumps and combi boilers etc. take over when you disconnect people from the heat network.

Please re-open if this is unclear.
