### ISSUE TITLE
Business case for Heat doesn't seem to work

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1214]
When I change the distance and lifetimes of the dispatchable plant types I see no change in the business case. Also the effect of changing the values for the heat market model (number of heat connections and kWh of heat consumed) is not visible in the business case. I deleted all the gas assets and the costs for the electricity grid, but I still get the same numbers as I did before I deleted those. Is this a known issue? And is someone working on this?

**Comment by ChaelKruip** [comment]
@antw is still working on the heat-producer stakeholder. Correct @antw?

**Comment by antw** [comment]
I have tested this in my own LES and it seems to be working fine. I edited distances and technical lifetimes and saw a change in the business case for both.

Use the *blue* "Save" button, and ignore the green "Save and view..." buttons for now.
