### ISSUE TITLE
Business case does not calculate money in for stakeholder cooperation

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1217]
I have defined a [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/588/business_cases/349) with a cooperation with a PV plant. I would expect the cooperation to receive money. However, this is not the case. Is it a bug or an error in my market model?

In my market model the cooperation is defined as follows:
![image](https://cloud.githubusercontent.com/assets/19907658/16623426/2b3028bc-439e-11e6-95ba-546dd10ede7d.png)

In my business case I get the following result:
![image](https://cloud.githubusercontent.com/assets/19907658/16623775/6f755118-439f-11e6-9838-887b9e250b22.png)

cc @dennisschoenmakers

**Comment by ChaelKruip** [comment]
>  Is it a bug or an error in my business case?

I think you mean 'market model' instead of 'business case'. I have looked at the relevant transactions and they seem to be fine. Assigning @antw to see what goes wrong in the back-end (that is where I am assuming things are going wrong).

**Comment by DorinevanderVlies** [comment]
> I think you mean 'market model' instead of 'business case'.

You are right, thanks, I changed it.

**Comment by antw** [comment]
Closing because this does appear to be fixed.
