### ISSUE TITLE
The business case table in "edit LES" does not allow scrolling

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1219]
I want to examine my [business case](https://beta-moses.energytransitionmodel.com/testing_grounds/588/edit) in the Edit menu.
However, I cannot scroll through te tabel.

![image](https://cloud.githubusercontent.com/assets/19907658/16646756/30ae1e8c-442c-11e6-929d-eee1d12b27cc.png)

cc @dennisschoenmakers

**Comment by antw** [comment]
I'm able to scroll left-and-right through the table, and it looks like you're using Chrome as your browser as am I.

This might just be that Mac OS X hides scrollbars by default, which gives the impression that you cannot scroll. Click the  icon on the left of the menu bar at the top of your screen → System preferences → General. Then choose "Scroll bars: Always". Hopefully the horizontal scrollbar will now appear in the table.

![screen shot 2016-07-07 at 09 27 12](https://cloud.githubusercontent.com/assets/4383/16647094/76b86ee8-4425-11e6-9464-cb2031170cd4.png)
