### ISSUE TITLE
Add "save as" option to edit market model

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1220]
When editing a market model a "save as" option would be nice.
Currently it is only possible to change the name and save, but not to create a new market model (keep the old one as it is).

![image](https://cloud.githubusercontent.com/assets/19907658/16648065/7c5b1f00-4432-11e6-9550-fe589947e585.png)

cc: @dennisschoenmakers

**Comment by antw** [comment]
> Currently it is only possible to change the name and save, but not to create a new market model (keep the old one as it is).

If you choose "Edit LES" and make changes to the market model there, your changes are saved to a copy of the market model rather than to the original (so as not to change other LESes which use the same market model). If you save your changes and then refresh the page, you'll find that it is now called something like "Default Market Model - Clone 1".

I think there might be value to a "Save as" feature on the market model page, but for consistency we should do the same for topologies.

I'd like to come back to this after the "Input validation" milestone.

**Comment by DorinevanderVlies** [comment]
>If you choose "Edit LES" and make changes to the market model there, your changes are saved to a 
copy of the market model rather than to the original 

Thanks, currently I indeed use that workaround.

 > I think there might be value to a "Save as" feature on the market model page, but for consistency we should do the same for topologies.

Agree, I think this would be useful for both topology and market model

**Comment by ChaelKruip** [comment]
I would like this option as well. 👍

**Comment by ChaelKruip** [comment]
> If you choose "Edit LES" and make changes to the market model there, your changes are saved to a copy of the market model rather than to the original (so as not to change other LESes which use the same market model). If you save your changes and then refresh the page, you'll find that it is now called something like "Default Market Model - Clone 1".

It seems that this does not work with my [LES](https://moses.energytransitionmodel.com/testing_grounds/612), maybe because the market model is only used here... When I edit it, the only existing copy is edited as well.

**Comment by antw** [comment]
> maybe because the market model is only used here... 

This is indeed why. A market model or topology won't be cloned when in use by only one LES.

**Comment by DorinevanderVlies** [comment]
This issue will become relevant in the coming week for the Groningen/Paddepoel Project.
Currently the workaround described above is still the only way to save a variation on an existing market model.
A "save as" option in editing a market model (and topology) outside a LES would still be much more convenient.

**Comment by antw** [comment]
I've done the same as @grdw did with topologies: view the market model list, click the one you want to clone and you will find a "Save as new market model" button next to "Edit" and "Delete":

![screen shot 2016-11-21 at 14 15 21](https://cloud.githubusercontent.com/assets/4383/20485812/2c934e6e-aff5-11e6-981c-f0e5aaa43891.png)

**Comment by DorinevanderVlies** [comment]
Perfect, thanks!
