### ISSUE TITLE
Error when saving market model with Merit price as tariff

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1221]
In Edit market model (so not inside my LES) I want to add Merit price as Tariff from supplier to producer.
This gives the error that " interactions value for tariff can't be blank".

Changing back to fixed price removes this error.
Sometimes when I change back again from fixed price to Merit price I can save the market model once.
However, when saving again the same error comes up.

[Link to market model](https://beta-moses.energytransitionmodel.com/market_models/271)

![image](https://cloud.githubusercontent.com/assets/19907658/16648242/5c314190-4433-11e6-9ff3-dcde22c70ff4.png)

cc @dennisschoenmakers

**Comment by antw** [comment]
I have already fixed this locally and should have it on beta shortly. I believe this may be the cause for #1217.
