### ISSUE TITLE
Business case of stakeholder cooperation unrealistic when considering input

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1226]
It seems to me that something goes wrong in my business case. The part I'm focussing up now is the stakeholder cooperation, which has one PV plant.
The other part of the business case is less relevant now as I'm still tuning the load, and not all stakeholders have been defined properly.

### Summary
I have initial investment of 7 million euro, O&M of 10,000 euro. My business case gives yearly spend money is 14 million euro.

### Link
[LES](https://beta-moses.energytransitionmodel.com/testing_grounds/599)

### Details

My PV plant, on end node owned by cooperation, is specified as follows:
One panel with total capacity -6000 kW, initial investment 7,000,000, O&M 10,000, technical lifetime 25 years.
![image](https://cloud.githubusercontent.com/assets/19907658/16680571/cf4a02cc-44ef-11e6-882d-e2dfabae5317.png)

My market model includes a cooperation which receives 0.065 euro/kWh produced (line 7).
![image](https://cloud.githubusercontent.com/assets/19907658/16680603/186e98b4-44f0-11e6-926a-c3d27f368ef7.png)

**The resulting business case gives**
- in 455,332 euro (seems reasonable, but I would expect something slightly different: 867 flh * 6e10^3 kW * 0,065 euro/kWh = 338,000 euro)
- out 14,558,137 euro (unrealistic, I would expect (7,000,000 euro / 25 years ) + 10,000 euro/year = 290,000

![image](https://cloud.githubusercontent.com/assets/19907658/16680736/10869bb4-44f1-11e6-873e-9ec077a906cc.png)

cc: @dennisschoenmakers

**Comment by ChaelKruip** [comment]
@antw can you pik this up with priority?

**Comment by antw** [comment]
> out 14,558,137 euro (unrealistic, I would expect (7,000,000 euro / 25 years ) + 10,000 euro/year = 290,000

This happens because all the gas infrastructure is assigned to the co-operation. In a local copy of the LES I reassigned the infrastructure to the "aggregator", and then the co-operation costs drop to the expected €290k.

<img width="668" alt="screen shot 2016-07-08 at 10 39 34" src="https://cloud.githubusercontent.com/assets/4383/16683538/5466c2a8-44f8-11e6-96a1-e598c3dceb9b.png">

> in 455,332 euro (seems reasonable, but I would expect something slightly different: 867 flh * 6e10^3 kW * 0,065 euro/kWh = 338,000 euro)

I'm not entirely sure from where that FLH comes. The average value of the `solar_pv_zwolle` curve is `0.13327`.

```ruby
0.1332783562416742   # Average
x 8760               # Hours    = 1167.518400677066 (FLH)
x 6000               # Capacity = 7005060.0 (kWh)
x 0.065              # Price per kWh

= 455332.1762640558  # Total price
```

**Comment by ChaelKruip** [comment]
> I'm not entirely sure from where that FLH comes. 

I think that the FLHs come from ETEngine. Perhaps we should base the FLHs on the profile that the user specifies. This would make this more consistent.

**Comment by ChaelKruip** [comment]
> This happens because all the gas infrastructure is assigned to the co-operation.

This is related to https://github.com/quintel/etmoses/issues/1229
