### ISSUE TITLE
Demand/volume/capacity of technologies is reduced / multiplied when toggling concurrency

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1228]
As specified by @antw  in [this pull request](https://github.com/quintel/etmoses/pull/1216#issuecomment-231099936)

> 
> Add a second "Buffer space heating" to "Endpoint 1", set demand to 1000 and hit "Apply" on the concurrency settings (no changes made). The original buffer is removed, and all the technologies are moved to the new one.
> 
> I guess that's expected since the concurrency setting for that technology is "max", but for buffers I would expect the demand, volume (and perhaps capacity?) attributes to be summed (i.e. two buffers with demand of 1000 should be merged into one with 2000).
> 
> Similarly, without making any changes to the test scenario, if "Buffer space heating" is toggled to "min" concurrency, there are now five buffers all with the original amount of demand (total heat demand for the LES is now 5x higher than before).

**Comment by grdw** [comment]
@ChaelKruip is this still relevant?

**Comment by ChaelKruip** [comment]
> @ChaelKruip is this still relevant?

No. Closing.
