### ISSUE TITLE
Concurrency should be set per technology

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#123]
It would be really nice if you could select the technologies for which you would like to maximise or minimise the concurrency. For solar PV concurrency is likely to be high (same neighbourhood) even though it could be low for EV in that same neighbourhood.

**Comment by grdw** [comment]
I think that this can be done, if #157 is merged. 

Interactively I'd suggest that we use:

![bla](https://confluence.atlassian.com/download/attachments/152045542/CollapseAllIcon.png?version=1&modificationDate=1213772121583&api=v2)

this button to minimize concurrency.

When maximizing concurrency and the arrows in the opposite direction when minimizing concurrency

A table row - when the concurrency is maximal - would look like this:
![screen shot 2015-06-10 at 9 53 43 am](https://cloud.githubusercontent.com/assets/2676542/8077506/a4f02d3c-0f56-11e5-8e16-fa99de7132ab.png)

**Comment by ChaelKruip** [comment]
As discussed with @grdw: It makes more sense to choose max/min concurrency per technology rather than for every row.

**Comment by grdw** [comment]
Not really sure about the position. should it be up or below the radio buttons, what do you think @ChaelKruip ? 

![screen shot 2015-06-10 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/2676542/8083500/563f67aa-0f85-11e5-9872-a274d8e68edc.png)

**Comment by ChaelKruip** [comment]
I don't really have a strong opinion about it.

**Comment by grdw** [comment]
Pull request made #166
