### ISSUE TITLE
missing documentation on heat networks

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1235]
In the heat section under modelling approach, I still miss some explanation on how the heat network is modelled. More explanation about things like: 
- topology of primary and secundary (transport and distribution) network , difference
- capacities of network 
- calculation:
   * if temperatures are used in calculation
  *  if losses are taken into account
- How connections of the heat network are associated with the topology
- Numbers and sources for the costs
etc.

Inspiration can be fount in issues mentioned in:
https://github.com/quintel/etmoses/issues/862

**Comment by jorisberkhout** [comment]
Closed with https://github.com/quintel/etmoses/wiki/Heat-network/4e668e829a37d563265a87bf0ecb08c530d84159.

Could you have look @MarjoleinSchwachofer . Please re-open if you think more documentation should be added.
