### ISSUE TITLE
[Airbrake] [Staging] undefined method `symbolize_keys' for "#<InstalledGasAsset:0x007ff74aecbb18>":String

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1236]
**Airbrake error:** [#3473](https://quintel.airbrake.io/projects/111227/groups/1725375173498483473)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `symbolize_keys' for "#<InstalledGasAsset:0x007ff74aecbb18>":String ``
**Where:** `gas_asset_lists#update`
**Occurred at:** Jul 08, 2016 13:30:52 UTC
**First seen at:** Jul 08, 2016 13:30:52 UTC
**Occurrences:** 1 (1 since last deploy on Jul 08, 2016 12:42:51 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/607/gas_asset_lists/497](https://beta-moses.energytransitionmodel.com/testing_grounds/607/gas_asset_lists/497)
**File:** `[PROJECT_ROOT]/app/models/asset_list_serializer.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/asset_list_serializer.rb:9:in map
[PROJECT_ROOT]/app/models/asset_list_serializer.rb:9:in load
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:105:in unserialize
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:96:in unserialized_value
```

**Comment by grdw** [comment]
Closing. I know who did it and why it happened 😶
