### ISSUE TITLE
How to define my market model to pay for imported electricity?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1242]
## Aim / situation
I have a [LES](
In my business case I want to see how much the supplier pays the producer for the produced energy (electricity and gas).
) with a large PV plant. In my business case I want to see how much the supplier pays the producers for the produced energy (electricity and gas).

So, in my business case I want 
- the supplier to pay the PV plant for all electricity that is produced
   I managed to do this by measuring at the PV plant node
- the supplier to pay external producers for all "imported" electricity

## Question
How should I define my market model and topology?

## Details
The documentation gives me this information:
![image](https://cloud.githubusercontent.com/assets/19907658/16729480/0c62a9a0-476d-11e6-8140-752083237526.png)

I cannot measure the energy produced by the external producer at the end nodes (because part of the demand is filled by the PV plant). I think I should measure this at my top node. The stakeholder of this node is the system operator. But, the system operator owns more nodes than are useful for this case. If all nodes are added (as the documentation says) the costs will be overvalued. 

_My topology contains 3 serial nodes with system operator as stakeholder_
![image](https://cloud.githubusercontent.com/assets/19907658/16729183/1556db0a-476b-11e6-9ff0-07242810bc1c.png)

_My current market model had two lines to define the payment to the external producer:_
![image](https://cloud.githubusercontent.com/assets/19907658/16729279/ac0a2052-476b-11e6-8e8c-32a85c44e34b.png)
![image](https://cloud.githubusercontent.com/assets/19907658/16729283/b899ba12-476b-11e6-9615-c0440ad270fc.png)

cc @dennisschoenmakers

**Comment by antw** [comment]
If you insert another node between the HV and MV networks and assign it to a new stakeholder, I believe you will be able to use "kWh of electricity produced" measure to determine how much energy flows through it from the HV network.

**Comment by DorinevanderVlies** [comment]
>If you insert another node between the HV and MV networks and assign it to a new stakeholder

Thanks! I think this will work indeed.

It feels a bit like a workaround though. I prefer my nodes to represent physical entities.
I can imagine that in a more complicated topology more problems like this one will arise (for example if one stakeholder has different euro/kWh for different nodes). Filling up the topology with "dummy nodes" feels a bit devious.
@antw what is your opinion?

**Comment by ChaelKruip** [comment]
Closing this as the original question has been answered.
