### ISSUE TITLE
My profile curve differs from my load curve

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1243]
## Problem/question
In my [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/611) I do not see the shape of my demand curve for hot water which is supplied by electrical heating represented in my "household water heater electricity" curve.

## Suspicion
I have a suspicion that the capacity of my electrical water heater might be insufficient to supply the peaks. Is my demand not satisfied? If that is indeed the case, where can I see that? 

## Details
I am using a particular curve to represent my demand for water heating
![image](https://cloud.githubusercontent.com/assets/19907658/16730916/c17c1c24-4775-11e6-9a57-12ebae26cc28.png)

In my technology profile I assigned this profile to my two water buffers at the "toerisme" end node.
![image](https://cloud.githubusercontent.com/assets/19907658/16730851/7742c842-4775-11e6-9b89-ed16005ac6a9.png)

In my stacked gas curve I **do see** the specific shape of the demand
![image](https://cloud.githubusercontent.com/assets/19907658/16730907/b72ec726-4775-11e6-8388-2e5998dcb33d.png)

However, in my stacked electricity curve I **do not** see the specific shape of the demand
![image](https://cloud.githubusercontent.com/assets/19907658/16730900/a82c0e6e-4775-11e6-9cb9-307d0d95fd90.png)

cc @dennisschoenmakers

**Comment by ChaelKruip** [comment]
> Is my demand not satisfied? If that is indeed the case, where can I see that?

In the [heat load chart](https://beta-moses.energytransitionmodel.com/testing_grounds/611/heat_load) you can see the production deficit.

> However, in my stacked electricity curve I do not see the specific shape of the demand

Is this the same node as where the gas-technologies are? Perhaps the gas-techs are supplying the peaks?

**Comment by DorinevanderVlies** [comment]
>In the heat load chart you can see the production deficit.

So, no deficits :-).

As there are two different buffers with both one technology, but the same load, I don't think the gas can supply the peaks for both buffers.

**Comment by DorinevanderVlies** [comment]
I did find some deficits in summer. 
Do you think they are the reason I'm not seeing the shape of the demand curve?

![image](https://cloud.githubusercontent.com/assets/19907658/16758485/14cb1f3c-4812-11e6-8756-fd2ae23baf24.png)

**Comment by ChaelKruip** [comment]
> Do you think they are the reason I'm not seeing the shape of the demand curve?

Could be! Try installing more capacity (one very big electric water heater) and see if you get the right peaks?

**Comment by DorinevanderVlies** [comment]
>Could be! Try installing more capacity (one very big electric water heater) and see if you get the right peaks?

Yes, it's working! 

I think my standard water heater should have enough capacity to fulfil normal individual demand . So, with an aggregated curve the problem of deficit should be solved (see #1248).

![image](https://cloud.githubusercontent.com/assets/19907658/16759511/9cd1fe82-4817-11e6-91dc-ea29056b7bee.png)
