### ISSUE TITLE
Add aggregated hot water profile(s).

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1248]
As far as I can see, the current hot water profiles are for individual households.

It would be nice to have a/some aggregated profile(s).

Especially when scaling up the peaks become unrealistically high, leading to deficits which I think in real life will not occur. Splitting the demand over more buffers is an option, but right now quite a lot of effort.

cc @dennisschoenmakers

**Comment by ChaelKruip** [comment]
@jorisberkhout can you help me do this? You made the original profiles and I remember you also have an aggregated curve (basically the probability distribution for domestic hot water use).

**Comment by jorisberkhout** [comment]
> @jorisberkhout can you help me do this?

Yes! By when do you need this, @DorinevanderVlies ?

**Comment by DorinevanderVlies** [comment]
>Yes! By when do you need this, @DorinevanderVlies ?

Thanks!
This week would be awesome. Next week Tuesday latest.

**Comment by ChaelKruip** [comment]
I've uploaded [a profile for hot water](https://beta-moses.energytransitionmodel.com/load_profiles/428) taken from the BDH scenariotool:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16798342/e002cc2a-48eb-11e6-8588-c6410d62e881.png)

This profile is less peaked and should be not too far off from the truth. Closing
