### ISSUE TITLE
Peak loads in weekly and yearly load curve do not correspond

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1254]
In the folowing LES: https://moses.energytransitionmodel.com/testing_grounds/477 the electricity load with capacities do not correspond in the weekly and yearly view:

When you look at the weekly view of 16-22 July, see picture below, you can clearly see that the electricity load with strategies exceeds the capacity of the MSR. 
![bug buurtbatterij week vs jaar load week](https://cloud.githubusercontent.com/assets/17741822/16767565/5aed5b1e-4840-11e6-8baf-84c7f27fa1ff.PNG)

While when you look at the yearly load, the electricity load with strategies doesn't exceed the capacity. In the next picture I zoomed in on the same time frame. 
![bug buurtbatterij week vs jaar load jaar](https://cloud.githubusercontent.com/assets/17741822/16767669/d78ee930-4840-11e6-8e79-0bfcb13d62f8.PNG)

**Comment by antw** [comment]
A fix has been pushed to `master` (beta) and `production`.
