### ISSUE TITLE
Add aggregate space heat demand profile for detached houses with low isolation.

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1255]
For the Ameland scenario an aggregated load profile which represents detached households with low isolation would be very useful.

@ChaelKruip could you provide this?
cc @dennisschoenmakers

**Comment by ChaelKruip** [comment]
I have taken the NEDU gas-consumption profile for 'kleingebruikers' (see the first five days):
![screenshot_12_07_16_17_49](https://cloud.githubusercontent.com/assets/1303760/16773765/7703c2fc-4859-11e6-9c92-a4378142dfb5.png)

It is quite spiky still but I don't have anything better at the moment...

**Comment by DorinevanderVlies** [comment]
Thanks!

Would you say it's overall more smooth than the current profiles? For example "Vrijstaand Hoog"?

![image](https://cloud.githubusercontent.com/assets/19907658/16794240/c9a4b4da-48d6-11e6-90d9-f4fa4eb2a893.png)

**Comment by ChaelKruip** [comment]
I have uploaded one new profile: the [total gas consumption](https://beta-moses.energytransitionmodel.com/load_profiles/427):
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16796659/255c472c-48e4-11e6-8217-bdd8c2d4c172.png)

**Comment by ChaelKruip** [comment]
Closing.
