### ISSUE TITLE
Make all space heat profiles available for beta server

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1256]
Currently there are more load profiles for space heating on the live than on the beta server.
It would be nice if all profiles become available on the beta server.

**Live server:**
![image](https://cloud.githubusercontent.com/assets/19907658/16768527/fc097f7e-4844-11e6-849a-4b9ec1b5b62a.png)

**Beta server:**
![image](https://cloud.githubusercontent.com/assets/19907658/16768491/e1ca9a80-4844-11e6-8ecc-0a4f85f1b92a.png)

cc @dennisschoenmakers

**Comment by ChaelKruip** [comment]
@grdw @antw is there an easier way to get these profiles to BETA than manually uploading them?

**Comment by grdw** [comment]
> is there an easier way to get these profiles to BETA than manually uploading them?

Hmm, not really... Paperclip uses the database ID to associate the CSV file with the load profile row in the database. So manually copying them over from the staging database to prodcution will do more harm than good. I guess that we'd need to write some sort of script to do this nicely.

**Comment by ChaelKruip** [comment]
Closing this as the profiles have been uploaded.
