### ISSUE TITLE
Default financial profiles

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1258]
When you're creating a new market model there are three financial profiles available when selecting "price curve". Will these also be explained in the documentation just as the technological profiles?

**Comment by ChaelKruip** [comment]
> When you're creating a new market model there are three financial profiles available when selecting "price curve". Will these also be explained in the documentation just as the technological profiles?

At the moment these are not well researched. I think that two of them have been created by @JeroenvdLogt . I could write something about them but I'm not sure what it would add for the user.

**Comment by ChaelKruip** [comment]
I have added a line in the documentation about day-night profiles but this part of the model is very volatile (as users can add their own profiles) so the documentation is hard to keep up-to-date. Closing.

**Comment by Sanne512** [comment]
> At the moment these are not well researched.

This, or something similar that states that the available profiles are created by users and not provided by Quintel, is also a valuable addition to the wiki and would provide more clarity
