### ISSUE TITLE
Model the hybrid heat pump as a single technology

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1262]
The hybrid heat pump is now modelled as two separate technologies. A gas part and an electricity part. This is only necesarry for the load calculation. In the front-end and in the database I'd like to only save the fact that there is a 'hybrid heat pump' for space heating or water heating. When calculating we can split it up in two separate parts. Much like once said in this [issue](https://github.com/quintel/etmoses/issues/740).

**Comment by grdw** [comment]
CC @ChaelKruip

**Comment by ChaelKruip** [comment]
Why was I assigned to this issue @grdw? I have assigned you because I think this is a splendid idea!

**Comment by grdw** [comment]
Just to re-assign someone. I was seeing lots of issues with no assignee.

**Comment by grdw** [comment]
I think this is solved by https://github.com/quintel/etmoses/commit/98e0a730b3b222ac321f03025c220615e2e6c7ab#diff-28b8f12a979f4ed447a3c31fdc44670e
