### ISSUE TITLE
Explanation of compressor is missing in user interface documentation of gas asset

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1265]
In the gas asset list you can choose different compressors. However I am missing documentation about this since, at least for me, it was not clear that in order to choose a compressor connected at 125 mbar, you need to set the pressure level at 0.125 (bar). I think it would be nice to add this. I'm assigning @jorisberkhout.

**Comment by ChaelKruip** [comment]
Good point @ThomBuijs!

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etmoses/wiki/Gas-network/c1840202588d1f13b3e4166439e0366e82c3c86c. Re-open if you feel more explanation is needed.
