### ISSUE TITLE
Gas load charts on the network should be rendered on a per week basis like the heat load chart

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1266]
* The gas load chart "Load on the gas network" should be rendered the same as the Heat load chart. 
* The Yearly gas load chart should not render unless explicitly desired by the user.

**Comment by ChaelKruip** [comment]
I think some context to this issue would help:

Currently, the yearly gas load chart causes a server time-out for large LESses (https://github.com/quintel/etmoses/issues/1050 and others). This renders the whole gas-load chart useless for such LESses.

Possible ways to improve the situation:
* Show gas load in a weekly-only chart (like the one for heat)
* Move the yearly chart to another place where it is only rendered if the user explicitly requests a full yearly calculation

@antw @dennisschoenmakers what do you think?

**Comment by antw** [comment]
I think this relates to #1083, which is that any action involving a calculation should go through a dedicated CalculationController, and accept parameters such as `range_start`, `range_end`, and `resolution`. This way, network load, gas load, and heat load would all have an identical API (and hopefully be able to use `Poller` on the front-end to wait for a calculation to complete).

In the short-term, we can probably make the gas load chart work like the heat chart, by removing the option to display the full annual load, and instead showing only one week at-a-time. That would avoid the need to do all the CalculationController stuff, which *might* depend on first completing [the caching improvements](https://github.com/quintel/etmoses/issues/1152) (which I haven't properly documented yet, and aren't even scheduled for this sprint).

**Comment by ChaelKruip** [comment]
> In the short-term, we can probably make the gas load chart work like the heat chart, by removing the option to display the full annual load, and instead showing only one week at-a-time.

Let's do that first indeed. 👍

**Comment by grdw** [comment]
The yearly gas load chart is now behind a load button and a warning:
<img width="1170" alt="screen shot 2016-07-15 at 10 32 15" src="https://cloud.githubusercontent.com/assets/2676542/16868355/7a8c3466-4a77-11e6-98fb-c970fdbba13a.png">

After you click on the render button:

<img width="1176" alt="screen shot 2016-07-15 at 10 32 01" src="https://cloud.githubusercontent.com/assets/2676542/16868354/7a69197c-4a77-11e6-8ade-d4e66cd2811b.png">

As discussed with @ChaelKruip

**Comment by ChaelKruip** [comment]
Closing as this has been done.
