### ISSUE TITLE
Discussion: Add button to "split" technologies; replace concurrency

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#1267]
[As suggested here](https://github.com/quintel/etmoses/pull/1216#issuecomment-231333920), I'd like to propose a "Split" button as a replacement for the concurrency options we have today.

The idea is that any technology with two or more `units` can be split into two separate technologies, with half the number of units each.

For example, if we have a Household with 4 units:

> <img width="895" alt="screen shot 2016-07-14 at 10 35 51" src="https://cloud.githubusercontent.com/assets/4383/16835076/cb22938a-49ae-11e6-8f9c-f14688e3c753.png">

... the visitor may hit "Split", which will result in two households each containing two units:

> <img width="895" alt="screen shot 2016-07-14 at 10 36 58" src="https://cloud.githubusercontent.com/assets/4383/16835094/ebc84fee-49ae-11e6-9ff7-6bd1603f8b42.png">

If that is not enough, the visitor can then click "Split" on *those* two, ending up with four separate technologies, each with one unit:

> <img width="896" alt="screen shot 2016-07-14 at 10 39 16" src="https://cloud.githubusercontent.com/assets/4383/16835174/58469c98-49af-11e6-8905-fe0d8df40bdc.png">

The "Split" button would be greyed out and disabled if the technology has only one unit installed.

--

Things we might consider:

* Should the split technologies both use the same profile, or should we auto-select a different profile for the new technology?

* Should we support splitting buffers and all their technologies? (I think for simplicity, no).

* *Nice-to-have?* Should we allow a user customise how many technologies are created? Perhaps they want to split a `units=50` technology into five separate technologies of 10 units? That could be a "..." option which the user clicks, and enters how many techs they'd like (up to, but not exceeding, the number of units already installed):

  <img width="265" alt="screen shot 2016-07-14 at 11 15 20" src="https://cloud.githubusercontent.com/assets/4383/16836262/9c961e00-49b4-11e6-843c-35ed5de95422.png">

  I'm on the fence about this, I would like to avoid adding a "..." button – at least at first – and see if a simple "Split" button will suffice. We could add "..." if necessary later.

#### Motivation

1. Splitting technologies using the current "min concurrency" option is like using a sledgehammer. Maybe the user only wants to split that solar array of 500 units into two or three separate technologies, not 500?

2. Discouraging huge numbers of `units=1` technologies will result in faster calculations, and a more responsive technology form.

3. Removing "max concurrency" eliminates a category of bugs where merging technologies would lose any custom settings entered by the visitor. *"Add 2 P2P batteries and set a custom capacity on one. Apply the concurrency settings. You either end up with two custom-capacity batteries, or two default-capacity batteries (depending on which order they appeared on the form)."*

4. [We could delete a lot of code relating to concurrency](https://blog.codinghorror.com/the-best-code-is-no-code-at-all/).

#### :space_invader: Bonus Round :space_invader:

When saving an LES, we could de-duplicate technologies which have a common parent (heating techs which belong to the same buffer, or non-heating techs which belong to the same endpoint). Two identical `units=1` solar arrays (all attributes are exactly the same) could be merged into one technology with `units=2`.

--

*Pinging @ChaelKruip, @dennisschoenmakers, and @grdw for feedback.*

**Comment by dennisschoenmakers** [comment]
> I'm on the fence about this, I would like to avoid adding a "..." button – at least at first – and see if a simple "Split" button will suffice. We could add "..." if necessary later.

I agree about that '...' button which is mysterious. Why not use *one* button that reads: Split, then you get that dialogue: 

![image](https://cloud.githubusercontent.com/assets/104830/16836429/c12b921e-49bd-11e6-959a-b1fb24bedbe6.png)

Default should be 2 (what if it is not divisible by 2? 😒 ) or the last chosen number. Disadvantage is a standard 'two click', but I wouldn't be bothered too much about that.

**Comment by antw** [comment]
> (what if it is not divisible by 2?)

Round one up, round one down. `units=3` => `units=2` + `units=1`.

**Comment by ChaelKruip** [comment]
I ❤️  the ideas in this post! 

> Should the split technologies both use the same profile, or should we auto-select a different profile for the new technology?

Auto-select a new one. This is the reason why people might want to split anyway.

> Should we support splitting buffers and all their technologies? (I think for simplicity, no).

I am not sure about this one. Perhaps not at first but heating is an important part of the load and being able to change concurrency of that is worth some effort IMO.

> Nice-to-have? Should we allow a user customise how many technologies are created? 

Yes. I think that we need to have an option to split into more groups than two. I like @dennisschoenmakers suggestion.

**Comment by grdw** [comment]
The split does need to be limited to `[technology_units, number_of_profiles].min`. Also - as discussed with @ChaelKruip yesterday the first approach shall be with non-buffer technologies. The technologies will automatically-assign a profile.

What I'm thinking about though. When clicking the split button it should only affect the technology to which the split button is attached.

Some code about how I think it might work for a single technology:

````javascript
$("a.btn.split").each(function () {
    $(this).off('click').on('click', Splitter.split.bind(this));
});

/*contents of Splitter*/
var Splitter = (function(){
    'use strict';
    
    return {
        split: function () {
            // Do an Ajax request to the server with the data of the technology
            // The Ajax request should grab the data and the ID of the technology.
            // This way  the Ajax request knows which technology field to update
            //
            // { 
            //    technology_data: $(this).parents(".technology").data(),
            //    technology_id:   $(this).parents(".technology").attr("id"),
            //    units:           $(this).data('max_units') || -> fetch content from input?
            // }
        }
    };
}());
````

Imagined contents of the `def split` action in `testing_grounds_controller.rb`
````ruby
def split
  @technology_id = params_for_splitting.fetch(:technology_id)
  @splitted_technologies, @technology_id = TestingGround::Splitter.new(params_for_splitting).split
end
...

private

def params_for_splitting
  params.require(:split).permit(:technology_data, :technology_id, :units)
end
````

Imagined contents of the `splitter.rb` or something in those lines.
````rb
class Technologies::Splitter
   def initialize(technology_data:, units:, **)
       @technology_data = InstalledTechnology.new(technology_data)
       @units = units
   end

   def split
      # do the splitting magic :) 
   end
end
````


Imagined contents of the `split.js.erb`
````javascript
<% @splitted_technologies.each do |technology| %>
  $("#<%= @technology_id %>").append("<%= render 'technology_template' %>");
<% end %>

$("#<%= @technology_id %>").remove();
````

**Comment by antw** [comment]
> Some code about how I think it might work for a single technology:

I'm not sure I follow the need for any Ruby, or the round-trip to the server. Can't this be done all in JS?

I was expecting that we might be able to reuse/adapt the "Add technology" code in the tech form, except that "Split" would:

* Add a new technology immediately below the one being split (the "source"), instead of at the top of the list.
* Take the attributes from the source technology instead of using the default attributes.
* Assign a new profile.
* Set the number of units on both the new and source technologies.

**Comment by grdw** [comment]
> Can't this be done all in JS?

It could I guess. 👍  I do need to draw up some different pseudo code than. You're take on the word 'split' would be cut in half I guess. So hit the split button, get two technologies with the units divided by two and assign a new profile for the technology below that.

However the BONUS ROUND should be done at the server end I guess. That makes a bit more sense to me.

> Take the attributes from the source technology instead of using the default attributes.

This would probably be the main reason why an *all js* approach would be better 👍

**Comment by grdw** [comment]
Pure JS solution would be something like:

````javascript
$("a.btn.split").off('click').on('click', Splitter.split.bind(this));

/*contents of Splitter*/
var Splitter = (function(){
    'use strict';
    
    return {
        split: function () {
            var tech = $(this).parents('.technology');
            
             for(var i = 0; i < units; i++) {
                var clone = tech.clone(true, true);
                tech.after(clone);
            }
            
            // set profiles
            // set units
        }
    };
}());
````
