### ISSUE TITLE
[Airbrake] [Staging] undefined method `total_yearly_costs' for #<InstalledHeatAssetPipe:0x007fe71c6d6d60>

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1269]
**Airbrake error:** [#4371](https://quintel.airbrake.io/projects/111227/groups/1729697056121404371)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `total_yearly_costs' for #<InstalledHeatAssetPipe:0x007fe71c6d6d60> ``
**Where:** `<no information>`
**Occurred at:** Jul 14, 2016 12:36:49 UTC
**First seen at:** Jul 14, 2016 12:36:49 UTC
**Occurrences:** 1 (1 since last deploy on Jul 14, 2016 12:24:48 UTC)

**URL:** `<no information>`
**File:** `[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb:17:in block in calculate
[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb:27:in block in group_sum
[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb:26:in each
[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb:26:in each_with_object
```

**Comment by grdw** [comment]
This is the delayed job handler freaking out because of the changes in #1237. 

Maybe we should merge these changes on a more quiet moment.
