### ISSUE TITLE
Unexpected deficits in heat load curve

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1278]
### Situation
The [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/627/heat_load) contains 4 nodes. 3 of them have heat buffers and load profiles attached to them. The hot water demand profile of "toerisme" is higher in summer than in winter. 

### Question
I would expect the capacity of my technologies to be sufficient to supply the demand. However, the heat load curve shows deficits. For example in a week in july (see image below). The position of the deficits surprises me as they occur when demand is relatively low. With higher demand there are no deficits.

Is it possible to see where those deficits come from? 

![image](https://cloud.githubusercontent.com/assets/19907658/16910479/288f5f30-4cd9-11e6-987c-17b7dadf3741.png)

cc @dennisschoenmakers

**Comment by antw** [comment]
There are water heating technologies installed for which a COP/Efficiency of 0.95 has been set. COP is presently supported only on heat pumps and will result in unknown behaviour when used on other technologies. Set the COP back to 1.0 (100% efficiency) and the deficit will go away.

**Comment by ChaelKruip** [comment]
Closing this.
