### ISSUE TITLE
Attributes of technologies: are all used in ETMoses?

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1279]
Do all the possible  attributes of the technologies relevant for ETMoses?
E.g. are there any technologies that use:
- O&M costs for ccs per full load hour: operation & maintenance costs for carbon capture & storage per full load hour
- O&M costs per full load hour: operation & maintenance costs per full load hour
 
A good enhancement for the future would be to only have the relevant attributes for each of the technologies there, or make these attributes grey and not possible to put a number there.

**Comment by ChaelKruip** [comment]
> Do all the possible attributes of the technologies relevant for ETMoses?

No, we currently import more than needed for some technologies. We are thinking about a more tailored approach as well.

**Comment by jorisberkhout** [comment]
@ChaelKruip , has this been solved by the commits in https://github.com/quintel/etmoses/pull/1298 ?

**Comment by ChaelKruip** [comment]
> @ChaelKruip , has this been solved by the commits in #1298 ?

Yes. Closing.

**Comment by MarjoleinSchwachofer** [comment]
I don't think my question is fully answered/solved with #1298. 
When I look at the technology table, still  O&M costs for ccs per full load hour is still visible; is white and it is possible to fill in a number. 
My suggestion would be that since almost all technologies do not have CCS, to remove this item for them (or grey). O&M costs per full load hour can still be available and is sufficient for these technologies.

**Comment by ChaelKruip** [comment]
> When I look at the technology table, still O&M costs for ccs per full load hour is still visible; is white and it is possible to fill in a number. 

Well spotted @MarjoleinSchwachofer! 

> My suggestion would be that since almost all technologies do not have CCS, to remove this item for them (or grey). 

👍 

> O&M costs per full load hour can still be available and is sufficient for these technologies.

I think we should hide this one as well because the full load hours are currently taken from ETE and are static. Once we dynamically determine FLHs (from the load profiles, see https://github.com/quintel/etmoses/issues/1312), we can re-introduce this attribute. Right now, it will lead to confusion. O&M cost per year can serve as a placeholder for now.

**Comment by ChaelKruip** [comment]
@antw can you also remove/hide the "O&M costs for ccs per full load hour" and "O&M costs per full load hour" from the technologies?
