### ISSUE TITLE
Deleting a load profile works, but gives leads user to a "page that doen't exist"

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1281]
When deleting a load profile the user is now sent to this page:
![image](https://cloud.githubusercontent.com/assets/19907658/16909782/09e83ae2-4cd5-11e6-99ad-2766bfc3a7eb.png)
I think it would be more appropriate to be sent to either the general load profile page, or to receive a message like "your load profile has been deleted successfully"

cc @dennisschoenmakers

**Comment by grdw** [comment]
Duplicate of #1257
