### ISSUE TITLE
Explanation of units

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1282]
Many people have problems with getting the units rights in the topology when using Units and children (for capacities etc.). Some text is added for this, but an calculation example would be better to explain this.

**Comment by jorisberkhout** [comment]
I have added two examples in https://github.com/quintel/etmoses/wiki/Topologies/f4200ca4af397b5b17130dbfe8da9feb92e6e6d0 and https://github.com/quintel/etmoses/wiki/Topologies/b44d86773c93341cf84b9f4c51c3af78b824cc44.

Closing this issue. Re-open if needed.

**Comment by MarjoleinSchwachofer** [comment]
This isn't how it works on the pro server. I made a seperate issue of this: #1340, but the outcome of this question should be explained on the WIKI
