### ISSUE TITLE
What should the 'split'-function do for buffers?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1285]
In general I think that splitting a buffer should to the following:

* Split the buffer into X buffers (as long as the 'units' of the parent buffer > X and the number of available distinct profiles > X)
* Connect the technologies which were connected to the parent buffer to the child buffers as fairly as possible

Specifying the second bullet is the aim of this ticket.

# Case one: same technologies, units = buffer_units

*Starting situation*:
* buffer_1: units = 2
* technology_1: units = 2, connected to buffer_1

*Action*: split into maximum number of groups

*Resulting situation*:
* buffer_1: units = 1
* technology_1: units = 1, connected to buffer_1
* buffer_2: units = 1
* technology_2: units = 1, connected to buffer_2

# Case two: same technologies, units > buffer_units

*Starting situation*:
* buffer_1: units = 2
* technology_1: units = 5, connected to buffer_1

*Action*: split into maximum number of groups

*Resulting situation*:
* buffer_1: units = 1
* technology_1: units = 3, connected to buffer_1
* buffer_2: units = 1
* technology_2: units = 2, connected to buffer_2

# Case three: mixed technologies, units = buffer_units

*Starting situation*:
* buffer_1: units = 2
* technology_1: units = 2, connected to buffer_1
* technology_2: units = 2, connected to buffer_1

*Action*: split into maximum number of groups

*Resulting situation*:
* buffer_1: units = 1
* technology_1: units = 1, connected to buffer_1
* technology_2: units = 1, connected to buffer_1
* buffer_2: units = 1
* technology_1: units = 1, connected to buffer_1
* technology_2: units = 1, connected to buffer_1

**Comment by grdw** [comment]
Copy pasting my content from issue #1283 

The splitting up of buffers is harder than first imagined. So we're going to give it a shot in this issue. How I'm currently thinking about this problem is as follows:

#### Scenario 1 (1 Buffer, 1 technology attached to buffer, units similar)

````
Buffer #1 (2)
↳ HP Water (2)
````
After split in groups of 2:

````
Buffer #1 (1)
↳ HP Water (1)
Buffer #2 (1)
↳ HP Water (1)
````

----

#### Scenario 2 (1 Buffer, 1 technology attached to buffer, units technology lower than buffer)

````
Buffer #1 (2)
↳ HP Water (1)
````
After split in groups of 2:

````
Buffer #1 (1)
↳ HP Water (1)
Buffer #2 (1)
````

In this case, what do you do with the buffer without technologies?

----

#### Scenario 2 (1 Buffer, multiple technologies)

````
Buffer #1 (4)
↳ HP Water (5)
↳ HP Space (3)
````
After split in groups of 4:

````
Buffer #1 (1)
↳ HP Water (2)
↳ HP Space (1)
Buffer #2 (1)
↳ HP Water (1)
↳ HP Space (1)
Buffer #3 (1)
↳ HP Water (1)
↳ HP Space (1)
Buffer #4 (1)
↳ HP Water (1)
````

----

Technically there are not many different scenario's except that the units might be different or there might be more or less technologies attached to the buffer. However maybe there are different solutions physically.

**Comment by ChaelKruip** [comment]
> Technically there are not many different scenario's except that the units might be different or there might be more or less technologies attached to the buffer.

@dennisschoenmakers had a very nice idea in my opinion: heating technologies should 'inherit' their 'units' from their associated buffer. So, if you have a buffer with units = 3, attaching a heat pump to it will automatically set the units = 3 for the heat pump (and the user cannot change this). 

This has the very favourable effect that splitting buffers will be identical to splitting normal technologies!

Some examples:

Q: What if the user connects technology B to a buffer that already has technology A
A: The buffer now has two technologies each with the number of units equal to those of the buffer

Q: What if a user connects technology A to a buffer that already has technology A
A: This is not allowed!

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @antw

**Comment by antw** [comment]
> @dennisschoenmakers had a very nice idea in my opinion: heating technologies should 'inherit' their 'units' from their associated buffer. So, if you have a buffer with units = 3, attaching a heat pump to it will automatically set the units = 3 for the heat pump (and the user cannot change this).

I like that a lot. Yes please. :grinning:

**Comment by grdw** [comment]
This makes everything way easier 👍  It's just splitting the buffer and duplicating all children. I like it.

**Comment by ChaelKruip** [comment]
I think we all agree about the idea of inheriting units for heaters from the buffer. This, however, implies that each unique heating technology gets its own buffer. I don't think this is a problem though. 

Right @antw @grdw?

**Comment by antw** [comment]
> This, however, implies that each unique heating technology gets its own buffer. I don't think this is a problem though.

That's interesting, I hadn't considered that. When you say that they would get their own buffer, do you mean that they would each:

1. Get their own heat buffer *and* demand profile, or
2. Each technology would have a buffer, but still use a shared demand profile between them.

(1) is how heating technologies *used* to be implemented.

**Comment by ChaelKruip** [comment]
> When you say that they would get their own buffer, [...]

What I mean is the following. If you have 10 residences, 5 with a combi-boiler and 5 with a heat pump, you will have two heating buffers (which could use the same or distinct profiles) each with units = 5. Buffer 1 will use combi-boilers and Buffer 2 will use heat pumps. The technologies still get their demand via their respective buffers. 

Another way of saying this is that it would not be possible to 'inherit' units and have a buffer with units = 10 with 5 combi-boilers and 5 heat pumps attached. You *could* add both combi-boilers and heat-pumps to the same buffer would they would have the same units (10 in this case) as the buffer.

**Comment by antw** [comment]
> If you have 10 residences, 5 with a combi-boiler and 5 with a heat pump, you will have two heating buffers (which could use the same or distinct profiles) each with units = 5. Buffer 1 will use combi-boilers and Buffer 2 will use heat pumps.

:+1:

That seems quite sensible to me. I'm guessing many (real-world) houses will only have one type of heating technology, so giving each type it's own buffer is probably a better representation of reality anyway.

**Comment by ChaelKruip** [comment]
Closing as this issue is out-dated.
