### ISSUE TITLE
[Airbrake] [Production] undefined method `attributes' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1287]
**Airbrake error:** [#2203](https://quintel.airbrake.io/projects/111227/groups/1732593164220872203)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `attributes' for nil:NilClass ``
**Where:** `gas_asset_lists#calculate_cumulative_investment`
**Occurred at:** Jul 18, 2016 12:31:55 UTC
**First seen at:** Jul 18, 2016 12:31:55 UTC
**Occurrences:** 1 (1 since last deploy on Jul 18, 2016 11:54:39 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/506/gas_asset_lists/26/calculate_cumulative_investment](https://moses.energytransitionmodel.com/testing_grounds/506/gas_asset_lists/26/calculate_cumulative_investment)
**File:** `[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:10:in block in decorate
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:7:in map
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:7:in decorate
[PROJECT_ROOT]/app/services/gas_asset_lists/calculator.rb:4:in initialize
```

**Comment by grdw** [comment]
Closing due to duplicate: #1288
