### ISSUE TITLE
Being able to delete a (private) LES

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1289]
A LES should be removeable by it's creator and an admin user.

*A LES consists of the following parts:*

- A topology
- A market model
- A business case
- A behavior profile
- A selected strategy
- A gas asset list
- A heat source list
- A heat asset list
- Testing ground delayed jobs

----

*The following items can be deleted with the LES:*
- A business case
- A selected strategy
- A gas asset list
- A heat source list
- A heat asset list
- Testing ground delayed jobs

*The following items can't be deleted:*
- A behavior profile

*The following items I'm unsure if they should be deleted (maybe they can be deleted if no other user is currently using the topology or market model?):*
- A topology
- A market model

**Comment by ChaelKruip** [comment]
> maybe they can be deleted if no other user is currently using the topology or market model?

👍
