### ISSUE TITLE
Importing storage technologies

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#129]

**Comment by grdw** [comment]
I fixed this last week by giving the `import_from` attribute for batteries in the `technologies`-table an `electricity_output_capacity` property. But EtModel doesn't export the batteries correctly. Also `Generic Battery` isn't working in the `technologies` table, with this setting.

**Comment by ChaelKruip** [comment]
> I fixed this last week by giving the import_from attribute for batteries in the technologies-table an electricity_output_capacity property.

For storage options, both `electricity_output_capacity` and `electricity_input_capacity` need to be assigned. For now, we can set them to the same value.

**Comment by antw** [comment]
> Also Generic Battery isn't working in the technologies table, with this setting.

Ignore "Generic battery" for now; it was used temporarily for testing and has been replaced by `households_flexibility_p2p_electricity` / "Battery". I'll make a note to remove it.

**Comment by ChaelKruip** [comment]
`households_flexibility_p2p_electricity` is not picked up correctly by ETLoader yet it seems.
I have 60% batteries in my scaled scenario but none in my technology table.
