### ISSUE TITLE
Definitions colours Yearly gas flow graph on the wiki

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1290]
In the definitions of the colours of the yearly gas flow chart on the wiki: https://github.com/quintel/etmoses/wiki/Gas-network#loads-and-flows , everything is explained by the _connector_ between two pressure levels. Shouldn't there be a distinction between a _connector_ and a _compressor_? For example: isn't the Feed-in dependent on a compressor instead of a connector?

**Comment by Sanne512** [comment]
What's the status?

**Comment by jorisberkhout** [comment]
Good point, @Sanne512 . I have clarified the documentation in  https://github.com/quintel/etmoses/wiki/Gas-network/7685b4590bc1fa6a376e8ddf11521442d9205f14.

Closing this issue. Re-open if needed.
