### ISSUE TITLE
Why does my battery not discharge

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1295]
### Question
In my LES I have a battery connected. The battery does not seem to discharge? How can I solve this? 

### Information
[LES](https://beta-moses.energytransitionmodel.com/testing_grounds/630).
To the "PV plant" node 3 PV plants and one large battery are connected.
The battery does charge initially, but does not seem to decharge.

![image](https://cloud.githubusercontent.com/assets/19907658/16920055/6873a222-4d0c-11e6-8567-c78e52ea732d.png)

cc @dennisschoenmakers

**Comment by DorinevanderVlies** [comment]
I added the label bug

**Comment by antw** [comment]
@DorinevanderVlies I've been experimenting which this scenario on my own machine. While I can see the same thing, can you identify any time in the LES when the batteries are not discharging, but you expect that they should be?

It would be helpful since I could check out the behaviour each technology at that point in time, and then find out why the loads are the way they are.

**Comment by DorinevanderVlies** [comment]
I would expect my batteries to discharge during night, when there is no sun, but there is still demand.

So, an example of a point in time where I would expect my batteries to discharge is January 1, 22:00h

**Comment by antw** [comment]
I'm going to use the dreaded phrase: this is a feature and not a bug. 😱 

Calling it a "feature" might be too strong a term, but this *is* a property of our network calculator and not a mistake. Storage in ETMoses is selfish and prefers to keep energy in the endpoint to which it is attached. If there are no consumption technologies in the endpoint which want the energy, the battery will keep it for later.

The best analogy I can think of is: if you install a solar panel and battery in your house, you want to get home at night to find a full battery ready for you to use. You wouldn't be very happy if you found that your neighbour (another endpoint) had used all the energy you saved.

Perhaps we might be better calling these "Household batteries" or "Endpoint batteries"; either way I think the behaviour you are seeing is correct, at least in our current model.

@ChaelKruip What do you think about renaming the battery? Are either of those terms to your liking?

--

I created [a copy of your LES](https://beta-moses.energytransitionmodel.com/testing_grounds/639) which adds a P2P battery on the three main endpoints – each with a third of the capacity and volume of the original – and removed the battery from the solar PV node. There's not enough excess energy to fill all three, but if you look at the "Gebouwen" node, as the solar PV energy begins to disappear you'll see the battery discharging to meet the needs of consumption on that endpoint.

![screen shot 2016-07-20 at 16 39 37](https://cloud.githubusercontent.com/assets/4383/16992815/b78e88e4-4e98-11e6-84a5-0bea9309eba0.png)
