### ISSUE TITLE
EV profile-names should describe a bit better what they represent

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1306]
@jorisberkhout can you have a look this with me some time?

**Comment by jorisberkhout** [comment]
Each availability profile is based on a typical commute distance which is followed during workdays and several "free time" trips, which are used in the weekends, which are the same for all profiles. The main difference between the availability profiles is thus in the distance of the commute. To reflect this a bit better, I have renamed the profiles on the Beta server to `EV availability profile <S/M/L> commute <#>`, where `<S/M/L>` is short, medium or large and `<#>` is a number. The table below specifies the exact distance of the commute for each profile.

| Profile name | Commute distance (km) |
|---|---|
| `EV availability profile short commute 1` | `4.3` |
| `EV availability profile medium commute 1` | `24.8` |
| `EV availability profile medium commute 2` | `31.0` |
| `EV availability profile medium commute 3` | `35.2` |
| `EV availability profile medium commute 4` | `40.1` |
| `EV availability profile long commute 1` | `50.8` |
| `EV availability profile long commute 2` | `58.8` |
| `EV availability profile long commute 3` | `65.9` |
| `EV availability profile long commute 4` | `77.0` |
| `EV availability profile long commute 5` | `91.8` |
| `EV availability profile long commute 6` | `109.2` |

I have also updated the documentation in https://github.com/quintel/etmoses/wiki/Profiles/c35cf02e4863f3940d0d871802280ce96da1f217.

Closing this issue.
