### ISSUE TITLE
Secondary heat assets table does not update costs correctly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1308]
When changing the type of connection, the attributes do not update in [my LES](https://beta-moses.energytransitionmodel.com/testing_grounds/602/edit)
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16985972/4c14ec02-4e84-11e6-9484-b4ab66e22ef9.png)

**Comment by grdw** [comment]
Note to self: only for second row... event listeners gone off.
