### ISSUE TITLE
Are we double-counting secondary heat infra?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1310]
When adding a district heater from the ETM, this has an investment cost of 6050 EUR and O&M costs of 70 EUR/year:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16985899/cd9ca77a-4e83-11e6-8f26-fd5cb9699389.png). These costs are typically payed by the customer (the stakeholder associated with the end-points).

At the same time, we also assign costs to secondary infra per connection:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16986013/98edb28e-4e84-11e6-92ac-a742d61f7f1c.png). The system operator pays these by default. 

My feeling is that we should not make the customer pay so much (or at all?) for the district heater in his/her house.

@Sanne512 what do you think?

**Comment by Sanne512** [comment]
Before I can answer this question I have another question: is the district heater in the technology table that follows from the ETM connected to the heat infrastructure in ETMoses?

**Comment by ChaelKruip** [comment]
> Before I can answer this question I have another question: is the district heater in the technology table that follows from the ETM connected to the heat infrastructure in ETMoses?

Yes, that is its only function: to connect the heat network to the buffers in the households.

**Comment by Sanne512** [comment]
> My feeling is that we should not make the customer pay so much (or at all?) for the district heater in his/her house.

I agree, I can't think of any situation where a customer pays for the district heating infrastructure other than their connection to the heat network.

**Comment by ChaelKruip** [comment]
> I agree, I can't think of any situation where a customer pays for the district heating infrastructure other than their connection to the heat network.

So, shall we put the costs for the 'connection' (actually the heat exchanger) to zero? The user can than add the costs for the number of connections in the market model as with gas and electricity.

**Comment by Sanne512** [comment]
> So, shall we put the costs for the 'connection' (actually the heat exchanger) to zero? The user can than add the costs for the number of connections in the market model as with gas and electricity.

Yes! This sounds like a good idea. 

Including @MarjoleinSchwachofer

**Comment by ChaelKruip** [comment]
> So, shall we put the costs for the 'connection' (actually the heat exchanger) to zero?

Assigning @antw to make this happen.
