### ISSUE TITLE
Round values down in the front-end, keep the original value in some part of the input

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1311]
There should be a way to split up rounded and non-rounded values in the front-end.

Something like:

````haml
%input{ value: 1.0, data: { non_rounded_value: 1.0000003 } }
````

Renders as:
````
[ 1.0 ]
````

When saving this it should look at `non_rounded_value`. However when someone changes the value of this input to '2.0' the `non_rounded_value` will just update along with it to: '2.0'. However, I can imagine this is going to get really annoying. Let's say you're really specific about your numbers and you want:

2.12345 units of something.

The front-end saves this, than when returning back to the page it rounds it down to: 

````haml
%input{ value: 2.123, data: { non_rounded_value: 2.12345 } }
````

Renders as:
````
[ 2.123 ]
````

If you want to change the last two digits... 

@ChaelKruip , what do you think? Is it likely to happen or am I just making up some once in a lifetime scenario?

**Comment by ChaelKruip** [comment]
> If you want to change the last two digits...

You did successfully change those digits right? Only the front-end does not show it which is fine.

> @ChaelKruip , what do you think?

I think your approach looks fine. I'd like to hear @antw opinion too as this seems like something he might have come across.

**Comment by grdw** [comment]
*Todo:*
- [ ] Never round anything (show everything raw)
- [ ] Write a little JS class that rounds 'most' inputs (sets data-raw).
- [ ] Unrounded value should be stored in `data` attribute.
- [ ] Show unrounded raw value in front-end when clicking
- [ ] Onblur should round again
