### ISSUE TITLE
Consistency check between topology and market model too stringent

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1313]
IN [my LES](https://beta-moses.energytransitionmodel.com/testing_grounds/641) I have the stakeholders which are in the applied to stakeholder' column of the market model in my topology but still get the warning that I need to fix my market model or topology.

To be clear: the only relevant market model stakeholders that need to be present in the topology are those in the 'applied to stakeholder' column of the market model.

**Comment by grdw** [comment]
> which are in the 'measured' column in my topology 

I don't get what you mean by this. It should be 'measured' column of your *market model* I guess. The topology just has a `stakeholder` attribute and that's it. In [here](https://github.com/quintel/etmoses/blob/master/app/services/finance/business_case_validator.rb#L20) you see which stakeholder colum it fetches from the Market model.

**Comment by ChaelKruip** [comment]
> I don't get what you mean by this.

I was unclear and rephrased it.

> It should be 'measured' column of your market model I guess. 

No, the stakeholders in the 'measured at stakeholder' are the ones that should be present in the topology:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17851192/080fc9c2-6861-11e6-88ac-43b6c0372a54.png)

**Comment by grdw** [comment]
The LES id = 641

The `topology_id` is 309 and the `market_model_id` is 293.

<img width="769" alt="screen shot 2016-08-23 at 14 49 48" src="https://cloud.githubusercontent.com/assets/2676542/17892359/26d3b586-6941-11e6-93e3-f71361645a53.png">

And I don't really see anything happening locally.  Did you edit one of the two afterwards or? I can't seem to reproduce the behavior you specified, also the code agrees with your description: 

> No, the stakeholders in the 'measured at stakeholder' are the ones that should be present in the topology:

Which is what I meant by the "Measured column". The label of the column is called "Measured at stakeholder" but the attribute is called "applied_stakeholder". So the validator validates the correct columns.

**Comment by ChaelKruip** [comment]
Closing as this seems to be fixed indeed.
