### ISSUE TITLE
[Airbrake] [Staging] Validation failed: Technology profile includes a connection to missing node "PV plant"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1315]
**Airbrake error:** [#5222](https://quintel.airbrake.io/projects/111227/groups/1734747130954235222)
**Airbrake project:** ETMoses

**Error type:** `ActiveRecord::RecordInvalid`
**Error message:** `` Validation failed: Technology profile includes a connection to missing node "PV plant" ``
**Where:** `testing_grounds#save_as`
**Occurred at:** Jul 21, 2016 11:51:26 UTC
**First seen at:** Jul 21, 2016 11:51:26 UTC
**Occurrences:** 1 (1 since last deploy on Jul 20, 2016 11:58:10 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/629/save_as](https://beta-moses.energytransitionmodel.com/testing_grounds/629/save_as)
**File:** `[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/validations.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in block in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in block in with_transaction_returning_status
```

**Comment by grdw** [comment]
Hmm.. looks like somebody renamed the Topology names.... funny that nobody does this until now haha. This should not be possible in the first place however I have no simple fix on how to prevent a user from doing this.

**Comment by grdw** [comment]
With the new topology editor this is not possible anymore. Therefor closing this issue.
