### ISSUE TITLE
Is it possible to simulate heat cold storage in ETMoses

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1316]
I am going to work on a use case which wants to include heat cold storage (WKO) is this a possibility in ETMoses and how? @ChaelKruip

**Comment by ChaelKruip** [comment]
> I am going to work on a use case which wants to include heat cold storage (WKO) is this a possibility in ETMoses and how? @ChaelKruip

Not really. ETMoses does not store cold or explicitly models cooling at the moment. You could simulate/fudge WKO up to a certain level by increasing the COP of a (ground) heat pump and making it more expensive (at least the investment). This is in first order what the effect of WKO will be. This will not depend on the time-resolved heat-demand and temperature though...

Closing this. Please re-open if your question has not been satisfactorily answered.
