### ISSUE TITLE
Stacked load should be ordered according to variability/spikiness

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1318]
Stacked plots are difficult to read because curves with high variability are stacked under more well-behaved ones:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17104051/64448872-5281-11e6-8e50-fe18166937ab.png)

A possible technique to improve this is to order the curves according to how spiky they are. A measure for spikiness could be the following:
```
spikiness = MAX(curve) / SUM(curve)
```
The curves should be ordered beginning with the lowest spikiness up to the highest spikiness.

**Comment by grdw** [comment]
I copied the 'spikiness' method from ETModel and implemented it in ETMoses.
