### ISSUE TITLE
Heating technologies should not have a storage volume

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1323]
I don't know if these numbers are actually used but I'm worried as they are non-zero:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17133219/8651c99e-5325-11e6-8c2b-eb0f5c03d9a4.png)

**Comment by antw** [comment]
Volume is always inherited from the buffer to which the heating technology belongs, so that number is not used. Nonetheless, I agree that no value should be set.

**Comment by ChaelKruip** [comment]
> I agree that no value should be set. 

It would be also good to remove it from the above interface as it would be always be zero.
