### ISSUE TITLE
Working of the P2G stratgy is strange/not correct

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1325]
I was testing the P2G strategy, but it works very strange and not realistic. 

It looks like **all** te PV electricity is converted to gas, instead of only the amount of PV that leads to congestion. It sometime also creates extra electricity need from the grid; probably because the in-house direct use of PV isn't done anymore.
I do not think this is the way you would want it and it is unrealistic. Can this be changed?

![image](https://cloud.githubusercontent.com/assets/17849585/17138939/b9c3dc14-5342-11e6-8a27-a0100031280e.png)

It also looks like power to gas doesn't use any electricity, see image below. There are conversion losses and energy is needed for this. Isn't this taken into account?
![image](https://cloud.githubusercontent.com/assets/17849585/17139254/05e4c29c-5344-11e6-8956-f08f184dbe7d.png)

@ThomBuijs @JeroenvdLogt FYI

**Comment by ChaelKruip** [comment]
> It looks like all te PV electricity is converted to gas, instead of only the amount of PV that leads to congestion.

To clarify: The P2G strategy uses (or should use) *excess* production only. Just as P2H, it was never the intention to make P2G aware of network congestion. 

> It sometime also creates extra electricity need from the grid; probably because the in-house direct use of PV isn't done anymore.

This is indeed unexpected as P2G should use *excess* electricity only!

**Comment by MarjoleinSchwachofer** [comment]
I still think it is strange to convert all the PV into gas. If you have no electricity congestion, you would want to feed electricity back to the grid and not make gas of it with extra losses and feed this back to the grid (as there will probalby more gas produced than you can use yourself at that time). Otherwise a gas storage tank would be needed in ETMose with this strategy as you wouldn't want to produce that much gas. This technology isn't avaliable yet in ETMoses.

**Comment by antw** [comment]
> This is indeed unexpected as P2G should use excess electricity only!

I'm looking into this. That extra electricity load should not be there.

**Comment by MarjoleinSchwachofer** [comment]
I looked into it, and this is probably because the pv is not used for other parties/technologies on the node, so they have to use electricty from the HV level, instead of the locally produced PV. Is this correct?

**Comment by antw** [comment]
It took me longer to figure this out that it should have. 😊 

The reason is simple: "Households 2" and "Households 3" have excess solar PV production in these time periods. Since nothing else consumes that energy, it ends up consumed by the P2G technology. That is why there is consumption.

Here is 11:00 on 12th July:

| Households 1 | Households 2 | Households 3 |
| --- | --- | --- |
| <img width="255" alt="screen shot 2016-08-02 at 12 47 01" src="https://cloud.githubusercontent.com/assets/4383/17327385/84687ef4-58af-11e6-999b-8243d06da2f5.png"> | <img width="224" alt="screen shot 2016-08-02 at 12 49 28" src="https://cloud.githubusercontent.com/assets/4383/17327391/92e26184-58af-11e6-8d59-cce966f10e18.png"> | <img width="230" alt="screen shot 2016-08-02 at 12 49 48" src="https://cloud.githubusercontent.com/assets/4383/17327398/9c43d82a-58af-11e6-84d0-9a78c540e7e7.png"> |

0.26kW and 0.57kW of excess respectively, equals 0.83kW of electricity (converted to gas) on Households 1.

**Comment by MarjoleinSchwachofer** [comment]
So no energy is lossed in the conversion from electricity to gas? 42,02+0,83=42,85kW and this is also the gas value of what is fed back into the grid

**Comment by antw** [comment]
> So no energy is lossed in the conversion from electricity to gas?

Currently, yes this is correct. It would not be terribly difficult to support efficiency/CoP on P2G, but we'd prefer to do it *right* and implement a solution which could apply to all technologies. See #805 for more.

> 42,02+0,83=42,85kW and this is also the gas value of what is fed back into the grid

Also correct. An issue with the "stacked" chart has been fixed, and you can now see the P2G consumption:

<img width="557" alt="screen shot 2016-08-02 at 14 27 41" src="https://cloud.githubusercontent.com/assets/4383/17330075/4b19ec56-58bd-11e6-876e-d753dd00239e.png">

**Comment by MarjoleinSchwachofer** [comment]
I now understand how the stratgy works in ETMoses. P2G can also use excess pv from another endpoint to produce power-to-gas. I will add this in the documentation.

I will discuss the working of the strategy with my team members when they get back from their holiday. Because I think that a strategy that looks at congestion would be a good enhancement. But I will make a new item of it if they agree , labelled enhancement.  

@antw  In my LES I do not see P2G consumption in the stacked chart. Does P2G use electricity in your modelling? Would it get a number?
Also, should P2G not also be an item in the stacked gas chart?

**Comment by antw** [comment]
> @antw In my LES I do not see P2G consumption in the stacked chart. Does P2G use electricity in your modelling? Would it get a number?
Also, should P2G not also be an item in the stacked gas chart?

It does use electricity, and yesterday I fixed an issue with P2G not appearing in the stacked chart. If you still don't see P2G in the chart, would you mind including a link to the LES and, if possible, on which days/time-periods you would expect to see the load?

I might be stating the obvious, but also make sure you turn the strategy view on (the stacked chart defaults to showing you the loads with all the strategies turned off; which is probably something we should change):

![screen-shot-2016-08-03-at-13 22 07](https://cloud.githubusercontent.com/assets/4383/17365546/9293fb14-597e-11e6-8682-dfca170f8b81.png)

**Comment by MarjoleinSchwachofer** [comment]
That''s indeed the solution, now I see a number. I didn't know I had to switch the button and because in the customise technology behaviour bar the strategy was selected, I though this was included in the graph.

This is a good thing to add in the result section of the documentation.

**Comment by MarjoleinSchwachofer** [comment]
> Also, should P2G not also be an item in the stacked gas chart?
Shouldn't this be an enhencement? Then you can see where your gas comes from.

**Comment by ChaelKruip** [comment]
> Shouldn't this be an enhencement? Then you can see where your gas comes from.

It is shown in the load chart as @antw pointed out:

> It does use electricity, and yesterday I fixed an issue with P2G not appearing in the stacked chart.

It is also shown in the gas load chart *if* production (feed-in) exceeds consumption (negative loads signify net production).

**Comment by antw** [comment]
> > Also, should P2G not also be an item in the stacked gas chart?
>
> Shouldn't this be an enhencement? Then you can see where your gas comes from.

Sorry, let me clarify: the consumption of *electricity* by P2G will show up in the stacked chart. Production (of gas) is currently not shown – see #1063 – but we do intend to fix this shortly.

**Comment by MarjoleinSchwachofer** [comment]
>Sorry, let me clarify: the consumption of electricity by P2G will show up in the stacked chart.
 
This is clear. 
I just wondered wether the gas production would be added to the stacked gas chart. Beacuse PV is already an item in the electricty chart, it just doesn't show correctly. But P2G is not an item in the **gas stacked chart** yet. Will this be added in your improvements in  #1063, because it isn't explicitly stated there?

**Comment by ChaelKruip** [comment]
> But P2G is not an item in the gas stacked chart yet. Will this be added in your improvements in #1063, because it isn't explicitly stated there?

I have added it now so we don't overlook adding P2G. 

Closing this issue.
