### ISSUE TITLE
wrong link from beta ETMoses to beta ETM

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1327]
When you want to go from the beta ETMoses to the beta ETM to make a new LES, it doesn't work:
![image](https://cloud.githubusercontent.com/assets/17849585/17140744/d8de4eac-5349-11e6-951d-9d0c486bfeb9.png)

The link is wrong, it should be 
https://beta-pro.energytransitionmodel.com
instead of 
https//beta-pro.energytransitionmodel.com
( a colon is missing after https)

**Comment by grdw** [comment]
Do you remember where you found this link?

**Comment by MarjoleinSchwachofer** [comment]
This link opens when I click on the green bar 'Go to the energy tranistion model' at https://beta-moses.energytransitionmodel.com/welcome
