### ISSUE TITLE
The 125 mbar pressure level is not shown in the `Load on the gas network` chart

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#1329]
The `Load on the gas network` chart shows the 4, 8 and 40 bar pressure levels, and I would expect it to show the 125 mbar level as well. What do you think, @ChaelKruip ?

<img width="582" alt="screen shot 2016-07-27 at 09 22 56" src="https://cloud.githubusercontent.com/assets/4669028/17167154/d1998c8c-53db-11e6-878b-6069b7ebba78.png">

**Comment by ChaelKruip** [comment]
> What do you think, @ChaelKruip ?

Me too.

**Comment by ChaelKruip** [comment]
Assigning @antw to pick this up.
