### ISSUE TITLE
Power-to-heat profiles are still shown in list of all available profiles

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#1331]
Power-to-heat no longer uses its own profile but follows the load profile for the buffer to which it is connected, right @ChaelKruip ?

<img width="385" alt="screen shot 2016-07-27 at 10 46 11" src="https://cloud.githubusercontent.com/assets/4669028/17169395/907d5d58-53e7-11e6-8f28-32cd09daebb0.png">

**Comment by ChaelKruip** [comment]
Assigning @grdw as he knows how to do this without anything breaking...

**Comment by grdw** [comment]
> without anything breaking...

Famous last words

**Comment by grdw** [comment]
I removed the category on beta since there were no profiles with that load profile category. Production however still has [6 profiles left](https://moses.energytransitionmodel.com/profiles) for Power-to-Heat. What should we do with those? Deprecate them?

**Comment by ChaelKruip** [comment]
> Deprecate them?

Yes.

**Comment by grdw** [comment]
I've done it throguh the rails console on production. 👍  Therefor closing.
