### ISSUE TITLE
Domestic hot water profiles need to be improved

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#1337]
The domestic hot water (DWH) profiles are used in ETMoses to determine how much energy is drawn from the water heating buffer at every time step. An aggregated version of this profile is also used in ETModel to determine how much energy is drawn from the power-to-heat buffer.

Both profiles are based on [this study](http://sel.me.wisc.edu/trnsys/trnlib/iea-shc-task26/iea-shc-task26-load-profiles-description-jordan.pdf), in which the (unrealistic) assumption is made that every household has a bath. Filling a bath costs much more hot water than any other application of how water and therefore introduce quite big spikes in the profiles, which appear very unrealistic.

I will see if I can improve the DHW profiles by finding other studies and/or talking to experts.

**Comment by MarjoleinSchwachofer** [comment]
I also got some questions about where the heat demand profiles come from. Could this information be added to the documentation?  I can only find something about this at the heat pumps, but this goes for all the heating technolgies so this should be explained generally or at the buffers.

**Comment by jorisberkhout** [comment]
I did some more research into DHW consumption and profiles and think that our current profiles can be improved in three ways:
- create separate profiles for household with and without bath (I found that about 1 in every 7 Dutch households has a bath)
- create profiles for different sizes of households (1, 2, 3 and 4 persons)
- update the water consumption per type of event and number of times such event occurs per day

I will update the script to create the following 17 profiles:
- [ ] 3 randomly generated profiles for 4 different household sizes **without** bath (12 in total)
- [ ] 1 randomly generated profiles for 4 different household sizes **with** bath (4 in total)
- [ ] 1 aggregated profile which takes into account the fact that 1 in 7 households has a bath

I will also:
- [ ] update the documentation

@MarjoleinSchwachofer , I have updated the documentation regarding hot water profiles in https://github.com/quintel/etmoses/wiki/Profiles/5b669d29ae3b3d40f28864acb620d47aba51fca8. I think this answers your concerns.

**Comment by MarjoleinSchwachofer** [comment]
Thanks Joris. I will let my collegue know that it can be found on the Wiki.

**Comment by jorisberkhout** [comment]
I have created and uploaded the aforementioned 17 DHW profile by:

- adding the script that generated them in https://github.com/quintel/etmoses/commit/989cec1ebf5b8f073b3548400569adb56ba17003
- updating the documentation in https://github.com/quintel/etmoses/wiki/Profiles/408305c3ad912cee4141150a604fb3b7715a4bdf
- uploading the new profiles (starting with `DHW_demand_profile...`) on the Live server

I think these profiles are a major improvement over the previous ones, but would be happy to hear your feedback @ChaelKruip , @MarjoleinSchwachofer and @DorinevanderVlies .

Closing this issue.

**Comment by MarjoleinSchwachofer** [comment]
I have no knowledge about heat demand profiles. @JeroenvdLogt can you look at this after you holiday?
