### ISSUE TITLE
New stakeholder wanted: "Heat System Operator"

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1341]
Quoting from https://github.com/quintel/etmoses/issues/1338

> Maybe there could be a new stakeholder defined for the heat network? Otherwise it will be the same stakeholders als the system operator for E and G in the business case and currently this are seperate parties. Heat producers currenlty are also sometimes the network operator, but there can also be split and a seperate producer and system operator. I suggest the heat system operator. Is it difficult to add this as a new stakeholder?

**Comment by antw** [comment]
Perhaps we should default *assets* (pipes, connections, compressors) to the `heat system operator` and heat *sources* to the `heat producer`?

**Comment by ChaelKruip** [comment]
> Perhaps we should default assets (pipes, connections, compressors) to the heat system operator 

You seem to be referring to gas assets (there are no compressors for heat) Gas assets should be defaulted to "system operator". For the primary and secondary heat assets I fully agree!

> and heat sources to the heat producer?

👍

**Comment by antw** [comment]
> You seem to be referring to gas assets (there are no compressors for heat) Gas assets should be defaulted to "system operator". For the primary and secondary heat assets I fully agree!

Urgh, yes; what was I thinking? I meant the primary and secondary assets. :grinning:

**Comment by antw** [comment]
Fixed by 6ad67ef9.
