### ISSUE TITLE
Strategies - strange priorities and enhancement documentation

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1342]
I have some questions about and enhancements for the strategies

•	Priorities: The priorities of the strategies is strange. Solar capping should be one of the last things you do, first buffering, storage, postponing baseload etc.

•	Storage in EV: Name doesn’t directly display the difference between buffering and storage in EV. Storage means it also delivers back to the grid (V2G). Many people do not know the difference between bufffering and storage they way it is used in ETMoses. I would therefore want to add the (V2G) to the name, not only in documentation but in the ETMoses list.

Enhancement documentation:
•	An explanation for  P2G and P2H should be added with what is meant with excess PV (could be interpreted as part that leads to congestion, but this isn’t the case as I learnt in #1325 )
•	Saving:  examples should be given of how electricity can be saved in the amount the strategy applies. And the source for this.

**Comment by antw** [comment]
> Priorities: The priorities of the strategies is strange. Solar capping should be one of the last things you do, first buffering, storage, postponing baseload etc.

Solar capping is indeed the very last strategy to be applied.

**Comment by ChaelKruip** [comment]
> Solar capping is indeed the very last strategy to be applied.

Changed this in the documentation.

> I would therefore want to add the (V2G) to the name, not only in documentation but in the ETMoses list.

Changed it in documentation and front-end.

> An explanation for P2G and P2H should be added with what is meant with excess PV (could be interpreted as part that leads to congestion, but this isn’t the case as I learnt in #1325 )

The documentation about strategies has a list of definitions where excess is defined as follows:

"Local excess: production which is not cancelled by consumption in the same time-step for the 
same end-point"

> Saving: examples should be given of how electricity can be saved in the amount the strategy applies. And the source for this.

A simple example has been added. Also the source (internal communication with Alliander and TU/e experts) has been included.

Closing this issue. Please re-open if your questions have not been answered satisfactorily.

**Comment by MarjoleinSchwachofer** [comment]
>Solar capping is indeed the very last strategy to be applied.

>Changed this in the documentation.

Was the priority list only wrongly documented? Or should also be changed in the modelling?


I've also added to  the documentation of P2G: Excess production from another node can also be used to produce gas in the case that it is not used in any other point in the LES and it should otherwise be transported to the HV grid.

**Comment by ChaelKruip** [comment]
> Was the priority list only wrongly documented? Or should also be changed in the modelling?

Only documentation 😄 

> I've also added to the documentation of P2G: Excess production from another node can also be used to produce gas in the case that it is not used in any other point in the LES and it should otherwise be transported to the HV grid.

👍

**Comment by MarjoleinSchwachofer** [comment]
>  Saving: examples should be given of how electricity can be saved in the amount the strategy applies. And the source for this.

> A simple example has been added. Also the source (internal communication with Alliander and TU/e experts) has been included.
  I did not mean numerically, but how (e.g. using no air conditioning )
@JeroenvdLogt can you say anything about this?

**Comment by MarjoleinSchwachofer** [comment]
See question above

**Comment by ChaelKruip** [comment]
I have updated the documentation with the examples given in the expert session at Alliander. 

Closing.
