### ISSUE TITLE
Can a merit order for heat be used in the tariffs of the market model or is this the electricty merit order?

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1343]
In the heat network, a heat merit order is introduced. Can this also be used in the tariffs, or is the merit order which you can select at kWh heat produced the electricity merit order ?

**Comment by ChaelKruip** [comment]
> In the heat network, a heat merit order is introduced. Can this also be used in the tariffs, or is the merit order which you can select at kWh heat produced the electricity merit order ?

The merit order price used in the market model transactions is indeed the electricity merit order price. 

Closing. Please re-open if this does not satisfactorily answer your question.
