### ISSUE TITLE
yearly costs instead of depreciation costs

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1349]
Since the depreciation costs are in reality not only the depreciation costs, but the yearly costs, including depreciation and O&M cocts, wouldn't it be better to call it yearly costs everywhere?

**Comment by ChaelKruip** [comment]
> Since the depreciation costs are in reality not only the depreciation costs, but the yearly costs, including depreciation and O&M cocts, wouldn't it be better to call it yearly costs everywhere?

Very good suggestion! In the back-end we already call it that but we should change it in the front-end as well. 👍

**Comment by MarjoleinSchwachofer** [comment]
This should also be changed in the documenation. I therfore reopened this issue and added the label documentation.

**Comment by ChaelKruip** [comment]
> This should also be changed in the documenation. I therfore reopened this issue and added the label documentation.

I have updated the documentation [about gas assets](https://github.com/quintel/etmoses/wiki/Gas-network) and [business cases](https://github.com/quintel/etmoses/wiki/Business-cases) to reflect the changes. Closing.

Please re-open if I missed anything.
