### ISSUE TITLE
[Airbrake] [Staging] key not found: "default"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1350]
**Airbrake error:** [#6178](https://quintel.airbrake.io/projects/111227/groups/1743487572348746178)
**Airbrake project:** ETMoses

**Error type:** `KeyError`
**Error message:** `` key not found: "default" ``
**Where:** `testing_grounds#data`
**Occurred at:** Aug 02, 2016 13:18:43 UTC
**First seen at:** Aug 02, 2016 13:18:43 UTC
**Occurrences:** 1 (1 since last deploy on Aug 02, 2016 09:56:44 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/614/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/614/data.json)
**File:** `[PROJECT_ROOT]/app/models/calculation/technology_load.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:82:in fetch
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:82:in block in comps_for
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each_with_object
```

**Comment by grdw** [comment]
I can't seem to reproduce this issue. Therefor closing.
