### ISSUE TITLE
Cloning a LES should let you choose a new name

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1352]
Now, the same name is used which is confusing.

**Comment by antw** [comment]
Since this is almost identical to the "Save a new Local Energy Solution" button on the edit page, I think upon completing this request we should also make the "Clone" button visible on private LESes (currently it shows only on those which are public).

**Comment by grdw** [comment]
I was a bit to quick with that one. 

> we should also make the "Clone" button visible on private LESes 

Hmm.. should we? I don't have a really strong opinion about this matter but maybe people who work at Alliander do? What insights do you have @ChaelKruip

**Comment by ChaelKruip** [comment]
> Hmm.. should we?

Yes, I think so. Only the owners (and admin's) can use this button for private LESses so it is a very logical way to go IMO.

@dennisschoenmakers @MarjoleinSchwachofer do you have an opinion?

**Comment by MarjoleinSchwachofer** [comment]
It isn't directly clear to me what the difference is, so I would have to look into this.
@ThomBuijs @JeroenvdLogt: do you already have an opinion on this?

**Comment by MarjoleinSchwachofer** [comment]
If I clone  my own LES, cloning works and works the same as save as, only do not have to go to click edit, go to the general page en find this button (which needs a lot of more steps and is not directly visible). Is this correct?
I tried to clone a public LES from someone else, but nothing happened. This would be a handy function  and than it would be logical to give it another name so that it can be clear which was the orginal from the other person and which one is you new LES.

**Comment by grdw** [comment]
>cloning works and works the same as save as, only do not have to go to click edit, go to the general page en find this button (which needs a lot of more steps and is not directly visible). Is this correct?

Yes. This is correct.

> I tried to clone a public LES from someone else, but nothing happened

Could you be more specific? Nothing as in, the Clone button didn't work, the 'Save' button didn't bring you to the page of the cloned LES?

**Comment by MarjoleinSchwachofer** [comment]
Then the button didn't work. However I tried it again today and now it worked.

**Comment by ChaelKruip** [comment]
Can we close this @grdw?

**Comment by grdw** [comment]
I think we can 👍
