### ISSUE TITLE
Do buffers still show up in the heat load chart?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1353]
In [my LES](https://beta-moses.energytransitionmodel.com/testing_grounds/677/heat_load) I have set my combi-boilers to "buffering" but I don't see the buffers show up in the heat load chart:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17407055/304313e4-5a66-11e6-8b69-cf93b193daeb.png)

**Comment by antw** [comment]
Erm... uh oh. :worried:

Why would a combi-boiler place energy into a buffer? *Heat pumps* will fill up an endpoint buffer; other technologies will not. If set to "buffering", your combi-boiler will respect the capacity of the buffer before failing over to "boosting" technologies, but it will only run as much as needed to meet demand. It won't place extra energy into the buffer.

I thought that was half the point of #626; that *all* electric heating technologies were being enabled for buffering like heat pumps?

If you [swap the combi-boiler for heat pumps](https://beta-moses.energytransitionmodel.com/testing_grounds/678/heat_load) you will see buffering taking place.

![screen shot 2016-08-04 at 17 53 40](https://cloud.githubusercontent.com/assets/4383/17410622/6a246a26-5a6c-11e6-96f1-8cc5f2f55542.png)

**Comment by antw** [comment]
[The documentation seems to support my view](https://github.com/quintel/etmoses/wiki/Buffers#space-heating), so perhaps I'm just misunderstanding the question?

The "buffer" series will not show up on the chart, or in the legend, if there is no buffering taking place.

**Comment by ChaelKruip** [comment]
> Why would a combi-boiler place energy into a buffer?

My bad. I was under the impression that all technologies behaved the same when set to buffering. Thanks for enlightening me @antw!

> If set to "buffering", your combi-boiler will respect the capacity of the buffer before failing over to "boosting" technologies, but it will only run as much as needed to meet demand. It won't place extra energy into the buffer.

I don't see the physical rationale for this behaviour. Could we not disable the 'buffering' option for all technologies that don't really buffer (i.e., place extra energy into the buffer)? That would be less confusing for users in the end and just as useful as the current implementation IMO.

> If you swap the combi-boiler for heat pumps you will see buffering taking place.

👍

**Comment by antw** [comment]
> I don't see the physical rationale for this behaviour. Could we not disable the 'buffering' option for all technologies that don't really buffer (i.e., place extra energy into the buffer)? That would be less confusing for users in the end and just as useful as the current implementation IMO.

Let's do this. :+1:
