### ISSUE TITLE
Doubts about investment and O&M cost calculation in business case

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1354]
### Summary
I have some doubts about the business case of stakeholder customer AC1. The investment and O&M costs seem too low.

### Details
[This is the LES](https://beta-moses.energytransitionmodel.com/testing_grounds/680/edit)
The "huishoudens" node is assigned to "customer AC1".
The most costly technologies are:
- Combined network gas, 1406 pieces.
The inital investment is  ‎€1500 (over 15 years), O&M costs are  ‎€156.2 per year
- 50 hybrid heat pumps investment (€1500+€3235), O&M costs are (€156.2+€97) per year
- other technologies

In total I would expect minimally 
- 1406*((1500/15)+156)= €359936, for combined network gas
- 50*(€1500+€3235)/15+(€156.2+€97)=€28433, for heat pumps

So, in my business case I would expect stakeholder Customer AC1 to pay at least €388,369 to itself.
However, this is just €31,703

![image](https://cloud.githubusercontent.com/assets/19907658/17476857/60e04234-5d62-11e6-8ed6-043085872fa4.png)

**Comment by antw** [comment]
Should now be fixed; good catch!

![screen shot 2016-08-08 at 18 11 23](https://cloud.githubusercontent.com/assets/4383/17488936/8cf4b2f2-5d93-11e6-92ff-dcfa35a4088f.png)
