### ISSUE TITLE
Save all and view gas load button triggers errors in my LES

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1358]
In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/685), my gas asset page hangs after saving:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17511925/91ac001a-5e25-11e6-9d7f-2998c39c2f58.png)

**Comment by grdw** [comment]
You can reproduce it by:

1. Hit apply button
2. Than change something (or not?)
3. Hit "Save all and view gas-load"

**Comment by grdw** [comment]
I found the problem after sitting with @ChaelKruip for 5 minutes.
