### ISSUE TITLE
Surplus should be plotted as production (negative y-axis)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1359]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17512000/f329cc8c-5e25-11e6-8c67-a79b025c89f6.png)

It is production which cannot be accommodated by the network, so it should be shown as production.

**Comment by grdw** [comment]
Assigning @antw because this should be returned as a negative serie from the gas flow calculation. I could also do it in the .js but this sounds unelegant.
