### ISSUE TITLE
[Airbrake] [Staging] 845: NaN not allowed in JSON

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1362]
**Airbrake error:** [#3750](https://quintel.airbrake.io/projects/111227/groups/1749254454825693750)
**Airbrake project:** ETMoses

**Error type:** `JSON::GeneratorError`
**Error message:** `` 845: NaN not allowed in JSON ``
**Where:** `calculation#heat`
**Occurred at:** Aug 10, 2016 12:16:34 UTC
**First seen at:** Aug 10, 2016 12:16:34 UTC
**Occurrences:** 1 (1 since last deploy on Aug 10, 2016 09:50:43 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/685/calculation/heat](https://beta-moses.energytransitionmodel.com/testing_grounds/685/calculation/heat)
**File:** `[GEM_ROOT]/gems/json-1.8.2/lib/json/common.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/json-1.8.2/lib/json/common.rb:223:in generate
[GEM_ROOT]/gems/json-1.8.2/lib/json/common.rb:223:in generate
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/json/encoding.rb:96:in stringify
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/json/encoding.rb:34:in encode
```

**Comment by antw** [comment]
This was related to the ETSource chemical / industry update and should now be resolved.
