### ISSUE TITLE
Counting buffers issue for #1322

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1363]
The current situation for buffers is that a buffer contains multiple heating technologies. When creating a LES the following happens:

````
Endpoint #1
- Buffer space heating #1
 -> HP1
 -> HP2
 -> GH1
- Buffer water heating #1
 -> HP1
 -> HP2
 -> GH1
````

Right now this is changed in #1322 to:

````
Endpoint #1
- Buffer space heating #1 -> HP1
- Buffer space heating #2 -> HP2
- Buffer space heating #3 -> GH1
- Buffer water heating #1 -> HP1
- Buffer water heating #2 -> HP2
- Buffer water heating #3 -> GH1
````

However the counting is a bit off when there are multiple end-points.

````
Endpoint #1
- Buffer space heating #1 -> HP1
- Buffer space heating #3 -> HP2
- Buffer space heating #5 -> GH1
- Buffer water heating #1 -> HP1
- Buffer water heating #3 -> HP2
- Buffer water heating #5 -> GH1

Endpoint #2
- Buffer space heating #2 -> HP1
- Buffer space heating #4 -> HP2
- Buffer space heating #6 -> GH1
- Buffer water heating #2 -> HP1
- Buffer water heating #4 -> HP2
- Buffer water heating #6 -> GH1
````

And I'm wondering how I could get:
````
Endpoint #1
- Buffer space heating #1 -> HP1
- Buffer space heating #2 -> HP2
- Buffer space heating #3 -> GH1
- Buffer water heating #1 -> HP1
- Buffer water heating #2 -> HP2
- Buffer water heating #3 -> GH1

Endpoint #2
- Buffer space heating #4 -> HP1
- Buffer space heating #5 -> HP2
- Buffer space heating #6 -> GH1
- Buffer water heating #4 -> HP1
- Buffer water heating #5 -> HP2
- Buffer water heating #6 -> GH1
````

**Comment by antw** [comment]
Perhaps they can be renumbered as a separate step after building the list of technologies? I guess new buffers could have a completely random ID (`SecureRandom.uuid`) instead of having an incrementing number, and then a suitable name is assigned purely for display purposes?

```ruby
# Bad pseudo-code; sorry!

class BufferCounter
  def initialize
    @counters = Hash.new { |h, k| h[k] = 0 }
  end

  def next_number(technology_key)
    @counters[technology_key] += 1
  end
end

# Create technology profile, then...  -------------------------------

counters = BufferCounter.new

technologies.each do |tech|
  tech.assign_name(counters)
end

# installed_technology.rb -------------------------------------------

class InstalledTechnology
  def assign_name(counters)
    if type == 'buffer_water_heating' || type == 'buffer_space_heating'
      self.name = "#{ type.humanize } ##{ counters.next_number(type) }"
    end
  end

  # ...
end
```

**Comment by ChaelKruip** [comment]
@grdw are HP1 and HP2 the same *type* of technology? If so, why are they getting their own buffer in the new situation:
```
Endpoint #1
- Buffer space heating #1 -> HP1
- Buffer space heating #2 -> HP2
- Buffer space heating #3 -> GH1
- Buffer water heating #1 -> HP1
- Buffer water heating #2 -> HP2
- Buffer water heating #3 -> GH1
```
?

Wouldn't it be more logical to group the same technologies:
```
Endpoint #1
- Buffer space heating #1 -> HP1. HP2
- Buffer space heating #2 -> GH1
- Buffer water heating #1 -> HP1, HP2
- Buffer water heating #2 -> GH1
```
?

**Comment by ChaelKruip** [comment]
Perhaps a bit more background for @antw (not that I don't like his solution!) to fully understand why the situation is as it is:

Technologies 'know' to which end-point they belong. The reverse is not true (as @grdw told me): end-points don't know which technologies are attached to them.

If end-points would have this info, however, more intuitive naming would be a lot simpler: 

Even worse pseudo-code:
1. assign technologies to end-points
2. loop through end-points:
   for each end-point:
   determine the number of unique technologies and assign buffers to those (groups) of technologies

@antw do you think it would be possible/a good idea to make the end-points 'aware' of the technologies that are assigned to them?

**Comment by antw** [comment]
> Technologies 'know' to which end-point they belong. The reverse is not true (as @grdw told me): end-points don't know which technologies are attached to them. [...] @antw do you think it would be possible/a good idea to make the end-points 'aware' of the technologies that are assigned to them?

I'm guessing this is specific to the ETEngine import? If so, I'll defer to whatever @grdw thinks is best because I'm not familiar enough with the buffer-import code to know how difficult this is. Assigning a number to a buffer doesn't seem to depend on the endpoint though.

**Comment by grdw** [comment]
> @grdw are HP1 and HP2 the same type of technology? If so, why are they getting their own buffer in the new situation:

No, these are two different one's. Sorry, for the ambiguity.

> Assigning a number to a buffer doesn't seem to depend on the endpoint though.

Yes I agree, they shouldn't. Maybe I should extract the `Counter` as a separate module.
