### ISSUE TITLE
Create the possibility to save a LES as "read-only"

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1366]
### Situation
I want to share some of my LESses with other people.
However, I do not want other people to be able to apply changes.

### Request
Therefor I would like to be able to save my LES as "read-only".
In this "read-only" LES and option to "save as a new LES" (so adjustments can be made in an other LES) would be nice.

**Comment by ChaelKruip** [comment]
> Therefor I would like to be able to save my LES as "read-only".

I think your LES is read-only by default. Right @antw?

I'm not sure if everyone can 'clone' your LES now. @antw could you enlighten us?

**Comment by DorinevanderVlies** [comment]
> I think your LES is read-only by default. Right @antw?

I'm not sure, if I open a random LES which was not created by me it seems that I'm allowed to make changes. (See image below)

![image](https://cloud.githubusercontent.com/assets/19907658/17584789/ca184230-5fb8-11e6-81e8-efe1346ee211.png)

**Comment by antw** [comment]
Indeed. [Only the author – or an admin user – may edit a LES](https://github.com/quintel/etmoses/blob/b4838ac1df4256f4d9dda58fc3227672e651a9be/app/policies/private_policy.rb#L3). We QIs are all admins, so it might not be obvious to us, but "normal" visitors should not be able to edit someone else's LES.

**Comment by DorinevanderVlies** [comment]
>Indeed. Only the author – or an admin user – may edit a LES. We QIs are all admins, so it might not be obvious to us, but "normal" visitors should not be able to edit someone else's LES.

Perfect! 

Can a "normal" visitor save the LES as a new LES and make changes to that one?

**Comment by antw** [comment]
> Can a "normal" visitor save the LES as a new LES and make changes to that one?

Yes, that's correct. Ordinary visitors can still clone the LES, and will then be able to make changes to *their* copy.

Viewing someone else's LES as a non-admin:

<img width="521" alt="screen shot 2016-08-11 at 10 48 45" src="https://cloud.githubusercontent.com/assets/4383/17584998/4aebce7a-5fb1-11e6-93fb-b8a9450308fc.png">

Viewing my clone of that LES, as a non-admin:

<img width="634" alt="screen shot 2016-08-11 at 10 49 11" src="https://cloud.githubusercontent.com/assets/4383/17585003/5401ea80-5fb1-11e6-99f3-d9f266143822.png">
