### ISSUE TITLE
Changing concurrency should not redistribute the technologies over the end-points

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#137]
The distribution of profiles and technologies over end-points should be decoupled in the code.

**Comment by grdw** [comment]
This is decoupled now in the code. However if you change certain technologies on one endpoint and change the concurrency of the overall technologies, the technology on that single endpoint will be distributed over the other endpoints aswell (as to be expected).

Maybe it's an option to lock a certain technology row from being taken into the concurrency calculation.

**Comment by ChaelKruip** [comment]
> Maybe it's an option to lock a certain technology row from being taken into the concurrency calculation.

As discussed with @grdw: The relation between node/end-point and technology should not change due to any operation except explicit re-assignment by the user.

**Comment by grdw** [comment]
Fixed with: 
https://github.com/quintel/etmoses/commit/f8aedfc23c0457d45bde989032adb9e6d2fb0beb
