### ISSUE TITLE
Load graph is not displayed but keeps loading

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1374]
I am trying to let ETMoses calculate my LES, but it keeps loading and doesn't display the chart.
https://moses.energytransitionmodel.com/testing_grounds/532
Are you by any change working on the PRO-server?

**Comment by antw** [comment]
I have fixed this LES manually. There were some hot water technologies assigned to a buffer which didn't exist; unfortunately there's no way for you to fix this yourself. This tends to happen when changing [the concurrency settings](https://github.com/quintel/etmoses/wiki/Concurrency). We have a replacement for this feature in-progress (#1322), and once finished this problem should not occur anymore.

**Comment by ThomBuijs** [comment]
Thank you for fixing it
