### ISSUE TITLE
All of a sudden change in Data HHP components

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1376]
Related: #1262 

I'm trying to split up the hybrid heat pump in components. However, I'm storing the data as such:

````ruby
[
  ...
   {"buffer"=>"buffer_space_heating_1",
    "components"=>
     [{"type"=>"households_space_heater_hybrid_heatpump_air_water_electricity_electricity", "capacity"=>4.9, "performance_coefficient"=>4.5},
      {"type"=>"households_space_heater_hybrid_heatpump_air_water_electricity_gas", "capacity"=>"22.0", "performance_coefficient"=>1.067}],
    "composite"=>false,
    "concurrency"=>"max",
    "full_load_hours"=>1197,
    "initial_investment"=>"2481.0",
    "node"=>"Households 1",
    "om_costs_per_year"=>252.892561983471,
    "performance_coefficient"=>3.583,
    "sticks_to_composite"=>true,
    "technical_lifetime"=>15,
    "type"=>"households_space_heater_hybrid_heatpump_air_water_electricity",
    "units"=>1},
  ...
]
````

Which makes sense. This data is taken from a pry session:

````ruby

    126: def technology_profile=(techs)
 => 127:   case techs
    128:     when Hash   then super(TechnologyList.from_hash(techs))
    129:     when String then super(TechnologyList.load(techs))
    130:     else             super
    131:   end
    132: end
````

However, when I check the content of the  `self.load`  method in `TechnologyList` something weird happened to the components... 

````ruby
 {"buffer"=>"buffer_space_heating_1",
    "capacity"=>nil,
    "composite"=>false,
    "composite_value"=>nil,
    "congestion_reserve_percentage"=>nil,
    "demand"=>nil,
    "position_relative_to_buffer"=>nil,
    "profile"=>nil,
    "type"=>"households_space_heater_hybrid_heatpump_air_water_electricity",
    "units"=>1,
    "volume"=>nil,
    "composite_index"=>nil,
    "concurrency"=>"max",
    "full_load_hours"=>1197,
    "initial_investment"=>2481.0,
    "om_costs_for_ccs_per_full_load_hour"=>nil,
    "om_costs_per_full_load_hour"=>nil,
    "om_costs_per_year"=>252.892561983471,
    "performance_coefficient"=>3.583,
    "technical_lifetime"=>15,
    "associates"=>[],
    "node"=>"Households 1",
    "profile_key"=>nil,
    "components"=>
     ["Hybrid heat pump space heating (electricity) (households_space_heater_hybrid_heatpump_air_water_electricity_electricity)",
      "Hybrid heat pump space heating (gas) (households_space_heater_hybrid_heatpump_air_water_electricity_gas)"]}, <-- Say, whaaat.
````

Taken from pry session point:

````ruby
    12: def self.load(data)
 => 13:   binding.pry
    14:   data.blank? ? new({}) : from_hash(JSON.parse(data))
    15: end
````

Is there some step in between that does this (and automatically adds a load of attributes (I also don't know where for instance `profile` comes from)?). I'm sort of blindly assuming that the `self.load` comes directly after the part where I'm adding the `technology_profile` and that there are no steps in between.

**Comment by antw** [comment]
Looks like something is calling `#to_s` on the InstalledTechnology for the components?

```ruby
InstalledTechnology.new(type: :households_space_heater_hybrid_heatpump_air_water_electricity_electricity).to_s
# => "Hybrid heat pump space heating (electricity) (households_space_heater_hybrid_heatpump_air_water_electricity_electricity)"
```

**Comment by antw** [comment]
[Maybe here?](https://github.com/quintel/etmoses/pull/1322/commits/9c1ce2a9d5d675512ba12cf66710bc8d455d0557#diff-7a156f529649278a2dcfb8039d893abeR19)

**Comment by grdw** [comment]
I found out what it was. There's a bit of a ping-pong going on when creating a LES. The `technology_profile` is first put into `InstalledTechnology` objects right [here](https://github.com/quintel/etmoses/blob/master/app/models/technology_list.rb#L26). Than it dumps again [here](https://github.com/quintel/etmoses/blob/master/app/models/technology_list.rb#L62) and loads again (causing the actual problem). The issue was in the dumping part, that one turned the components into `InstalledTechnology` objects while it should've turned them into a Hash aswell.

Therefor closing this issue.
