### ISSUE TITLE
For higher nodes, the stacked chart for gas does not show the load correctly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1380]
In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/700), the gas-load on the lowest (end-node) level looks like:
![etmoses_](https://cloud.githubusercontent.com/assets/1303760/17742817/d0c33e12-64a1-11e6-9e9f-fd69ce0bdbcc.png)
Clicking a higher level, the chart freezes:
![etmoses_](https://cloud.githubusercontent.com/assets/1303760/17742848/f2d2cc98-64a1-11e6-879d-d7146489033c.png)

**Comment by antw** [comment]
A "Charts are empty" error is raised whenever clicking a node which has a non-existent load (e.g. clicking an MV node while viewing gas). Ideal behaviour would be to show an empty chart with a "there is no load to show" (or words to that effect) like we do with the ETModel excess events chart:

![screen shot 2016-08-23 at 09 04 04](https://cloud.githubusercontent.com/assets/4383/17884503/93f001e6-6910-11e6-8a2f-7a141da0738a.png)

I can pick this up later in the week if @grdw is busy with other things.

**Comment by grdw** [comment]
I'll take a look :)

**Comment by grdw** [comment]
<img width="1155" alt="screen shot 2016-08-23 at 12 41 11" src="https://cloud.githubusercontent.com/assets/2676542/17889095/ed89add8-692e-11e6-8444-ed23a7c7a723.png">

I managed to make it like this. Also I'm not keen on showing the axis of the chart. This is mainly due to the distortion of the message. You're telling the user that there's no chart available (yet) and you're already showing them a bit of the chart which is a bit confusing when you think about it.

**Comment by ChaelKruip** [comment]
> I managed to make it like this.

I think this is fine but I would say "All load is zero for Households 1"

Even better would be to include the selected type of load in the message: "All *gas* load is zero for Households 1" because many users are confused by the workings of the carrier-selection button.

**Comment by grdw** [comment]
> "All load is zero for Households 1"

The check is now purely for *['all load'](https://github.com/quintel/etmoses/pull/1386/files#diff-50b59e598d9801423712d14f44c844ecR119)*. If there's only `gas` load zero, you could still show the chart if there's electricity or heat, right?

**Comment by ChaelKruip** [comment]
> The check is now purely for 'all load'.

That's fine. I meant to say that you can have the following working chart:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17893892/ab2e59c0-6947-11e6-807f-f346a300f06f.png)
But if you change the carrier (to gas) the chart is empty:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17893976/efd71ea4-6947-11e6-9f48-22fc16c4cd59.png)

Some people might be less confused if you tell them that the chart is empty because there is no **gas** load (given that they selected the 'gas' version of the chart).
If you'd tell them that there is no load at all, you are actually lying because there might be electricity or heat load that you are not currently displaying.
