### ISSUE TITLE
Consumption of P2G should be shown on higher nodes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1389]
Currently it is not shown for higher nodes:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17931596/8f58d03e-6a0c-11e6-80ae-1fda0069a006.png)
Although it is available for lower nodes:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17931606/9ff4c04c-6a0c-11e6-84f9-dfe600661742.png)

**Comment by antw** [comment]
The P2G is using the excess solar production on the endpoint. I don't see why it's would load appear on the MS-LS node.

This sounds very much like #1378?

**Comment by ChaelKruip** [comment]
> This sounds very much like #1378?

Yes! And I understand my own confusion a bit better now: because it cancels local production, its effects are locally only. In my mind, each technology was having impact on the higher nodes but this is a misconception.
