### ISSUE TITLE
How does the P2H strategy work for heat pumps?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1395]
I'm testing the P2H strategy with heat pumps, but I can't figure out why there is no difference between the standard case and the one with the strategy applied. I'm using this [les](https://beta-moses.energytransitionmodel.com/testing_grounds/712). When I add an electric heater there is a change between the strategy applied and not applied but it's still looking weird to me, as there is an increase in electricity consumption without excess PV electricity.

![30 heat pumps for water heating and excess solar](https://cloud.githubusercontent.com/assets/20039533/17971017/4c14ef6a-6ad9-11e6-8e58-97b86de3bbc3.PNG)
This is with only heatpumps
![30 heat pumps and 1 electric water heater for water heating and excess solar](https://cloud.githubusercontent.com/assets/20039533/17971026/5627bf3c-6ad9-11e6-8c76-60fcca012073.PNG)
This is with 1 additional electric water heater.

As it looks to me right now, this strategy isn't working properly, but maybe I'm missing something so if someone can please explain it to me that would be great :)

**Comment by ChaelKruip** [comment]
> I'm testing the P2H strategy with heat pumps, but I can't figure out why there is no difference between the standard case and the one with the strategy applied.

My suspicion is that the buffers are already full and therefore no extra heat can be stored with the P2H strategy. This would be solved by https://github.com/quintel/etmoses/issues/670 right @antw?

> When I add an electric heater there is a change between the strategy applied and not applied but it's still looking weird to me, as there is an increase in electricity consumption without excess PV electricity.

I think this is due to the difference in COP. If no strategy is applied, heat pumps (with COP = 4.5) fill the buffers. If the strategy is applied, a part of the heat is provided by the electric heater (with efficiency = 1.0) so more electricity is needed.

@antw is my explanation consistent with your implementation?

**Comment by antw** [comment]
Prior to [the recent P2H changes]((https://github.com/quintel/etmoses/commit/522ceca32f4256f64d838256f765ba997f272dcf)), heat pumps would *always* convert excess electricity to (buffered) heat. The strategy only affected the (now-removed) dedicated P2H technology.

In making those changes, the dedicated P2H tech was removed and all electric heating technologies we made to buffer whenever the P2H strategy was turned on. Heat pumps were left unchanged, which means they will still always buffer regardless of whether the strategy is turned on or off.

**Comment by ThomBuijs** [comment]
Okay, so if I understand correctly the P2H strategy doens't use heat pumps?

**Comment by ChaelKruip** [comment]
> Prior to the recent P2H changes, heat pumps would always convert excess electricity to (buffered) heat.

Unless the buffer is full right? But that would change with #670...

> if I understand correctly the P2H strategy doens't use heat pumps?

Yes and no. It uses them alright but because the buffers are already full due to the default buffering strategy it has no visible effect.

**Comment by ThomBuijs** [comment]
> Yes and no. It uses them alright but because the buffers are already full due to the default buffering strategy it has no visible effect.

This means that due to the default buffering of heat pumps the P2H strategy can't be applied when there are heat pumps in the technology table, since it will cause the buffers to be full. Therefore, the other heating technologies can't convert excess solar electricity to heat for the buffer.

**Comment by antw** [comment]
> Unless the buffer is full right? But that would change with #670...

Correct. If the buffer is full, no further buffering can occur and the excess electricity will go unused (returned to the grid, or used by a buffer or technology in another endpoint).

> This means that due to the default buffering of heat pumps the P2H strategy can't be applied when there are heat pumps in the technology table, since it will cause the buffers to be full.

That depends on how much buffering volume, and how many heat pumps, are available in your LES. If you have a large volume and few heat pumps, there will still be plenty of opportunity for other technologies to convert excess electricity to heat.

**Comment by ChaelKruip** [comment]
> Or will this be different when #670 is implemented?

Yes. That is exactly why I think #670 is important and I hope we can make it happen this sprint. That will allow buffers to be filled to a higher temperature (bigger volume) when the P2H is in effect. So, the buffers will reserve some extra space for those moments that there is excess electricity production.

**Comment by ThomBuijs** [comment]
> That depends on how much buffering volume, and how many heat pumps, are available in your LES. If you have a large volume and few heat pumps, there will still be plenty of opportunity for other technologies to convert excess electricity to heat.

If I'm correct, the number of heat pumps is equal to the number of buffers, since I can't change the number of heat pumps directly. So I guess this means that I would have 2 (or more) buffers where each buffer has its own heating technology, for example heat pumps for buffer water heating #1 and electric boilers for water heating #2. In this case then the effect of P2H would become visible for the electric boiler part I think. However if I do so, the electric boiler is switched on continuously.

Without strategy the electric boiler is on during the day when there is hot water demand.
![geen strategie](https://cloud.githubusercontent.com/assets/20039533/17973292/29637ab4-6ae2-11e6-9e7c-d8b9262b5983.PNG)

With strategy the electric boiler is continuously on.
![met strategie](https://cloud.githubusercontent.com/assets/20039533/17973327/49fcefbc-6ae2-11e6-85d9-cf52558f5819.PNG)

This technology should then use the excess electricity of the PV to fill the buffer right, not try to fill it completely? As it looks right now, the heating technologies try to fill the buffer completely when P2H is switched on.

**Comment by ThomBuijs** [comment]
So for my own understanding, P2H strategy isn't working in the way that it uses excess (solar) electricity to produce heat (but instead tries to fill the buffer completely). When #670 is implemented then the P2H strategy will convert the excess electricity to heat? Because in my opinion this is not the case right now.

**Comment by antw** [comment]
> So for my own understanding, P2H strategy isn't working in the way that it uses excess (solar) electricity to produce heat (but instead tries to fill the buffer completely).

You're correct about this; energy is being taken from the grid in order to fill the buffers, and not just from excess solar PV. I'm fairly sure that's a mistake and it will be corrected momentarily.

I'm unclear whether heat pumps are permitted to take energy from the grid when buffering – the documentation doesn't say one way or another. Historically they *have* been allowed to do this in our model, and for now they will continue to do so. @ChaelKruip What do you think?

**Comment by ChaelKruip** [comment]
>  @ChaelKruip What do you think?

In default 'buffering' mode, heat pumps all fill up the storage as quickly as they can using local production first and electricity from the grid secondly if needed.

If the 'only buffer heat pumps if network has spare capacity'-strategy is invoked, electricity is only taken from the grid if this does not lead to congestion.

**Comment by ThomBuijs** [comment]
Yes I agree and it is clear to me. So for now the P2H is not working but will be fixed with the help of #670, is this correct. Then I will test this strategy again when this is implemented.

**Comment by ChaelKruip** [comment]
Closing this issue as it is superseded by #670

**Comment by ThomBuijs** [comment]
I'm currently testing the P2H strategy for heat pumps but there not working as they should. I am using this [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/712) but as you can see there is no change in the excess local electricity (due to PV). 
![p2h with heat pumps](https://cloud.githubusercontent.com/assets/20039533/18226155/c48595f4-7203-11e6-923c-85b8a24aa9c4.PNG)
It was my understanding that when the #670 was completed the buffer has a minimum volume for meeting heat demand and an upper limit volume which is filled when there is excess electricity. It works this way for the electric heating technologies, except the heat pumps. So in my opinion the P2H strategy isn't working for heat pumps at the moment. Therefore I am reopening this issue.

**Comment by antw** [comment]
There are no electric heating technologies installed in that LES except for the heat pump. Heat pumps may always buffer electricity into heat, therefore there is no change in behaviour when enabling the P2H strategy.

In addition, our implementation of heat pumps presently cannot distinguish between energy coming from the grid and energy coming from excess local production (solar PV), therefore they do not fill the the "upper" volume.

In [a clone of your LES](https://beta-moses.energytransitionmodel.com/testing_grounds/715) I swapped the gas space heater for an electric heater, and now there is a (small) difference:

![screen shot 2016-09-03 at 17 36 45](https://cloud.githubusercontent.com/assets/4383/18226272/177e0b3e-71fe-11e6-832c-5ae54644e1ba.png)

**Comment by ThomBuijs** [comment]
Exactly, therefore issue #626 should be open I guess. Since the heatpump is not influenced by the P2H strategy. Or am I missing something?
