### ISSUE TITLE
Total consumption/production of a connection should be consistent with its load profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#14]
# Background

From the scaled ETM scenario we know the number of households and the technologies that they contain. For each technology we also know the proportion of the total electricity demand we assign to that technology. 

# Problem

For the time-resolved load calculation we will use load-profiles that are generated by some tool that knows nothing about the capacity and full load hours (and, therefore, demand) of the ETM technologies. In general the demand of the technology resulting from the ETM will not be consistent to what the load-profile describes.

# Possible solutions

There are two solutions:
* scale the load-profiles to match the demand. In this case the surface area under the load-curves will  equal the demand of the technology. This is what we currently do with load-profiles for volatiles and must-run CHPs in Merit.
* scale the peaks of the profile to match the maximum capacity of the technology. That is: **input** capacity for consuming technologies and **output** capacity for producing technologies.
* generate a profile that reproduces both the maximum capacity and the total demand of the technology.

# Complications

The first option is energetically correct but may lead to peaks in the load to **exceed** the maximum capacity of the technology. Because the load is the main concern of ETLoader, the second approach may be more appropriate. 
The third option is obviously the best but might be hard to accomplish because the 'load profile generator' that we will like use does not allow the user to use the total yearly demand as input variable.

Including @antw @dennisschoenmakers @jorisberkhout @AlexanderWirtz

**Comment by dennisschoenmakers** [comment]
Is it possible (for us all) to have a look at the Load Profile Generator that we would like to use from Enschede?

**Comment by ChaelKruip** [comment]
> Is it possible (for us all) to have a look at the Load Profile Generator that we would like to use from Enschede?

Yes, if you run Windows on your computer. Unfortunately, the guys that wrote the LPG do not want to port it to other operating systems for the moment.

**Comment by ChaelKruip** [comment]
Closing this as this is not an actionable ticket anymore.
