### ISSUE TITLE
What is the effect of changing the charging power and battery volume?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1400]
I would like to make a LES with electric vehicles with a different then default charging power and battery volume. Can I just use the standard availability scenario's which have a default charging power of 3.7 kW and battery capacity of 25 kWh? Or what kind of assumptions am I making when I for example change the charging power to 11 kW and battery volume to 85.5 kWh?

**Comment by ChaelKruip** [comment]
The profiles for EV are such that they cannot be meaningfully used with other charging capacities and storage volumes. It is, however, not difficult to produce profiles for other combinations of capacity and volume with [this Python script](https://github.com/quintel/etmoses/blob/master/scripts/electric_vehicles/EV_availability_profile_generator.py). 

You can download, edit and run the script yourself and upload the profiles. If this does not work out, I can also run the script and send you the profiles you need.

**Comment by ThomBuijs** [comment]
I am not too familiar with Python and at the moment I cannot install it on my laptop. If it isn't too much trouble can you make a profile for a charging power of 11 kW and a battery volume of 85.5 kWh? These are the specifications of a Tesla  Model S P90D. Thank you in advance

**Comment by ChaelKruip** [comment]
The profiles (11 different ones) can be downloaded here:
[tesla_profiles.zip](https://github.com/quintel/etmoses/files/444247/tesla_profiles.zip)

You can upload them into the application by choosing 'create new load profile' from the profile menu.

**Comment by ChaelKruip** [comment]
Let me know if this does not solve your problems.

**Comment by ThomBuijs** [comment]
Thank you very much!
