### ISSUE TITLE
I'am not able to access a own private LESS

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#1413]
When I want to look at a own private LES at the regulering@alliander.com account on PRO server I get an error message. Refreshing and recalculation is not working. 

Showcase buurtbatterij - buurtbatterij en capping - aangepaste business case has number 522.

![image](https://cloud.githubusercontent.com/assets/7781037/18271286/a1f97732-7431-11e6-83e7-60e468f56d9e.png)

**Comment by grdw** [comment]
You have to be signed in as "regulering@alliander.com" to view the LES for "regulering@alliander.com". I could give the LES to your own personal account though. It looks as though you're singed in with that account (you can verify by clicking on "Your account", right next to the "Sign out" button).

**Comment by grdw** [comment]
It should be fixed now. This is still bug-worthy though. What I saw was the following:

- The LES belonged to regulering@alliander.com
- The Market model aswell
- The Topology belonged to the orphan user (implying that somebody tried to delete that Topology while it was still used in a LES)

I'll create a follow up issue.

**Comment by ChaelKruip** [comment]
> I'll create a follow up issue.

Can this one be closed than @grdw?
