### ISSUE TITLE
[Airbrake] [Production] undefined method `each_pair' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1420]
**Airbrake error:** [#1692](https://quintel.airbrake.io/projects/111227/groups/1773231324503981692)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `each_pair' for nil:NilClass ``
**Where:** `business_cases#compare_with`
**Occurred at:** Sep 12, 2016 14:13:52 UTC
**First seen at:** Sep 12, 2016 14:13:52 UTC
**Occurrences:** 1 (1 since last deploy on Sep 09, 2016 10:01:11 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/572/business_cases/336/compare_with](https://moses.energytransitionmodel.com/testing_grounds/572/business_cases/336/compare_with)
**File:** `[PROJECT_ROOT]/app/helpers/business_case_helper.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/helpers/business_case_helper.rb:31:in content_for_breakdown
[PROJECT_ROOT]/app/helpers/business_case_helper.rb:44:in breakdown_data
[PROJECT_ROOT]/app/views/business_cases/_table.html.haml:24:in block in _app_views_business_cases__table_html_haml___1580884749734417392_70310721866300
[PROJECT_ROOT]/app/views/business_cases/_table.html.haml:19:in each
```

**Comment by grdw** [comment]
Fixed by: https://github.com/quintel/etmoses/commit/a49a6a1e7ef6c5c173e572b4b6aa02f36c7171fb
