### ISSUE TITLE
Marketmodel not updated and topology gone by removing LES

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#1421]
I made changes to the marketmodel 
TKI-SGE Usecase Presikhaaf standaard markmodel 
and
TKI-SGE Usecase Presikhaaf standaard markmodel - Hoeveel flex

The business case of
LES 'TKI-SGE: Usecase Presikhaaf netverzwaring conventioneel + stroomversnelling' 
and 
LES 'TKI-SGE: Usecase Presikhaaf standaard netwerk + hybride warmtepomp + batterijen'
were not update however.

So I cloned the LES and removed the orginal LES. Thereby, however, the topology was also removed. Now I cannot open the LES anymore. Strange thing is that the topology is not in the topology list anymore but I am still able to view it within the LES.

**Comment by ChaelKruip** [comment]
> So I cloned the LES and removed the orginal LES. Thereby, however, the topology was also removed. 

This should not be possible right @antw @grdw?

**Comment by ChaelKruip** [comment]
@antw @grdw can you retrieve the topology for the LESses mentioned here? @JeroenvdLogt needs these LESses for a project with some time pressure.

**Comment by JeroenvdLogt** [comment]
I have to leave now, I have some time left to look at this after dinner. If there are questions you can call me Chael (I can answer your call in the train).

**Comment by grdw** [comment]
I gave the topology id 541 and market model id 232 back from user id 42 (which is the orphan) back to user 67. 

This is the same issue as #1414. It is not removed, just not visible to non-admin users.

**Comment by antw** [comment]
I don't think this is the same as #1414, which says that deleting a topology from the *topology page* causes a LES to break. In this issue, deleting a LES caused the topology (and market model) to be reassigned to the orphan user, even though the topology owner was still using it elsewhere.

@JeroenvdLogt, @grdw has reassigned the market model and topology back to you, and you should be able to use them once again. I have fixed the bug; you can safely delete a LES with your other LESes remaining unaffected.
