### ISSUE TITLE
Y-axis doesn't update

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1429]
I am using this [LES](https://moses.energytransitionmodel.com/testing_grounds/586), but when I look at the results, the Y axis unit for node MSR wageningen campus isn't updated. It shows me values in kW which would be logical in MW.

**Comment by grdw** [comment]
![screen shot 2016-09-15 at 16 50 39](https://cloud.githubusercontent.com/assets/2676542/18554429/903d4f8e-7b64-11e6-8d7b-c3840cec4fbc.png)

I'm not able to reproduce this behavior exactly. I just looked at your LES and I see the units in MW. Did you do anything else than just look at the results? For example; update the strategies, selected another week, changed from 'Total' view to 'Stacked' and back?

**Comment by ThomBuijs** [comment]
I did play a bit with the the view to see a whole year and a week, and stacked and total view. However right now I get the following problem that the unit on the Y-axis is MW also for other nodes while the order of magnitude for the values are in kW. 

![units wrong](https://cloud.githubusercontent.com/assets/20039533/18580973/bd6707f8-7bfe-11e6-9fa0-cf9795a9ca5f.PNG)

![knipsel2](https://cloud.githubusercontent.com/assets/20039533/18581034/0e5ace88-7bff-11e6-85fb-15f218b62165.PNG)

**Comment by grdw** [comment]
I'll fix this with some priority 👍

**Comment by grdw** [comment]
@ThomBuijs  these changes won't be visible directly on production though. For now they're on the beta server. 

@antw is it ok, if I cherry-pick this single commit to production?

**Comment by antw** [comment]
> @antw is it ok, if I cherry-pick this single commit to production?

Sure thing! It's easy to rollback, so go for it. :+1:

If [this](https://github.com/quintel/etmoses/commit/a49a6a1e7ef6c5c173e572b4b6aa02f36c7171fb) can also go to production, you can just merge master into the production branch rather than cherry-picking. I've done that a couple of times this week with small fixes.
