### ISSUE TITLE
The Moses Logo review-issue

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#143]
![logo](https://cloud.githubusercontent.com/assets/2676542/7729619/0aea48ee-ff16-11e4-9a6d-845aae21ac12.png)

Showing off my Gimp-skills :art: 
I picked the general ETM blue to make a clear distinction between the word ETM and MOSES. 

What do you think? @ChaelKruip

**Comment by grdw** [comment]
Opinion time: @dennisschoenmakers @antw @jorisberkhout

**Comment by jorisberkhout** [comment]
Looking sharp!

I would personally change the color of the logo (the circles with the wheel) to ETM blue and go for a dark grey instead of black for MOSES and the subtitle. There is a little two much contrast to my liking. Just my 2 cents.

**Comment by ChaelKruip** [comment]
I don't like the two M's so close to each other.
Here's an idea: E T M O S E S where the first three letters are the same colour.
The M stands for Model(ling) :smile:

**Comment by dennisschoenmakers** [comment]
Chael :+1:

**Comment by antw** [comment]
![moses](https://cloud.githubusercontent.com/assets/4383/7738196/c607920c-ff49-11e4-8f65-e359508425cf.png)

**Comment by ChaelKruip** [comment]
Haha, this is truly A.M.A.Z.I.N.G! :laughing:

**Comment by dennisschoenmakers** [comment]
ROFL!

**Comment by grdw** [comment]
@antw amazing logo! Would also implement a `burning_bush` technology type, some 10 commandments page somwhere etc.

**Comment by grdw** [comment]
@ChaelKruip @jorisberkhout thanks for your suggestions :+1:

**Comment by jorisberkhout** [comment]
:laughing:

**Comment by grdw** [comment]
![logo](https://cloud.githubusercontent.com/assets/2676542/7743803/531798aa-ff9e-11e4-8487-572f7ef9dc32.png)

**Comment by antw** [comment]
I like that.

Would it be possible to see a version with the "M" also in black? The blue "M" looks to me like it should be read as "ETM OSES".

**Comment by grdw** [comment]
![logo-gray-m](https://cloud.githubusercontent.com/assets/2676542/7744693/bf590394-ffa5-11e4-864b-5ffbc3f73605.png)

yes

**Comment by antw** [comment]
Thanks! That looks better to me – I'm used to saying ET**Model**, ET**Engine**, ET**Source**, so ET**Moses** has a nice ring to it.

I'm happy with either though; they're both good. :+1:

**Comment by grdw** [comment]
There's only one way to solve this problem. ~~Let Moses decide!~~ or we can just vote. 

<table>
<tr>
<th>Logo</th>
<th>Vote count</th>
</tr>
<tr>
<td>Black M</td>
<td>2 (antw, grdw)</td>
</tr>
<tr>
<td>Blue M</td>
<td></td>
</tr>
</table>

**Comment by ChaelKruip** [comment]
:+1:
