### ISSUE TITLE
Add UUID's to topology nodes when adding and inflating them

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1436]
This module should be able to take hierarchal data like:

```ruby
{ 
   name: "HV",
   children: [ { name: "MV" } ] 
}

```
to:

```ruby
{  
  "<identifier-hv>":   { name: "HV" },
   "<identifier-mv>":  { name: "MV", parent: "<identifier-hv>" }
}

```
and the other way around.

**Comment by antw** [comment]
I'm not married to UUIDs by the way (UUIDs might be a bit long?). Any sufficiently-random string will do; [maybe this?](http://stackoverflow.com/a/19964557)

**Comment by grdw** [comment]
I'm closing this due to the irrelevance in the current implementation.
