### ISSUE TITLE
Translation missing in business case table (in edit LES)

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1439]
The translation for `en.business_case.yearly_depreciation	` is missing in the business case table.
Both on the beta and the live server.

I think it should read "Stakeholder".

![image](https://cloud.githubusercontent.com/assets/19907658/18631806/781537d8-7e74-11e6-9b83-7a785e2bd811.png)

**Comment by ChaelKruip** [comment]
@grdw can you pick this up?
