### ISSUE TITLE
Heat deficit where I don't expect it

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1440]
In [this LES](https://moses.energytransitionmodel.com/testing_grounds/592/heat_load), the heat deficit does not seem to disappear when the demand should be low enough to be fully satisfied by the heat network and the local sources of heat:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/18665373/378ba3f6-7f27-11e6-87c1-f8f6b58bd1fb.png)

It seems almost as if the deficit is a fixed fraction of the demand rather than the difference between demand and supply. 

Also, it would be clearer to plot deficit as the last series (as it previously was if I recall correctly).

**Comment by ChaelKruip** [comment]
@antw what is the status here?

**Comment by antw** [comment]
> @antw what is the status here?

#1446

**Comment by antw** [comment]
#1446 has been merged; are there any objections on sending it to production today?

**Comment by ChaelKruip** [comment]
No objections! Go ahead! I'm doing a demo between 14:00 and 16:00 my time. That's the only thing to take into account.

**Comment by antw** [comment]
> I'm doing a demo between 14:00 and 16:00 my time.

Unless you think these heat issues will crop up during the demo, perhaps it's best to wait until after you've finished?

**Comment by ChaelKruip** [comment]
I'm fine with you deploying now. The demo is not that critical and I can switch to beta in case it's not ok on production.
