### ISSUE TITLE
I can't select any profile for the must-run sources on LIVE server

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1442]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/18666148/8a537d7c-7f2a-11e6-9565-a833a90e9294.png)

**Comment by grdw** [comment]
Fixed:
![Uploading Screen Shot 2016-09-20 at 17.28.22.png…]()

The constant profile didn't had the correct associated technology `central_heat_network_must_run`, which you can easily add at the permitted technologies at a certain profile.

![screen shot 2016-09-20 at 17 29 43](https://cloud.githubusercontent.com/assets/2676542/18677048/e7db317e-7f57-11e6-8974-f880c64d9898.png)
