### ISSUE TITLE
Wanted: option to load a market model into my LES

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1455]
Currently market models can be selected when creating a LES. However, when starting my LES I don't always know which market model will be applicable. 

It would be nice if it was possible to load an existing market model to a LES.

**Comment by ChaelKruip** [comment]
Related to https://github.com/quintel/etmoses/issues/839

**Comment by DorinevanderVlies** [comment]
This issue will become relevant for the Paddepoel/Groningen project next week. Is it possible to rise the priority?

Notifying @AlexanderWirtz

**Comment by antw** [comment]
When editing a LESes market model, a "Replace market model" button is now available at the bottom of the form:

![screen shot 2016-11-21 at 17 20 27](https://cloud.githubusercontent.com/assets/4383/20493016/10ffcf28-b00f-11e6-92ea-ddb85ac635c6.png)

**Comment by DorinevanderVlies** [comment]
Very useful, thanks!
