### ISSUE TITLE
Switching between YAML input and Graphical input

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1464]
I'm currently thinking about how to make a nice switch between the YAML input and the graphical input for the new topology editor. 

My first approach will be a little blue text link on the bottom of the graphical editor like:

![screen shot 2016-09-29 at 11 54 25](https://cloud.githubusercontent.com/assets/2676542/18949392/7dcca4a8-863b-11e6-8eab-a13483fa439c.png)

Considering this an advanced feature I don't want normal users to find it that quickly. 

Also after hitting the YAML-editor button the switch should point back to the graphical editor or should it?

**Comment by ChaelKruip** [comment]
> Also after hitting the YAML-editor button the switch should point back to the graphical editor or should it?

I think so yes.

**Comment by grdw** [comment]
Switching works however. There is a 'thing' which might be bad or good. So I'm leaving it up to you to decide.

*This is the YAML:*
![screen shot 2016-09-30 at 15 13 46](https://cloud.githubusercontent.com/assets/2676542/18992796/90220a04-8720-11e6-88d7-424225dcd473.png)

*This is the graph:*
![screen shot 2016-09-30 at 15 14 30](https://cloud.githubusercontent.com/assets/2676542/18992807/9cd24c0a-8720-11e6-8d46-92ed6875f44f.png)

👍 Looking good and fine.

---

*When you add a new node, the YAML will look like this:*
![screen shot 2016-09-30 at 15 14 56](https://cloud.githubusercontent.com/assets/2676542/18992823/ab7bad28-8720-11e6-82ca-ffc02a9f30fb.png)

It's still valid YAML but for one, the keys are not sorted. You could for that matter also end up with this: 

![screen shot 2016-09-30 at 15 16 45](https://cloud.githubusercontent.com/assets/2676542/18992872/ee7072f8-8720-11e6-9695-e9678ba80c44.png)

Still valid YAML (I guess?) but the investment costs on the bottom belong to the HV node which is a little confusing. Also I'm not sure whether or not we should display the `x`, `y`, `depth` and `id` attributes in the YAML for they make no sense. On the other hand this is a rather advanced feature and advanced feature require some technical skill so.. might also be that it's sort of nice to show these keys.

**Comment by grdw** [comment]
@antw might you have a suggestion to format the YAML properly? I'm using a library called [jsyaml](https://github.com/nodeca/js-yaml) but I'm guessing it has to do with the way the `Object` is build up in Javascript. 

For example:

````javascript
{
   children: [ ... ]
}
````

After update info:

````javascript
{
   children: [ ... ],
   initial_investment: 100
   ...
}
````

What I'd like is: 

````javascript
{
   initial_investment: 100,
   ...,
   children: [ ... ]
}
````

A way I'd do it is something like:

````javascript
var a = { children: [], initial_investment: 100 },
    b = {};

Object.keys(a)
    .sort(function (c,d) { 
        return (c == 'children') ? 0 : -1;
    }).forEach(function(key) {  
        b[key] = a[key];
    });

console.log(b);
````
