### ISSUE TITLE
Number including parenthesis should be displayed on same line in business case comparison

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1469]
This is hard to read:
![screen_shot_2016-10-03_at_14_43_04_png](https://cloud.githubusercontent.com/assets/1303760/19037742/18a342a4-8978-11e6-9e75-da93d924c28f.png)

**Comment by grdw** [comment]
Do you have a link to the LES in question?

**Comment by grdw** [comment]
That explains a lot...

**Firefox:**
![screen shot 2016-10-14 at 11 45 25](https://cloud.githubusercontent.com/assets/2676542/19383265/b6f27838-9203-11e6-890f-e7fdbea54d9a.png)

**Chrome:**
![screen shot 2016-10-14 at 11 46 10](https://cloud.githubusercontent.com/assets/2676542/19383292/d4158f18-9203-11e6-91ea-4b688b398470.png)
