### ISSUE TITLE
Should we rename flexibility measures?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1478]
Wouldn't it be clearer to say "kWh of flexibility realised" in stead of "flexibility realised"?

Follow up question: do we indeed 'measure' flex in kWh or currently in kW-15-minutes?

**Comment by antw** [comment]
> Follow up question: do we indeed 'measure' flex in kWh or currently in kW-15-minutes?

kWh. The measures [use `energy_at`](https://github.com/quintel/etmoses/blob/9db3b1c5a97e7505a5bef524fa2199f7a0dcd248/app/models/market/measures/flexibility.rb#L13-L14) rather than `load_at`.
