### ISSUE TITLE
Axis label for heat load chart needs to be 1000 times higher

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1480]
In [this LES](https://moses.energytransitionmodel.com/testing_grounds/615/heat_load), every household (4400 in total) has connections to the heat network. I expect heat loads in the order of MWs but the axis only shows kW:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/19112797/213d11de-8b07-11e6-9f54-24c7b0731f6f.png)

**Comment by antw** [comment]
The data is correct, the legend is not. It should indeed say "MW".

**Comment by ChaelKruip** [comment]
Assigning @grdw to pick this up
