### ISSUE TITLE
Strange extra line in business case

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1483]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/19145337/cc5fea12-8bae-11e6-9b14-cb17cef57725.png)

Occurs in [this LES](https://moses.energytransitionmodel.com/testing_grounds/614/business_cases/378) if you don't blank the heat assets list:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/19145389/0236b652-8baf-11e6-9f57-cb6066308c7b.png)

**Comment by grdw** [comment]
I just imported the production database and runned the calculation locally but couldn't find that extra line. 

![screen shot 2016-10-27 at 14 46 30](https://cloud.githubusercontent.com/assets/2676542/19767684/3a600050-9c54-11e6-9190-29dc9f3da002.png)

It has also dissapeared from from production. I'll close this for I can't see this strange extra line anymore. Re-open if it still occurs though.

**Comment by ChaelKruip** [comment]
Still some weird things are going on. Now I have no sources for the heat network but still primary infrastructure to those sources in [this LES](https://moses.energytransitionmodel.com/testing_grounds/614).

**Comment by grdw** [comment]
Unrelated I'll create another issue.

**Comment by grdw** [comment]
#1534
