### ISSUE TITLE
The unit of the Y-axis for the heat load should scale to MW

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1485]
In this [LES](https://moses.energytransitionmodel.com/testing_grounds/609/heat_load) the unit of the Load on the heat network should be in MW but right now it is in kW. It looks as if the unit doesn't update accourdinly.

**Comment by ChaelKruip** [comment]
Closing as this is a duplicate of https://github.com/quintel/etmoses/issues/1480 and already fixed on BETA (will be deployed to production server after some testing).

**Comment by ThomBuijs** [comment]
👍
