### ISSUE TITLE
User should get a clear error message when using a non-existent profile

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#149]
Now ETMoses just tells you that:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7879653/9cff8176-05f2-11e5-81b3-d1a72955acda.png)

Which should read "LES or Local Energy Solution" BTW

**Comment by grdw** [comment]
@antw Is this the only thing that can go wrong or are there any other situations which might need some custom error message?
