### ISSUE TITLE
Detach topology from LES

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1503]
The current LES's are dependable on the topologies table. We need to merge them together in order for the LES to become independent of a `topology`. 

---

When that's all done we need to move the old topologies to the template topologies. Can we than remove all the clones and variations or should we keep everything? @ChaelKruip do you have some insight into this.

**Comment by ChaelKruip** [comment]
> Can we than remove all the clones and variations or should we keep everything?

I think we should remove everything unless it breaks/changes existing LESses. Also, please, please, keep a back-up of the databases.

**Comment by grdw** [comment]
> Also, please, please, keep a back-up of the databases.

Yes 👍
