### ISSUE TITLE
I don't need to sign in for electricity load, but I do for gas and heat load

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1507]
Is that ok behavior? @ChaelKruip @antw 

It seems odd to me.

**Comment by antw** [comment]
> It seems odd to me.

Me too. :+1:

**Comment by grdw** [comment]
The business case is also behind a sign in wall so it seems.

**Comment by grdw** [comment]
> The business case is also behind a sign in wall so it seems.

Ping @ChaelKruip

**Comment by ChaelKruip** [comment]
It is not clear to me what this issue is about. Are we talking public LESses? 

I think that anyone should be able to explore load (G, H, E) and the business case of public LESses without the need for an account.

**Comment by grdw** [comment]
> Are we talking public LESses? 

Yes.
