### ISSUE TITLE
Adding technical lifetime, initial investment, yearly o and m costs to gas asset table

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1509]
I added the three columns + they are editable. However this makes the attributes that are stored in the `db/static/gas_assets/**/*.yml` files act as defaults. Should they be? @ChaelKruip

**Comment by ChaelKruip** [comment]
> However this makes the attributes that are stored in the db/static/gas_assets/**/*.yml files act as defaults. 

I think that is fine! We don't have any other numbers anyways right?
