### ISSUE TITLE
[Airbrake] [Staging] TypeError: String can't be coerced into Float

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1512]
**Airbrake error:** [#9018](https://quintel.airbrake.io/projects/111227/groups/1801361367394399018)
**Airbrake project:** ETMoses

**Error type:** `TypeError`
**Error message:** `` TypeError: String can't be coerced into Float ``
**Where:** `DelayedJob Worker`
**Occurred at:** Oct 21, 2016 09:43:24 UTC
**First seen at:** Oct 21, 2016 09:43:24 UTC
**Occurrences:** 0 (0 since last deploy on Oct 20, 2016 08:56:46 UTC)

**URL:** `<no information>`
**File:** `[PROJECT_ROOT]/app/models/business_case_costs.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/business_case_costs.rb:9:in /
[PROJECT_ROOT]/app/models/business_case_costs.rb:9:in depreciation_costs
[PROJECT_ROOT]/app/models/business_case_costs.rb:3:in total_yearly_costs
[PROJECT_ROOT]/app/models/market/initial_costs/costs.rb:17:in block in calculate
```

**Comment by grdw** [comment]
Looks like someone turned `technical_lifetime` into a string in the `gas_asset_list`.

One moment please.

**Comment by dennisschoenmakers** [comment]
*Comment from Airbrake:* Resolved [error](https://quintel.airbrake.io/projects/111227/groups/1801361367394399018) reoccurred.
