### ISSUE TITLE
Not able to run migrations regarding changes in Topologies/Market Models in serie

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1518]
For #1515 I updated the migrations to run in a single go. However they don't (it works in 2 goes, but it works). Appearantly after I remove x-columns from the `topologies` table and try to create a unique `topology` per LES, Mysql tries to store columns to the database which no longer exist.

Is this because the `Topology.find_by_id` still finds the old records from cache?

Do you know what this might be?

After [this migration](https://github.com/quintel/etmoses/blob/0374c58911b7ae0e206b5c0bd6710a931f386bab/db/migrate/20161020102039_create_unique_topology_per_testing_ground.rb) fails, I run `rake db:migrate` again and all is well.

**Comment by antw** [comment]
> Appearantly after I remove x-columns from the topologies table and try to create a unique topology per LES, Mysql tries to store columns to the database which no longer exist.

After making the changes to the table structure, try running [`Topology.reset_column_information`](http://apidock.com/rails/ActiveRecord/ModelSchema/ClassMethods/reset_column_information).

**Comment by grdw** [comment]
Yes that was it 👍 thanks!
