### ISSUE TITLE
Why do we save a dispatchable attribute with must run heat sources?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1524]
I was checking some issues with #1517 and I found [these 2 lines](https://github.com/quintel/etmoses/blob/master/app/views/heat_source_lists/_must_run_table_row.html.haml#L29-L30). I was wondering why we do this? 

Ping @ChaelKruip

**Comment by ChaelKruip** [comment]
> I was wondering why we do this?

No idea!

**Comment by grdw** [comment]
Maybe it's some old relic from when the heat source list was a single table and contained both dispatchable and must run sources. I'll remove it 😅

**Comment by grdw** [comment]
>  I'll remove it 

To elaborate; `dispatchable` is an attribute which is determined by the `db/static/technologies/*.yml` files and must not be determined by an attribute in the `heat_source_list`.
