### ISSUE TITLE
Sorting the index template page

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1525]
![screen shot 2016-10-26 at 11 27 58](https://cloud.githubusercontent.com/assets/2676542/19720629/47ab27de-9b6f-11e6-90d3-ae3a02041d3b.png)

I'm currently grouping the templates.

Would like some feedback on look and styling. This looks odd.

- [x] For one I think `created_at` is a weird column to show. I don't think that many users actually care that deeply about it. I think this can be transfered to a `title` attribute on the link of to the topology. 

- [ ] The sub-header's alignment is off with the `name` header off the table. It bothers me a little
- [x] Spacing between main header and first sub-header is too small.
- [x] Visually preview your + featured templates
- [x] Move related LES's to show page of topology template

**Comment by grdw** [comment]
@ChaelKruip 

![screen shot 2016-10-26 at 14 25 02](https://cloud.githubusercontent.com/assets/2676542/19725815/036fd718-9b88-11e6-9a30-f95f5bb09a98.png)

**Comment by antw** [comment]
![file 26-10-2016 13 34 37](https://cloud.githubusercontent.com/assets/4383/19726120/27675724-9b81-11e6-89e4-eaf44a4fb623.jpeg)

**Comment by ChaelKruip** [comment]
With respect to https://github.com/quintel/etmoses/issues/1525#issuecomment-256331774, I think that if there are many we should show a few LESses and a 'show more' link to unfold the whole list.

I like the visual idea of @antw where you can preview the features topologies. Perhaps we can also render previews of the others upon clicking them.

**Comment by grdw** [comment]
> I like the visual idea of @antw where you can preview the features topologies. Perhaps we can also render previews of the others upon clicking them.

Maybe we could visually preview the featured + your templates. And leave the others like they are? 😄 I mean, visually showing every topology template might become a bit painful for the browser.

**Comment by grdw** [comment]
> With respect to #1525 (comment), I think that if there are many we should show a few LESses and a 'show more' link to unfold the whole list.

We could also show this on the `show` page of a `topology template`. When you click one of the topology templates. This doesn't necessarily have to be on the `index` page.

**Comment by ChaelKruip** [comment]
>  I mean, visually showing every topology template might become a bit painful for the browser.

That's why I suggested to wait until the user clicks them to render a preview:

>  Perhaps we can also render previews of the others upon clicking them.

**Comment by ChaelKruip** [comment]
> We could also show this on the show page of a topology template. When you click one of the topology templates. 

👍

**Comment by grdw** [comment]
![screen shot 2016-10-27 at 11 41 07](https://cloud.githubusercontent.com/assets/2676542/19762450/45db0688-9c3a-11e6-8de1-57764321e78d.png)

**Comment by grdw** [comment]
![screen shot 2016-10-27 at 12 15 19](https://cloud.githubusercontent.com/assets/2676542/19763599/0be0f406-9c3f-11e6-8418-7b6c728df6c7.png)

With a little bit more fancy details.
