### ISSUE TITLE
Manually added profile does not show up in technologies interface

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1529]
As I think the following problems are highly correlated I put them in the same ticket.

### Problem 1:
I made new profile on the beta server:
[EDSN E1A for indiv households](
https://beta-moses.energytransitionmodel.com/load_profiles/454) 
This profile is a copy of ESDN E1A, I want it to be an individual load profile as a quick fix of #1528.

Currently I cannot select this profile in the "edit technologies" interface. Neither for individual, nor for aggregated households.

### Problem 2:
I have used it in a CSV. 
This works on this [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/765):

![image](https://cloud.githubusercontent.com/assets/19907658/19726651/39d569ae-9b8c-11e6-95b3-2e52e612df1e.png)

But, when I [clone the LES](https://beta-moses.energytransitionmodel.com/testing_grounds/766) I get the following error and the profiles are shown as empty in the "edit technologies" interface :

![image](https://cloud.githubusercontent.com/assets/19907658/19726699/73c87bc4-9b8c-11e6-9a1d-078c69368af8.png)

**Comment by ChaelKruip** [comment]
I think the profile did not have any 'permitted technology' selected. I added one:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/19732831/66517822-9ba2-11e6-9807-0b64dfc6e1a1.png)

@DorinevanderVlies can you check if it works now?

**Comment by DorinevanderVlies** [comment]
Yes, it's working! Thanks, I think I overlooked that part after selecting the category..

Although I did have to select "household" again just now.

It raises another question, it seems that I cannot define whether my profile is for aggregated or individual households. That should be possible right?

**Comment by ChaelKruip** [comment]
> That should be possible right?

You can choose "Household" or "Household aggregated".

Closing.
