### ISSUE TITLE
Changes made to topology layout in a LES are not saved

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1532]
It seems possible to change the topology in a LES, but it is not.

In "edit LES" there is a tab in which the topology can be adjusted. In the interface empty end nodes can be removed and the topology can be extended. In the interface this works (see image below). But the changes are not saved when "save" is pressed. On viewing the LES the old topology is still present.

Attributes like `investment costs` and `technical lifetime` can be adjusted and are saved when save is pressed. 

If it is not possible to enable changing the lay-out of the topology within a LES I think the option to adjust it should be disabled.

![image](https://cloud.githubusercontent.com/assets/19907658/19769208/c685bf38-9c5a-11e6-9a95-d5e81e9f4be5.png)

**Comment by grdw** [comment]
Which topology is this? I was just changing a topology you made by hand in the database 😶. I know I should not do that, but at least I don't smoke.

**Comment by DorinevanderVlies** [comment]
You are forgiven ;-).

This [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/770) is a clone I assigned to this issue.

The topology is quite extensive. In the images I tried to delete 3 empty nodes connected to node "6" (on the left of the topology).

**Comment by grdw** [comment]
Yes I edited that topology by hand 👍 I think that's why it didn't save. If you'd just do the same thing now, all should be fine I guess. Unless it's another problem.

**Comment by DorinevanderVlies** [comment]
Thanks! Closing this issue.
