### ISSUE TITLE
Total cost for energy is not corresponding with manual calculation

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1543]
I'm working with this [LES](https://moses.energytransitionmodel.com/testing_grounds/654/edit). The total amount the customer pays for energy (electricity and gas) doesn't correspond when I calculate it manually.  When I look at the business case of this LES I can see that the customer pays a total of €19,917,735.16 for his gas and electricity. But when I check my calculations it sums up to €4,688,028.688. The difference is more than a factor 4. In my technology table besides the profile  I specify the total demand for each technology aswell. When I add these demands and multiply them with the corresponding cost per kWh for electricity and gas I get the number of €4,688,028.688. As discusses with Chael earlier, a factor 4 could mean that the problem is due to the CSV files containing values for each 15 minutes. However, in this case it is a factor of 4.24863..... So I don't understand what is causing this. I have used this LES as my standard LES from where I made several scenario's. So this bug? will be in those LESses aswell.

**Comment by ThomBuijs** [comment]
I looked into it. It appears that when the electricity grid is also owned by the customer the electricity consumed is counted at all the nodes, not only at the endnodes. I changed the stakeholder of the endnodes to customer AC1 and now the total amount payed for the energy corresponds with my calculation. I guess it makes sense, but this wasn't clear for me. Can I just copy the changed topology and paste it in my other LESses, to solve this problem?

**Comment by ChaelKruip** [comment]
>Can I just copy the changed topology and paste it in my other LESses, to solve this problem?

That is a different issue: https://github.com/quintel/etmoses/issues/1499

Closing this issue.

**Comment by ThomBuijs** [comment]
Maybe this should be added to the wiki?

**Comment by ChaelKruip** [comment]
> https://github.com/quintel/etmoses/issues/1499

👍
