### ISSUE TITLE
Something saved a Ruby hash into a JSON field (Airbrake)

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#1552]
**Airbrake error:** [#4082](https://quintel.airbrake.io/projects/111227/groups/1810876764904734082)
**Airbrake project:** ETMoses

**Error type:** `JSON::ParserError`
**Error message:** `` 757: unexpected token at '{"name"=>"HV Network", "stakeholder"=>"producer", "children"=>[{"name"=>"HV-MV trafo", "capacity"=>16000, "technical_lifetime"=>30, "investment_cost"=>150000, "stakeholder"=>"system operator", "children"=>[{"name"=>"MV-LV trafo", "capacity"=>6000, "technical_lifetime"=>30, "investment_cost"=>50000, "stakeholder"=>"system operator", "children"=>[{"name"=>"LV end node", "capacity"=>17.25, "units"=>600, "stakeholder"=>"customer"}]}]}]}' ``
**Where:** `topologies#update`
**Occurred at:** Nov 03, 2016 12:49:34 UTC
**First seen at:** Nov 03, 2016 12:48:36 UTC
**Occurrences:** 23 (23 since last deploy on Nov 03, 2016 11:43:27 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/780/topologies/998.js](https://beta-moses.energytransitionmodel.com/testing_grounds/780/topologies/998.js)
**File:** `/gems/json-1.8.3/lib/json/common.rb`

**Backtrace:**
```
/gems/json-1.8.3/lib/json/common.rb:155:in parse
[GEM_ROOT]/gems/json-1.8.3/lib/json/common.rb:155:in parse
[PROJECT_ROOT]/app/models/topology_graph.rb:15:in graph=
[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/attribute_assignment.rb:45:in public_send
```

**Comment by grdw** [comment]
Was already looking into it
