### ISSUE TITLE
Rescale to gas connections does not assign gas connections to a node with hybrid heat pumps

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1554]
This [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/785) has hybrid heatpumps connected to` LV end node - gas`.

However, when I use `rescale to gas connections` no gas infrastructure is made; all units remain on 0.

There is gas flowing to ` LV end node - gas`.
![image](https://cloud.githubusercontent.com/assets/19907658/19999503/0c101bf2-a273-11e6-81a2-668033d1562c.png)

assigning @antw, please reassign if you think it appropriate.

**Comment by DorinevanderVlies** [comment]
@antw thanks for looking at this issue!

Are you sure it is fixed? When I press `Rescale to gas assets` for a LES containing hybrid heat pumps (like the LES above) I still get 0 for all units in the gas infrastructure.

**Comment by antw** [comment]
It *is* fixed but the new code wasn't picked up (we've been upgrading some things on the servers). I restarted ETMoses and it should be fine now.

**Comment by DorinevanderVlies** [comment]
Awesome, thanks!
