### ISSUE TITLE
CSV export / import does not work properly for hybrid heat pumps

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1556]
This [ETM scenario](https://beta-pro.energytransitionmodel.com/scenarios/597147) contains 100% heat pumps for both hot water and space heating.

When I export this scenario to a [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/783/edit) the heat pump technology is working. After exporting it to a CSV and importing that CSV again the heat pumps are not working properly any more. It seems that information gets lost in the process.

As the csv import does not have priority this issue might not be urgent. 

### When adding heat pumps through the interface
![image](https://cloud.githubusercontent.com/assets/19907658/19999733/545e1b24-a274-11e6-85d6-ca938a3f8081.png)

The LES contains working heat pumps
![image](https://cloud.githubusercontent.com/assets/19907658/19999747/6dbbd3c2-a274-11e6-8004-42e8c4d14116.png)

### After exporting to a CSV and importing that CSV
![image](https://cloud.githubusercontent.com/assets/19907658/19999794/aa4c7da0-a274-11e6-9120-74f017641a8e.png)

The heat pumps are malfunctioning
![image](https://cloud.githubusercontent.com/assets/19907658/19999775/9ba7ceb2-a274-11e6-93c4-2e3f747a951f.png)

**Comment by DorinevanderVlies** [comment]
@grdw 
I previously said: 
> As the csv import does not have priority this issue might not be urgent.

However, in the following weeks we'll be constructing some variations of scenario's with hybrid heatpumps. The csv is the most efficient way to do this. Currently I still have to  manually add the hybrid heatpumps.
Especially in combination with the csv import this is prone to error. 

I would be awesome if there is a fix for this problem.

**Comment by grdw** [comment]
Steps to reproduce:

Step 1: Create a les with one buffer; one hybrid heat pump
<img width="1126" alt="screen shot 2016-11-25 at 13 41 14" src="https://cloud.githubusercontent.com/assets/2676542/20625628/db7fa54a-b314-11e6-96fd-4653a58b5013.png">

Step 2: Export LES

Step 3: Import LES
<img width="1212" alt="screen shot 2016-11-25 at 13 43 05" src="https://cloud.githubusercontent.com/assets/2676542/20625671/1f81d114-b315-11e6-9913-9abcd3e92652.png">

Load is gone 🤔

**Comment by DorinevanderVlies** [comment]
> Load is gone 🤔

Indeed

**Comment by grdw** [comment]
I found the reason. The `Hybrid heat pump` is modelled as a single technology consisting of two components. When exporting, it doesn't export the components but just the `technology` which is than just a shell with nothing in it. 

- [ ] Export components in a sane way
- [ ] Import components in a sane way
