### ISSUE TITLE
This LES has costs in business case for unknown stakeholder

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1558]
In the business case of this [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/790) 216.000 euro depreciation costs are assigned to an unknown stakeholder? Is it possible to see where these costs come from?

![image](https://cloud.githubusercontent.com/assets/19907658/20053593/9dd801f4-a4d9-11e6-909a-938e4664a1cc.png)

**Comment by antw** [comment]
@DorinevanderVlies This should be fixed. The costs were associated with the heat assets, but they were assigned to a stakeholder with no name. Let us know if you see this happen again and we'll look into it further.
