### ISSUE TITLE
Improve grouping of profiles for end points min. concurrency

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#156]
Nice to have:

Grouping of profiles should have a little touch of random when grouping them with a minimum amount of concurrency.

**Comment by ChaelKruip** [comment]
> Grouping of profiles should have a little touch of random when grouping them with a minimum amount of concurrency.

I see what you are saying here @grdw but I think that randomisation is not necessarily the way to solve the fact that some profiles can occur systematically more often then others in the current implementation.

**Comment by grdw** [comment]
It's either randomisation for the start of a sequence or systematically 'jump one place ahead' - the fudge factor solution.

**Comment by ChaelKruip** [comment]
I think this is not relevant anymore.
