### ISSUE TITLE
Merit order gives (too) high values per kWh

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1560]
I'm using this [LES](https://moses.energytransitionmodel.com/testing_grounds/666/edit). When applying the merit order to a stakeholder I get an average price per kWh for the realised flex of €0.60/kWh. I think this is way too high. Also, I am unable to download the merit order price/load curve and it gives me tis error:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

So I couldn't see the actual merit order curves.
So I checked the total amount of shifted flex which is equal to 74608 kWh and the amount payed by the system operator to customer AC1b which is equal to €44,764.61. 

The LES is scaled from a SER 2023 scenario and no other changes have been made.

**Comment by jorisberkhout** [comment]
Could you look into this with priority, @grdw ?

**Comment by grdw** [comment]
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

Yes, this is a caching problem as far as I'm thusfar aware.

Technical details:

> No such file or directory @ rb_file_s_mtime - /var/www/etmoses/releases/20161026091620/tmp/networks/production/666/feature/electricity/49a08c0e397826d795e50f9a6a16b08f35708bd965875a2b22d9bb1db5e25bc6.load.current_week.tmp

Including @antw

**Comment by jorisberkhout** [comment]
@grdw and I looked into this. We managed to download the merit order curve and found that all 35040 entries in this curve are `0.60`. The merit order curve of the SER 2023 scenario shows more variability in the price and the average price is `46 EUR / MWh` or `0.046 EUR / kWh`. Do you know what might cause the difference, @antw ?

**Comment by antw** [comment]
> Do you know what might cause the difference, @antw ?

Not off the top of my head, sorry. I can look into this as soon as I've dealt with quintel/etmodel#2296.

**Comment by jorisberkhout** [comment]
> Not off the top of my head, sorry. I can look into this as soon as I've dealt with quintel/etmodel#2296.

Thanks!

**Comment by antw** [comment]
> The merit order curve of the SER 2023 scenario shows more variability in the price and the average price is 46 EUR / MWh or 0.046 EUR / kWh. Do you know what might cause the difference, @antw ?

The production park is completely maxed-out because there are *far* more households in the LES than the original scenario.

The scenario was scaled to 610 households, but the LES has 47500 households present (aggregated and individual). I think it's fair to say that a central production park scaled for a region of 610 households is incapable of meeting demand for 48k. Hence all the central producers are running all the time. €600EUR/MWh (€0.60/kWh) is [the fallback price used by Merit](https://github.com/quintel/merit/blob/b9a2147522c7c510ab198abc26dc22416ba157c0/lib/merit/price_curves.rb#L67) in the case that all producers are fully-loaded.

**Comment by jorisberkhout** [comment]
Thanks, @antw . Does this answer your question, @ThomBuijs and @JeroenvdLogt ? If so, could you close this issue?

**Comment by JeroenvdLogt** [comment]
This is strange because I can't find any unit field with a value of 100+. Also in the topology all the unit values are 1 or not filled.

**Comment by antw** [comment]
> This is strange because I can't find any unit field with a value of 100+. Also in the topology all the unit values are 1 or not filled.

You're completely correct, I don't know what I was thinking. I misread the "demand" fields; in my defence, the demand field and unit label [are quite close](https://cloud.githubusercontent.com/assets/4383/20133347/1f4eb79c-a65f-11e6-99cb-52c7181618ec.png). 😬

The explanation for the price is still true though: €0.60/kWh means that all the central producers are maxed-out. I will take a quick look into why this is the case.

**Comment by DorinevanderVlies** [comment]
The following might help the search.
I just looked at my [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/797]) which is based on an [ETM scenario ](https://beta-pro.energytransitionmodel.com/scenario/demand/households/prosperity) with an overload of electricity. The merit curve consists solely of 0.60 euro/kWh.

**Comment by antw** [comment]
@ThomBuijs @JeroenvdLogt The incorrect pricing should be fixed now. A (pretty big) oversight caused dispatchable sources of energy to not be included when calculating the merit order price.

**Comment by MarjoleinSchwachofer** [comment]
I have the asme problem with a LES that ties to this one:  In https://moses.energytransitionmodel.com/testing_grounds/681/edit it look goed but in https://moses.energytransitionmodel.com/testing_grounds/683/edit the merit order gives a to high cost from supplier to producer. Why doesn't this work now? I need thid for a presentation.

**Comment by MarjoleinSchwachofer** [comment]
looks fixed after some trying, but don't know why

**Comment by antw** [comment]
> looks fixed after some trying, but don't know why

The business case probably had not been recalculated; you made a change to the market model or LES and this forced it to be recomputed; replacing the old and incorrect prices with the new, correct ones.
