### ISSUE TITLE
Remove Concurrency from documentation

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1563]
A user alerted me that concurrency is still mentioned in the documentation. However, as far as I know this feature has been removed from ETM-SA.

@jorisberkhout Is this indeed the case and is it OK that I remove it from the documentation?

**Comment by jorisberkhout** [comment]
Good point @DorinevanderVlies . If I understand correctly concurrency is implemented differently now, so maybe it is better to update the documentation. I guess @grdw knows more about this, right?

**Comment by grdw** [comment]
Yes it is no longer there. It has become a rather simple 'splitter'. So you can split up technology boxes in a way while keeping the same units. So if you have a technology of units=10 and you split, it becomes two technologies with units=5. If you do it with a technoloy of units=9, it becomes 5 and 4 respectively.

**Comment by DorinevanderVlies** [comment]
Closing through [Wiki](https://github.com/quintel/etmoses/wiki/split)
