### ISSUE TITLE
wanted: option to export business case (to csv)

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1565]
For analysis it would be nice if the business case of a scenario can be exported. For example to a CSV file.

**Comment by antw** [comment]
Once the business case has been calculated, a "Download CSV" button will be available:

![screen shot 2016-11-21 at 13 53 06](https://cloud.githubusercontent.com/assets/4383/20485104/05591098-aff2-11e6-8c2c-0688590efc79.png)

**Comment by DorinevanderVlies** [comment]
Thanks!
