### ISSUE TITLE
Question about total heat production table in ETM

### ISSUE THREAD

**Issue by niessink** [quintel/etmoses#1578]
Hi  Anthony @antw , Dorine @DorinevanderVlies 

Thanks a lot for answering my other question about the heat network deficits. However i have one more:

- First i start a scenario (for 1000 housholds) and change it to 100% heat network for households and buildings.
- As a test case: I pick a heat network with 85% biogas CHP and 15% centralized district heating.
- In the ETM supply section there is a table that shows the total heat and cold production. In this case: total heat production is 79TJ.
- Now i compare total heat production to a 100% geothermal heat network scenario (everything else stays the same). The total heat production is much lower in this case: 43TJ What are the reasons for this? Are this all losses and if so what kind of losses? (the heat demand did not change). 
- Also notice, if the share of biogas CHP's is changed compared to centralized district heating, then total heat production changes with it.

**Comment by DorinevanderVlies** [comment]
The title of the chart is confusing. This chart shows the **primary use** of resources needed to supply the total heat and cold demand.

So, the demand stays the same, but the efficiency of the various techniques varies.

> Now i compare total heat production to a 100% geothermal heat network scenario (everything else stays the same). The total heat production is much lower in this case: 43TJ What are the reasons for this? Are this all losses and if so what kind of losses? (the heat demand did not change).

CHP for example supplies both heat and electricity. More primary resources are required if CHP is used than if geothermal is used.

>Also notice, if the share of biogas CHP's is changed compared to centralized district heating, then total heat production changes with it.

The chart shows primary use. The demand for heat and cold stays the same.

**Comment by niessink** [comment]
Thanks! I was also curious if ETM calculates total heat demand of all sectors combined. That would help to match heat demand and supply. (for electricity i could find this) Otherwise, i suppose i have to add up all sectors.

**Comment by DorinevanderVlies** [comment]
Currently there is no chart that shows the total heat demand. Using table view of the first chart that pops up when you open a section (households, building, industry) will help to add up the sectors. But you probably already found these charts.

**Comment by ChaelKruip** [comment]
Closing this.
