### ISSUE TITLE
Depreciation and O&M costs of heat system operator incorrect in business case

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1582]
This [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/847/business_cases/617) contains a heat network.

There are both investment and O&M costs for the heat system operator. However, there are no costs in the heat system operator to heat system operator cell.

![image](https://cloud.githubusercontent.com/assets/19907658/20882778/f014ed78-bae2-11e6-9a1d-59fe57d4c2ea.png)

![image](https://cloud.githubusercontent.com/assets/19907658/20882825/26fc5290-bae3-11e6-9c61-8143e1d69117.png)

**Comment by grdw** [comment]
I'm a bit unsure about the role of the "Heat system operator". I do know that the initial costs of the Heat source are applied to the "Heat producer"; for all I can see in the code.

**Comment by DorinevanderVlies** [comment]
True, the costs for the heat sources are assigned to the heat producer.

The heat system operator is concerned with the heat assets.
In the second image you can see that the primary heat infrastructure has 16426 euro/km investment costs for 17 km. These costs are assigned to the heat system operator.
In this scenario I also assigned the costs of the secondary infrastructure to the heat system operator.

**Comment by grdw** [comment]
Ho, I was meant to look at heat assets. Heat assets is returning a `NaN` as far as I can see. I'm investigating why that is ... 🤔 one moment 😅

**Comment by grdw** [comment]
The technical lifetime of the secondary heat assets can't be 0.

**Comment by DorinevanderVlies** [comment]
Check, sorry I missed that one. Thanks a lot!
