### ISSUE TITLE
Investement costs of technologies should be the same as future costs in ETM

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1583]
In ETModel the costs of technologies (for heating and PV) can be set for the future.
The export to ETM-SA however has standard costs.
It would be nice if the export takes these cost reduction into account.

![image](https://cloud.githubusercontent.com/assets/19907658/20882994/0f60c354-bae4-11e6-9e6c-28481525091e.png)

**Comment by ChaelKruip** [comment]
Is this true @antw @grdw?

**Comment by antw** [comment]
I tried this with heat humps (ground) and could not reproduce it myself.

**Default cost**

![screen shot 2016-12-21 at 09 07 33](https://cloud.githubusercontent.com/assets/4383/21383356/3c46de1e-c75d-11e6-85b9-926839ca50b1.png)

**Electric heat pump cost = -75%**

![screen shot 2016-12-21 at 09 07 39](https://cloud.githubusercontent.com/assets/4383/21383372/4eeee78c-c75d-11e6-8be7-fda8cc9d61bb.png)

**Comment by DorinevanderVlies** [comment]
OK, I think after the cost reduction I still thought the technologies were expensive...  
Closing for now.
