### ISSUE TITLE
Heat load chart breaks if you update geothermal number of units

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1589]
In [this scenario](https://moses.energytransitionmodel.com/testing_grounds/722/heat_load)

**Comment by ChaelKruip** [comment]
Changing the NoU in the heat source list and clicking 'save and view LES' makes the model break.

**Comment by antw** [comment]
This appears to be because the list of must-run profiles doesn't get populated and is already fixed on beta. I've corrected the profile for this LES, but it will break again if further edits are made.

I suggest a deploy in the new year as it's been some time since we pushed changes to production.

**Comment by ChaelKruip** [comment]
> I suggest a deploy in the new year as it's been some time since we pushed changes to production.

I agree. But because our external client would like to work on his LESses, could we cherry-pick this fix to production perhaps?

**Comment by ChaelKruip** [comment]
> But because our external client would like to work on his LESses, could we cherry-pick this fix to production perhaps?

@grdw and myself did this already.
