### ISSUE TITLE
Treating postponable load in measured 'base-load' profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#159]
## Background
We have access to measured 'smart meter' data from individual households. This data typically shows a minimal load below ~300W and peaks of higher load that last for maximally 2 hours.
Some of these peaks might be due to technologies whose load is inflexible, others might be 'postponable' and we should be able to treat them as such.

## Problem
How can we:
* extract the peaks and assign them to technologies?
* postpone a load-event (characterised by its hight and duration)

## Possible solution 1
Assign a technology to each peak 'on-the-fly' as we 'walk through the year'. This would mean that we assign each technology a probability and draw a 'random number' to decide what the current peak is going to be.

If we have decided that a peak is 'postponable', a postponed-load-object (?) could be created which needs to be checked for possible 'execution' for following time steps until it either cannot be postponed any longer or a suitable moment for execution has been found.

Advantages:
* No new profiles needed (the current base-load profiles with peaks can be used)
* The user could change the probabilities of assigning the various technologies and the code could take them into account directly

Disadvantages:
* Need for random seeds to ensure reproducibility
* Not very transparent what is happening
* Need for a new 'postponable load object' (?)
* Possibly negative impact on performance

## Possible solution 2
(thanks to @dennisschoenmakers)

Extract the peaks and assign technologies to them prior to calculation. In practice this would mean that we pre-process a base-load profile in a (Python) script and break it up into several parts (the inflexible part) and several postponable parts that correspond to specific technologies or groups thereof.
These parts could be treated as normal profiles (for the inflexible part) and 'postponement' profiles (for the postponable technologies).

Advantages:
* Transparent: it is clear which part of the base-load is flexible and which is not
* No need for random number magic in ETMoses
* Fits well in the current profile-based decision making

Disadvantages:
* The user cannot easily influence the probability (or other aspects) of the technologies assigned to peak

## General
Both solution mean that we need to find data on the occurrence and duration of load events for each relevant technology in the base-load.

Personally I would vote for possible solution 2 as it seems 'cleaner' to me. @dennisschoenmakers @antw @jorisberkhout please chip in!

**Comment by dennisschoenmakers** [comment]
Possible solution 2 :+1:

**Comment by antw** [comment]
Solution 2 has my vote also.

> (solution 2 disadvantage) The user cannot easily influence the probability (or other aspects) of the technologies assigned to peak

I'm not sure this is a disadvantage; there needs to be a balance between being able to customise the calculation, and providing a good user experience. "Assign probability of base load flexibility" seems *too* advanced for most users.

**Comment by ChaelKruip** [comment]
Solution 2 has been implemented. Closing.
