### ISSUE TITLE
Stacked chart not the same for two subsequent nodes

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1596]
This [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/919). 
The end node (4 - portiekflat)  shows all parts individually (both negative and positive)
The node above the end node (k+z 4) already performs a substraction and. The chart follows the same line as the "total" chart.

I prefer the way the end node shows it.

![image](https://cloud.githubusercontent.com/assets/19907658/22254296/7365869a-e254-11e6-9758-33aaa6bdb184.png)

![image](https://cloud.githubusercontent.com/assets/19907658/22254305/8067f440-e254-11e6-90ee-341519ae142b.png)

**Comment by ChaelKruip** [comment]
@antw doesn't this have to do with the way loads are calculated across the network? I.e., that only the resulting loads after locally (on the end-node) supply and demand have been subtracted?

**Comment by antw** [comment]
> @antw doesn't this have to do with the way loads are calculated across the network? I.e., that only the resulting loads after locally (on the end-node) supply and demand have been subtracted?

Yes, that's correct. The chart shows which technologies are responsible for the load on the selected component. Any supply/demand satisfied entirely at lower levels of the network will not appear on higher-level components.
