### ISSUE TITLE
Depreciation costs of business case of stakeholders not taken into account when stakeholder is connected to heat network

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1599]
The business case does not show depreciation costs for stakeholders that are connected to the heat network.

Even though no depreciation costs are associated with the heat network, there are depreciation costs for P2P and PV for these stakeholders.

[Example of LES](https://beta-moses.energytransitionmodel.com/testing_grounds/915/edit), in this LES stakeholders AC1, AC2, AC3 and AC6 are connected to the heat network.

![image](https://cloud.githubusercontent.com/assets/19907658/22473703/fce48238-e7d9-11e6-8a3c-15e4b1aa7374.png)

**Comment by ChaelKruip** [comment]
@grdw can you look into this please?

**Comment by DorinevanderVlies** [comment]
One moment, it might have to do with a technical lifetime of 0 (even though costs are 0).
I'll check this first

**Comment by DorinevanderVlies** [comment]
Indeed, by default Excel returns 0 when referring to the empty cell. It is solve now!

This was my mistake. Another issue is that making a small mistake happens easily. I would be nice if ETM-SA gives feedback when a div/0 (or other error in calculation) occurs. Something like a status report of the LES. I'll make another issue about this.
