### ISSUE TITLE
OVERVIEW: assigning profiles to end-points

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#16]
# Background

In Step 4 of the Alliander project, the end-points of the network are initialised with load profiles (also see https://github.com/quintel/etloader/issues/15). The user can manually assign load profiles but if the testing ground is created directly from a scenario in the ETM, we should give a decent starting position for the user. In other words: the computer should assign profiles to end-points with some 'intelligence'.

# Two types of testing-grounds

Testing grounds come in two flavours:
* Individual households are modelled
* Groups of households are modelled

If the households are modelled individually, each connection of the network normally represents a household. Depending on the type of household (does it have heat pumps, solar PV, electric vehicles?), the computer should assign profiles to the connection and scale them appropriately.

If groups of households are modelled, the computer should combine multiple profiles (properly scaled) to represent the group.

# Choosing the profiles

Not all households are the same. For that reason we have generated a series of profiles for all entries of the following matrix:

  | Appartment | Terrace house ('Rijtjeshuis') | Detached house
------------ | ------------- | ------------- | ------------- 
**Couple** |A1 | A2 | A3 | 
**Family with two children**  |B1 | B2 | B3 | |
**2 Students**  |C1 | C2 | C3 | |
**Single person**  |D1 | D2 | D3 | |

Where the types of houses have the following characteristics:
* Appartment: 75m2, heat demand: 1000 cubic meter of gas (or 10 MWh) per year
* Terrace house ('Rijtjeshuis'): 100m2, heat demand: 1500 cubic meter of gas (or 15 MWh) per year
* Detached house: 150m2, heat demand: 2500 cubic meter of gas (or 25 MWh) per year

To choose profiles out of this matrix we need to keep into mind:
* The total number of households needs to be equal to those in the scenario
* The number of people in the households needs to be (more or less) equal to the people in the scenario
* The distribution of households should more or less reflect a realistic situation

The first and second criteria seem rather straightforward. For the last one, we need to have some extra data. What are the odds of 2 students living in a detached house? A possible 'probability distribution' for the components in the matrix could be as follows:

 | Appartment | Terrace house ('Rijtjeshuis') | Detached house
------------ | ------------- | ------------- | ------------- 
**Couple** |10% | 15% | 5% | 
**Family with two children**  | 5% | 20% | 5% | |
**2 Students**  |10% | 9% | 1% | |
**Single person**  | 10%  | 5% | 5% | |

When choosing households from the matrix, the percentages describe the chance of picking that type of household.

**Comment by ChaelKruip** [comment]
@jorisberkhout @dennisschoenmakers @AlexanderWirtz @antw does the above make sense to you? Any clues on how to approach the data-angle of finding typical sizes and heating demands of housetypes in NL?

**Comment by dennisschoenmakers** [comment]
> @jorisberkhout @dennisschoenmakers @AlexanderWirtz @antw does the above make sense to you? 

For **groups** of households it absolutely does. I hope @AlexanderWirtz can provide the requested data clues.

**Comment by ChaelKruip** [comment]
> For groups of households it absolutely does

@dennisschoenmakers why wouldn't it make sense for individual households? If you have 100 connections in a testing ground you still need to choose how many apartments and detached houses there are right?

**Comment by AlexanderWirtz** [comment]
For the data you should talk to Alliander, their database tries to list different kinds of dwellings for each connection, so they should be able to do some statistics for heating demands and they might be able to help you with the sizes as well. 
@jorisberkhout does the HH source analysis for NL2012 contain anything about typical sizes etc?
 
I am not sure I understand how you plan to go about creating a testing grounds with the method described above. Do you generate it randomly using this probability distribution?

**Comment by ChaelKruip** [comment]
Putting this on-hold for now.

**Comment by ChaelKruip** [comment]
Closing this.
