### ISSUE TITLE
Use select boxes all the time instead of double clicking on the testing ground / profile table

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#160]
Instead of clicking to reveal the actual select box; just show the select box.

This will improve usability since users don't have to double click (credits to @antw). 

Incomplete screenshot to give an idea:

![screen shot 2015-06-09 at 3 28 15 pm](https://cloud.githubusercontent.com/assets/2676542/8058785/351f97a8-0ebc-11e5-9f71-8af08ec50d8c.png)

If there are other ways; please suggest!

**Comment by grdw** [comment]
![screen shot 2015-06-09 at 3 50 43 pm](https://cloud.githubusercontent.com/assets/2676542/8059270/528ac0a8-0ebf-11e5-85ae-aae78e968fb0.png)
It will look like this.

**Comment by ChaelKruip** [comment]
@grdw I like this approach. It communicates to the user what the function of the boxes is.

**Comment by antw** [comment]
Since the topology cannot be changed on the "new/edit testing ground" page, maybe the "Node" column could also be replaced with a hidden form field? Instead we'd have a table for each leaf node:

    MV-LV Trafo #1
    --------------

    [ Household      | v ]  [ Profile ]  ...  (-)
    [ Electric car   | v ]  [ Profile ]  ...  (-)
    [ Residential PV | v ]  [ Profile ]  ...  (-)

        [ Add Technology to MV-LV Trafo #1 ]

    MV-LV Trafo #2
    --------------

    [ Household      | v ]  [ Profile ]  ...  (-)
    [ Electric car   | v ]  [ Profile ]  ...  (-)

        [ Add Technology to MV-LV Trafo #2 ]

    MV-LV Trafo #3
    --------------

        [ Add Technology to MV-LV Trafo #3 ]

I'm guessing this would be a bigger task than just changing the table to show `<select>`s though.

**Comment by ChaelKruip** [comment]
> Since the topology cannot be changed on the "new/edit testing ground" page, maybe the "Node" column could also be replaced with a hidden form field? Instead we'd have a table for each leaf node:

I like this from the point of view of clarity and aesthetics. However, in the current form it would be easier to move a technology to another end-point by simply selecting it from the list. 
Is that supported @grdw ?

**Comment by grdw** [comment]
Still becomes a little hard to read when there are +100 endpoints.

Do get the point that the table might have to be a little less wide.

Maybe this does the trick aswell:

![magical-preview-46](https://cloud.githubusercontent.com/assets/2676542/8060900/060a5118-0ec8-11e5-8cce-ec1e7014c252.png)

And use drag and drop to drag a row to another endpoint.

**Comment by antw** [comment]
> However, in the current form it would be easier to move a technology to another end-point by simply selecting it from the list. 

Hadn't considered that, but you're right. I suppose a "Move to..." button could be added, but that's not ideal either. It *could* be useful if a user wants to move a certain number of units to another node, but now I'm away in fantasyland. :dancer: 

    |  [ Household      | v ]  [ Profile | v ]  ...  (-) (~)  |
    |  [ Electric car   | v ]  [ Profile | v ]  ...  (-) (~)  |
    |  [ Residential PV | v ]  [ Profile | v ]  ...  (-) (~)  |
                                                          ∧
                -----------------------------------------/ \-----+
                |  Move [ 5 ] of 10 units to [ MV-LV Trafo #2 ]  |
                +------------------------------------------------+

Is it common to move a technology from one node to another? If so, it's likely best to put my idea aside and leave the "Node" drop-down as it is.
