### ISSUE TITLE
Why the strategy "Switch HHP to gas if network is congested" effect uncongested times as well?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1606]
In [this LES ](https://beta-moses.energytransitionmodel.com/testing_grounds/1052)there are some periods with congestion.

I would expect the strategy "Switch HHP to gas if network is congested" to just effect these periods. However as far as I can see it has continuous effect. @antw what is the reason behind that?

### Image
**Switch HHP to gas if network is congested** 
![image](https://cloud.githubusercontent.com/assets/19907658/25743903/3495938c-3197-11e7-9c5a-8aaa851a34e0.png)

**Comment by antw** [comment]
This was not intentional and should now be fixed on beta:

![screen shot 2017-05-08 at 16 53 10](https://cloud.githubusercontent.com/assets/4383/25812657/e31fec58-340e-11e7-9f10-08f19d02f865.png)

**Comment by DorinevanderVlies** [comment]
Thanks!
