### ISSUE TITLE
Question regarding HHP strategy

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1607]
In addition to #1606: how does this strategy work? Are all HHP's switched to gas at times of congestion, or just enough to prevent congestion? I would expect/prefer the latter to happen.

**Comment by antw** [comment]
Just enough to prevent network congestion. This is a LES whose only technology is an HHP, with and without the strategy:

![screen shot 2017-05-08 at 16 50 35](https://cloud.githubusercontent.com/assets/4383/25812523/7d0cc5e4-340e-11e7-85ca-83966640a578.png)
