### ISSUE TITLE
Add icon to tab title

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1608]
It would be nice if ETM-SA/ETMoses would have a small icon at the tab title.

I think this can be the same icon as ETM currently has. Maybe with a different color (eg black and white) to differentiate between the two.
![image](https://user-images.githubusercontent.com/19907658/26917613-4122be1a-4c2f-11e7-8839-8e1b68cbdba1.png)

Assigning @antw (please reassign if appropriate)
Notifying @ChaelKruip

**Comment by antw** [comment]
I don't have the original source file for that image and the version used on ETModel is very small; recolouring it might prove difficult.

@dennisschoenmakers Any chance you have the original?

**Comment by dennisschoenmakers** [comment]
Actually, I think we should change the favicon, and no, I do not have the original.

**Comment by DorinevanderVlies** [comment]
As the original file is not there anymore I propose to use the same favicon for ETM-SA as we use for ETM.
