### ISSUE TITLE
Stakeholder cooperation 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1609]
[This LES](https://beta-moses.energytransitionmodel.com/testing_grounds/1084/) is an export from [this local scenario](https://beta-pro.energytransitionmodel.com/scenarios/688189).

The market model is very simple. Cooperation is does not own any nodes and is not mentioned in the market model. However the business case contains depreciation costs for the cooperation.

For [the same LES on the Live server](https://moses.energytransitionmodel.com/testing_grounds/746/business_cases/510) this is not the case.

**Market model**
![image](https://user-images.githubusercontent.com/19907658/27338608-fa868b84-55d5-11e7-936e-506f9d357f68.png)

**Business case**
![image](https://user-images.githubusercontent.com/19907658/27338581-ea954698-55d5-11e7-89d9-e232de04ddb3.png)

**Comment by antw** [comment]
The "Households 3" node was assigned to the `copperation` stakeholder. I reassigned it to `customer` (as is the case on the live server) and "Cooperation" no longer appears in the business case.
