### ISSUE TITLE
Business cases and whole-year view do not load

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1614]
I made a [simple LES](https://beta-moses.energytransitionmodel.com/testing_grounds/1093/business_cases/864) to illustrate this issue.

Trying to load the business case or the whole year view does not give results.

This issue reminds me of: https://github.com/quintel/etmoses/issues/1597

**Comment by DorinevanderVlies** [comment]
This issue occurs on the beta-server only

**Comment by grdw** [comment]
Yes, I can confirm this. Was about to open an issue on this until I saw that there already was one.

**Comment by grdw** [comment]
The delayed job runner isn't on ... that explains. 😅

**Comment by grdw** [comment]
Fixed with https://github.com/quintel/etmoses/commit/d024888896f3e1518a5ae888ed8ac2d027c55b21

**Comment by DorinevanderVlies** [comment]
Thanks @grdw
