### ISSUE TITLE
Not possible to add a technology to ETM-SA on live server through interface

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1618]
In the technologies tab the "add" button remains inactive for some technologies when they are selected.

This is at least the case for "Residential PV panel" and "Electric car". "Other" on the other hand works fine.

[LES used for testing](https://moses.energytransitionmodel.com/testing_grounds/804/edit)

![image](https://user-images.githubusercontent.com/19907658/38367015-d5f48efc-38e1-11e8-9878-00483f5d84e7.png)

notifying @ChaelKruip

**Comment by antw** [comment]
Was fixed in a9b15da. I've merge that into production and the fix should be deployed momentarily.
