### ISSUE TITLE
Live: export of a scenario gives incomplete LES

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1619]
When exporting a scenario not all technologies are included in the LES.

**Example** 
Empty dataset Antwerp scaled to 2642 households (359617)
Exported to a topology with one endpoint.

The LES includes:
- Household
- Buildings

The LES does not include:
- Heating technologies
- PV

**Screenshot of technologies:**
![image](https://user-images.githubusercontent.com/19907658/38558414-54192472-3cd0-11e8-83a8-3b61480baafb.png)

notifying @ChaelKruip

**Comment by antw** [comment]
Was already fixed on beta; I've cherry-picked the commit to production.

**Comment by DorinevanderVlies** [comment]
thanks!
