### ISSUE TITLE
Is is possible to add a price curve?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1621]
The market model in Spain has variable tariffs for some customers.

ETM-SA already provides the option to use a price curve.
Is is possible to add price curves? I would need to add roughly 4  curves.

![image](https://user-images.githubusercontent.com/19907658/39417481-c4ee1192-4c54-11e8-9ecf-dbb686a193a7.png)

**Comment by ChaelKruip** [comment]
You can add financial profiles:
![image](https://user-images.githubusercontent.com/1303760/39417768-bc59f404-4c56-11e8-8366-9db4af63fcf7.png)

**Comment by DorinevanderVlies** [comment]
Thanks! I missed that one
