### ISSUE TITLE
Columns are wrongly displayed in 'Technologies' table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#165]
I created a new LES (#99) and viewed the technologies connected to one of the endpoints. The entries in the 'Technology' table do not match with the headers (see below).

![screen shot 2015-06-11 at 11 32 44](https://cloud.githubusercontent.com/assets/4669028/8104080/28573724-102e-11e5-9441-be87ec9623b1.png)

If I edit the table, the entries and headers do match up.

![screen shot 2015-06-11 at 11 33 07](https://cloud.githubusercontent.com/assets/4669028/8104125/96e1e37e-102e-11e5-9893-da82460b0f1e.png)

**Comment by grdw** [comment]
Will be fixed if #166 is merged
