### ISSUE TITLE
Texts needed for tooltips accross etmoses

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#173]
All gray information icons contain a tooltip. These now contain 'Lorum-ipsum-esque' texts. These need to be filled.

# Load profiles form

![screen shot 2015-06-18 at 3 15 25 pm](https://cloud.githubusercontent.com/assets/2676542/8232021/e013ba6a-15cc-11e5-8570-d799fbd92f08.png)

------

- [ ] Tooltip: Key
- [ ] Tooltip: Curve
- [ ] Tooltip: Permitted technologies

------

# Topologies form

![screen shot 2015-06-18 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/2676542/8232036/f7cac374-15cc-11e5-96c8-908a22d5d2fb.png)

------

- [ ] Tooltip: Permissions
- [ ] Tooltip: Graph

------

# Import from ETM

![screen shot 2015-06-18 at 3 16 36 pm](https://cloud.githubusercontent.com/assets/2676542/8232072/2c9ffa9c-15cd-11e5-805e-989cae0f0ad2.png)

------

- [ ] Change 'test test test' import text to something useful.
- [ ] Tooltip: Topology
- [ ] Tooltip: Scenario

------

# LES form

![screen shot 2015-06-18 at 3 17 19 pm](https://cloud.githubusercontent.com/assets/2676542/8232081/3900b0ba-15cd-11e5-99ad-ef95ab81713a.png)

------

- [ ] Tooltip: Permissions
- [ ] Tooltip: Technology profile CSV

------

**Comment by grdw** [comment]
@ChaelKruip  in the code you can look for `'CHAEL TEXT HERE' ` on the `documentation` branch

**Comment by ChaelKruip** [comment]
> @ChaelKruip in the code you can look for the self-explaining-'CHAEL TEXT HERE'-placeholder, on the documentation branch

:+1:

**Comment by grdw** [comment]
I'm asuming this is done. Therefor closing.
