### ISSUE TITLE
Treat EDSN profiles differently from individual profiles when assigning them to households

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#178]
EDSN profiles represent groups of households larger than typically 100. It would be nice if they are selected only for connections with > 100 households.

We have to think what would happen if the concurrency is minimised for such a group...

**Comment by grdw** [comment]
I think we should handle it as a 'separate technology'. Household larger than 100 and Household's smaller than 100. It would than automatically select the correct 'technology' according to the total amount of `units`.

**Comment by ChaelKruip** [comment]
> It would than automatically select the correct 'technology' according to the total amount of units.

As long as that is the case you can make it two different technologies indeed. Not highest priority now.

**Comment by grdw** [comment]
I'm well on my way with this issue. Though we still need to think about the concurrency.

**Comment by ChaelKruip** [comment]
> Though we still need to think about the concurrency.

If after minimising concurrency the groups become smaller then the 'threshold' for aggregation, the individual profiles should be used IMO. 

Also, I think that the threshold should be lower than 100. Perhaps we can even make this user-defined?

**Comment by ChaelKruip** [comment]
> Though we still need to think about the concurrency.

If after minimising concurrency the groups become smaller then the 'threshold' for aggregation, the individual profiles should be used IMO. 

Also, I think that the threshold should be lower than 100. Perhaps we can even make this user-defined?

**Comment by grdw** [comment]
In merge #206
