### ISSUE TITLE
It should be possible to make a topology or profile private

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#181]
Now the interface does not seem to support it.

**Comment by grdw** [comment]
You can already make a topology private / public:
![screen shot 2015-06-25 at 9 47 40 am](https://cloud.githubusercontent.com/assets/2676542/8349696/3e8fca8c-1b1f-11e5-8ffe-ddb2ef8f39a8.png)

I don't think you can make load profiles private / public.

**Comment by grdw** [comment]
It's now also possible to make load profiles public/private. http://beta.moses.et-model.com/load_profiles/new
