### ISSUE TITLE
Massive interaction improvement when it comes to the current load graph

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#187]
![screen shot 2015-06-25 at 10 41 00 am](https://cloud.githubusercontent.com/assets/2676542/8350527/c670a848-1b26-11e5-8236-4aa462ca3407.png)

Just throwing in a wild idea here. Is it possible to just always show the user the coloured dots (under the 'View default topology' button). And whenever he clicks on the green one - a tiny loader will appear and the loadGraph will add the green line for storage. 

This way we don't need to deal with those rather ugly radio buttons and just throw those out of the window.

@ChaelKruip what do you think?

**Comment by ChaelKruip** [comment]
After discussing this @grdw and I decided that this idea is going to confuse the user because different strategies will show up as the same (green) effective load curve. So, there is no one-on-one relation between the suggested buttons and the curves in the chart. Closing.
