### ISSUE TITLE
Discussion: Computing market models

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#193]
@ChaelKruip @dennisschoenmakers Here is my understanding of market models, and how I expect them to behave with an LES. Please correct anything I have wrong, or add any other thoughts of your own. :grin:

#### Basics

* Market models assign nodes from an LES into groups (a `stakeholder`).
* Endpoints in the LES are likely to be assigned to a “Consumer” and/or “Aggregator” stakeholder.
* Nodes higher in the network will be assigned to other stakeholder groups, such as “Supplier”.
* Stakeholders are associated with each other through a `relation`.

#### Relations

Relations describe the way one stakeholder interacts with another. They consist of:

* A `measure` (or “base”) which describes some measurable quantity. This might be maximum kW load, capacity, flexibility, etc. See #191.

* A `tariff` uses the relation, the LES, and the `measure` to determine a price.

* The combination of a `measure` and `tariff` constitute a `payment rule`.

#### Example

For simplicity, imagine a “consumer” group with two endpoint nodes, and a “supplier” group. “consumer” is related to “supplier” with a “max kW” measure.

![a-simple](https://cloud.githubusercontent.com/assets/4383/8454890/809fef82-1ff8-11e5-8fe8-3785fc0f6bfb.png)

To determine the price of a relation, we need to

1. Determine the maximum load of each consumer for the chosen interval (one month?).
2. Compute the tariff.
3. Sum each computed tariff to get the total price of the relation.

#### Random Thoughts

1. I prefer “measure” to “base”, as the latter is a very generic term. “Unit” would be better still, but is already used to describe the number of installed units of a technology. "Quantity" might be another alternative.

2. A consumer is omitted when calculating a relation if the supplier is not a parent:

  ![a-exclusion](https://cloud.githubusercontent.com/assets/4383/8454900/91dc0092-1ff8-11e5-8c61-f316d9bccdcf.png)

  Even though (C) is member of the "consumer" group, it isn't considered part of the relation as it doesn't have a "supplier" parent.

3. It's not clear if we need to return a single price for the relation over the entire year, or if we need to compute the price separately for each time-step.

4. ???
5. Profit!

**Comment by ChaelKruip** [comment]
> Market models assign nodes from an LES into groups (a stakeholder).

Not really. A node will not necessarily overlap with any stakeholder or vice versa. More concretely:

* Customers: are represented by end-nodes of the topology (or groups thereof, see Cooperations). One LES can have many.
* Cooperations: One per LES for now. End-points or even individual technologies (the latter is point of discussion and will be clarified next Tuesday) can be made part of the Cooperation. Once they are part of it, we need to be able to treat them as a group: the Cooperation can have interactions with other stakeholders as if it was a customer (but now with the joint consumption and production of the end-points it represents).
* System Operator: this is the stakeholder that is responsible for the infrastructure. This does **not** mean that he should be associated with any nodes, however. He is the one who has to pay if a transformer needs to be replaced though.
* Producer: This stakeholder is also not associated with a node. It is the owner of the (scaled) electricity production park and basically has to pay for fuel and power plants (the cost calculations for this are already in the ETM).
* Supplier/retailer: also not part of the topology. He buys electricity from the producer and sells it to the customers and/or cooperation. Only a financial stakeholder.

So, the market model is only very mildly 'connected' to the topology and the households. The strongest link is that the customer/cooperation are associated with end-points and needs to keep track of kWh consumption and connection size (kW_connection). The S.O. needs to extract some info from the topology: mostly investment costs and possibly some extra costs if stuff breaks down.

**Comment by ChaelKruip** [comment]
> Endpoints in the LES are likely to be assigned to a “Consumer” and/or “Aggregator” stakeholder.

Yes. Where the Aggregator is the stakeholder that groups customers into a cooperation (which is another customer).

**Comment by ChaelKruip** [comment]
> Nodes higher in the network will be assigned to other stakeholder groups, such as “Supplier”.

No. (see long answer for details).

**Comment by ChaelKruip** [comment]
> Stakeholders are associated with each other through a relation.

Yes. Every line in the relation table corresponds to a financial transfer.

> A tariff uses the relation, the LES, and the measure to determine a price.

Not quite. The tariff **describes** the price for a quantity (specified by the 'measure') and measured in the LES. So, when you measure 2kWh consumed in a time step, the measure is set to 'kWh' and the tariff is '1EUR/kWh' the financial interaction will yield 2EUR.

The tariff does not have to be a fixed number but also might be given by a static profile. Later (sprint 8), we are planning to make the tariff dynamic: dependent on the Merit Order price.

**Comment by ChaelKruip** [comment]
> I prefer “measure” to “base”, as the latter is a very generic term. “Unit” would be better still, but is already used to describe the number of installed units of a technology. "Quantity" might be another alternative.

@grdw and I decided to go with 'foundation' for now as we felt the same about 'base'. 'Quantity' is also fine by me.

**Comment by ChaelKruip** [comment]
> A consumer is omitted when calculating a relation if the supplier is not a parent:

No. The supplier is more like an abstract entity that provides all electricity needed by the LES. It acts through the HV network for the moment.

**Comment by ChaelKruip** [comment]
> It's not clear if we need to return a single price for the relation over the entire year, or if we need to compute the price separately for each time-step.

True! I think that we need to have pricing on each time-step. In the current Market model (real life) most financial interactions are based on year-totals but this is likely going to change. Noteworthy exceptions are the kW_contracted and kW_max which are even now under constant 'measurement'.

**Comment by antw** [comment]
> No. No. No. ... No.

We're off to a good start. :anguished: 

> A node will not necessarily overlap with any stakeholder or vice versa.

Given a stakeholder with no mapping to the LES, how does a price rule work? So far, all the foundations described are concrete concepts within an LES – kWh, max kW, etc. How would we determine the price of an interaction in this situation?

**Comment by dennisschoenmakers** [comment]
> > No. No. No. ... No.

https://www.youtube.com/watch?v=umDr0mPuyQc :grinning:

**Comment by ChaelKruip** [comment]
> Given a stakeholder with no mapping to the LES, how does a price rule work?

Price rules are generally linked to concrete concepts within the LES fortunately. Most are related to what the customers use, produce or 'deploy' (flexibility), the kind of capacity their connection has etc.

To give a (hopefully reassuring) example of an interaction between stakeholders that do not directly reflect nodes in the LES:
The Government (added it to the stakeholders list above as well) gives a subsidy of 4EUR/kW to every kW of flexibility provided by the Cooperation. Both Government and Cooperation are not associated with a node but the actual 'stuff' that is used as the 'foundation' can be measured in the LES.

**Comment by antw** [comment]
> The Government (added it to the stakeholders list above as well) gives a subsidy of 4EUR/kW to every kW of flexibility provided by the Cooperation. Both Government and Cooperation are not associated with a node but the actual 'stuff' that is used as the 'foundation' can be measured in the LES.

This makes sense as the *thing* being measured exists in the LES. But what if I create a payment rule between a producer and a supplier/retailer:

`Producer`  →  `Retailer`  →  `Customer`

If neither exist as an entity in our network, what are we measuring between the producer and retailer?

Why not...

`Producer` ↘
`Retailer`  →  `Customer`

I'm not suggesting we'd actually do that, but the retailer must be adding some sort of behaviour which justifies its placement between the producer and the customer, and prohibits us from relating the two directly. What *is* that behaviour?

So far, it seems to me that we have only two *types* of Stakeholder:

* **Those which have a direct mapping to nodes in the LES.**
  *Consists of customers and co-operations. Customers contain all end-points; co-operations contain a subset.*

* **Those which have no direct mapping**, but aggregate information from the stakeholders below.
  *Producers, suppliers, governments, ...*

> System Operator: this is the stakeholder that is responsible for the infrastructure

I might be inclined to argue that an S/O also has a direct mapping to the LES: it is a set of all nodes containing infrastructure for which it is responsible. It might be that in a small LES, the S/O is a set containing *all nodes*, or all nodes minus the endpoints.

> The supplier is more like an abstract entity that provides all electricity needed by the LES. It acts through the HV network for the moment.

*All* electricity? Including that produced in LES (solar PV, etc)? My mental model had producers and retailers representing energy coming from – or returned to – the grid. In an LES, this is the top-level "root" node.

> https://www.youtube.com/watch?v=umDr0mPuyQc :grinning: – *@dennisschoenmakers*

![swallowed ideas](https://cloud.githubusercontent.com/assets/4383/8463405/ee7b96da-2031-11e5-80e9-01be490b8604.jpg)

**Comment by antw** [comment]
> Producer → Retailer → Customer
> 
> If neither exist as an entity in our network, what are we measuring between the producer and retailer?

I'm guessing the answer to this is...

* The consumer may have a load equivalent to 10 kWh.
* `Retailer` → `Customer` has a price rule consisting of `kWh` and `€1/kWh`, therefore the price of that relation is €10. 
* `Producer` → `Retailer` has a similar price rule, but with a tariff of `€0.80/kWh`, therefore its relation is priced at €8.

We can therefore infer that the retailer is making €2 profit.

But even in this case, the producer gets information about its *foundation* – the number of kWh – from the customer(s) at the end of the path.

**Comment by ChaelKruip** [comment]
> What is that behaviour?

Excellent question! We have been suggesting to group the producer and supplier into one stakeholder. The client has been pushing for separate ones. I think that in this case the measurable quantity is the total amount of electricity (kWh) produced by the producer and bought by the supplier. This is again related to the consumed amount of electricity of the customers.

**Comment by antw** [comment]
> I think that in this case the measurable quantity is the total amount of electricity (kWh) produced by the producer and bought by the supplier.

Thanks! That being the case, I don't think this is too hard. :+1:

**Comment by ChaelKruip** [comment]
> All electricity? Including that produced in LES (solar PV, etc)? My mental model had producers and retailers representing energy coming from – or returned to – the grid. In an LES, this is the top-level "root" node.

You are right. Only the electricity that is transported through the HV net node is produced by the 'Producer'.

**Comment by ChaelKruip** [comment]
Closing this.
