### ISSUE TITLE
Profile uploading interface should allow for uploading of multiple curves (for flexible profiles)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#198]
Profiles for technologies that have load-management options often have two components. When uploading profiles for such technologies, the user should be invited to upload the correct number of curves.

When the user selects a technology, the number of upload widows (and their titles) should dynamically be adjusted.

The properties of curves are as follows:

|Technology|number of curves|Curve 1| Curve 2| Scaling|Part(s) used when load-management is 'off'|
|----|----|----|---|---|---|
|Base load (individual)| 2 | Inflexible part| Flexible part| yearly demand in kWh|sum of both|
|Base load (aggregated)| 2 | Inflexible part| Flexible part| yearly demand in kWh|sum of both|
|Electric vehicles| 1 | Inflexible part| | storage volume kWh||
|Solar PV| 1 | Inflexible part| | capacity in kW||
|Space heating HP| 2 | Use part| Availability part| storage volume in kWh|use part|
|Hot water HP| 2 | Use part| Availability part| storage volume in kWh|use part|

@antw Do you agree with the above?

**Comment by grdw** [comment]
I managed to change the underlying dat structure for this issue . 

Things that are still out in the open

- [] Migrate current flex/inflex profiles correctly to `profile_curves`-table
- [] After deploy: rename `load_profiles` folder in shared/public to `profile_curves`
