### ISSUE TITLE
How can high concurrency for EV have a positive effect on load reduction with storage

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#202]
I am trying to wrap my head around the following effect (at least qualitatively): If, in [this LES](http://beta.moses.et-model.com/testing_grounds/129), I give all EV the same profile and apply storage, the reduction is a LOT (even in January):
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8499895/8dc14fa8-2197-11e5-89ce-76b1f0a939f0.png)

But when I use as many profiles (spreading the load), the reduction when using storage is far less:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8499888/63730430-2197-11e5-9ee9-8f47300d33bc.png)

How can this be?

**Comment by jorisberkhout** [comment]
This has to do with the differences in distance travelled for each profile. Driver 1 travel only 4.3 km (total from and to work). See an overview of the distances travelled for each driver in the tabel below:

<img width="211" alt="screen shot 2015-07-03 at 16 12 22" src="https://cloud.githubusercontent.com/assets/4669028/8500669/9043fda0-219e-11e5-8998-64bf8daedd3f.png">

**Comment by ChaelKruip** [comment]
@jorisberkhout thanks for your input. Unfortunately, it seems to be a more technical issue. If you look at the first week of January for one profile you can see huge reductions in load:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8500973/90e4ca0c-21a1-11e5-9046-530776e579ec.png)
For a number of profiles that reduction is gone:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8501026/05bb1ad4-21a2-11e5-9950-b3141bfae721.png)

I would trust the latter result more because there is not enough local solar PV production (see blue curve) to charge the EV at all.

**Comment by ChaelKruip** [comment]
After @antw's fix of https://github.com/quintel/etmoses/commit/969cf3b2b6fc1d4e87c45b99032068855ee25332, the results are less weird but still there is the following issue:

For a single profile there are moments that the EVs are all loading to buffer the excess PV production (which is expected):
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8501280/58900182-21a4-11e5-98b0-2a8f4a744c29.png)

For multiple profiles, I would think this effect would be less: the concurrency of loading is lower with multiple profiles. But I see much higher peaks in summer weeks then would be the case without storage enabled. Maybe I'm tired and not reading these curves right but it looks to me as if the cars are loading at a higher capacity then the solar panels are actually proving:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8501260/1b1777fe-21a4-11e5-8d49-87a44a61c890.png)

Now that I think of it, this may be because the cars can only load at their maximum capacity at the moment and are (in effect) not loading for the entire duration of the time-step. Is that the case @antw ?
If not, are we sure that energy is conserved? Or are EVs buffering more kWh's than PV are actually producing?

**Comment by antw** [comment]
I think the problem in your example is that you're comparing a testing ground which has an EV technology which uses `profile_1` and `units=15` to a testing ground which uses a wide range of different profiles and `units=1`.

I created two new LES' based on yours: one which uses one EV `profile_1` and `units=15` technology **[here](http://beta.moses.et-model.com/testing_grounds/131)**, and another which uses 15 separate `profile_1` and `units=1` EVs **[here](http://beta.moses.et-model.com/testing_grounds/130)**. The charts are almost identical. In theory, I think they should be completely identical – I'll make an effort to find out why next week – but I think the remaining anomalies are tiny in the big scheme of things.

##### 1x `profile_1` and `units=15`

<img width="1179" alt="screen shot 2015-07-03 at 16 44 55" src="https://cloud.githubusercontent.com/assets/4383/8501990/e93f6e40-21a2-11e5-815b-82848b7779db.png">

##### 15x `profile_1` and `units=1`

<img width="1188" alt="screen shot 2015-07-03 at 16 45 56" src="https://cloud.githubusercontent.com/assets/4383/8501995/03433f56-21a3-11e5-807c-8054c56d5478.png">

> Or are EVs buffering more kWh's than PV are actually producing?

If you look at the load on `Cluster #2` and `Cluster #3` in the same time period, they have negative loads. PV from Cluster 2 and 3 is being used to charge EVs in cluster 1. Ideally they would prioritise EVs attached to their own node – PV in cluster 2 should charge EVs in cluster 2 first – but that depends on "subnet awareness" (got to find a better name for that).

![clusters](https://cloud.githubusercontent.com/assets/4383/8502205/e558ce78-21a4-11e5-8889-eaacd6658ec0.png)

**Comment by ChaelKruip** [comment]
@antw thanks for looking into this. I think your assessment makes sense. I'll do some more quantitative checks later.

**Comment by ChaelKruip** [comment]
I think this issue is fixed!
