### ISSUE TITLE
"Save as" option for LES would be great

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#203]
Now I end up editing and destroying my LES to try stuff out.

**Comment by grdw** [comment]
I fixed this accordingly: 

![screen shot 2015-07-06 at 11 19 43 am](https://cloud.githubusercontent.com/assets/2676542/8519165/ee84d7a2-23d0-11e5-8920-63ce1a3a6ec3.png)

It literally duplicates the current testing ground.
