### ISSUE TITLE
Stakeholders should become part of the technology table

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#205]
An extra column with a select box need to include:

* Customer
* Aggregator
* System operator
* Supplier
* Producer

**Comment by ChaelKruip** [comment]
This will also allow the user to assign an asset (a P2P or P2G installation, or a solar PV park) to a stakeholder. That stakeholder must then pay investment costs (spread of the lifetime of the asset).

The assets in the network that are **not** connected to an end-point (e.g., transformers) are property of the System Operator (so he needs to pay investments).

**Comment by antw** [comment]
FYI, the market model calculation currently operates at the *node level* (endpoints), not the technology level. I'm still thinking through the implications; just wanted to make it clear that this behaviour is not explicitly supported *at present*.

**Comment by ChaelKruip** [comment]
>  the market model calculation currently operates at the node level

Yes, that is what we need I think. First of all because we can only 'measure' most stuff (flexibility, capacity of the connection) on the node level. On the other hand, it makes sense to couple stakeholders to end-points (and assets in those end-points) through the technology table. 
I am still thinking about an elegant way to ensure that once and end-point is part of a stakeholder, all its rows in the table are too. Also see https://github.com/quintel/etmoses/issues/207

**Comment by grdw** [comment]
We decided to put this in topology. Closing.
