### ISSUE TITLE
When editing profiles, the 'defaults' that are shown are not the original/correct ones 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#216]
This is what I get when editing a heat-pump profile for instance:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8597362/3e06a54a-2655-11e5-87fe-302cf5b07379.png)

**Comment by grdw** [comment]
This was more of a database issue. The `technology`-keys in the couple-table were bad for Heat pumps. I've fixed it by manually changing the 4 rows in the database.
