### ISSUE TITLE
Validation needed for space heating heat pump profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#217]
The availability looks like this:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8597490/f91c27a6-2655-11e5-9942-1b37ebefe0ac.png)
I would expect the 'staircases' to be inverted for such profiles. Perhaps I am overlooking something in my scripts...

**Comment by jorisberkhout** [comment]
I looked into the scripts that generate the use and availability profiles for space heating **and** hot water heat pumps and spotted the following points that need fixing:

**Space heating script**
- [ ] There is no need to multiply by the COP as `capacity_in kW` already is the heat output capacity
- [ ] The volume that is set in `hp_space_heater_availability_profile_generator.py` (100 liter) conflicts with the volume that is set in `heat_pump_classes.py` (1000 liter). Either is fine, but they need to be consistent.

**Hot water script**
- [ ] There is no need to multiply by the COP as `capacity_in kW` already is the heat output capacity
- [ ] The temperature difference in `hp_water_heater_availability_profile_generator.py` (line 76) is too high. I suggest to use `temp_diff = 65 - 15 # degrees`

**Comment by jorisberkhout** [comment]
Reassigning to @ChaelKruip to make the changes and re-create the profiles.
