### ISSUE TITLE
Solar capping: expected behaviour

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#224]
# Complex (most beautiful) version

The slider for the capping of solar panels is a percentage between 0 and 100. This percentage gives the 'maximum percentage of the installed capacity that may be capped' if there is a congestion-problem. The installed capacity is defined for an end-point as:
```
pv_installed_cap = units * pv_capacity
````
and each end-point should be treated separately.

When deciding if there is congestion, we need to take into account all transformers that are affected by an end-point. It is probably easiest to do this top-down: find out if there is congestion on a transformer and then see which end-point are 'under' that transformer.

When all end-points are identified, the potential for solar capping can be determined:
```
total_capping_potential = 0
for each end-point:
   total_capping_potential += end-point.pv_installed_cap * max_capping_percentage
end
```
If the potential is smaller than the exceedance of the transformer, all end-points will cap the maximum.
If the total potential is larger than or equal to the exceedance of the transformer, the end-points will decrease their solar pv output by the following amount:

```
for each end-point:
   capping = end-point.pv_installed_cap * max_capping_percentage /  total_capping_potential
end
```

This will result in a load that is *just* what the transformer can handle.

# Simpler version (still depends on trafo congestion)

I realise that the above is quite complex (although it would be nice to have). A simpler version could be as follows:

The slider-value indicates the percentage of capping **no matter how big the problem at the transformer**. So, if the capping strategy is in effect, and there is congestion on a transformer 'above' the end-point, the solar pv production will be reduced by the following amount:

```
for each end-point:
   capping = end-point.pv_installed_cap * max_capping_percentage
end
```

# Simplest version

The simplest thing we can do and which is still relevant is to make the simpler version independent on the transformer failure. So, whenever the capping strategy is in effect, the solar panels will be capped with the percentage given by the slider. The user must then 'tweak' this slider value to solve congestion events manually.

@dennisschoenmakers @antw @grdw what do you think about the feasibility of the three options described above?

**Comment by antw** [comment]
The "Simpler version" should be easy to implement, although there is a caveat (described below). [ConservingProducer#conditional_consumption_at](https://github.com/quintel/etmoses/blob/0d8f10aca22d8a882af27c3d69e87517b83efbf2/app/models/network/conserving_producer.rb#L15-L17) needs to be changed to reflect the capping percentage:

```ruby
def conditional_consumption_at(frame)
  capping    = capacity * 0.5  # caps to 50% of capacity
  production = production_at(frame)

  production > capping ? capping : production
end
```

(@grdw: Note that we can't do `[production, capping].min` as the calculation happens in a tight loop with one iteration for each 15 minutes of the year; we can't afford the GC costs of 35,040 additional arrays per PV technology). 

You need to get the capping percentage to the technology, but I think inspiration can be taken from [ElectricVehicle](https://github.com/quintel/etmoses/blob/0d8f10aca22d8a882af27c3d69e87517b83efbf2/app/models/network/electric_vehicle.rb#L11-L23): just add an `attr_writer :capping_fraction` and override `self.build`.

**Unfortunately there is one problem with this:** if a "mandatory" technology (such as an inflexible base load) *needs* energy, the solar PV may be used beyond the user-defined capacity even if it will exceed the transformer capacity. Capping is only guaranteed to happen when there is a net surplus in the LES. I am quite confident that the subnet calculator can solve this, but that won't happen for a couple of weeks yet.

The "simplest solution" (number 3) would be foolproof, and will work exactly as expected in periods of surplus *and* deficit. To implement that, you want to leave `conditional_consumption_at` unchanged, and instead add `production_at`:

```ruby
def production_at(frame)
  capping    = capacity * @capping_fraction
  production = super

  production > capping ? capping : production
end
```

I think I would steer clear of option 1 ("complex version") for now. It would require an extra step after load calculation, and has the potential to become quite difficult in the event that a solar PV has *multiple* congested parents. Certainly do-able, but options 2 and 3 are preferable.

**Comment by ChaelKruip** [comment]
@antw thanks for your comments and pointers.

> The "Simpler version" should be easy to implement, although there is a caveat

@antw Do we already have a method to trace back a congestion event to the 'responsible' children? 

> The "simplest solution" (number 3) would be foolproof

Let's do this and refine later if the calculator allows it.

If we already have a method to find the children of a congested transformer, we could make the simplest version a bit less 'stupid / oversimplified' by only capping the production of  children that are actually responsible for the congestion.

**Comment by ChaelKruip** [comment]
> @antw Do we already have a method to trace back a congestion event to the 'responsible' children?

I guess that same question is relevant for most of the other load management options as well right? 

We only want to resort to 'saving' (of aggregated base-load) if there is a problem for example...

**Comment by grdw** [comment]
> You need to get the capping percentage to the technology, but I think inspiration can be taken from ElectricVehicle: just add an attr_writer :capping_fraction and override self.build.

This is already done.

````ruby
def production_at(frame)
  capping    = capacity * @capping_fraction
  production = super

  production > capping ? capping : production
end
````

All this is where the confusion starts. `capacity` is the maximum value of a certrain profile? Or is this the `capacity` of a node (confusing term). And why would I take the fraction of the capacity.

**Comment by antw** [comment]
> We only want to resort to 'saving' (of aggregated base-load) if there is a problem for example...

This is already true for all the "flexibility" technologies (in fact, for any Technology subclass where `capacity_constrained?` returns `true`, which is currently the case for flexibility technologies, and EV when load management is enabled).

> @antw Do we already have a method to trace back a congestion event to the 'responsible' children?

You should not need to do this for solutions 2 or 3; changing `conditional_consumption_at` or `production_at` will suffice. [TechnologyPath](https://github.com/quintel/etmoses/blob/0d8f10aca22d8a882af27c3d69e87517b83efbf2/app/models/network/technology_path.rb) will take care of limiting the consumption of technologies (including PV capping) when load management is turned on.

> If we already have a method to find the children of a congested transformer, we could make the simplest version a bit less 'stupid / oversimplified' by only capping the production of children that are actually responsible for the congestion.

I don't think this is possible without an extra step after load calculation (as suggested for solution 1) – or, at least, non-trivial changes to the calculation loop. I hate to sound like a broken record, but: subnet calculation. :grin:

> All this is where the confusion starts. capacity is the maximum value of a certrain profile? Or is this the capacity of a node (confusing term).

"confusing term" indeed. Technology `capacity` and node `capacity` are similar concepts, but not *quite* the same.

* The technology capacity is the value given by the user in the technology table ([adjusted for number of units](https://github.com/quintel/etmoses/blob/master/app/models/network/technology.rb#L92-L94)) and describes the maximum load that the technology may place on the network. For example, if you have **3 units** of a **2kW** solar PV, the technology capacity is 6kW.

* Node capacity describes the amount of load which may pass through the transformer before it becomes overloaded.

> And why would I take the fraction of the capacity.

If you want to limit the production of the solar PV not to exceed 50% of it's capacity, you need to know what that amount is.

**Comment by grdw** [comment]
@antw We're making this feature a bit more advanced. 

We try to detect if there's congestion within the network. I know how this is done in the Javascript (with the drawing of the red lines). But we're wondering if there's something similar in the `app/models/network` classes to detect if there's congestion. 

**Thinking out loud:**
I see this method though 

````ruby
def paths
  @paths ||= Network::PathCollection.new(
   technology_nodes.map(&Network::TechnologyPath.method(:find)).flatten,
   path_order)
end
````
And the `TechnologyPath` classes contain the `congested_at?` method. 

So through paths I'm able to see if there's a problem with a certain technology on a node. 

Am I warm or are these methods not going to help me?

**Stop thinking**
The reason for all this is to see if there's a problem with any node.

**Comment by antw** [comment]
> And the `TechnologyPath` classes contain the `congested_at?` method.
> So through paths I'm able to see if there's a problem with a certain technology on a node.

That's right. If `congested_at?` returns true, it means that a node in the path has reached (or exceeded) its capacity. The technology itself knows next-to-nothing about the network or its capacity. It asks for a certain load (`conditional_consumption_at`) which may or may not be fulfilled.

So the `Technology` says "I want this please..." but the `TechnologyPath` decides how much it can *actually* receive.

@ChaelKruip often describes looking for a node whose capacity has been exceeded, and then looking "down" into the network for affected endpoints. In reality, the load calculation works the other way around: it calculates individual technologies and looks "up" to find if there is an exceedance and then behaves accordingly. The `TechnologyPath` is used for this purpose. It contains the technology being calculated, and each parent node back to the HV network (the top-most node).

**Comment by ChaelKruip** [comment]
>  In reality...

Suggesting I am quite removed from it hub @antw? :rage:

**Comment by ChaelKruip** [comment]
> t calculates individual technologies and looks "up" to find if there is an exceedance and then behaves accordingly

If I interpreet this correctly, wouldn't it then be super easy to loop through all solar PV technologies and only decide to apply capping if the path upwards is congested?

Of course, we must check if the congestion is due to over-production (rather than consumption) otherwise capping will only aggravate the issue.

**Comment by antw** [comment]
> Suggesting I am quite removed from it

![south-park-s17e08c06-stay-out-of-my-damn-yard-16x9](https://cloud.githubusercontent.com/assets/4383/8723455/a6216a28-2bc5-11e5-81e2-4fa597b7a8ca.jpg)

--

> If I interpreet this correctly, wouldn't it then be super easy to loop through all solar PV technologies and only decide to apply capping if the path upwards is congested?

Depends on your definition of super-easy. Stopping the calculation mid-loop to do something else – in this case, cap solar PV – would be ugly, rather than hard. My *feeling* is that the TechnologyPath will already give you this behaviour for free and should not affect the technology in the event that capacity is not exceeded. I think [what I said for discharging EVs](https://github.com/quintel/etmoses/issues/174#issuecomment-115308346), is also true of solar PV capping.

Sorry that I can't be more exact in my prediction, but the lack of high-level network specs really hurts in situations like these. :disappointed:

**Comment by grdw** [comment]
If I understand correctly:

In this scope of code:

````ruby
def production_at(frame)
  production = super
  capping = (capacity * capping_percentage).abs

  production > capping ? capping : production
end
````
It's hard to detect if there's a problem in the overall network/topology (full thingy with all the loads).
So that has to be calculated somwhere else? For instance in another `calculation` class? Or does this need to be intertwined with the `TechnologyLoad` calculation? 

I'm sort of struggling right now where a logical starting point would be, to make our 'advanced' version of calculating the solar capping .

**Comment by grdw** [comment]
Maybe somwehere intertwined with the `PullConsumption` class?

**Comment by antw** [comment]
> Maybe somwehere intertwined with the PullConsumption class?

Yes, right at the end of the `context.frames do |frame| ...` loop we could look for paths which have an exceedance and end in a solar PV technology, and then call `path.consume` with however much load the PV may be capped.

```ruby
paths.each do |path|
  conservable = path.technology.conservable_production_at(frame)

  if path.congested_at?(frame) && conservable > 0
    amount = [conservable, path.exceedance_at(frame)].min
    path.consume(frame, amount, true)
  end
end
```

This would need:

* `conservable_production_at` added to the base Technology class, which returns 0.0.
* `conservable_production_at` added to ConservingProducer. It should contain the contents of the current `conditional_consumption_at`.
* `exceedance_at` added to TechnologyPath, which returns by how much capacity has been exceeded. This, in turn, probably needs you to add an equivalent method to both `Path` and `Node`; [see Path#available_capacity_at](https://github.com/quintel/etmoses/blob/e2a1c1189330c140c9192e8d8471c3e0e91d88a2/app/models/network/path.rb#L52-L59) for inspiration.
* And of course, don't actually do Array#min if you can help it, but compare the two values directly. :smiley:

--

Personally, I think adding special cases for one technology is an ugly solution, but if we must have this feature, then this solution is probably the quickest and simplest way to go about it.

**Comment by dennisschoenmakers** [comment]
> Sorry that I can't be more exact in my prediction, but the lack of high-level network specs really hurts in situations like these. :disappointed:

What do you mean with 'the lack of high-level network specs', @antw ?

**Comment by antw** [comment]
> What do you mean with 'the lack of high-level network specs', @antw ?

I mean tests which build a small network containing multiple nodes and technologies, calculates their loads, and asserts that everything is correct. We have a good number of tests for each individual technology types ([such as this one](https://github.com/quintel/etmoses/blob/e00ce2213c051c9b543a91b595f8adc6f33ae2e5/spec/models/network/electric_vehicle_spec.rb)), but it would be amazing to have some integration tests where we put together a small network and see how things behave.

Refinery has this (see [spec/integration](https://github.com/quintel/refinery/tree/master/spec/integration), or [this file as a simple example](https://github.com/quintel/refinery/blob/58c1138fd1a785ce77b5277b7c0e76d59befe11b/spec/integration/parent_and_two_children_spec.rb)) and the result is:

* We can have a lot of confidence about the way the calculation behaves.
* If we are unsure about something, it's easy to build a test and find out.
* Most importantly: because the tests are thorough, it's really hard to break things. If you have a Refinery network which calculated correctly yesterday, it will calculate correctly tomorrow. If you make a change to Refinery which would break an existing network, the tests are very likely to catch it before you commit.

Similar tests would be very useful in Moses because the technologies don't exist in a bubble; they are on a network with other techs, each reacting to one another and the network conditions (such as local excesses, or capacity constraints).

This was something @ChaelKruip and I discussed when I was in the office a few weeks ago, and we hope to do it as part of the post-project cleanup. There's a ["debt" Trello card](https://trello.com/c/NDbWUyJk/17-5-add-flow-calculation-specs) but it doesn't add any more details to what I said here.

**Comment by grdw** [comment]
> I mean tests which build a small network containing multiple nodes and technologies, calculates their loads, and asserts that everything is correct.

An idea about this: 

We could make more complex specs though, concering the load management strategies. These specs will high likely become 'slow'. So maybe we could tag those slower specs - exclude them from the default run - and only run those specs when you explicity tell the test-runner to run those tests. 

See: https://relishapp.com/rspec/rspec-core/v/3-1/docs/command-line/tag-option

**Comment by antw** [comment]
> Yes, right at the end of the context.frames do |frame| ... loop we could look for paths which have an exceedance and end in a solar PV technology, and then call path.consume with however much load the PV may be capped.
> 
> ```ruby
> paths.each do |path|
>   conservable = path.technology.conservable_production_at(frame)
> 
>   if path.congested_at?(frame) && conservable > 0
>     amount = [conservable, path.exceedance_at(frame)].min
>     path.consume(frame, amount, true)
>   end
> end
> ```

I'm a bit worried that my example may be too simplistic. `path.congested_at?` is only going to tell you if _consumption_ exceeds capacity, not if _production_ exceeds it. I think this is a problem, because you want to cap solar PV when there is too much production.

So it may be that you *also* have to rename `congested_at?` to `consumption_congested_at?` and add something like `production_congested_at?` to detect when we have to cap solar PV.

Here's a heavily annotated version which (I hope!) explains the idea a bit better:

```ruby
paths.each do |path|
  # Technology#conservable_production_at would be a method which tells us
  # how much of the technology's production may be capped at each point in
  # time. So, if the tech has a capacity of 2.0 kW and may be capped by
  # 50%, I expect this method would return 1.0 -- 1.0 kW may be removed
  # from its production in order to avoid exceeding the network capacity.
  conservable = path.technology.conservable_production_at(frame)

  # Here we'd check to see if the path is actually congested, and ensure
  # that the technology is allowed to be capped...
  if path.production_congested_at?(frame) && conservable > 0
    # ... then determine by how much to cap the technology. We don't want
    # to cap by any more than the exceedance (it makes little sense to
    # remove 1 kW if the network capacity is exceeded by only 0.1). At
    # the same time, we have to respect the technology and not cap it by
    # more than it allowes.
    #
    # In my mind, path.exceedance_at would return a positive value if an
    # exceedance is triggered by too much consumption, and a negative
    # value when too much production is the cause.
    exceedance = -path.exceedance_at(frame)    
    cap_amount = conservable < exceedance ? conservable : exceedance

    # Finally, "consume" the `amount` of energy. This effectively reduces
    # the production of the solar PV.
    path.consume(frame, cap_amount, true)
  end
end
```
