### ISSUE TITLE
Including stakeholders into topology

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#226]
- [x] Adding validation for stakeholders in Topology model
- [x] Showing stakeholders sub-menu section
- [x] When clicking a stakeholder - show which topology-nodes include this stakeholder.

**Comment by grdw** [comment]
@ChaelKruip with this feature. Can the 'include in cooperation' row in the technologies table be removed?

**Comment by ChaelKruip** [comment]
> Can the 'include in cooperation' row in the technologies table be removed?

Yes :smile:
