### ISSUE TITLE
Error when changing name of financial profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#227]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/8717996/93179468-2ba0-11e5-93c8-4431f5ee3ad5.png)

clicking 'update' results in:
![the_page_you_were_looking_for_doesn_t_exist__404_](https://cloud.githubusercontent.com/assets/1303760/8717986/85d5f330-2ba0-11e5-99f2-b6512174fdc5.png)

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/e2a1c1189330c140c9192e8d8471c3e0e91d88a2
