### ISSUE TITLE
Limit for assigning aggregated base-load profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#229]
The number of households for which the aggregated profiles should be used should be 30.

For buildings, the edsn are the only profile we have so we need to use those always.

**Comment by grdw** [comment]
https://github.com/quintel/etmoses/commit/ae2013ec9275e96bcb65b948a06215d6085a85b7

**Comment by grdw** [comment]
One question though, is it larger than and 30 (`>=`). Or just more than 30 (`>`)?

**Comment by ChaelKruip** [comment]
Doesn't matter. Both are fine.
