### ISSUE TITLE
Duplicates of stakeholders should be removed from drop down menu

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#231]
![screen shot 2015-07-16 at 15 21 03](https://cloud.githubusercontent.com/assets/1303760/8723496/64ac7a02-2bce-11e5-95b4-63dae01d71f4.png)

**Comment by grdw** [comment]
See https://github.com/quintel/etmoses/blob/master/app/helpers/testing_grounds_helper.rb#L82
