### ISSUE TITLE
If a measure does not exist for the selected topology, the user should be warned

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#236]
I think that there should be some feedback after the user clicks the  'calculate business cases'  button (which we do not yet have). 

The warnings/error messages should be quite specific because things can go wrong in several locations:

* The topology does not contain the information necessary for a measure:
  * Depreciation costs rely on **investment_cost, economic_lifetime, yearly_o_and_m_cost**
  * If stakeholders are not included, the measures do not know who to apply to
  * If capacities and 'units' are not specified for end-points, the measure for connections fails
* The stakeholder is defined in the topology but not in the Market Model (this does not need to be a problem, but the user should probably be warned)

**Comment by grdw** [comment]
> Depreciation costs rely on investment_cost, economic_lifetime, yearly_o_and_m_cost

How does this work exactly? 

> If stakeholders are not included, the measures do not know who to apply to

This means that my market model measures contain `stakeholders` that aren't in the topology. And the calculation should stop and throw an error?

> The stakeholder is defined in the topology but not in the Market Model (this does not need to be a problem, but the user should probably be warned)

And the other way around.

**Comment by ChaelKruip** [comment]
> How does this work exactly?

This is the 'transaction' from the stakeholder to itself in the matrix (see 'investments' cells in https://github.com/quintel/etmoses/issues/213). It is the sum of:
* Depreciation cost: investment / lifetime
* O&M cost per year (given by yearly_o_and_m_cost)

**Comment by ChaelKruip** [comment]
> This means that my market model measures contain stakeholders that aren't in the topology. And the calculation should stop and throw an error?

Not necessarily. Stakeholders do not have to be in the topology to send or receive money. But they do have to be in the topology to have a **measure apply to them**.

**Comment by ChaelKruip** [comment]
> And the other way around.

Not really. The Government, Supplier, Aggregator and Producer are usually not physically associated with any nodes of the topology. The user does not need to be warned about this.

**Comment by grdw** [comment]
We talked about this last friday I remember. The thing was that if 

![screen shot 2015-09-14 at 10 33 57 am](https://cloud.githubusercontent.com/assets/2676542/9845559/225fbdbc-5acc-11e5-9bc6-cff99fa298fe.png)

One of these does not appear in the topology the user should get a warning. 

If I understand correctly.

**Comment by ChaelKruip** [comment]
> If I understand correctly.

Wrong column! The payer or the payee don't have to be owners of nodes in the topology. The stakeholder to which the measure is applied **does**, however.
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9845979/7266dc7a-5acf-11e5-8092-a103f6c4448c.png)
The measures need to be able to measure (what's in a name :stuck_out_tongue_winking_eye: ) some quantity in the topology like how many kWh pass through a node or how high the load is for an end-point. So they apply to the topology.

**Comment by ChaelKruip** [comment]
In other words: The user should be warned if one of the stakeholders in the 'applied to stakeholder' column does not exist in the topology.

**Comment by grdw** [comment]
Thanks for explaining! :+1: 

I think the nicest way to do this is to use the import form to validate whether or not the business case can be build. 

Question: should this only be a warning? Or should the user not be able to make a LES at all?

**Comment by ChaelKruip** [comment]
> Or should the user not be able to make a LES at all?

I think it would be a bit too much to prohibit the user from choosing a combination of topology and market model that are not calculable. He should be able to combine them but get a clear message. This way, the user can either choose to edit the market model or the topology to make it work.

**Comment by grdw** [comment]
> but get a clear message.

I wrote a tiny validator class that checks if the applied to stakeholders are in the topology. However, when should the user be messaged? After importing, before importing?

**Comment by ChaelKruip** [comment]
> After importing, before importing?

I don't really have a preference. After might be more logical as the user is than in the position to edit the market model and the topology.

**Comment by grdw** [comment]
@ChaelKruip I need some warning text :smiley: 

I currently made the following sentence:

" This combination of market model and topology will cause the business case not to calculate completely."

But I'm guessing that you might have a better suggestion?
