### ISSUE TITLE
P2P batteries should not charge with capacities > their defined capacity (in kW)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#241]
This battery charges faster than 200kW:
![batterij_laden_-_chael_kruip_quintel_com_-_quintel_com_mail](https://cloud.githubusercontent.com/assets/1303760/8802422/968cb464-2fc1-11e5-9439-b6b0e3c50e1c.png)

**Comment by antw** [comment]
Can you link me to the LES please? It probably goes without saying, but that shouldn't be happening. :confused:

**Comment by ChaelKruip** [comment]
It's a LES that our client made... I was also looking for it. Perhaps it is private?

**Comment by antw** [comment]
It is indeed private, and seems to have been changed since the screenshot was taken. I'll try to reproduce it myself.

**Comment by ChaelKruip** [comment]
> Can you link me to the LES please?

[http://beta.moses.et-model.com/testing_grounds/172](http://beta.moses.et-model.com/testing_grounds/172)

**Comment by antw** [comment]
Okay, I know what the problem is. The conversion between kW loads and kWh *stored* is messing up the capacity limit on the technology. I'll aim to fix this tomorrow.

**Comment by antw** [comment]
![screen shot 2015-07-22 at 16 49 35](https://cloud.githubusercontent.com/assets/4383/8829995/acdb95fc-3091-11e5-9847-7dc0920085c6.png)
