### ISSUE TITLE
Buffering of local PV excess in EV Question

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#247]
![screen shot 2015-07-29 at 2 31 00 pm](https://cloud.githubusercontent.com/assets/2676542/8957617/e2ac3268-35ff-11e5-8efe-765c86737256.png)

Joris and I were discussing about the buffering of local pv excess.

The LES contained a single solar panel and a single electric car.

We fiddled around with some numbers.

But it somehow seems that the volume of the electric car is *always* being used in the network. That would be weird since in this testing ground there aren't any other consuming technologies that would be making use of the battery of the electric car, so why use it?

**Comment by grdw** [comment]
Including @jorisberkhout

**Comment by antw** [comment]
> But it somehow seems that the volume of the electric car is always being used in the network. That would be weird since in this testing ground there aren't any other consuming technologies that would be making use of the battery of the electric car, so why use it?

* The car does not know what other technologies are present in the network. I suspect that real-world EVs also don't inspect the network to determine if something else will want the energy later.

* There's no guarantee that PV excess will be available later. The excess energy stored in the EV may be used by the vehicle *itself*, to satisfy the requirements of its next journey.

The behaviour of electric vehicles was discussed in some detail in #234.

**Comment by jorisberkhout** [comment]
Thanks for clarifying this, @antw!
