### ISSUE TITLE
Selecting a strategy which has no impact on the load curve

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#248]
![screen shot 2015-07-29 at 2 37 20 pm](https://cloud.githubusercontent.com/assets/2676542/8957727/9db5a530-3600-11e5-8a10-8edb15c243b5.png)

It's possible to select a strategy which has no impact on the load curve.
However it looks like it has changed by a single quarter.

**Comment by antw** [comment]
Was an issue in the front-end chart, which I think I may have introduced last week. Sorry!

The loads calculated by the back-end are correct; the clue that it was an issue with the chart is that the loads were offset by exactly one point when showing the annual chart *and* the weekly charts. The annual chart plots 365 points (one per day) while the weekly chart plots 672 (one per 15 minutes for a one week period, i.e. 96 points per day).

If the back-end had been calculating "strategy" loads a day early, we'd expect the weekly load chart to show them as offset by 96 points.
