### ISSUE TITLE
Postponing of individual base-load

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#249]
I'm currently working my way through the 'Postponing of individual base-load'.

**What I've done so far:**
- Wrote specs to get a better understanding of the underlying code
- Trying to dissect `DeferrableConsumer`

**Comment by grdw** [comment]
There's one problem here right now. The `flex` profile is assigned to the `DeferrableConsumer`. However, the `flex` profile - when the strategy is enabled - is allowed to move to a non-congested point in the *profile* (for a max of 12 steps else the 12th step (3rd hour) is used). The *profile* consists of the `inflex` profile (and any other load on that particular node for that matter). 

**The actual problem:**
The `DeferrableConsumer`-class has no knowledge of congestion or the other loads on the network (?) so it never knows when it exceeds. The problem sounds the same as with `capping_of_solar_pv` so I'm considering to move this logic to the `PullConsumption` part of the code. Would this be a correct solution?

**Comment by antw** [comment]
> The problem sounds the same as with capping_of_solar_pv so I'm considering to move this logic to the PullConsumption part of the code. Would this be a correct solution?

No, but I can see why it might seem that way.

The technology doesn't know about congestion, but the calculator (PullConsumption) doesn't work directly on the technology itself, but instead acts on [the path from the technology to the root node](https://github.com/quintel/etmoses/blob/5fe28f264b969edd36979ed920a8bde5fbf0429e/app/models/network/technology_path.rb). This path *does* know about network congestion, and [is able to respond](https://github.com/quintel/etmoses/blob/5fe28f264b969edd36979ed920a8bde5fbf0429e/app/models/network/technology_path.rb#L25-L32) accordingly.

[It really does work already](https://gist.github.com/antw/e9f94ed3d7cb84cce67a#file-02-deferring-md). :grin:

**Comment by grdw** [comment]
I wrote specs to assert the code:

- https://github.com/quintel/etmoses/blob/issues/load-management/spec/controllers/testing_grounds_load_management_controller_spec.rb#L66:L73 
- https://github.com/quintel/etmoses/blob/issues/load-management/spec/controllers/testing_grounds_load_management_controller_spec.rb#L76:L87

These specs succeed now in the `issues/load-managment` branch.

I created another branch locally where I use the same tests on the current postponing strategy, but those two specs are not succeeding. It looks like the flex-load always shift 12 places even though it should shift 12 places unless there is 'space' on the network.

Including @jorisberkhout
