### ISSUE TITLE
Technical issue when it comes to set(:techs) and get(:techs)

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#250]
**In TechnicalLoad calculation**
The code [here](https://github.com/quintel/etmoses/blob/master/app/models/calculation/technology_load.rb#L13) sets the correct classes for the technologies (`OptionalConsumer`, `DeferrableConsumer`, etc.) and adds those technologies to a node. Which is fine.

**In PullConsumption**
Over [here](https://github.com/quintel/etmoses/blob/a8dd8146afb361328226d11a5221010b357a9eb5/app/models/network/technology_path.rb#L15) it gets those technologies but interprets every technology as a `Generic` in a test setup. Possibly also in the actual development env.

This is really annoying since I need to have that clear distinction between types of technologies.

How is this suppose to work?

**Comment by antw** [comment]
> Over here it gets those technologies but interprets every technology as a Generic in a test setup. Possibly also in the actual development env.

Do you have all the storage and flexibility strategies turned off? If you have them turned off, most technologies will become `Generic` since they no longer have any special behaviour (some will turn into `Null` since, when disabled, they should place no load on the network).

**Comment by grdw** [comment]
Yes it had to do with `disabled`, turns out that the `disabled_class` of a `DeferrableConsumer` is `Generic`.  Thanks! :smile:
