### ISSUE TITLE
When downloading a profile, the original name of the file is used (instead of the optional assigned name)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#26]
I'm not sure if this is a feature or a bug. To me it is a bit confusing.

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
I sort of gave this my own swirl. But you can change the filename by editing the `load_profile` name. The format of a `load_profile_component` file will be the following:

````ruby
"#{ name | key }.#{ component_type }.csv"
````
