### ISSUE TITLE
Text for buffering strategies should be changed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#264]
Buffering is not limited to local PV excess!

![etmoses](https://cloud.githubusercontent.com/assets/1303760/9197560/6f5e4dec-4035-11e5-9895-ba78bd17c6b9.png)

They should read something like:

* "buffering of electricity in EV"
* "buffering of heat in heat pumps"

**Comment by grdw** [comment]
Fixed with: b643b73
