### ISSUE TITLE
Buffering for EV seems to not be energy conserving

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#265]
When looking at the first week of september for [this testing ground](http://beta.moses.et-model.com/testing_grounds/187), I see that the load with buffering in EV is higher almost everywhere:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9197803/c578331c-4037-11e5-8231-481bca065fe5.png)
It seems that there is much more energy consumed when the buffering strategy is 'on'. This should not be the case. Buffering should only shift load to earlier times (in order to possibly prevent stresses on the network later on).

**Comment by antw** [comment]
I think this is because #131 is still pending. The EV is buffering up to 100% of it's battery volume even though it doesn't need that much for its next journey. The car gets reset to zero when it reconnects, hence it charges back up to 100% *again* creating additional load on the network.

**Comment by ChaelKruip** [comment]
:+1:
