### ISSUE TITLE
Buffering in heat pumps does not seem to do anything

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#266]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9198109/0d8fd5e0-403a-11e5-8947-086934cdc216.png)
There is no difference between the blue and green curves

**Comment by antw** [comment]
There's no `volume` set on the heat pumps in that LES. Presumable they can't buffer an infinite amount of energy, so lacking a volume, they won't buffer anything at all.

Setting a volume seems to inflate the loads though; I'm not sure why. I'll look into it also.

**Comment by antw** [comment]
Hmm... the load is inflated because when you supply a volume, the assumption is that you're using availability curves instead of load curves. This is a tricky one because that is true for EV but not for heat pumps.

**Comment by ChaelKruip** [comment]
> This is a tricky one because that is true for EV but not for heat pumps.

For heat pumps we **do** have both availability curves and load curves. Aren't they used both?

**Comment by antw** [comment]
No, the current behaviour (when heat pumps are on or off) is based on a "use" profile:

* **Buffering in heat pumps disabled:**

  Places a load on the network according to values in the "use" profile.

* **Buffering in heat pumps enabled:**

  Buffers whenever there is sufficient network capacity, and stores this energy internally for later. Energy is subtracted from the stored amount according to the "use" profile. If there is insufficient energy stored in the buffer, a load will be placed on the network to make up the difference.

#### For example

We might give a heat pump a use profile such as: `[0, 0, 0, 0.5, 0.4, 0.5]`, a capacity of 1.0 and volume of 2.0 (values in kW).

With buffering disabled, the heat pump load follows the profile `[0, 0, 0, 0.5, 0.4, 0.5]`.

With buffering enabled, the heat pump will start to buffer immediately (assuming network capacity permits): `[1.0, 1.0, 0.0, 0.5, 0.4, 0.5]`. The buffer fills entirely in the first two steps; it places loads on the network in the final three steps to refill the amount used. If the network had become constrained at that point, the loads might look like: `[1, 1, 0, 0, 0, 0]`.

Value | 1 | 2 | 3 | 4 | 5 | 6
--- | --- |  --- | --- | --- | --- | ---
Network Capacity | ∞ | ∞ | ∞ | ∞ | ∞ | ∞
Amount Used ("Use profile") | 0.0 | 0.0 | 0.0 | 0.5 | 0.4 | 0.5
External Load | **1.0** | **1.0** | **0.0** | **0.5** | **0.4** | **0.5**
Amount Stored | 1.0 | 2.0 | 2.0 | 2.0 | 2.0 | 2.0

Value | 1 | 2 | 3 | 4 | 5 | 6
--- | --- |  --- | --- | --- | --- | ---
Network Capacity | ∞ | ∞ | ∞ | 0.0 | 0.0 | 0.0
Amount Used ("Use profile") | 0.0 | 0.0 | 0.0 | 0.5 | 0.4 | 0.5
External Load | **1.0** | **1.0** | **0.0** | **0.0** | **0.0** | **0.0**
Amount Stored | 1.0 | 2.0 | 2.0 | 1.5 | 1.1 | 0.6

Value | 1 | 2 | 3 | 4 | 5 | 6
--- | --- |  --- | --- | --- | --- | ---
Network Capacity | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
Amount Used ("Use profile") | 0.0 | 0.0 | 0.0 | 0.5 | 0.4 | 0.5
External Load | **0.0** | **0.0** | **0.0** | **0.5** | **0.4** | **0.5**
Amount Stored | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0

**Comment by grdw** [comment]
I'm trying to make it work but somehow I'm not sure if the current buffering is working as it should.

As you can see at:

https://github.com/quintel/etmoses/compare/master...issues/%23266-buffering-heat-pumps-not-working#diff-697edaa1d8f85247b43b4350cd51e35bR106

However I have no idea what is influencing the output in the current setup.

**Comment by antw** [comment]
[Here's an example of it working](http://beta.moses.et-model.com/testing_grounds/110) (turn on "Buffering in heat pumps").

Here's the technology profile:

```json
{
  "Consumer": [
    {
      "name": "Buffer",
      "type": "households_space_heater_heatpump_air_water_electricity",
      "behavior": null,
      "profile": [0.0, 0.0, 1.0, 1.0],
      "load": null,
      "capacity": 500.0,
      "demand": null,
      "volume": 1000.0,
      "units": 1,
      "concurrency": "max"
    },
    {
      "name": "Base load",
      "type": "base_load",
      "behavior": null,
      "profile": [0.0, 0.0, 1.0, 1.0],
      "load": null,
      "capacity": 500.0,
      "demand": null,
      "volume": null,
      "units": 1,
      "concurrency": "max"
    }
  ]
}
```

**Comment by ChaelKruip** [comment]
> We might give a heat pump a use profile such as: [0, 0, 0, 0.5, 0.4, 0.5], a capacity of 1.0 and volume of 2.0 (values in kW)

Just to avoid confusion: the capacity is specified in units of kW and the volume in units of kWh.

> With buffering disabled, the heat pump load follows the profile `[0, 0, 0, 0.5, 0.4, 0.5]`.

The profiles (both 'use' and 'availability') for heat pumps should be scaled by the storage volume of the tank (also see https://github.com/quintel/etmoses/issues/299). So, if the volume and capacity are specified as above, a use/availability of 0.5 translates into `0.5 * 2.0
