### ISSUE TITLE
Making a separate technology for EDSN base loads

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#273]

**Comment by grdw** [comment]
I made a seperate technology for edsn-base loads and gave it the `optional` behavior. 

@ChaelKruip Does the code (based upon the units) need to auto-detect which base load technology type there's needed (aggregated or anonimous) ?

**Comment by ChaelKruip** [comment]
> @ChaelKruip Does the code (based upon the units) need to auto-detect which base load technology type there's needed (aggregated or anonimous) ?

Yes.

**Comment by ChaelKruip** [comment]
Can this be closed @grdw?

**Comment by grdw** [comment]
Not yet. There's still some front-end things that need to be discussed.
