### ISSUE TITLE
It should be possible to edit a topology (and market model) 'interactively'

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#274]
When you are working, you should be able to go back-and-forth between editing technologies, topology and market model until you are satisfied with the LES as a whole. 

I don't know how to ensure the following though:
* changing the topology/market model should not break other LESs
* changing the topology/market should not require constant renaming ('saving as')
* when satisfied the user should be able to 'save as' (I think)

**Comment by grdw** [comment]
> changing the topology/market model should not break other LESs 
> changing the topology/market should not require constant renaming ('saving as')

I think we should - when in the edit screen of a LES - make two buttons for 'topology' and 'market model'. When clicking on those buttons it would duplicate the topology/market_model and saving it as a new one everytime you make changes to that topology. 

Downside: database clutter.

**Comment by antw** [comment]
> I think we should - when in the edit screen of a LES - make two buttons for 'topology' and 'market model'. When clicking on those buttons it would duplicate the current topology/market_model and you can make changes.

Would it not be better to clone the MM/Topology only if there are other LES' using them?

```ruby
market_model = testing_ground.market_model

if market_model.testing_grounds.count.one?
  # Edit-in-place
else
  # Clone
end
```

Doesn't completely avoid cluttering the DB, but at least it won't create duplicates for every change the user makes.

**Comment by ChaelKruip** [comment]
> Would it not be better to clone the MM/Topology only if there are other LES' using them?

:+1:

**Comment by grdw** [comment]
> Would it not be better to clone the MM/Topology only if there are other LES' using them?

Sounds good.

**Comment by jorisberkhout** [comment]
I agree with @ChaelKruip that it would be nice if this can be solved. Changing the capacity of a transformer is now quite a lot of work, while it is something that I want to change in particular when testing a LES.
