### ISSUE TITLE
How does the current buffering function?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#275]
There's a `use` and `availability` profile. The user uploads it as such when creating a `LoadProfile`. 

Now I can't really find my way in where the `use` profile is and where the `availability` profile is, in the code (also in the specs for that matter). And where and how the two are 'connected'? To put it into basics: how is the current buffering implemented?

**Comment by grdw** [comment]
*Sees explanation at #266 *

**Comment by antw** [comment]
> *Sees explanation at #266 *

Yeah, I've yet to add the availability profile support to `Buffer` :disappointed:. I'll make sure that's done during this sprint.

**Comment by grdw** [comment]
@antw, @ChaelKruip and I also are trying to do the same. In order not to get two people working on the same job..

**Comment by antw** [comment]
:+1:

**Comment by antw** [comment]
FYI: [ElectricVehicle](https://github.com/quintel/etmoses/blob/b643b7304491684555033d14d794b013f6d8da9c/app/models/network/technologies/electric_vehicle.rb) uses an availability profile, so perhaps that can be of some use to you?
