### ISSUE TITLE
Scaling a scenario does not work anymore

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#277]
After hitting 'scale', the page does not load a new scenario.

**Comment by antw** [comment]
It's working fine for me. Maybe it has something to do with the full-size scenario being scaled; could you grab the ID for me?

**Comment by ChaelKruip** [comment]
> Maybe it has something to do with the full-size scenario being scaled;

I think it has to do with the presets having faulty input keys (https://github.com/quintel/etsource/issues/938). It works with a fresh scenario but not with preset scenarios.

**Comment by ChaelKruip** [comment]
Closing.
