### ISSUE TITLE
Scaling with the number of residents should be disabled

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#282]
The user should only be able to scale with the number of residences (that is the only supported option anyway).

**Comment by grdw** [comment]
This is in ET-model right?

**Comment by ChaelKruip** [comment]
> This is in ET-model right?

Yes, sorry.

**Comment by antw** [comment]
Closed by quintel/etmodel#1883.

**Comment by ChaelKruip** [comment]
:+1:
