### ISSUE TITLE
All technologies should get appropriate default values 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#285]
This table summarises the debts for the assignment of default values from the different technologies in ETMoses.  Boldface capital words mean that this still has to be done.

|Technology| Still needs capacity|Capacity should be fixed|Still needs volume|Volume should be fixed|Comments|
|---|---|---|---|---|---|
|HP space heating (air)| no | **YES** | **YES** | **YES** | (see https://github.com/quintel/etmoses/issues/270)|
|HP space heating (ground)| **YES** | **YES** | **YES** | **YES** | (see https://github.com/quintel/etmoses/issues/270)|
|HP hot water (air)| no | **YES** | **YES** | **YES** | (see https://github.com/quintel/etmoses/issues/270)|
|HP hot water (ground)| **YES** | **YES** | **YES** | **YES** | (see https://github.com/quintel/etmoses/issues/270)|
|P2G| **YES** | no | no | no ||
|P2H| **YES** | **YES** | **YES** | **YES** ||

**Comment by ChaelKruip** [comment]
P2H also must get a use profile (see https://github.com/quintel/etmoses/issues/296)

**Comment by ChaelKruip** [comment]
For volumes of HPs see https://github.com/quintel/etmoses/issues/270. The capacity should be taken from ETE but is 10.0kW in all cases.

**Comment by grdw** [comment]
![screen shot 2015-08-27 at 12 03 51 pm](https://cloud.githubusercontent.com/assets/2676542/9517974/b6d1228c-4cb3-11e5-9bb4-00ec5a5967e4.png)

With this being my database table, what would be the correct defaults (apart from the values you just specified)? Also could you maybe tell me which technology-values do and don't have a default?
