### ISSUE TITLE
Now that profiles are referenced by a database key, that key should be visible in the profile overview

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#290]
For example in the 'technology CSV dump', the user has no idea what profiles are used:
![screenshot_24_08_15_13_28](https://cloud.githubusercontent.com/assets/1303760/9439095/308d2050-4a64-11e5-8f95-5de5f80b67dd.png)

**Comment by grdw** [comment]
This is already deployed, forgot to close.
