### ISSUE TITLE
NICE TO HAVE: persistence of load chart and flex options options after editing

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#295]
Now you have to re-do everything (zooming, choosing which flex options to use etc) after an edit.

**Comment by antw** [comment]
Maybe we could save these options to `localStorage` whenever the user makes a change? That way it's easy to restore the settings when they come back to the page.

**Comment by ChaelKruip** [comment]
@grdw can we close this?

**Comment by antw** [comment]
I think the relevant pull request is #457 which is unmerged. I'll look into it today.
