### ISSUE TITLE
P2H must use a 'use profile' to empty its tank and should get default capacity and volume

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#296]
The specs are the same as the hot water heat pump:

* Tank volume: 100 liters
* Temperature difference: 80 degrees (from 15 to 95)
* Specific heat capacity of water: 0.00116 kWh / degree

Which results in a volume of: **9.3 kWh**

**Comment by antw** [comment]
As far as I can tell, this should work as expected save for the lack of profiles currently on beta. P2H already has a default volume assigned in the database, and correctly imports the capacity from ETEngine.

@ChaelKruip I'll reassign to you on account of the needed profiles. Assign back to me if I've misunderstood.

**Comment by ChaelKruip** [comment]
Profiles have been uploaded. Closing.
