### ISSUE TITLE
Volume of HP should not change its capacity

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#299]
If the heat pumps in my scenario have a 'volume' of 10.0kWh, the load is:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9443256/62867c98-4a80-11e5-8bcb-8bc72935fc72.png)
But with volume=100, the load is:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9443253/5e9ead8a-4a80-11e5-8b57-99e71ef4cfff.png)

**Comment by antw** [comment]
This is a known issue, caused by the HP load profile – currently a *use* profile – being scaled by the `volume` instead of the `capacity` (necessary for EVs). I'll revisit this in the next day or so once I have finished heat pump availability profiles and EV use.
