### ISSUE TITLE
'Saving' of aggregated base load profiles does not work 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#302]
Although the capacity of the transformer is exceeded, there is no reduction in load:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9462503/a0d44890-4b16-11e5-8888-991f66ac29b7.png)

@antw, please re-assign to @grdw if that makes more sense to you.

**Comment by antw** [comment]
> @antw, please re-assign to @grdw if that makes more sense to you.

I'll leave this assigned to me, but I *think* saving will work once we have a separate `base_load_large` technology for the EDSN base loads (see #273).

I'll keep the issue open and assigned to me as a reminder to check that the results are as expected.

**Comment by ChaelKruip** [comment]
@antw can this be closed?
