### ISSUE TITLE
Postponing of individual base load does not work

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#303]
Similar to #203 

![etmoses](https://cloud.githubusercontent.com/assets/1303760/9462573/0b01c63e-4b17-11e5-8f69-291f155998b6.png)
@antw, please re-assign to @grdw if that makes more sense to you.

**Comment by antw** [comment]
The curve being used in [that testing ground](http://beta.moses.et-model.com/testing_grounds/207) does not have separate flexible and inflexible components. In fact, there are only a couple of curves which do seem to have separate components:

* [edsn_e2a_flex](http://beta.moses.et-model.com/load_profiles/321)
* [edsn_e3a_flex](http://beta.moses.et-model.com/load_profiles/341)
* [anonimous_base_load_1](http://beta.moses.et-model.com/load_profiles/311)
* [anonimous_base_load_2](http://beta.moses.et-model.com/load_profiles/323)
* ...
* [anonimous_base_load_10](http://beta.moses.et-model.com/load_profiles/339)

The "create/edit" form only contains a field to upload one "default" curve, so I'm guessing this is still pending?

**Comment by ChaelKruip** [comment]
> The "create/edit" form only contains a field to upload one "default" curve, so I'm guessing this is still pending?

I think so. Let's assign to @grdw as he was working on this.

**Comment by ChaelKruip** [comment]
The postponing seems to work fine. I'll make a separate issue for the splitting up of profiles. Closing.
