### ISSUE TITLE
All automatically chosen base-load profiles need a flex and inflex part

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#305]
Now only a few have one.

**Comment by antw** [comment]
I suspect what's really needed here is the "upload / edit load profile" page to allow a user to upload the curve *components* depending on the type of curve, then we wouldn't have to do this manually ourselves.

**Normal curve:**
* "default" component only

**Base load profile:**
* "inflex" component
* "flex" component

**Heat pump profile:**
* "availability" component
* "use" component

(Maybe we can find a more generic name than "heat pump profile"?)

**Comment by ChaelKruip** [comment]
> I suspect what's really needed here is the "upload / edit load profile" page to allow a user to upload the curve components depending on the type of curve,

Yes! :+1:

**Comment by grdw** [comment]
This is already the case if you look at:

http://beta.moses.et-model.com/load_profiles/new

Close this issue. Re-open at will.
