### ISSUE TITLE
Flexible and inflexible parts should not be presented in the profile overview

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#306]
It is not very clear for the user which profile is which:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9463558/9bd0cda8-4b1d-11e5-99c8-9ad4dda97a6d.png)

**Comment by grdw** [comment]
Well this has to do with categorization of the *load profiles*. Not wether the *load profile components* have a `flex` or `inflex` part. I removed the categorizations `flex` and `inflex` for it has nothing to do with the actual load profile.
