### ISSUE TITLE
The market model table needs a re-style

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#308]
Currently it has the following columns:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9467778/4efe8bd4-4b3e-11e5-9830-38032a48e54d.png)
This should become:

|From stakeholder|To stakeholder|Measure|Applied to stakeholder|Tariff (EUR/unit)|
|---|---|---|---|---|
|Customer|Supplier|kWh consumed|Customer|0.22|

As described in https://github.com/quintel/etmoses/issues/219

**Comment by ChaelKruip** [comment]
Including @antw as this ties in with the way the measures work ('measure' and 'applied to').

**Comment by grdw** [comment]
What's the purpose of the 'Applied to stakeholder' field? Is that a completly different field than `from` and `to`?

**Comment by ChaelKruip** [comment]
> What's the purpose of the 'Applied to stakeholder' field? Is that a completly different field than from and to?

Yes. That is the stakeholder that the measure is applied to. So, the customer (from) might pay the supplier (to) for the number of kWh produced (measure) by the producer (stakeholder that the measure is applied to).

**Comment by grdw** [comment]
![screen shot 2015-09-01 at 10 09 48 am](https://cloud.githubusercontent.com/assets/2676542/9599133/99cbe8a2-5091-11e5-8f31-2ddd80c5ef86.png)

Does that imply that the edit and new screen also need another dropdown box, selecting to which stakeholder (from or to) the measure applies to?
