### ISSUE TITLE
It should be possible to 'see' which Market Model you are using

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#309]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9468401/bac9fbc0-4b41-11e5-910f-15654d97b2c7.png)

**Comment by grdw** [comment]
This sounds like it will result in @dennisschoenmakers making another issue to remove this market model link :sweat_smile:  

Don't know what your current thoughts are?

**Comment by ChaelKruip** [comment]
> This sounds like it will result in @dennisschoenmakers making another issue to remove this market model link 

Not really. The topology is shown explicitly in the current page and therefore the link to view the topology does not add any new information. This is not true for the market model. Only the business case summary is shown... I would say that a link is still desirable.
