### ISSUE TITLE
"Subnet Awareness" needed for load calculation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#310]
This ticket is meant to document and discuss the wanted improvement of the load calculation. 

# Background 
The current 'push-pull' implementation for load calculation first pushes all production (starting at the end-points) 'up' to the stem of the network (the HV node). Subsequently, the (mandatory) consumption of all technologies is 'pulled' from the network (again starting at the end-nodes).

# Problem with 'push-pull'
Because the 'push' and the 'pull' are independent, load is unable to 'cancel out' during its traveling over the network. 

Perhaps two neighbouring end-points have opposite and equal loads (let's say, 5 and -5). In reality, these loads would cancel out at their first common ancestor (trafo 1):
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/9471247/bdc75cec-4b4f-11e5-9f05-ca520b8191d9.png)
No load would ever make it up to trafo 2, as the current would flow from HH2 to HH1.
With 'push-pull', however, the load is transported up to the highest level and the capacity of trafo 2 (3 kW) is exceeded by both the 'push' and the 'pull' step. In this way, the network thinks that it is congested even if in reality it isn't.

# Proposed solution
An alternative load calculation strategy would be to start (again) from the end-points of the network but try to cancel out production and consumption at every 'branching point'. Such a strategy would recognise that there is no load transported past trafo 1 and conforms with how electricity behaves in real life.

Including @dennisschoenmakers @jorisberkhout
@antw is this a proper description of the issue with 'push-pull' or did I misunderstand/forget anything?

**Comment by dennisschoenmakers** [comment]
What's the verdict on this? :smile:

**Comment by ChaelKruip** [comment]
I have made a [LES that recreates the above example](http://beta.moses.et-model.com/testing_grounds/212). Strangely (but as @antw did mention before), trafo 2 is not congested as would be expected from the 'push-pull' algorithm. At least we can use the LES to check if things are still working properly and to use as integration test for the new method (subnet awareness).
