### ISSUE TITLE
Expand topologies by default to maximum size

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#312]
Now, most topologies are actually collapsed too far and the user needs to expand them after each editing step (of the technology matrix or the topology itself or a profile etc).

It would be even better if the topology view could 'remember' its state after each editing step.

**Comment by grdw** [comment]
I managed to. However, I'm now testing with the Lochem topology. 
Which results in this: 

![screen shot 2015-08-31 at 11 18 46 am](https://cloud.githubusercontent.com/assets/2676542/9575723/1417fac6-4fd2-11e5-95ce-17ccedaec094.png)

**Comment by ChaelKruip** [comment]
> Which results in this:

I don't think that is a problem. The user can collaps the topology view right?

**Comment by grdw** [comment]
> I don't think that is a problem. The user can collaps the topology view right?

In a way. I'll show you what the issue is.

**Comment by grdw** [comment]
Issue fixed with: 033a3d8
