### ISSUE TITLE
LESS show page can be better organised

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#316]
Currently, it is a bit chaotic.

My thoughts on how it can be improved:

* It should show all the generic stuff first, on top (e.g. strategies, stakeholders, the topology).

* Below the topology it should read something like: "Click on a node above to see the load and technologies".

* Once you select a node you should see a header title "Load and technologies for connection HH1", the load chart (already implemented now) and the technologies. No need to 'open and close' the latter I think.

cc @antw and @ChaelKruip

**Comment by ChaelKruip** [comment]
:+1:

**Comment by grdw** [comment]
@ChaelKruip Is this issue still relevant? 

> Once you select a node you should see a header title "Load and technologies for connection HH1", the load chart (already implemented now) and the technologies. No need to 'open and close' the latter I think.

This is maybe something that's still nice to do though.

![screen shot 2015-09-14 at 10 17 29 am](https://cloud.githubusercontent.com/assets/2676542/9845288/0cab470e-5aca-11e5-98b6-a8d1438ae416.png)

Maybe something subtle like the header in the screenshot above.

**Comment by ChaelKruip** [comment]
> Maybe something subtle like the header in the screenshot above.

If this can be done without too much work I would like that yes.

**Comment by grdw** [comment]
> If this can be done without too much work I would like that yes.

Yes. This can be done without too much work.

**Comment by grdw** [comment]
Fixed with: 1274e5b
