### ISSUE TITLE
Business case interface needs 'back to load' button or should be opened in new tab

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#317]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9492565/fe6bf2e0-4bf8-11e5-8835-8ea9a643a525.png)

@dennisschoenmakers @antw which option would you prefer? Open in 'new tab' or 'go back'?

**Comment by antw** [comment]
> @dennisschoenmakers @antw which option would you prefer? Open in 'new tab' or 'go back'?

"Go back" please. Opening in a new tab/window [isn't very user-friendly](http://www.webcredible.com/blog/beware-opening-links-new-window/).

**Comment by grdw** [comment]
![screen shot 2015-08-28 at 3 01 52 pm](https://cloud.githubusercontent.com/assets/2676542/9546772/c1212830-4d95-11e5-9bcb-c5736262c745.png)
Like this?

**Comment by grdw** [comment]
DIscussed it and changed it on the fly.
