### ISSUE TITLE
Depreciation cost and O&M cost of infrastructure and technologies should be included in cost

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#319]
As mentioned in https://github.com/quintel/etmoses/issues/219, the depreciation cost of the network needs to be accounted for. 

I just realised that the same goes for O&M costs and the depreciation costs of technologies. I suggest the following approach:
Depreciation cost and O&M cost are paid to 'yourself'. So, in the financial interaction matrix, the diagonal should include those costs. Obviously, these costs should only be accounted for once: as expenses. 

The System Operator (SO) usually 'owns' the network nodes that are not end-points. If we keep a 'one-stakeholder-per-node' approach (but see https://github.com/quintel/etmoses/issues/315) this payment to oneself does not have to be included explicitly in every Market Model.

Similarly, the depreciation costs of technologies at the end-points could be calculated for customers and cooperations. This requires that `initial_investment` and `technical_lifetime` are imported from ETE.
NOTE: we use 'economic_lifetime` for the network components in ETMoses because they make more sense for such investments but they are to be used in the same way (depreciation_cost = investment/lifetime).

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by grdw** [comment]
Also need to expand `etengine` becuase of these changes.

**Comment by ChaelKruip** [comment]
> Also need to expand etengine because of these changes.

:+1:
