### ISSUE TITLE
Behaviour of 'Capping of solar pv' strategy not as expected

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#320]
In [LES#216](http://beta.moses.et-model.com/testing_grounds/216), I created a very simple testing ground with only households and residential PV on the same, not technologies on the other. I applied the 'Capping of solar pv' strategy (with slider setting 100%) and, given the large installed capacity of PV I installed, I was expecting the load to be equal to the negative max of the transformer most of daytime. This is however not the case, see e.g. the circled part of the image below.

It appears like the strategy first caps the solar PV to the maximum capacity of the transformer and then subtracts the baseload, whereas I expect this to happen the other way around.

<img width="1244" alt="screen shot 2015-08-26 at 15 13 26" src="https://cloud.githubusercontent.com/assets/4669028/9494354/c4fef7f2-4c05-11e5-8570-66a8918a0481.png">

**Comment by ChaelKruip** [comment]
Good catch @jorisberkhout

**Comment by antw** [comment]
> It appears like the strategy first caps the solar PV to the maximum capacity of the transformer and then subtracts the baseload, whereas I expect this to happen the other way around.

I agree. This is strange since conservation of production (solar PV capping in this case) is the last thing to be calculated. This should result in the green line being flush with the lower capacity line; I'll investigate.
