### ISSUE TITLE
Expenses should be subtracted from income

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#323]
It seems that 'out; is now added to 'in':
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9495924/27cf6c88-4c0e-11e5-9369-e9607b1c4ed7.png)

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/57990fa45ec0d21da581555a700e3ad9ae1f6758
