### ISSUE TITLE
Setting the yearly demand of solar PV to `0` is possible and removes the solar load profile from the LES

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#325]
After ETMoses decided to set the yearly demand of my solar PV to `0` (see https://github.com/quintel/etmoses/issues/324), the solar load profile disappeared from my LES. I was expecting that solar PV does not take a yearly demand attribute at all since it already has a capacity.

**Comment by antw** [comment]
> I was expecting that solar PV does not take a yearly demand attribute at all since it already has a capacity.

By this, do you mean that you shouldn't be able to enter a `demand` value at all? This makes sense, but I just want to be clear.

**Comment by jorisberkhout** [comment]
> By this, do you mean that you shouldn't be able to enter a demand value at all? This makes sense, but I just want to be clear.

Yes, that is indeed what I mean. Sorry for not making this clear.

**Comment by ChaelKruip** [comment]
Adding to sprint 1 of GasInfra. If there is time...

**Comment by ChaelKruip** [comment]
@antw can we close this?
