### ISSUE TITLE
kW_max should let the customer pay for the highest load in a month

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#329]
kW_max is the monthly maximum load (could also be negative) for a given end-point. 

The payment tariff that goes with it is just the normal 'fixed' tariff.
The tariff (max-kW-measured-in-month * (EUR/kW))  should be 'transferred' for each month.

At second thought, I am not quite sure how the client envisions this:
* Look at the load of each end-point individually and add for each stakeholder or
* Add all load for end-points of same stakeholder first and measure peak load of total

@dennisschoenmakers what do you think makes most sense?

**Comment by ChaelKruip** [comment]
> Add all load for end-points of same stakeholder first and measure peak load of total

Am I correct in thinking that this is already implemented @antw? I did a short test and it seems to work nicely :smile:

**Comment by antw** [comment]
> Am I correct in thinking that this is already implemented @antw?

Yes indeed.

> Look at the load of each end-point individually and add for each stakeholder or
> Add all load for end-points of same stakeholder first and measure peak load of total

The second of the two suggestions is how it currently works. If the tariff is a fixed amount (EUR/kW), does it matter which of the two we implemented? If there are two stakeholders each with a maximum load of 5kW, and a price of 2 €/kW, the final price will be the same either way:

* **5.0** × 2.0 + **5.0** × 2.0 = €20.0
* **10.0** × 2.0 = €20.0

The only time it matters whether we measure the stakeholder total, or each endpoint, is when using a "stepped" tariff. Stepped tariffs are implemented, but not available in the front-end at this time.

**Comment by ChaelKruip** [comment]
> The second of the two suggestions is how it currently works.

I think that's fine!

> does it matter which of the two we implemented?

In your example it does not matter. I think it can matter in general because the peak load is an *instantaneous* thing. Suppose two end-points have loads as follows:
* HH1: [5, 1]
* HH2: [1, 5]

For method 1 we would find 10 (5 for each end-point). For the stakeholder as a whole, we would find the maximum of the joint load: [6, 6], which is 6 obviously.

> when using a "stepped" tariff.

I think we can do without stepped tariffs for the moment. Perhaps we can make that work at some later point if the client requests it.

**Comment by antw** [comment]
> Suppose two end-points have loads as follows: [...]

Good point!

**Comment by antw** [comment]
Closing as this measure is implemented.

If we want add the ability to charge the tariff per-stakeholder, per-endpoint, and per-connection (and so on), then we shall have to schedule a couple of days to make that a reality.
