### ISSUE TITLE
kW_flex does not seem to work

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#330]
With this Market Model:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9521667/7ca5be34-4cd0-11e5-8129-8a849615edba.png)
and [this LES](http://beta.moses.et-model.com/testing_grounds/230), I get an error when trying to calculate a business case. I have tried to use different strategies. 

I realise that there are no technologies with working flexibility strategies in this LES but there are blue and green curves nevertheless (which are equal). I expect zero flexibility to be measured.

**Comment by antw** [comment]
The flexibility measures aren't properly "hooked up"; I'll see that this gets done.

Out of interest, what is the kW_flex measure specifically? The market model has two flexibility-related measures implemented:

* **FlexibilityRealised**: The *actual* flexibility of each endpoint throughout the year: the difference between the blue and green curves in each time-step.
* **FlexibilityPotential**: The average flexibility throughout the year: the average difference between the blue and green curves.

(See "Flexibility-related measures in #219).

**Comment by ChaelKruip** [comment]
> what is the kW_flex measure specifically?

I think we should have them both indeed and name them:
* kWh_flex_realised
* kWh_flex_potential

We will be measuring the total **kWh** of flex in our LES anyway instead of the instantaneous flex in **kW** so let's make that expicit.

**Comment by antw** [comment]
> We will be measuring the total kWh of flex in our LES anyway instead of the instantaneous flex in kW so let's make that explicit.

Understood! The measures *are* in fact in kWh already, but I'll change the name(s) to reflect that.

**Comment by antw** [comment]
Closing; the two flexibility measures have been added to the front-end, called "flex_realised" and "flex_potential".
