### ISSUE TITLE
COP should be taken into account for heat pumps

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#334]
The 'capacity' attribute of heat-pumps refers to the **output of heat** and is not equal to the **input** capacity of electricity which determines the load on the network.

For heat pumps, the coefficient of performance (COP) determines how a given input capacity is related to the output capacity. The COP can be used as an efficiency in the sense that:

```
ouput_of_heat [kW] = input_of_electricity * COP
```

So, the load of heat pumps should be corrected for this. If the heat pump is making heat at 10.0 kW (the default in ETM), and the COP = 4.0, the load on the network is only 10.0 / 4.0 = 2.5 kW.

**Comment by antw** [comment]
Does the COP come from ETEngine, or is it a user-provided/hard-coded value? I can see, for example, that [this heat-pump](http://beta.et-engine.com/data/latest/converters/households_space_heater_heatpump_air_water_electricity) gets 22.22% of its energy from electricity.

**Comment by ChaelKruip** [comment]
The COP can be taken from ETEngine as `coefficient_of_performance`.
