### ISSUE TITLE
Show LES interface should be restructured

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#337]
As discussed in the meeting with @grdw and @ChaelKruip 

![img_1241](https://cloud.githubusercontent.com/assets/104830/9581907/6fbdfcce-5002-11e5-9214-72aaff5d6396.JPG)

**Comment by grdw** [comment]
![screen shot 2015-09-02 at 2 24 19 pm](https://cloud.githubusercontent.com/assets/2676542/9631019/544a8e76-517e-11e5-90c7-9b71df9c9128.png)

Including @ChaelKruip @antw @dennisschoenmakers 

If the topology and load chart are next to each other; this is the result. 
I want to hear your thoughts.

**Comment by antw** [comment]
We used to have the topology top-down – instead of left-to-right – and abandoned it because it was difficult to show complex networks. *However* left-to-right [still has that problem with very large networks](https://cloud.githubusercontent.com/assets/2676542/9575723/1417fac6-4fd2-11e5-95ce-17ccedaec094.png) and I actually prefer top-down. So I think that's a win.

I also like the chart being next to the topology, as that results in less scrolling.

I would suggest "Pick a strategy" becomes "Choose network features..." or something similar; "strategy" is a bit too technical.

Overall I think this is a big improvement. :+1:

**Comment by dennisschoenmakers** [comment]
I like the charts next to each other, absolutely. :+1: 

It should be even more **clear** which node is selected, I think the current underline is too subtle.

**Comment by grdw** [comment]
![screen shot 2015-09-03 at 10 10 09 am](https://cloud.githubusercontent.com/assets/2676542/9655152/6eb8594e-522f-11e5-9e97-18ce81e44a54.png)

How about some opacity?

**Comment by ChaelKruip** [comment]
> How about some opacity?

I like!

**Comment by grdw** [comment]
Full-preview

![screen shot 2015-09-03 at 3 44 03 pm](https://cloud.githubusercontent.com/assets/2676542/9659806/aee0fecc-5252-11e5-8a00-ea800ee2b12f.png)

**Comment by ChaelKruip** [comment]
Very nice! :+1: :+1:

**Comment by antw** [comment]
> "When clicking a node, load will appear"

* Turn this into a call-for-action with something like "Click on a network component to view its load and attached technologies"; this encourages the user to do something (explore and experiment). "Network component" is likely more meaningful to them than "node", which is a comp-sci term.

  We should try not to use computer science terms when there are more general alternatives. Most people won't know what a "node" or "edge" is, and others like "graph" can be misinterpreted to mean something different ("graph" != "chart").

* "Download curve" should probably be hidden until the user clicks on something.

* I still think "Choose network features..." is preferable to "Pick a strategy". :smiley:

*Very* solid changes though, I like it a lot.

**Comment by dennisschoenmakers** [comment]
Yes, very nice! Maybe this is another ticket, but could we round those
Floats? 2239.99999994 is almost 2240, right? :)

On Thu, Sep 3, 2015 at 4:01 PM, Anthony Williams <notifications@github.com>
wrote:

> "When clicking a node, load will appear"
>
>
>    -
>
>    Turn this into a call-for-action with something like "Click on a
>    network component to view its load and attached technologies"; this
>    encourages the user to do something (explore and experiment). "Network
>    component" is likely more meaningful to them than "node", which is a
>    comp-sci term.
>
>    We should try not to use computer science terms when there are more
>    general alternatives. Most people won't know what a "node" or "edge" is,
>    and others like "graph" can be misinterpreted to mean something different
>    ("graph" != "chart").
>    -
>
>    "Download curve" should probably be hidden until the user clicks on
>    something.
>    -
>
>    I still think "Choose network features..." is preferable to "Pick a
>    strategy". [image: :smiley:]
>
> *Very* solid changes though, I like it a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quintel/etmoses/issues/337#issuecomment-137459625>.
>



-- 

Dennis Schoenmakers, *Partner*


*Quintel Intelligence*Atrium - Strawinskylaan 3051
1077 ZX  Amsterdam
The Netherlands

*Visiting Address:*
Keizersgracht 639
1017 DT Amsterdam

T  : +31 (0)20 301 22 69
F  : +31 (0)20 301 22 02
M : +31 (0)6 109 65 293

E : dennis.schoenmakers@quintel.com
I  : www.quintel.com and www.energytransitionmodel.com

*This message (including any attachments) is confidential and may be
privileged. Any review, retransmission, dissemination or other use of, or
taking any action with reference to this information by persons other than
the intended recipient is strictly prohibited. If you have received it by
mistake please notify the sender by return e-mail and delete this message
from your system. Please note that e-mails are susceptible to change. The
sender will not accept liability for the improper or incomplete
transmission of the information contained in this message.*

**Comment by grdw** [comment]
![screen shot 2015-09-08 at 10 16 36 am](https://cloud.githubusercontent.com/assets/2676542/9729856/b673f220-5612-11e5-9040-0f90c0e54988.png)

> but could we round those Floats? 

That's already fixed :)

**Comment by dennisschoenmakers** [comment]
:+1:

**Comment by ChaelKruip** [comment]
Fixed with https://github.com/quintel/etmoses/issues/352
