### ISSUE TITLE
Sign in form doesn't care what password I enter

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#345]
Steps to reproduce:

* Visit Moses while signed out.
* Enter a valid e-mail address.
* Leave password blank, or enter an incorrect password.

As long as you know the e-mail address of a registered user, you can sign in as them even though the password is incorrect. 

It looks like our custom SessionsController does not call [warden.authenticate! as the "official" Devise controller does](https://github.com/plataformatec/devise/blob/40258bf100c023f785ec0b4b730604da60f31b3f/app/controllers/devise/sessions_controller.rb#L17).

Do we need the custom controllers? I don't think we do anything special with users not already handled by the Devise defaults... I get the impression that they're holdovers from before we added Devise.

**Comment by grdw** [comment]
**slaps forehead**

> Do we need the custom controllers? I don't think we do anything special with users not already handled by the Devise defaults... I get the impression that they're holdovers from before we added Devise.

Yes, they are.

I'll fix this asap

**Comment by grdw** [comment]
@antw this is now solved. There are still some unused devise partials that can be removed before I close this issue.

**Comment by antw** [comment]
Thanks!

> slaps forehead

No harm done; that's what betas are for. :smiley:
