### ISSUE TITLE
Profile view needs some improvements

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#347]
It is unclear what those names mean (the allowed technologies) and 'Default' is not clear either:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9653898/14ff5c70-5227-11e5-9d0d-c51c8822fa57.png)

**Comment by grdw** [comment]
Hmmm because of the duplicate form fields issue not so long ago, it now uploaded 4 profiles for the heat pump you're now looking at. Should I remove the older profiles?

**Comment by ChaelKruip** [comment]
> Should I remove the older profiles?

Yes please. I'll be uploading other versions later today. When using the 'edit' function, I think any new upload should overwrite the current.

**Comment by grdw** [comment]
> Yes please. I'll be uploading other versions later today. When using the 'edit' function, I think any new upload should overwrite the current.

Yes they do .... except if the `curve_type` is `default` which was the case for all the old components.

**Comment by grdw** [comment]
![profile](https://cloud.githubusercontent.com/assets/2676542/9730321/08f6bd4a-5616-11e5-8b00-2fbedc80e978.png)

What is the issue in this case? Is it purely a lack of context or is it the somewhat technical notation with all the underscores?

**Comment by ChaelKruip** [comment]
Context. Needs a title like: "associated technologies" or something. It would be nice if the wording is consistent with the select boxes where the technologies can be selected for the first time.

**Comment by grdw** [comment]
![screen shot 2015-09-08 at 5 01 32 pm](https://cloud.githubusercontent.com/assets/2676542/9738345/4d7cb87c-564b-11e5-9cc6-783b5f8e7f97.png)

Hmm like this? :smiley:

**Comment by ChaelKruip** [comment]
> Hmm like this? :smiley:

Yes!

**Comment by grdw** [comment]
Fixed it: 2b49482
