### ISSUE TITLE
LES Edit page discussion

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#352]
![screen shot 2015-09-08 at 10 19 16 am](https://cloud.githubusercontent.com/assets/2676542/9729911/26fc0e10-5613-11e5-82ae-0101e92a378a.png)

@ChaelKruip had the request to make all the parts of the LES editable through one single page.

My first setup was a collapse structure,, that didn't look nice.
So I switched to tabs instead.

The market model and topologies are cloned or updated depending if the market model or topology is already used in another LES (otherwise a user could destroy a whole bunch of LES's)

Though, now I want to hear some feedback. What do people think of this?

Including: @ChaelKruip @antw @dennisschoenmakers

**Comment by dennisschoenmakers** [comment]
I like it, and I think tabs work well. I was wondering: 
* how do you 'save' it? And how to make sure that saving is not accidentally forgotten? For instance, when you toggle a concurrency, is that change saved? or do I need to press a button, if yes: where is it, and how do you communicate that?
* Could you communicate more clearly that the 'apply' button applies to the toggles above? E.g. bordering the lot of: making it one 'section': also: when nothing changed, the apply button could be grayed-out/disabled?
* Why is there explanation for the 'technology profile', and not for the other sections?
* I would rename 'technology profile' to 'connected technologies for this LES' (or something like it) 
* It is unclear to me what I can do with the 'technology profile CSV' form.

**Comment by dennisschoenmakers** [comment]
One more thing: the LES's name should not be in the tab of technologies, right?

**Comment by ChaelKruip** [comment]
I like the tabs and I fully agree with @dennisschoenmakers's questions/suggestions.

One more thing: the business case is the *output* of the market models but also editable (the free-format corrections). Wouldn't it be more logical to put them on the same page? If we do that, we must make sure that the user is guided to first edit the market model, apply the changes and only then adds corrections to the business case. 

Another way of dealing with the issue that the business case table is both input and output is to remove the free-format line and make corrections a part of the market model. This is perhaps cleaner. The user would then select a `payer` or `payee` (leaving the other blank) and could fill in a `fixed tariff` (without a measure) to correct for un-modelled transfers. 

@dennisschoenmakers @antw @grdw what do you think?

**Comment by grdw** [comment]
> how do you 'save' it? 

You save each individual part instead of the whole thing in one go.

> And how to make sure that saving is not accidentally forgotten? 

That's now the responsibility of the user. Maybe we could have soms sort of "you have unsaved changes, do you really want to leave"-prompt?  

> Could you communicate more clearly that the 'apply' button applies to the toggles above? E.g. bordering the lot of: making it one 'section': also: when nothing changed, the apply button could be grayed-out/disabled?

Apply, applies the concurrency settings. "Toggle-all" toggles all the switches.

> Why is there explanation for the 'technology profile' in situ, and not for the other sections?

Good question. Maybe we could also just hide that bit of information under a tooltip.

> I would rename 'technology profile' to 'connected technologies for this LES' (or something like it)

Yes. I agree. A littles less technical.

> It is unclear to me what I can do with the 'technology profile CSV' form.

I'm even wondering if this is actually used.

> One more thing: the LES's name should not be in the tab of technologies, right?

Yes and no. Due to technical constraints: yes. Due to logic: no.

**Comment by dennisschoenmakers** [comment]
> Yes and no. Due to technical constraints: yes. Due to logic: no.

Could you create an extra tab called 'general'? Maybe (later) we could all kind of generic information there, such as user, scenario_id, private or public, etc.

**Comment by grdw** [comment]
> Could you create an extra tab called 'general'? Maybe (later) we could all kind of generic information there, such as user, scenario_id, private or public, etc.

That sounds like a nice solution :+1:

**Comment by antw** [comment]
> Another way of dealing with the issue that the business case table is both input and output is to remove the free-format line and make corrections a part of the market model. This is perhaps cleaner. The user would then select a payer or payee (leaving the other blank) and could fill in a fixed tariff (without a measure) to correct for un-modelled transfers.

Depends. The same market model could be used for a very large LES and a very small one. Moving the correction into the market model means that the correction has to be the same, regardless of the LES on which it is used. If a user wants a correction to model "installation of cables", then that's going to be LES-dependant.

This might not be an issue since the new behaviour is to clone the market model when the user edits it...

**Comment by ChaelKruip** [comment]
> The same market model could be used for a very large LES and a very small one.

Good point!

> This might not be an issue since the new behaviour is to clone the market model when the user edits it...

Also a good point which seem to balance out the first a bit. Do you have a preferred solution @antw?

**Comment by antw** [comment]
> Do you have a preferred solution @antw?

I'm leaning in favour of us merging corrections into the market model. The downside is that if a user edits the correction in ten separate LES', they end up with ten clones of the market model. Thus, they lose the benefits of using the same MM in each LES (the ability to edit the MM and have the changes reflected immediately in all ten business cases).

There are ways around this that we could implement at a later date: find all descendants and try to apply the changes to them also.

However, so long as MM and topology clones are set to *private* – so they don't clutter up everyone's UI – I think the pros of merging the two outweigh the cons.

**Comment by grdw** [comment]
Still need to fix some feedback.
