### ISSUE TITLE
It should not be possible to view a LES containing a private topology that you don't own

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#364]
See [http://beta.moses.et-model.com/testing_grounds/243](http://beta.moses.et-model.com/testing_grounds/243)

**Comment by grdw** [comment]
@dennisschoenmakers came up with a nice solution. All the testing grounds that use a private topology or market model for that matter, are by default private.

And I would like to add that you cannot change your privacy settings of a testing ground unless both the market model and the topology are public.

**Comment by ChaelKruip** [comment]
:+1:

**Comment by grdw** [comment]
This applies only to future LES's for now. I should also run a migration to make all current LES's this way.

**Comment by grdw** [comment]
Fixed.
