### ISSUE TITLE
When you pan the topology, the current node looses focus and the rest unblurs

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#370]
CLick a node:
![image](https://cloud.githubusercontent.com/assets/104830/9791325/c55726e4-57da-11e5-84e6-72bafd2df798.png)

Now pan it:

![image](https://cloud.githubusercontent.com/assets/104830/9791310/b3ec22b0-57da-11e5-9c2c-e2774c5a7b2d.png)

**Comment by grdw** [comment]
Hmm yes. I know, I didn't do it for the 'panning'. I did it to make sure that the user can 'unfocus'. Though right now I'm not sure if that was such a practical feature.
