### ISSUE TITLE
When you select technologies and then click a(nother) node something weird happens

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#371]
![image](https://cloud.githubusercontent.com/assets/104830/9812020/dfd558f6-587a-11e5-8bf2-2d881e832bcc.png)

@ChaelKruip re-assign at wlll

**Comment by ChaelKruip** [comment]
Re-assigned to @grdw

**Comment by grdw** [comment]
Weird, I know of this problem.

He squeezes only the cached load graphs.

**Comment by grdw** [comment]
Fixed with d0c69ba
