### ISSUE TITLE
'View toplogy' is unnessary with current GUI

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#372]
And sometimes it doesn't even work. (in the case of http://beta.moses.et-model.com/testing_grounds/243, must be because it is 'private'?)
 
@ChaelKruip re-assign at wlll

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by grdw** [comment]
> 'View toplogy' is unnessary with current GUI

@dennisschoenmakers Your suggestion is to completly remove the link? 

The private thing is solved in: e0c48e5

**Comment by ChaelKruip** [comment]
> @dennisschoenmakers Your suggestion is to completly remove the link?

Yes.

**Comment by grdw** [comment]
Fixed by: 7b4c585
