### ISSUE TITLE
When I try to create a new topology I get a 'page not found' after clicking save

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#373]
![image](https://cloud.githubusercontent.com/assets/104830/9812241/36199a00-587c-11e5-9aee-13e00c090949.png)

@ChaelKruip re-assign at will

**Comment by ChaelKruip** [comment]
Re-assigned to @grdw

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/8753afe53c3b1dbb07672e69e6e6825292524875
