### ISSUE TITLE
Why does it not calculate?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#374]
e.g. http://beta.moses.et-model.com/testing_grounds/243

![image](https://cloud.githubusercontent.com/assets/104830/9812743/b0a82dc4-587f-11e5-8cf1-5fb1a4c28ab6.png)

**Comment by dennisschoenmakers** [comment]
Reminds me of the classic: :smile:

![](http://vignette2.wikia.nocookie.net/mysims/images/2/2d/YUNO.png/revision/latest?cb=20111207025749)

**Comment by antw** [comment]
This message almost always indicates a code or data error; it's the result of an exception being raised. In development and test environments you'll see a full backtrace, but in staging and production we opt for a user-friendly message (and the exception goes to Airbrake).

In this case, there's a heat-pump using an old-style profile which hasn't been split into separate `use` and `availability` curves. As of [8ca1ecfa](https://github.com/quintel/etmoses/commit/8ca1ecfa85e6a99ca9b4a8d0923154c0e85ee6d2#diff-74aa55f8c68dec361b1ef0d4ca6d681cR7) that's no longer acceptable.

My understanding is that @ChaelKruip will upload new profiles soon. This error can then be resolved by editing the testing ground and choosing a new profile, and/or we can create a migration to do this automatically for all old LES'.

> Reminds me of the classic:

[The front fell off.](https://www.youtube.com/watch?v=WcU4t6zRAKg)

**Comment by dennisschoenmakers** [comment]
:laughing:

**Comment by dennisschoenmakers** [comment]
Thanks for clearing this up. Matter resolved!

**Comment by ChaelKruip** [comment]
> My understanding is that @ChaelKruip will upload new profiles soon.

I have uploaded new profiles yesterday so this should not occur. Can we trace which one is the offender?

**Comment by antw** [comment]
[hp_space_heating_10kw_100m2_100liter](http://beta.moses.et-model.com/load_profiles/253). I removed the technology assignments from these deprecated profiles so that they won't be selected for any *new* testing grounds, but that does nothing for older testing grounds which use them.

If there are new equivalents of these old profiles, I'll create a migration to update the old scenarios.
