### ISSUE TITLE
EV should get default values when chosen from dropdown

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#375]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9814152/0ad0aa86-588c-11e5-8e05-4b49706bcded.png)

**Comment by grdw** [comment]
![screen shot 2015-09-11 at 4 21 16 pm](https://cloud.githubusercontent.com/assets/2676542/9817082/2cc92c2a-58a1-11e5-90c7-d045628625b8.png)
