### ISSUE TITLE
Documentation ET Moses

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#380]
I couldn't find documentation about ET Moses and the associated instructions in both the ETM interface and ET-Moses self. On git hub I found some instructions and I made them myselve too. Although they need some revision they are suited for users I think. I will mail my work to Dennis and Chael.

**Comment by ChaelKruip** [comment]
> I will mail my work to Dennis and Chael.

That would be really useful @JeroenvdLogt!

**Comment by jorisberkhout** [comment]
Linking to https://github.com/quintel/etmoses/issues/893.

**Comment by jorisberkhout** [comment]
> I will mail my work to Dennis and Chael.

@ChaelKruip , if you can forward me this information, I can pick it up as part of improving the documentation.
