### ISSUE TITLE
ET Moses standalone?

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#381]
In the ETM interface there are instructions to deploy ETM on a standalone laptop or desktop. Will this also be possible for ET Moses? This could be a possible solution for usecase with privacy & security issues.

**Comment by ChaelKruip** [comment]
Assigned @dennisschoenmakers

**Comment by ChaelKruip** [comment]
@JeroenvdLogt, ETMoses can make private LESs. Is that not sufficient for foreseen applications?

> Will this also be possible for ET Moses?

It is possible but still quite technically challenging (you need to be able to run some software that are not installed by default on a pc).

**Comment by JeroenvdLogt** [comment]
I believe this will be challenging Chael but still the only option in some usecases. Privacy & security requirements  and -procedures of Liander (and more parties) can be a really pain in the ass;) Any involvement of American companies for cases with sensitive data is seen as big risk. It must be completely clear where data is stored and transported to. Because of some major issues recently procedures will become more complex. 

In these cases a stand alone version is seen as less riskier and permission will be given more easy. It is worth trying I think.

**Comment by dennisschoenmakers** [comment]
We will add general instructions to the README file on how to run etmoses on your local machine comparable to the instructions found on [etmodel](http://github.com/quintel/etmodel). See #386. Closing this one.
