### ISSUE TITLE
Topology syntax

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#382]
For users it is not clear which syntax to use for topologies. I tried to create a simple topology with nodes for customers, cooperation and system operator. Altough load flow calculation are performed without problems it is not possible to create a business case. 

I did this experiment with topology (cooperatie testen) within the LES (cooperatie testen). After I clicked on the create busniess case button ET Moses crashes and it is not possible any more to edit the LES.

**Comment by JeroenvdLogt** [comment]
Would this be good syntax?
- name: gemeenschapsgebouw
  stakeholder: cooperation
  capacity: 345
  cost: 200000

**Comment by ChaelKruip** [comment]
> Would this be good syntax?

It is hard to answer that without the context of the whole topology. @JeroenvdLogt can you include more of the topology in a ['gist'](https://gist.github.com/) perhaps?

The 'cost' keyword is currently not recognised by ETMoses. There is support of `investment_cost`, however.

Syntax for topology YAML is given [here](https://github.com/quintel/documentation/blob/master/general/topology_syntax.md)

**Comment by JeroenvdLogt** [comment]
Thank you for this information. I will try again.

**Comment by JeroenvdLogt** [comment]
It have it working now for a market model with only customer, cooperation and supplier. Other features seem not to work in market table.

**Comment by ChaelKruip** [comment]
> Other features seem not to work in market table

Can you make specific tickets for those please @JeroenvdLogt ?

> Like in simple test cooperation.

Can you include links to your LES please?

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can we close this issue?

**Comment by ChaelKruip** [comment]
Closing. Please re-open if necessary.
