### ISSUE TITLE
Downloading and uploading curves

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#383]
It is possible to download curves (load on nodes and profiles). But this the value seems to be very strange and not corresponding to the load curve of nodes. 15 min values of more than 10^20 for just around 100 households.

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by JeroenvdLogt** [comment]
When I try to upload a direct downloaded csv file from ET Moses back to ET Moses it doesn't work. And this is Always the case for own made csv files.

**Comment by antw** [comment]
> But this the value seems to be very strange and not corresponding to the load curve of nodes. 15 min values of more than 10^20 for just around 100 households.

Can you paste a link to the LES where you see this behaviour? The CSV file describing the load of an LES node *should* be exactly the same as the load chart.

**Comment by JeroenvdLogt** [comment]
http://beta.moses.et-model.com/testing_grounds/251
It seems to correspend but only a factor 10^12 to big. 
20 kW vs 20197545587165600

**Comment by ChaelKruip** [comment]
> It seems to correspend but only a factor 10^12 to big.

Could it be that you use comma's as decimal separators? ETMoses uses periods. Perhaps the 197545587165600 are just the decimals after the 20 :smile:

**Comment by grdw** [comment]
![screen shot 2015-09-16 at 11 34 39 am](https://cloud.githubusercontent.com/assets/2676542/9901295/f03d2a8a-5c66-11e5-846d-ee64eec2dc7e.png)

We downloaded the load csv file from end point `portiek1a1`. Values seem to be correct using period as decimal separator. @JeroenvdLogt you can change the setting for decimal separator for [Excel in Windows](http://superuser.com/a/606274).

**Comment by JeroenvdLogt** [comment]
I changed the seperator accordingly to the instruction but it is still nog functioning.
![changed seperator1](https://cloud.githubusercontent.com/assets/7781037/9903040/34ca9f50-5c73-11e5-90da-d313d5243dbc.JPG)
![changed seperator2](https://cloud.githubusercontent.com/assets/7781037/9903039/34c9cb98-5c73-11e5-9d87-a96e4f3d7174.JPG)

**Comment by JeroenvdLogt** [comment]
For downloading it is functioning. For uploading I will make a new ticket.
