### ISSUE TITLE
Building a technology tabel in LES from scratch

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#384]
It is not possible to start a LES with a blank technology table. This is inconvenient with big complex topologies and LES'en. This because all relevant technologies are assigned to all end-nodes. Uncheck boxes is quit a lot of work for big tables.

**Comment by JeroenvdLogt** [comment]
Related to this issue: After a user deleted all techniques it is not possible to add new ones.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt you can refer to other issues by using links like this: https://github.com/quintel/etmoses/issues/348

**Comment by grdw** [comment]
Closed due to new interface
