### ISSUE TITLE
Some LES's take incredibly long to load causing a 504. 

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#385]
![screen shot 2015-09-14 at 3 54 58 pm](https://cloud.githubusercontent.com/assets/2676542/9851453/020db898-5af9-11e5-9f2e-9d12ccdcb788.png)

**Comment by antw** [comment]
The default Nginx `proxy_pass` timeout is 60s, which would explain the 504. We could increase that setting, but maybe the better solution is to move the calculation into a background worker once #377 is merged.

**Comment by grdw** [comment]
I do have a question about this though. Where would I store the load calculation when the background processor is finished with it's calculation? With a business case we just use the financials table. With this calculation I'm not to sure we should use the database for this.
`Rails.cache`?

What are your thought, @antw ?

**Comment by grdw** [comment]
This is currently in a branch with the same issue number. Waiting for pull request #377 before making a merge request.

**Comment by antw** [comment]
> Where would we store the load calculation **when the background processor is finished** with it's calculation? With this calculation I'm not to sure we should use the database.

For this reason alone, I'd suggest not proceeding too far with this, for now (5MB for a *small* LES). I think there is a good chance that there is simply too much data to put into a "dumb" cache and hope for the best. As we will also have to start storing individual technology loads and storage amounts, the requirements may increase by 10-100 times.

Caching is something we need to think about properly; we'll have to test and benchmark the off-the-shelf options like Memcache, Redis, etc, but may well end up with a home-made serialize-to-disk solution ([ETEngine does this](https://github.com/quintel/etengine/blob/master/app/models/etsource/atlas_loader.rb#L90-L111), though it's requirements are considerably simpler than Moses' are).

Sticking it in Rails.cache won't work: "staging" *currently* uses an in-process cache limited to 64MB. The calculated LES will end up in the delayed_job process cache, not the Rails one.

**Comment by grdw** [comment]
> Sticking it in Rails.cache won't work

Okay. Thanks for clarifying.

>Caching is something we need to think about properly; we'll have to test and benchmark the off-the-shelf options like Memcache, Redis, etc, but may well end up with a home-made serialize-to-disk solution

Yes.

**Comment by grdw** [comment]
@antw I'm just thinking out loud here and this may sound a little far off.

But couldn't we - instead of requesting the whole load calculation at once - request it in 'parts'. 
The first thing you request would be the [downsampled curve](https://github.com/quintel/etmoses/blob/master/app/assets/javascripts/testing_grounds.js.coffee#L174-L184)(the graph with a really low resolution). When you select a different week or month we would use `ajax` to request the calculation for all the points for that week and redraw the graph.

This would imply making the load calculation everytime they change the resolution of the graph. Which could result in a bad user experience due to waiting.

**Comment by ChaelKruip** [comment]
what is the status here @grdw
