### ISSUE TITLE
Some techniques seem not to work as it should be

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#387]
heat pumps: in general
batteries: surplus PV strategy is not capped by limitations of MSR's
P2H: althoug big volume and power doesn't seem to have much impact on load

**Comment by ChaelKruip** [comment]
I have trouble understanding what you mean by the above @JeroenvdLogt. Can you please be more specific? Also, could you try to make your tickets more 'atomic' and 'actionable'?

> Some techniques seem not to work as it should be

What are you trying to do here? Using strategies or viewing load? What are your expectations and how are the results not in line with those?

> heat pumps: in general

Are you referring to buffering strategies?

> batteries: surplus PV strategy is not capped by limitations of MSR's

Do you observe behaviour as described in #320 and #355 when using the 'PV capping strategy'?

> P2H: althoug big volume and power doesn't seem to have much impact on load

Please clarify what yo mean by this.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt If you find issues with the behaviour of a technology please make atomic, actionable issues for them. Closing this one.
