### ISSUE TITLE
Relative contribution to loadflow per node

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#388]
It is possible to see which nodes are owned by whom. But it is not possible to see the relative contributtion of cooperation to individual nodes.

**Comment by ChaelKruip** [comment]
That is correct. We already have [an issue](https://github.com/quintel/etmoses/issues/74) about this. There have to be some major changes to the way information is sent to the browser and the server in order to make this happen. Closing as this is a duplicate issue.

**Comment by JeroenvdLogt** [comment]
Okay, thanks for your reaction
