### ISSUE TITLE
test heatpump 16-9-2015: no load curves are generated

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#397]
![no load curve](https://cloud.githubusercontent.com/assets/7781037/9897964/7257ddda-5c4e-11e5-9cff-049b8c4776ed.JPG)
Is this because of maintenance of ET Moses?

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/0e802ddc10b21984817d4064200badaae5910c83
