### ISSUE TITLE
CSV upload is not working

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#405]
I have to go to a meeting now. I will give more comments after that.
![changed seperator1](https://cloud.githubusercontent.com/assets/7781037/9903159/42916b54-5c74-11e5-87e7-78d8ceb1dc2b.JPG)
![changed seperator2](https://cloud.githubusercontent.com/assets/7781037/9903160/42916f6e-5c74-11e5-99b3-ebfda1d742ae.JPG)

**Comment by grdw** [comment]
The only way I seem fit to reproduce the above error is to remove a Financial profile, correct? 

> I have to go to a meeting now. I will give more comments after that.

But I'll wait for your comments :+1:

**Comment by JeroenvdLogt** [comment]
Can I call you? Because can't figure out why it is not working.

**Comment by antw** [comment]
@grdw [Could this be it?](https://quintel.airbrake.io/projects/111227/groups/1480388160539571427/notices/1510806649691420960)

PriceCurvesController#create doesn't assert that the price curve passed validation and was created successfully. If the curve wasn't created, it's ID would be `nil` and route generation will fail.

**Comment by grdw** [comment]
@antw my guess is the same as yours.

Will change this and fiddle around with it to see if I can reproduce this error.

**Comment by antw** [comment]
@JeroenvdLogt This is a wild shot in the dark (I'm not too familiar with Excel), but your digit separator ("Cijfergroepering") should probably be blank. Commas are used to separate multiple values; if the numbers in your CSV file contain them, your price curve will not be interpreted correctly.

Price and load curves should contain a single value per line. For example:

```
1288.08
1344.92
1987.32
...
```

You may optionally use scientific notation:

```
0.00000000E+00
7.28845974E-08
7.28845974E-08
...
```

**Comment by grdw** [comment]
@antw  Made the `respond_with` change (a bit more manual due to the fact that Rails automagically named a single `price_curve` a `price_curf`). 

@JeroenvdLogt To put the above in more human-readable language.

I made the fix. However when you're uploading your csv I'm guessing that the csv get's rejected because of unknown reasons. If you could try it again and make a print screen of the error message you receive?

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can you put the offending CSV in a [gist](https://gist.github.com/) so we can have a look at it as well? That way we can try to upload your file and see if the problem is browser-, OS-, CSV-related or otherwise.

**Comment by JeroenvdLogt** [comment]
I had troubles making a gist with IE. BUt with google chrome it worked. 
https://gist.github.com/cb019826c2f48434ddc4.git

**Comment by JeroenvdLogt** [comment]
Chael also received the file by e-mail

**Comment by JeroenvdLogt** [comment]
https://gist.github.com/cb019826c2f48434ddc4.git

**Comment by ChaelKruip** [comment]
@JeroenvdLogt somehow your links do not work.

Hope [this one](https://gist.github.com/ChaelKruip/80be19dc32f71a5ce30d) works better.

**Comment by ChaelKruip** [comment]
I've tried uploading this profile but it does not seem to work for me either: "We're sorry, but something went wrong."

**Comment by antw** [comment]
Man, this was a weird one. :laughing: 

The CSV file is fine. In *some* circumstances Rails' "inflector" was singularizing "curves" as "curf" (as @grdw mentioned in another issue). It should be fixed now.

**Comment by JeroenvdLogt** [comment]
Great :+1: it works properly

**Comment by JeroenvdLogt** [comment]
To bad:( The try yesterday morning was on my personal PC with windows 10 and openoffice. Today I tried with my business laptop and microsoft excel and then ET Moses gives an error. I will mail the csv to CHael.
Curve content type is invalid
Curve is invalid

**Comment by JeroenvdLogt** [comment]
Now it works also with MS excel. Thanks for not giving up
![nevergiveup](https://cloud.githubusercontent.com/assets/7781037/9955311/2e2960fe-5df0-11e5-9078-d27f7956c63c.png)

**Comment by dennisschoenmakers** [comment]
:+1: Excellent!
