### ISSUE TITLE
Landing page need a make-over

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#406]
* Currently, a LES consists of (roughly speaking) four components:
  * Scaled ETM scenario
  * Technologies (from ETM)
  * Topology
  * Market model

* The "Import from the ETM" functionality is not user friendly at all, so instead the user should be guided to the ETM and explained some steps that will lead to a LES.

![etmoses](https://cloud.githubusercontent.com/assets/1303760/9904561/05b1a824-5c7f-11e5-9d53-501253443c76.png)

**Comment by grdw** [comment]
A link to http://beta.pro.et-model.com/scaled like this?

**Comment by grdw** [comment]
![screen shot 2015-09-17 at 12 30 26 pm](https://cloud.githubusercontent.com/assets/2676542/9930986/e7dfeda6-5d37-11e5-9cb5-e15607aa432d.png)

Maybe like this?

**Comment by grdw** [comment]
![screen shot 2015-09-17 at 12 30 26 pm](https://cloud.githubusercontent.com/assets/2676542/9932130/b66b0f44-5d41-11e5-978d-7764aabdb53c.png)

**Comment by grdw** [comment]
![screen shot 2015-09-17 at 1 40 38 pm](https://cloud.githubusercontent.com/assets/2676542/9932139/c630f38a-5d41-11e5-812e-5ba858bd279e.png)

**Comment by ChaelKruip** [comment]
I think it is quite an improvement. One detail: It is also possible to 'Start an existing scenario' and make a LES. Perhaps those two options should be highlighted?

@antw @dennisschoenmakers @jorisberkhout I am also interested in your opinions.

**Comment by grdw** [comment]
> One detail: It is also possible to 'Start an existing scenario' and make a LES. Perhaps those two options should be highlighted?

Yes. I think they should.

**Comment by antw** [comment]
Definitely an improvement. If I were to be *very* picky:

* There's a 1px border down the left side of the "step 1" image which is bothering me.
* It would be nice if the highlights around "Scale this scenario" and "Save and open..." were aligned with the sides of the drop-down menu, the the grey lines above and beneath each link.

**Comment by dennisschoenmakers** [comment]
Excellent step forward! 

I am not sure that people will understand that you have to click 'settings' first to arrive at the picture under 2. Any thoughts on this?

**Comment by grdw** [comment]
After @antw points:
![screen shot 2015-09-17 at 2 01 59 pm](https://cloud.githubusercontent.com/assets/2676542/9932509/c115fa1e-5d44-11e5-8752-a48b1dbd12c4.png)

**Comment by dennisschoenmakers** [comment]
Better! Change the header of step 1 to : "Start a new **or existing** scenario".

**Comment by dennisschoenmakers** [comment]
And since you have more than enough space I would use "Go to the Energy Transition Model".

**Comment by grdw** [comment]
> I am not sure that people will understand that you have to click 'settings' first to arrive at the picture under 2. Any thoughts on this?

My initial thought was that including the 'Settings' header would clarify things for a user (first it was excluded and that didn't made any sense). Obviously a complete ETModel rookie would still need a little more help. But I'm guessing there's some 'help/wiki' thing at ETModel for the people who are completly new.

**Comment by grdw** [comment]
Including @dennisschoenmakers text-edits.

![screen shot 2015-09-17 at 2 07 02 pm](https://cloud.githubusercontent.com/assets/2676542/9932583/679e74a6-5d45-11e5-8dc1-e021dd77013f.png)

**Comment by dennisschoenmakers** [comment]
> My initial thought was that including the 'Settings' header would clarify things for a user (first it was excluded and that didn't made any sense). Obviously a complete ETModel rookie would still need a little more help. But I'm guessing there's some 'help/wiki' thing at ETModel for the people who are completly new.

I agree with that. No rookies here (yet). Let's leave this for now.

**Comment by grdw** [comment]
I'm merging this one.

**Comment by antw** [comment]
> Including @dennisschoenmakers text-edits.

Pixel-perfect! :+1:
