### ISSUE TITLE
Groups of households larger than 30 should not get individual profiles assigned to them

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#408]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9904916/d7eb49d8-5c81-11e5-9523-8b83e1265503.png)

**Comment by ChaelKruip** [comment]
Maybe this is a visualisation issue only! The table looks like this:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9904962/168833fe-5c82-11e5-82e8-11ad28a7112a.png)

**Comment by grdw** [comment]
This was probably related to the load profile options bug during the demo? I can't reproduce this anymore. 

I'll close this for now.
