### ISSUE TITLE
'Financial profiles' header appears twice in profile overview

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#412]
When I hit `Profiles -> Show all` the bottom of the list looks like this. I think the first instance of `Financial profiles` should not be there. What about you, @ChaelKruip, @grdw ?

<img width="605" alt="screen shot 2015-09-16 at 16 01 12" src="https://cloud.githubusercontent.com/assets/4669028/9906821/6c53db8a-5c8c-11e5-98c2-8da8c51332c6.png">

**Comment by ChaelKruip** [comment]
> What about you, @ChaelKruip

Indeed, they should occur only once (the second one).

**Comment by grdw** [comment]
This is because `Financial profiles` is a category in the load profiles category table. This can be removed I guess.

**Comment by grdw** [comment]
I removed that category from the list. No load profiles were used with that category.
