### ISSUE TITLE
Units for financial profiles should not be 'kW'

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#413]
I'm guessing these should be Euro's. Is that correct, @ChaelKruip ?

<img width="1176" alt="screen shot 2015-09-16 at 16 13 08" src="https://cloud.githubusercontent.com/assets/4669028/9907183/1eeec146-5c8e-11e5-9a06-4007cba5f7fe.png">

**Comment by ChaelKruip** [comment]
> I'm guessing these should be Euro's. Is that correct, @ChaelKruip ?

Yes.

**Comment by grdw** [comment]
Fixed with 754137b
