### ISSUE TITLE
Show me what you got, before I sign in

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#414]
If you go to Etmoses now, you need to log in first, but why not show the world what we got?

Of course, then, if you want to edit, delete, create or upvote a LES, then you'll need to log in.

![image](https://cloud.githubusercontent.com/assets/104830/9926455/e22067aa-5d15-11e5-840f-bdcfda8a219e.png)

cc @grdw @antw

**Comment by grdw** [comment]
To make things clear:

The `show` (for public testing grounds/topologies/market models) and `index` pages should be viewable by anybody?

**Comment by dennisschoenmakers** [comment]
> The show (for public testing grounds/topologies/market models) and index pages should be viewable by anybody?

Yes, to start with. In addition: **edit** should not be available, and **create** should take you to the sign in page. :smile:

**Comment by ChaelKruip** [comment]
:+1: 

Assigned @grdw

**Comment by grdw** [comment]
I made the following things open to public:

- Testing grounds (only public) -> Index, show
- Business cases (only public - depends on LES) -> Summary, Data
- Market models (only public) -> Index, show
- Load profiles (only public) -> Index, show
- Load profile components (only public - depends on load profile) -> Data
- Price curves / Financial profiles (only public) -> Show

However, I first want to show this to @ChaelKruip or somebody else to check whether I'm not opening up any private data to anybody.

**Comment by dennisschoenmakers** [comment]
> However, I first want to show this to @ChaelKruip or somebody else [...]

Check!

**Comment by grdw** [comment]
> Check!

I'm writing specs :+1:  still there's some feeling in my gut that somebody made a testing_ground/load_profile/market_model public while it should have been private or some weird combination of a public topology / private market model. I'm going to test those weird combinations of privacy settings though.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt could you have a look at possible oversights after the https://github.com/quintel/etmoses/pull/501 has been merged? It is important that we test that private data is not published by accident.
