### ISSUE TITLE
It should not be possible to remove a topology once it's in use.

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#418]
The same accounts for market models.

Right now you can destroy a LES and cause errors by removing a topology which might be in use by another LES.

What we could do to fix this, is to:

- Let the LES gently break instead of raising an error. 
- Clone the deleted topology - if it's public - and assign it to Chael for instance?
- Forbid any user to remove any topologies - and only allow admin users to destroy a topology, except if the topology is not in use.

Including @ChaelKruip

**Comment by ChaelKruip** [comment]
> Clone the deleted topology - if it's public - and assign it to Chael for instance?

I prefer this one but perhaps instead of assigning them to me we could make a user called 'ETMoses' that owns such orphaned topologies.
