### ISSUE TITLE
ETMoses should get its own production environment

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#419]
similar to ETM. Also see https://github.com/quintel/etcentral/issues/124

Including @grdw @dennisschoenmakers

**Comment by antw** [comment]
The Merit price curve, and the soon-to-be-added heat pump COP and investment cost measures, both depend on changes to ETEngine. I think, therefore, a production ETMoses will have to wait until after the production deploy of ETEngine scheduled for next week. Can this wait until then?

**Comment by dennisschoenmakers** [comment]
> Can this wait until then?

Yes, a week is fine IMO, we'll have to take this into account for the deploy planning @ChaelKruip

**Comment by ChaelKruip** [comment]
> Can this wait until then?

Fine by me!

**Comment by ChaelKruip** [comment]
Closing as this is done.
