### ISSUE TITLE
Unit of use and availability profiles should not be 'kW'

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#420]
As these are fractions of the storage volume of the tank or battery, I believe these should not have a unit at all. What do you think, @ChaelKruip ? 

<img width="1181" alt="screen shot 2015-09-17 at 13 55 24" src="https://cloud.githubusercontent.com/assets/4669028/9932402/e495c6a0-5d43-11e5-90c8-10337f2d82dc.png">

**Comment by ChaelKruip** [comment]
> As these are fractions of the storage volume of the tank or battery, I believe these should not have a unit at all.

True!

**Comment by grdw** [comment]
Fixed with: 754137b
