### ISSUE TITLE
Market model: what about tarriff euro/kw connection for stakeholders not present in LES

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#424]
I was wondering what happens if I choose a network related tarriff for stakeholders not present in the LES. euro/kw connection between supplier and producer for example.
I did this in testingwijk 16-9-2015  and ET Mose came up with a business case....

**Comment by ChaelKruip** [comment]
The 'payer' and 'payee' do not have to be part of the topology but the 'applied to stakeholder' has to be. See also [this comment](https://github.com/quintel/etmoses/issues/236#issuecomment-140006825)
