### ISSUE TITLE
P2H and P2G strategies

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#429]
In this LES I can't see difference between green and blue graphs alltough I installed big P2G and P2H installations (2 different tries) to node "household 3".

http://beta.moses.et-model.com/testing_grounds/277

**Comment by ChaelKruip** [comment]
@JeroenvdLogt did you apply the "Conversion of local PV excess with P2H" and/or "Conversion of local PV excess with P2G" strategies?

**Comment by antw** [comment]
The LES has a deficit, with energy being taken from the grid (visualised in the network as the "HV Network" node) to meet the needs of the households. P2G and P2H will only run at times when there is a surplus (see #121).

**Comment by JeroenvdLogt** [comment]
So the surplus and deficit for purpose of P2G and P2H is determined at the top node?
Is this also the case for batteries?

**Comment by antw** [comment]
Yes, although there are plans to improve this behaviour in the very near future. The proposed changes would allow excesses to be stored locally (in "Households 3") even if there is a deficit in another endpoint (e.g. in "Households 1").

There are still some details to be worked out, but making this improvement is pretty high-priority.

For more information you can see:

* [#310: "Subnet Awareness" needed for load calculation](https://github.com/quintel/etmoses/issues/310)
* [#244: Considerations for 'subnet awareness'](https://github.com/quintel/etmoses/issues/244)

**Comment by JeroenvdLogt** [comment]
Okay thank you. It is kind of logic to say that loading is only possible if there is a surplus on the highest node. In reality the point in the network at which this could best be decided is difficult to say. Main question then is which network (including power quality and voltage controle) is the most robust. Also the place of the battery/P2G/P2H will be important than.
