### ISSUE TITLE
Cost of central production units (coal etc.) of producers in business case?

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#433]
I was wandering wether or not the cost for central produced electricity is included in de business case as cost for producers?

**Comment by ChaelKruip** [comment]
> I was wandering wether or not the cost for central produced electricity is included in de business case as cost for producers?

Interesting point! In principle, the merit order price can be though of as the cost of produced electricity. This 'price' is based on the 'marginal cost' which includes fuel cost, CO2-cost and variable operation and maintenance cost. The subtlety, however, is that the merit order price represents the marginal cost of the most expensive plant that is running to satisfy the demand at a given time. So, it is an upper limit for the marginal cost of the production park as a whole.

Investment cost and fixed O&M cost are not included in the marginal cost. It is possible to include the investment cost in the depreciation cost section of the financial balance. Perhaps we can do this next year?

**Comment by antw** [comment]
If you want to do this, assign the top-most node to the "producer" stakeholder, and set up your market model like so:

<img width="1122" alt="screen shot 2015-09-24 at 20 22 02" src="https://cloud.githubusercontent.com/assets/4383/10084205/176c5f2e-62fa-11e5-9737-db9988a78007.png">

[Here's an example LES](http://beta.moses.et-model.com/testing_grounds/288).

**Comment by JeroenvdLogt** [comment]
I'll try. For now I could also determine in another calculation the investment cost and fixed operational cost of central producers and make a transfer in the market model (customer to producer euros per connection).

**Comment by ChaelKruip** [comment]
> For now I could also determine in another calculation the investment cost and fixed operational cost of central producers and make a transfer in the market model (customer to producer euros per connection).

:+1:
