### ISSUE TITLE
Load chart does not have units on y-axis

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#437]
I believe they are `kW`, right @ChaelKruip ?

<img width="642" alt="screen shot 2015-09-24 at 17 03 29" src="https://cloud.githubusercontent.com/assets/4669028/10076939/55274b06-62de-11e5-9bf4-3582a2fc85ab.png">

**Comment by ChaelKruip** [comment]
> I believe they are kW, right @ChaelKruip ?

Yes indeed.

@grdw we had labels in the load chart right?

**Comment by grdw** [comment]
https://github.com/quintel/etmoses/commit/581180758b3dc0bf7fb0b8ea3f1390a9345cf2db
