### ISSUE TITLE
I am not sure how this can happen

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#438]
![image](https://cloud.githubusercontent.com/assets/104830/10076962/68a09c28-62de-11e5-891c-f432c88f6331.png)

Anybody any thoughts?

**Comment by ChaelKruip** [comment]
> Anybody any thoughts?

That's the ghost of a deleted topology that still haunts the new LESses built on its families burial grounds. :ghost:

**Comment by dennisschoenmakers** [comment]
> That's the ghost of a deleted topology that still haunts the new LESses built on its families burial grounds. :ghost:

Thank God, I feared it was my bad karma haunting me! :grin:

**Comment by grdw** [comment]
Hate to ask but how did you manage to discover this feature?

**Comment by dennisschoenmakers** [comment]
I tried to reproduce it, but now I get a weird compressed load chart.

![image](https://cloud.githubusercontent.com/assets/104830/10095334/4d3f2ea0-6369-11e5-8dac-82a84a728cbd.png)

I clicked impatiently on the topology and the load/technologies tabs when it's still loading.

**Comment by grdw** [comment]
> I clicked impatiently on the topology and the load/technologies tabs when it's still loading.

I can reproduce this one :dancer:

**Comment by dennisschoenmakers** [comment]
Again:

![image](https://cloud.githubusercontent.com/assets/104830/10163181/554abcea-66b1-11e5-8dcd-a32fa3218ac2.png)

Maybe: this happens when I open a Less, and during the 'loading' phase press another LES in the menu

**Comment by grdw** [comment]
> Maybe: this happens when I open a Less, and during the 'loading' phase press another LES in the menu

Yep, that's how to do it! :+1: 

![screen shot 2015-09-29 at 5 24 37 pm](https://cloud.githubusercontent.com/assets/2676542/10168890/fc513d4e-66ce-11e5-9945-43acd6d1ff0c.png)

**Comment by dennisschoenmakers** [comment]
https://www.youtube.com/watch?v=0hiUuL5uTKc

**Comment by grdw** [comment]
I fixed it by disabling the 'Local Energy Solutions' header menu item when a LES is loading. When it's done loading it enables again.

**Comment by grdw** [comment]
Fixed with: 37f8874
