### ISSUE TITLE
P2G strategy does not take into account number of units

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#439]
I made the following LES

<img width="595" alt="screen shot 2015-09-24 at 17 10 06" src="https://cloud.githubusercontent.com/assets/4669028/10077129/4120ae9e-62df-11e5-9227-69614711a070.png">

And expected the 1000(!) P2G units to easily take away any excess PV production. However, it appears like only 135 kW are taken away (in between the red arrows below). Since the capacity of one unit is 135 kW I believe that the number of units is not taken into account.

<img width="642" alt="screen shot 2015-09-24 at 17 03 29" src="https://cloud.githubusercontent.com/assets/4669028/10077143/4cedbf28-62df-11e5-9d4a-eccc5e738fda.png">

**Comment by antw** [comment]
This is odd since the number of units multiplier is a "general" feature used by technologies of all types. P2G is a pretty simple technology and doesn't require any special handling for units.

Still, your conclusion sounds right to me; I'll look into this ASAP.
