### ISSUE TITLE
I cannot create a LES from the ETM

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#441]
I followed the instructions on http://beta.moses.et-model.com/welcome and did the following steps:
1. I hit the `Go to the Energy Transition Model` button
2. I started a new scenario for NL/2050
3. I scaled this scenario to 100 residences using the scaling function in the settings menu
4. I then hit the `Save and open as local energy solution` button
5. This took me to http://beta.moses.et-model.com/testing_grounds with a set of technologies that seem to be correct

From there I couldn't create a local energy solution. Hitting the `Create Local Energy Solution` button didn't do anything and I ended up at the top of the page. I tried logging out and in since my permissions have been changed recently, but to no effect.

Assigning @ChaelKruip , please re-assign at will. Including @grdw and @antw .

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by jorisberkhout** [comment]
Ahhh, I see what I was doing wrong. @ChaelKruip pointed out that I forgot to give the LES a name, but this is not clear to me from the interface. @grdw, could you add a red box around the name field, such that it is obvious that I need to fill out something here before I can proceed.

<img width="755" alt="screen shot 2015-09-25 at 09 33 40" src="https://cloud.githubusercontent.com/assets/4669028/10095249/954d27ac-6368-11e5-916e-865508b0d63c.png">

**Comment by grdw** [comment]
I already managed to get the old error messages back. 

Still painting the erorr box red would be nice though. Maybe with `https://github.com/bootstrap-ruby/rails-bootstrap-forms`?

**Comment by grdw** [comment]
Continue at -> https://github.com/quintel/etmoses/issues/462
