### ISSUE TITLE
Could we move the selection box into the well?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#442]
When I saw the select box 'select stakeholder', I thought it was about the underlying business case overview.

I think if we can shift the select box just a bit upwards and place it in (or perhaps better explained: 'over') the well, this would be more clear to the eye.

![image](https://cloud.githubusercontent.com/assets/104830/10083918/f5ab1914-6300-11e5-9043-cf792b418d6b.png)

**Comment by ChaelKruip** [comment]
> I think if we can shift the select box just a bit upwards and place it in (or perhaps better explained: 'over') the well, this would be more clear to the eye.

:+1

**Comment by grdw** [comment]
![screen shot 2015-09-29 at 2 42 40 pm](https://cloud.githubusercontent.com/assets/2676542/10164174/5e1711be-66b8-11e5-92f7-31d92aabb9da.png)

Something like this?

**Comment by ChaelKruip** [comment]
> Something like this?

:+1:
