### ISSUE TITLE
Market models are not saved by hitting Save all button

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#446]
For http://beta.moses.et-model.com/testing_grounds/292, I updated the market model and hit the 'Save all' button. After the LES was reloaded, I noticed that the market model was not saved and was restored to its default.

**Comment by ChaelKruip** [comment]
@jorisberkhout are they saved with the 'normal' save button?

**Comment by jorisberkhout** [comment]
> @jorisberkhout are they saved with the 'normal' save button?

No. When I hit the save button, it appears to save the market model (i.e. when I switch to a different tab e.g. general and go back to market model, it has saved the changes), however when I return to the LES the market model has been reset to its default.

**Comment by jorisberkhout** [comment]
Mmm, I tried with @grdw and cannot reproduce this error. Will re-open if it occurs again.

**Comment by antw** [comment]
Might be fixed by #444.
