### ISSUE TITLE
When I create a new LES I should not get a warning that the market models are 

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#447]
I think the defaults should be compatible

![image](https://cloud.githubusercontent.com/assets/104830/10096152/977fc5fa-636f-11e5-8687-27e16d31133e.png)

Also: one is names 'default topology' the other 'test'. Can we also call the latter 'default market model'?

**Comment by ChaelKruip** [comment]
Fixed this by introducing a very simple Default market model.
