### ISSUE TITLE
Merit order tariff is not behaving as I expect

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#450]
To test the merit order tariff, I created a very simple LES (#298) with the following properties 

<img width="1144" alt="screen shot 2015-09-25 at 12 20 42" src="https://cloud.githubusercontent.com/assets/4669028/10098224/ec788c44-637f-11e5-8285-a2c9bc9e6c33.png">

And added the following market model

<img width="1146" alt="screen shot 2015-09-25 at 12 20 53" src="https://cloud.githubusercontent.com/assets/4669028/10098231/06716b3e-6380-11e5-9f67-32adffc04af5.png">

The only parameter I varied is the number of households which resulted in the following unexpected behaviour.

The price (or rather costs) that a consumer has to pay for a kWh highly depends on the total load on the network. As long as the Households 1 node is not congested, the consumer pays `EUR 0,00` per kWh, but as soon as the network is congested the consumer start paying a finite amount of money, going all the way up to `EUR 0.36` per kWh (for comparison in the ETM, the average cost of a kWh are `EUR 0.049` for the default scenario). I was expecting the price to be roughly constant with load as there is no local production that can make the price fluctuate.

**Comment by jorisberkhout** [comment]
Including @ChaelKruip .

**Comment by ChaelKruip** [comment]
Closing this.

**Comment by jorisberkhout** [comment]
Thank for fixing this, @antw. I repeated the test as described in the opening comment of this issue and this resulted in the following relation between costs per kWh and number of households. As discussed with @ChaelKruip , this looks very plausible to us.

<img width="640" alt="screen shot 2015-10-05 at 09 45 49" src="https://cloud.githubusercontent.com/assets/4669028/10275224/1811efd0-6b46-11e5-828d-6720eead6fe2.png">

**Comment by ChaelKruip** [comment]
:+1: thanks for testing this so thoroughly @jorisberkhout!

**Comment by antw** [comment]
Thanks indeed, @jorisberkhout; much appreciated!
