### ISSUE TITLE
Does the `number of connections` measure count the number of base-load profiles?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#454]
Or is it based on the 'units' that are specified for an end-point in the topology?

Looking at https://github.com/quintel/etmoses/issues/363 I would think the first right?

**Comment by antw** [comment]
[It counts the number of `base_load`, `base_load_edsn`, and `base_load_buildings` technologies](https://github.com/quintel/etmoses/blob/1c68aeac4db627a178013407450083903ba08d01/app/models/market/measures/number_of_connections.rb).

**Comment by ChaelKruip** [comment]
Thanks!
