### ISSUE TITLE
When opening a new LES, the business case does not show

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#465]
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10102300/ebe6d92a-639d-11e5-8e5a-fcf4880ade0e.png)
Only after I edit the LES, does it show up...

**Comment by grdw** [comment]
See #460

**Comment by grdw** [comment]
http://beta.moses.et-model.com/testing_grounds/304 now does show up.

**Comment by ChaelKruip** [comment]
> http://beta.moses.et-model.com/testing_grounds/304 now does show up.

It does show up after refresh or after 'editing' something. It seems that the initial background job finishes but never updates the front-end.

> I don't know whether or not this is an actual bug or just a result of impatience.

So, maybe I didn't wait long enough?
In that case I would expect the 'loading icon' to keep on showing until something has been calculated...

**Comment by grdw** [comment]
This will be fixed once: #458 is merged
