### ISSUE TITLE
The top-left cell should be shaded as well and say 'depreciation cost' for clarity

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#466]
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10102414/9301fcf8-639e-11e5-8954-b3d0015f41f8.png)

**Comment by grdw** [comment]
![screen shot 2015-09-29 at 10 56 58 am](https://cloud.githubusercontent.com/assets/2676542/10159505/d3b75430-6698-11e5-916c-3b1fdc01bc2d.png)

This is what it becomes.

Though, I like it better if the 'Depreciation cost' isn't bold and the diagonal line 'italic'.

![screen shot 2015-09-29 at 10 57 56 am](https://cloud.githubusercontent.com/assets/2676542/10159524/071665e6-6699-11e5-9b4d-8935a98c1873.png)

What do you think?

**Comment by ChaelKruip** [comment]
> Though, I like it better if the 'Depreciation cost' isn't bold and the diagonal line 'italic'.

I agree! :+1:

**Comment by grdw** [comment]
Cool I'll merge this than :+1:

**Comment by grdw** [comment]
Fixed with: 9fdc786
