### ISSUE TITLE
There seems to be a rounding error in the investment cost calculation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#469]
The topology has 300_000 EUR of assets for the S.O. with a technical lifetime of 30 years. I would expect exactly 10_000 EUR/y depreciation cost but I see 9_998 EUR/y:
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10103493/90d0feba-63a4-11e5-87fb-c602498c6cea.png)

**Comment by ChaelKruip** [comment]
LES: [http://beta.moses.et-model.com/testing_grounds/304](http://beta.moses.et-model.com/testing_grounds/304)

**Comment by antw** [comment]
There was also a test containing an incorrectly rounded value. :frowning: 

There's not much point in writing tests it the expected values are just copy/pasted from the output without being checked...
