### ISSUE TITLE
If there are multiple end-points in a LES, the storage in EV strategy introduces negative spikes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#475]
It is unfortunate that a strategy deployed to reduce network congestion introduces supply peaks that exceed the network capacity:
<img width="642" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/10119119/4033b18e-648d-11e5-9ca4-b38a1022bfb5.png">

@antw could this be the effect of the EVs in one end-point having some extra storage which is then used by EVs in another end-point? 

Would this be solved by 'subnet awareness'?

**Comment by ChaelKruip** [comment]
The LES in question: [http://beta.moses.et-model.com/testing_grounds/310](http://beta.moses.et-model.com/testing_grounds/310)

**Comment by antw** [comment]
> The LES in question: http://beta.moses.et-model.com/testing_grounds/310

The LES seems to have changed, and no longer has any loads on "Households 1".

> @antw could this be the effect of the EVs in one end-point having some extra storage which is then used by EVs in another end-point?
>
> Would this be solved by 'subnet awareness'?

That's a reasonable explanation, and I can imagine that would be the reason you would see this behaviour. Like you, I don't think it's ideal.

Subnet calculation might, in theory, be able to prevent this from happening.

**Comment by ChaelKruip** [comment]
> The LES seems to have changed, and no longer has any loads on "Households 1".

Oops! Sorry I think I dit some editing later :blush: 

> Like you, I don't think it's ideal.

I'm not complaining but I would like to give a demo tomorrow where I understand the behaviour well. Thanks for validating my thoughts @antw!
