### ISSUE TITLE
Green-line loads could be fetched in parallel with blue-line loads

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#477]
When an LES page loads, it fetches the all-strategies-off (blue line) loads. Once received, the JavaScript then asks the server for the green-line loads.

Instead of executing these requests in series, both requests could be sent simultaneously. This would improve the responsiveness of the "show LES" page.

@grdw Do you think this is this doable with the current "show LES" page?

**Comment by ChaelKruip** [comment]
Good catch @antw and I like your suggestion!

**Comment by grdw** [comment]
This is not to big of change. I'll look into it!
