### ISSUE TITLE
little discharging of batteries

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#486]
I try to simulate a street with PV, heatpumps, P2H, and batteries. If I use buffering Heatpumps/P2H strategies in combination with storage of excess PV production there is something strong. It looks like there is charging but no discharging in the summer weeks.

If I remove the P2H strategie the load curve looks normal.
![technology battery](https://cloud.githubusercontent.com/assets/7781037/10137437/d65f46c4-65f9-11e5-942c-a53a417963b9.JPG)
![battery charge-discharge](https://cloud.githubusercontent.com/assets/7781037/10137438/d65f6f0a-65f9-11e5-8f02-40a61595ba01.JPG)
![only battery](https://cloud.githubusercontent.com/assets/7781037/10137453/ef3ac8da-65f9-11e5-8e8f-7b32022f4b3f.JPG)

**Comment by JeroenvdLogt** [comment]
![power to heat](https://cloud.githubusercontent.com/assets/7781037/10137768/85f87708-65fb-11e5-89d9-eddaa62f8dd2.JPG)
Looks like this issue is caused by the P2H. It is a 'sink' for excess PV energy but the demand of P2H at a later time is not lower because of the buffering.

**Comment by ChaelKruip** [comment]
> the demand of P2H at a later time is not lower.

I think that is where the confusion occurs. P2H converts solar energy into heat and that heat is consumed using a domestic hot water profile. There is, however, no 'demand' for P2H because it is a volatile rather than a dispatchable technology. Perhaps we could make this more realistic by either:
* Satisfying the the remaining heat demand by a simple electric boiler
* Subtracting the heat demand satisfied by P2H from the buffer of heat-pumps or other hot water technologies.

**Comment by JeroenvdLogt** [comment]
Okay clear. This would mean that with P2H, customers simply increase their heat consumption so that energy in the electric boiler is released before the next buffering (no counter on "state of charge" of electric boiler). On the network you'll see only the buffering and no release of energy. 

I think that subtracting the heat demand satisfied by P2H from the buffer of heatpumps/hotwater would be most realistic. Is this difficult to simulate?

**Comment by ChaelKruip** [comment]
> I think that subtracting the heat demand satisfied by P2H from the buffer of heatpumps/hotwater would be most realistic. Is this difficult to simulate?

I agree. Not sure yet how complex this is. I'll make a separate ticket for this. Closing.
