### ISSUE TITLE
reset to 100% PV capping

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#487]
When I use the strategy of PV capping and change something in the technology table, ET Moses reset the slider of PV capping to 100%.

**Comment by grdw** [comment]
I also came across this problem yesterday. This will be fixed in pull request #485

**Comment by JeroenvdLogt** [comment]
Thank you
![elvis](https://cloud.githubusercontent.com/assets/7781037/10160650/2e8b5586-669f-11e5-986a-46f054985a00.jpg)

**Comment by ChaelKruip** [comment]
:smile:
