### ISSUE TITLE
saving of aggregated baseload

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#488]
As I remembered well savings of aggregated baseload was 10%. If I apply the strategy it cuts to the maximum capacity of the node. This is quit unrealistic because this type of flex is no demand shift but energy saving.
![saving of aggregated base load](https://cloud.githubusercontent.com/assets/7781037/10140288/0d3b42e4-6607-11e5-9edc-35a68d96f3a9.JPG)

**Comment by ChaelKruip** [comment]
> If I apply the strategy it cuts to the maximum capacity of the node. 

Do yo mean that it seems that the 'savings' exceed the 10%? From your example it seems that is what is happing... @antw could it be that the inflexible part of the aggregated base load is accidentally made flexible?

**Comment by JeroenvdLogt** [comment]
Indeed it seems 10% of aggregated load savings is not set as limits and ET Moses saves as much baseload as necaserry to not overload the network.

**Comment by antw** [comment]
Some of the EDSN curves only have a `default` component, when they should in fact have separate `flex` and `inflex` components. [E3A](http://beta.moses.et-model.com/load_profiles/341) is the only one I found with the separate curves.

@ChaelKruip Do you have a copy of the split-up curves available? I can upload them and remove the `default` component.

**Comment by ChaelKruip** [comment]
> @ChaelKruip Do you have a copy of the split-up curves available? I can upload them and remove the default component.

I have them indeed. Even thought I had uploaded them in the past :open_mouth: I can Slack them to you

**Comment by antw** [comment]
@JeroenvdLogt I have uploaded the corrected load profiles for households. You should find that this is now fixed.
