### ISSUE TITLE
Clear 'show page' needed for a testing ground

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#49]
This page would give the user info on:

* Name of scaled ETM scenario
* Associated topology
* Associated profiles
* G: Profile link when clicking a node
* Dates of creation/revisions

* ~~Original (national) ETM scenario~~
* ~~Preview options?~~

**Comment by dennisschoenmakers** [comment]
I already improved as much as I can in 93ab656.

However, still much is to be gained: first of all, the recorded attributes should be extended to host the (national/local) scenarios, creators, and such. 

Furthermore, @antw and I decided I should not touch the logic of the displayed technologies for now.

**Comment by dennisschoenmakers** [comment]
Assigned to @antw for further improvements.

**Comment by grdw** [comment]
Fixed the parent scenario id issue with 97a3fda

Also added separators between the 'national scenario' and 'scaled scenario' links, as discussed with @ChaelKruip 

Also setted a max-height for the topology; which is now 500px. https://github.com/quintel/etloader/blob/cc3e3861fc2eb2a0b5b49fdf913ed4061e596295/app/assets/javascripts/showTree.js#L34

**Comment by grdw** [comment]
I think this issue can be closed
