### ISSUE TITLE
Heat produced with P2H should be subtracted from demand

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#490]
Right now, P2H converts solar PV excess into heat but that heat is not really used anywhere (see https://github.com/quintel/etmoses/issues/486). It would be more realistic to add the heat from P2H to the buffers of heat pumps (for hot water) on the same connection.

@antw what is your estimation of the complexity of this? I think that it would mean that in effect the P2H and the heat-pump would share the buffer and the heat-pump is 'only' responsible for the demand left after the P2H technology is done.

**Comment by ChaelKruip** [comment]
What is the status of this @antw? Isn't this issue fixed now that P2H is connected to buffers?

**Comment by antw** [comment]
> Isn't this issue fixed now that P2H is connected to buffers?

Yes.
