### ISSUE TITLE
User sign up is broken because of activation email not working/not communicated properly to the user

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#492]
Now it's really confusing. If you sign up, you get redirected to the login page saying 'you need to sign in/ sign up'. If you type in your credentials again you get the cryptic:

![image](https://cloud.githubusercontent.com/assets/104830/10164761/abedc4f2-66bb-11e5-9b5f-e735ab083903.png)

* get rid of the activation requirement
* sign in when you sing up immediately.

cc @ChaelKruip

**Comment by ChaelKruip** [comment]
:+1:

**Comment by grdw** [comment]
> get rid of the activation requirement 

Ok.

**Comment by grdw** [comment]
> sign in when you sing up immediately

Which song should they sing? :smile:

**Comment by dennisschoenmakers** [comment]
Knocking on heavens door?
