### ISSUE TITLE
ETMoses landing page should advertise our workshops

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#495]
John pointed out that because ETMoses is a real experts-tool it would be good to if he user would find his way to a workshop about how to use ETMoses rather than him getting frustrated by reading a lot of complex documentation.

**Comment by grdw** [comment]
In relation to documentation efforts.

**Comment by jorisberkhout** [comment]
Do we still want this, @ChaelKruip ? If so, I will pick it up as part of improving the documentation.

**Comment by ChaelKruip** [comment]
> Do we still want this, @ChaelKruip ? If so, I will pick it up as part of improving the documentation.

👍
