### ISSUE TITLE
When importing a scenario from ET-model and refreshing something strange happens to households

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#496]
When you're importing a scenario from ET-model. The technology table is loaded. When you hit refresh (F5/Cmd+R) - the Households (aggregated) turn into Batteries (in Firefox that's the case). This is logical behaviour due to the fact that a browser remembers the option value from a select box in the browser-cache. In our case, we change this option value (after the dom has loaded) by hand to `base_load_edsn` if the amount of houses are bigger than 30. However when you reload that option is not present in the list so the browser automatically selects the first option from the select box. 

@antw do you have any ideas or suggestions how we might tackle this problem?

**Comment by antw** [comment]
Doesn't happen in Chrome or Safari, which is odd.

**Comment by antw** [comment]
> This is logical behaviour due to the fact that a browser remembers the option value from a select box in the browser-cache.

Oh I see what you mean; Firefox remembers the form settings from before the refresh. The problem isn't there if you force-refresh (Cmd+Shift+R). This is annoying... :anguished:
