### ISSUE TITLE
Merit information should be downloadable

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#499]
Keep it simple, comparable to http://beta.et-engine.com/data/latest/merit

**Comment by ChaelKruip** [comment]
:+1: 

> comparable to http://beta.et-engine.com/data/latest/merit
Indeed, both load curves and price curve are interesting for the user.

**Comment by grdw** [comment]
I was just looking at these two buttons. Therefor closing this issue.
