### ISSUE TITLE
Make it possible to create a LES with no account

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#502]
*This doesn't mean that you don't need an actual account*

`Import -> Perform Import -> New -> Create`

The create action should redirect to the `sign_up` or `sign_in` page and should return back to the `new` page with all the changes in-tact. Than the user should be able to save it. 

The polluting solution would be:

- Creating the testing ground without a user
- Sign up and sign in the user
- Attach the testing ground to the user
- Create a cron job that cleans up LES's without users every night. 

The nice solution is:

- Remembering the import table in cache
- Sign up and sign in the user
- Returning to the import table with a user
- Save it

**Comment by antw** [comment]
I would imagine it is easier to have the `import` or `new` actions redirect to a sign-up/sign-in page. It feels like a bit of a tease to allow someone to choose their technology mix and design their LES, only to hit a wall when hitting submit.

**Comment by grdw** [comment]
> I would imagine it is easier to have the import or new actions redirect to a sign-up/sign-in page

Yes, it would and I agree.
