### ISSUE TITLE
Suggestion: change default behaviour of heat pumps to something more stupid

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#503]
I think that the current default behaviour of heat pumps is too smart and does not do justice to the problems that we need to tackle with strategies. 

Right now, the heat pump behaves according to the availability profile: the pump starts to buffer when the availability profile tells it so. The availability profile takes into account any upcoming events for hot water or space heating. This 'knowledge about the future' is what I think is 'too smart' already and does not faithfully represent the 'stupid default'. **In effect, it is already applying some buffering.**

A better default behaviour IMO would be to just look at the 'use' profile and try to satisfy demand 'in the moment' as if there is no possibility to buffer at all. This has some advantages:

* We don't need an availability profile for heat pumps which simplifies the research and the software
* The contrast between the default and the 'buffering' strategy will be more apparent

@dennisschoenmakers @jorisberkhout @AlexanderWirtz @antw I'm interested in your thoughts on this

**Comment by antw** [comment]
This was the way heat pumps used to behave [before support for availability profiles was added](https://github.com/quintel/etmoses/commit/8ca1ecfa85e6a99ca9b4a8d0923154c0e85ee6d2). :neutral_face:

What would happen if the amount stored in the buffer and the capacity of the heat pump are insufficient to meet demand?

**Comment by ChaelKruip** [comment]
> This was the way heat pumps used to behave before support for availability profiles was added. :neutral_face:

I know :disappointed:. I just recently realised how using an availability profile is some sort of buffering...

> What would happen if the amount stored in the buffer and the capacity of the heat pump are insufficient to meet demand?

I think there are two options:

1. The needed extra heat is produced by an electric device with efficiency 100% or so. This would result in a tripling or quadrupling of the load on the network (the heat pump has effective efficiency of 400% or so). 
2. The needed extra heat is produced by a gas-fired thing with efficiency of about 100% as well. This is basically what the 'hybrid heat pump' is going to be. 

Given the fact that we are going to include the hybrid heat pump anyway it seems more natural to go with option 1. Moreover, option 1 will also aggravate possible congestion issues which makes it more instructive to use buffering strategies or hybrid heat pumps instead.

**Comment by ChaelKruip** [comment]
Assigning to @antw

**Comment by ChaelKruip** [comment]
@antw can this be closed?
