### ISSUE TITLE
Suggestion: encode heat use in kW instead of 'fraction of buffer volume' for heat pumps

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#505]
If we would simplify te behaviour of heat pumps as suggested in https://github.com/quintel/etmoses/issues/503, we would be able to offer more flexibility to the user by allowing him to choose the capacity (and COP) of heat pumps **and** the storage buffer volume independently. 

If the heat and hot water use is described in units of kW by the profiles, we can completely let go of the constraint that profile, capacity and volume of a technology 'belong together'. Personally I think this would be a huge improvement.

@dennisschoenmakers @jorisberkhout @AlexanderWirtz @antw I'm interested in your thoughts on this.

**Comment by dennisschoenmakers** [comment]
:+1: Excellent idea!
