### ISSUE TITLE
Profile chart does not show on Production

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#520]
cc @ChaelKruip. I also experienced the same malfunction yesterday. A refresh helped back then, not today :grin:

**Comment by grdw** [comment]
Do you have an example of this?

**Comment by dennisschoenmakers** [comment]
Closing. Cannot reproduce. Let's keep an eye out for it anyways.

**Comment by ChaelKruip** [comment]
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10423514/694b366e-70c7-11e5-9b83-36de82282f6b.png)

**Comment by grdw** [comment]
Awesome. Thanks! Already see what it is though.

**Comment by dennisschoenmakers** [comment]
:+1:
