### ISSUE TITLE
Legend acts weirdly

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#522]
If I click on households 3, it seems to alternate between capacity and households 3. (b.t.w. this also happens when you have a green line):

![legend](https://cloud.githubusercontent.com/assets/104830/10429300/ce051630-70f7-11e5-8d6a-7048d16771d7.gif)

cc @grdw

**Comment by ChaelKruip** [comment]
Assigning to @grdw

**Comment by ChaelKruip** [comment]
This is part of a more general class of weird behaviour that is observed in the load chart: 
* if you select/deselect a curve several times, the scaling can differ erratically
* Persistence is not always in working (sometimes the chart forgets your settings)
