### ISSUE TITLE
number of households is not correctly with units in topology

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#525]
I made topology with 94 MSR's, 1168 households with maximum 3 kW load. But in the loadcurve on the MSR node it results in just 3 kW load. 
I used topology standard (editied for Goor) in LES First trial oefencase Goor at the live server (not beta).

**Comment by ChaelKruip** [comment]
[This is the corresponding LES](http://moses.et-model.com/testing_grounds/336)

**Comment by JeroenvdLogt** [comment]
Yes it is

**Comment by antw** [comment]
I might be being thick, but I'm not sure what I'm supposed to be noticing in the above LES. :laughing: 

I do see that all the *technologies* have `units=1` (hence the low network load), but that appears to have been set manually; [a fresh import of the ETEngine scenario](http://moses.et-model.com/testing_grounds/import?scenario_id=264915) has the expected number of units for each technology.

**Comment by JeroenvdLogt** [comment]
I loaded a fresh scenario from ETM but still have the same problem. Units of MSR1 and MSR2 are 94 and number of households is 1168. But load at HV network 1 is just 84 kW.
![image](https://cloud.githubusercontent.com/assets/7781037/10456564/4f86e6fa-71c2-11e5-9006-56f7b9710f9c.png)

---
name: UHV Network
stakeholder: producer
children:
- name: HV network 1
  units: 1
  stakeholder: system operator
  capacity: 208000
  investmentcost: 1500000
  economic_lifetime: 50
  children:
  - name: MS klanten 1
    units: 213
    capacity: 1000
    stakeholder: customer
  - name: MSR 1
    units: 94
    stakeholder: system operator
    capacity: 417
    investmentcost: 7000
    economic_lifetime: 40
    children:
    - name: huishoudens 1
      units: 1168
      stakeholder: customer
      capacity: 18
    - name: bedrijven 1
      units: 57
      stakeholder: customer
      capacity: 50
- name: HV network 2
  units: 1
  stakeholder: system operator
  capacity: 95000
  investmentcost: 750000
  economic_lifetime: 50
  children:
  - name: MS klanten 2
    units: 57
    capacity: 1000
    stakeholder: customer
  - name: MSR 2
    units: 94
    stakeholder: system operator
    capacity: 417
    investmentcost: 7000
    economic_lifetime: 40
    children:
    - name: huishoudens 2
      units: 1168
      stakeholder: cooperation
      capacity: 18
    - name: bedrijven 2
      units: 57
      stakeholder: cooperation
      capacity: 50

**Comment by ChaelKruip** [comment]
> and number of households is 1168

Also, when I look in [your LES](http://moses.et-model.com/testing_grounds/338) I only see base_load profiles with units = 1 in the technology matrix:
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10456955/2fdd6a5c-71c4-11e5-995e-00ee6c478860.png)
That is the number which determines the number of units and thus the multiplication factor of the load profile.

The `units` in the topology simply multiply the capacity (and other properties) of the network components but **not** the number of houses or technolologies attached to the network.

@JeroenvdLogt could that be the root of your problem?

**Comment by JeroenvdLogt** [comment]
I think so. I always thought the households and technnologies were multiplied by both units in technology table and topology. So if I simulate the usecase of Hof van Twente f.e. I need to enter all the households (f.e. 3000) of HvT in the technology table and number of MSR's (94 f.e.) ? The aggregated baseload of households would then be 3000*1.1 kW? The total capacity of MSR's would then be 94*417kW?

**Comment by ChaelKruip** [comment]
> The aggregated baseload of households would then be 30001.1 kW? The total capacity of MSR's would then be 94417kW?

Exactly! This behaviour is the clearest in my opinion: all information about technologies and base-loads is in the technology matrix and all info about the topology is in the topology file. 

Closing. Please re-open if this does not solve your issue.
