### ISSUE TITLE
business case is not calculated and cannot be modified within LES

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#526]
In the LES: "oefening vrijdag 13-10-2015 opslag netbeheerder" ET Moses doesn't calculate the business case. I am not able to modify the market model within the LES. When I choose the merit-order or price-curve the screen blinks and after that tarrif fields are blank. 

This happens on the live-server (not beta).

**Comment by JeroenvdLogt** [comment]
I can calculate I BC now but the Totals seems not to be okay. 
5bln incoming - 8 bln outgoing is not equal to -8 bln.
![wrong total](https://cloud.githubusercontent.com/assets/7781037/10964047/d9a43cfe-83a4-11e5-8c94-0f1bb9e002aa.JPG)

**Comment by antw** [comment]
> 5bln incoming - 8 bln outgoing is not equal to -8 bln.

Where do you see this in ETMoses? The screenshot doesn't have any rows with 5bln incoming.

**Comment by JeroenvdLogt** [comment]
Ah wait, I see what's going on. I was referring to the balance of system operator. But the incoming for system operator is 5 mln instead of 8 bln. Maybe aligning of numbers can prevent misunderstandings.

**Comment by ChaelKruip** [comment]
Re-open if this issue is not solved.
