### ISSUE TITLE
End points are not 'equally treated' with local solar storage?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#529]
I started with the 100% co2 reduction 2030 preset, scaled down to 600 residences and choose all the defaults. I ended up with [**LES 340**](http://moses.et-model.com/testing_grounds/340). I selected the first strategy, and I found that all three end points have very different loads:

![image](https://cloud.githubusercontent.com/assets/104830/10476764/0c8fed80-7251-11e5-973b-15a7b8e0a8a7.png)

![image](https://cloud.githubusercontent.com/assets/104830/10476769/13d61664-7251-11e5-87e6-b15841c79f5b.png)

![image](https://cloud.githubusercontent.com/assets/104830/10476773/1c623362-7251-11e5-97c5-985ee5946df9.png)

Which is different from what I expect: since it wouldn't matter whether you are part of HH1, HH2 or HH3, right? :smile: 

cc @antw

**Comment by dennisschoenmakers** [comment]
BTW: Technologies are distributed equally over the end points, except some rounding differences.

**Comment by dennisschoenmakers** [comment]
Hopefully this behaviour will be solved with #310. First implementation expected today! I suggest we deploy this to production too.

**Comment by ChaelKruip** [comment]
Assigned to @antw
