### ISSUE TITLE
When creating a LES, could we show a 'preview' of the topology

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#530]
When presenting ETMoses, I notice that people would like to preview the topology before it is chosen. It's also hard to change it later.

Could we improve on this? I have two ideas:

1. Show the collection of three default, or choose by text:

    ![image](https://cloud.githubusercontent.com/assets/104830/10479273/ac84a36e-7263-11e5-9e25-db09c8529510.png)

2. Or preview the topology from the select box:

    ![image](https://cloud.githubusercontent.com/assets/104830/10479385/68fc0974-7264-11e5-833e-d8d763d73e4d.png)

More ideas? What do you think @ChaelKruip @antw @grdw ?

**Comment by grdw** [comment]
Maybe a dropdown with images:

![dropdown-with-images](https://cloud.githubusercontent.com/assets/2676542/10479993/eb1d839e-7267-11e5-9d9d-83df6a583906.png)

**Comment by dennisschoenmakers** [comment]
> Maybe a dropdown with images:

Good idea! Would the images be large enough to be understood though?

**Comment by grdw** [comment]
> Good idea! Would the images be large enough to be understood though?

It's only to get a basic idea of the 'shape' of the topology. Which for Lochem topologies might become a bit of a problem when it comes to size.

I personally like the "preview idea" a bit better than my own when I think a bit harder about the usability problem. Would also make the topology preview - not just a preview - but a bit more interactive. For instance: seeing which stakeholders are attached and maybe some advanced properties when you hover/click the node.

**Comment by antw** [comment]
Nice idea. :+1:

> Would also make the topology preview [...] seeing which stakeholders are attached and maybe some advanced properties when you hover/click the node.

Funnily enough, my first thought was in the opposite direction: strip out as much information from the topology preview as possible: reduce the nodes to a 3-4px wide, hide the labels, and bring the nodes closer together (kind of like in [the drop-down version](https://github.com/quintel/etmoses/issues/530#issuecomment-147990821)). That way we'd fit the diagram into a smaller space, and might stand a better chance of displaying the very large networks.

It's pretty easy to change attributes of the topology later (capacity, stakeholder, costs, etc); I don't think it's important that those are visible in the preview. Those could be shown in-detail on `TopologiesController#show`.

**Comment by JeroenvdLogt** [comment]
Good to see you're thinking about this! I would prefer the second option of Dennis. I am mostly interested in the shape of the availabe topologies (in bit more detail than the dropdownmenu option) when creating a LES and not in just the defaults.

**Comment by ChaelKruip** [comment]
:+1: Very nice idea indeed. 

> That way we'd fit the diagram into a smaller space, and might stand a better chance of displaying the very large networks.

I agree with @antw's reasoning here but I would like to show one 'property' of the topology that we currently don't really support/show: the typical number of households/connection that the topology is meant to represent. This can be extracted from the topology file by adding up the 'units' of the end-nodes.

**Comment by grdw** [comment]
![screen shot 2015-10-16 at 4 42 43 pm](https://cloud.githubusercontent.com/assets/2676542/10544656/f48bfd2a-7424-11e5-8c99-b5984270eadd.png)

Preview of the preview

**Comment by dennisschoenmakers** [comment]
Great. Could we also show it top to bottom, i.e. the same direction as in
the LES itself?

Sent from my iPhone

On 16 okt. 2015, at 16:43, Gerard Westerhof <notifications@github.com>
wrote:

[image: screen shot 2015-10-16 at 4 42 43 pm]
<https://cloud.githubusercontent.com/assets/2676542/10544656/f48bfd2a-7424-11e5-8c99-b5984270eadd.png>

Preview of the preview

—
Reply to this email directly or view it on GitHub
<https://github.com/quintel/etmoses/issues/530#issuecomment-148735812>.

**Comment by grdw** [comment]
I'm able to generate a preview pretty easily.

Only issue are the Lochem topologies:

![screen shot 2015-10-16 at 4 43 59 pm](https://cloud.githubusercontent.com/assets/2676542/10544687/2c4682d0-7425-11e5-9f25-513b85b55c3d.png)

**Comment by grdw** [comment]
@dennisschoenmakers yeah sure! :+1:

**Comment by JeroenvdLogt** [comment]
Great work Anthony! I consider the Lochem Topology as an exceptional situation. Simulation of bigger a LES with the same detail level could be feasible for ET Moses. But after a few usescase I notice it is allready prety hard to 'be in control' as user (read: difficult to see all implications of your input). 

Anyways the representation of the topology you suggest is a good one I think.

**Comment by antw** [comment]
> Great work Anthony! 

This was all Gerard, thanks @grdw!

--

I still think reducing the node size – and separation between each – would be worthwhile for the preview:

<img width="162" alt="screen shot 2015-10-17 at 12 24 51" src="https://cloud.githubusercontent.com/assets/4383/10558532/23c3cc6c-74ca-11e5-85a2-4a9af5c8f105.png"> <img width="201" alt="screen shot 2015-10-17 at 12 28 01" src="https://cloud.githubusercontent.com/assets/4383/10558539/8a0e0406-74ca-11e5-815c-087f50d6b974.png">

**Comment by grdw** [comment]
![screen shot 2015-10-19 at 11 25 22 am](https://cloud.githubusercontent.com/assets/2676542/10574103/25713c26-7654-11e5-88b1-823c23187572.png)
![screen shot 2015-10-19 at 11 25 30 am](https://cloud.githubusercontent.com/assets/2676542/10574104/2574bc0c-7654-11e5-9374-9eb908f09b2a.png)

@antw something like this? :+1:

**Comment by antw** [comment]
> something like this?

Exactly! I think that looks clearer. There's not much we can do with the really complex networks, so I think we'll have to live with the clutter in those cases.

Two *minor* things stand out in that screenshot:

* The `stroke` colour should be the same as the node colour (it looks like it is a lighter grey which makes the node look a bit blurry).
* Maybe the nodes could be 1-2px smaller?

**Comment by grdw** [comment]
> The stroke colour should be the same as the node colour (it looks like it is a lighter grey which makes the node look a bit blurry).
> Maybe the nodes could be 1-2px smaller?

Yes, and yes.

![screen shot 2015-10-19 at 11 41 58 am](https://cloud.githubusercontent.com/assets/2676542/10574461/6e43f770-7656-11e5-8761-83e3e96d46cf.png)

**Comment by antw** [comment]
Actually, I take that back. The smaller nodes looks a bit weird now :laughing:

It would work if the width between each node was smaller ([which is set here](https://github.com/quintel/etmoses/blob/master/app/assets/javascripts/charts/topology_tree/tree_graph.js#L86-L91)) – the topology preview would want to set the width to a constant (50px?) – but I think I'm being very picky now. I'll leave it to you to decide what you want to go with.

**Comment by grdw** [comment]
> the topology preview would want to set the width to a constant

Eh, no. I did that, but for the larger topologies that will become a bit of a mess. Maybe some `Math.min / Math.max` magic might turn out handy.
