### ISSUE TITLE
Adding more customer stakeholders

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#532]
This issues is merely as a status update

- [x] Adding stakeholders to the database
- [x] Adding hierarchy to stakeholder
- [ ] Finding a select box library that can show and hide suboptions
- [x] Expand business cases
- [x] Expand market models

**Comment by grdw** [comment]
@ChaelKruip I think the most easy way to make the 24 stakeholders work out, is if we blank out the stakeholders that we don't use in the `MarketModel` / `Topology`. This way you only get a business case with all the 'relevant' information. I'm still wondering if there was a reason to why we kept all the stakeholders listed in the business case eventhough there were no rules for them?

**Comment by ChaelKruip** [comment]
> I'm still wondering if there was a reason to why we kept all the stakeholders listed in the business case eventhough there were no rules for them?

Uniformity of the table mostly.
