### ISSUE TITLE
Now that we have 24 sub-customers, what for status should the customer have?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#535]
- Is customer the 25th?
- Is customer the parent of the 24 sub-customers

What to with the market model rules in which transactions are defined for a sub-customer or/and a customer?

The same question accounts for the topology.

Including @ChaelKruip @dennisschoenmakers

**Comment by ChaelKruip** [comment]
We have decided that the customer and the 24 'sub'-customers will be available alongside each other and thus have the same status. Closing.
