### ISSUE TITLE
When comparing business cases should all the stakeholders be visible?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#536]
Some context:

- This is when there are an additional 24 stakeholders.
- To make the business case fit into the summary box niceley on the LES show page - I rejected all the stakeholders which aren't also in your topology. This is to make it 'fit'.

---

Let's say you have two business cases:
````
# B1
{ stakeholder: "aggregator", incoming: 1.5, outgoing: 2.0, freeform: 0.5, total: 0 },
{ stakeholder: "system operator", incoming: 1.5, outgoing: 2.0, freeform: 0.5, total: 0 }
````

````
# B2
{ stakeholder: "aggregator", incoming: 1.5, outgoing: 2.0, freeform: 0.5, total: 0 },
{ stakeholder: "customer", incoming: 1.5, outgoing: 2.0, freeform: 0.5, total: 0 }
````

Would it have any significance to showing the differences for the `customer`? Considering that you left them out of of your original business case.

I would say: no, leave it out, due to the set scope of your current business case. On the other end, it could also be: yes, because when you leave out stakeholders from the other business case you're not *fully* comparing the whole business case.

**Comment by ChaelKruip** [comment]
> On the other end, it could also be: yes, because when you leave out stakeholders from the other business case you're not fully comparing the whole business case.

Indeed! I would show the [union](https://en.wikipedia.org/wiki/Union_(set_theory)) of the stakeholders in the two LESs (exclude only those that are in neither of them).
