### ISSUE TITLE
investment cost of nodes but no end-nodes

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#537]
I see in the business case table no investment cost of nodes which are no end-nodes.
you can look at Oefencase Etten-Leur SSU in the live server.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt please include a link to [your LES](http://moses.et-model.com/testing_grounds/341) (like this :smile:)

**Comment by ChaelKruip** [comment]
I see that the `system operator` has no depreciation costs although they should be equal to:
```
400000 / 50 + 25 * 6000 / 30 + 25 * 7500 / 30 = 19350 EUR/year
```

Assigning to @grdw

**Comment by grdw** [comment]
I already see what is happening here.

In some Topologies `technical_lifetime` is used to specify the 'duration' of a certain technology. In others the term `economic_lifetime` is used. The term to use for succesfully calculating the depreciation costs is `technical_lifetime`. There are no calculations that make use of the term `economic_lifetime`.

In order to not cause any future confusion about this term and it's usage, we could settle for a certain term. I don't feel a strong preference to either `economic_lifetime` or `technical_lifetime`. But maybe there are people with a stronger preference?

**Comment by JeroenvdLogt** [comment]
If calculations are right it is not important which term we chose I think. For Regulation Affairs there is however a big difference between economic_lifetime and technical_lifetime. To give an example: there are some cables in dutch networks older than 70/80 years (technical_lifetime). But in order to proper benchmark between DSO's a economic_lifetime is choosen (based on statistics about lifetime of large population of assets). This economic_lifeime is used to eventually calculate total needed investments and to determine tariffs. 

So technical_lifetime can be seen as the actual lifetime in the field (of individual assets) and economic_lifetime as a statistic value saying something about the average life_time of such a type of assets. This average life_time is used in calculations for (re-)investments and tariffs.

I will discuss this with Hans and Bianco because in some usecases I see this same issue (difference of economic and technical lifetime) keep coming back.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt thanks for expanding on the subject. 

I suggest that for the moment we allow both to be used. The lifetime (whichever one) is only used to determine the depreciation costs at the moment. It does not really matter which is used as long as it is representative for how to spread the investment. 

Anyone opposed?

**Comment by antw** [comment]
> I suggest that for the moment we allow both to be used.

:+1:

**Comment by grdw** [comment]
Just for clarity: `economic_lifetime` must be implemented as if an alias of `technical_lifetime` ?

**Comment by ChaelKruip** [comment]
> Just for clarity: economic_lifetime must be implemented as if an alias of technical_lifetime ?

Yes. :+1:

**Comment by ChaelKruip** [comment]
What is the status of this @grdw?

**Comment by antw** [comment]
It's part of [this pull request](https://github.com/quintel/etmoses/pull/539) and should be merged soon.
