### ISSUE TITLE
Load chart is screwed up for week-view

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#543]
In [this LES](http://beta.moses.et-model.com/testing_grounds/330) the load chart looks like this:
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10600645/7295e2fa-770c-11e5-9436-f1195f166e2f.png)

**Comment by grdw** [comment]
"Could you please include the steps you took in to reproducing this bug." 

Just kidding, because I think I know how this might happen though. I need to clear the brush from `localStorage`... I'll fix it asap.

**Comment by ChaelKruip** [comment]
> I'll fix it asap

:+1:
