### ISSUE TITLE
when editing the technology matrix, save all and view LES does not save my options

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#544]

**Comment by grdw** [comment]
I think this had to do with `IrregularCurveMeasuresValidator` not found. I saw this flying by in my console log but I think @antw fixed it with 95a9c80.

**Comment by antw** [comment]
> I think this had to do with IrregularCurveMeasuresValidator not found. I

That class didn't exist when this issue was created, and there were no references to it in the code. I suspect the message in the console was unrelated to this issue.

**Comment by grdw** [comment]
> I suspect the message in the console was unrelated to this issue.

Yes, I think so to. Bit weird though. Maybe it was a specific LES, @ChaelKruip  do you have the id of the LES?

**Comment by antw** [comment]
> Yes, I think so to. Bit weird though.

Was this in development? I just encountered the same thing; it turned out to be because the [Spring](https://rubygems.org/gems/spring) server hadn't picked up the new class (since it is in a new directory which wasn't being monitored for changes). Running `spring stop` fixed it.

**Comment by grdw** [comment]
I encountered it only on development. I couldn't detect the problem on the staging environment. Spring wasn't running locally in my environment so I guess it couldn't have been Spring (`spring stop` returned `Spring is not running`).

**Comment by grdw** [comment]
Talked with @ChaelKruip about this issue. It's a little bit more vague than I thought. The thing is that I can't reproduce this locally but I can on the beta and live servers.

**Comment by grdw** [comment]
Closing this.

**Comment by ChaelKruip** [comment]
> The thing is that I can't reproduce this locally but I can on the beta and live servers.

I think it is a real issue and should be addressed at some point. Re-opening this.

**Comment by grdw** [comment]
Is this the same issue as #614 ?

**Comment by grdw** [comment]
Hmm. I can sometimes reproduce this still. Only if I click really really fast. I think this is general slowness of parsing a large dataset. I could disable the button until the full JSON dataset is loaded into the dom part that contains the `technology_profile`.

**Comment by grdw** [comment]
Still one thing. I'm not going to do this on the old interface. It'll probably be the same problem on the new interface. So in order to not to fix the same bug twice...

**Comment by antw** [comment]
> I'm not going to do this on the old interface

New UI will be merged soon, I promise! Still got some loose ends to tie up with shared buffers (discussed with @ChaelKruip earlier today) and I'll merge the new editor and gas charts at the same time.

**Comment by grdw** [comment]
@ChaelKruip is this also still present in the new layout? I'm trying to be as fast as I can in adding/removing a new technology and saving but I can't really reproduce it. 

I also think (and I'm guessing here) that your problem might have been a result of another error / problem which is maybe already solved?

**Comment by ChaelKruip** [comment]
@grdw let's close this if you cannot reproduce and re-open if it occurs again.
