### ISSUE TITLE
It would be cool if the topology preview would work on mouseover

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#546]
Now you have to select the topology first to see the preview:
![screen shot 2015-10-20 at 11 00 31](https://cloud.githubusercontent.com/assets/1303760/10602672/f5eb1f3c-7719-11e5-8b2f-6adde83a7fce.png)

**Comment by antw** [comment]
I'm fairly sure `mouseover` and `mouseenter` events don't work on `<option>` elements. I think this would require a custom (JS-based) drop-down implementation such as [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/).
