### ISSUE TITLE
Are there names present for the 24 customer stakeholders?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#549]
Right now they're named Customer 1 until 24.

I think there are actual names for them.

Before merging: #548

**Comment by ChaelKruip** [comment]
Assigned to @JeroenvdLogt.

**Comment by JeroenvdLogt** [comment]
Customer AC8
Customer AC8a
Customer AC8b

same goes for:
:
Customer AC7/AC7a/AC7b
Customer AC6/AC6a/AC6b
Customer AC5/AC5a/AC5b
Customer AC4/AC4a/AC4b
Customer AC3/AC3a/AC3b
Customer AC2/AC2a/AC2b
Customer AC1/AC1a/AC1b
