### ISSUE TITLE
default capacity for P2H needs to be added

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#562]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/10662165/d7582840-78b2-11e5-986f-ba17378b2e10.png)

**Comment by grdw** [comment]
This value has to be imported from EtEngine?

**Comment by grdw** [comment]
@ChaelKruip see above question.

**Comment by ChaelKruip** [comment]
> This value has to be imported from EtEngine or filled in the database?

It should be imported from ETE but I'm not sure if it already exists :smile:

**Comment by grdw** [comment]
> but I'm not sure if it already exists

I would assume that it doesn't, since it doesn't get filled in automatically. So maybe a database default would suffice for now?

**Comment by ChaelKruip** [comment]
> I would assume that it doesn't, since it doesn't get filled in automatically. So maybe a database default would suffice for now?

:+1: I think we already added its specifications earlier. This comment contains the values: https://github.com/quintel/etdataset/issues/599#issuecomment-98747401

**Comment by grdw** [comment]
I'm assuming it's the `- input_capacity = 2 kW` field. :smiley: 

I added 2.0 as defaults for the `default_capacity` field for `households_flexibility_p2h_electricity` for the `etmoses_production` and `etmoses_staging` databases.

**Comment by ChaelKruip** [comment]
> I'm assuming it's the - input_capacity = 2 kW field.

:+1:
