### ISSUE TITLE
Creating a merit order download link

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#565]
There has to be a merit order download link for a LES. It has to be available under the options menu.

I have a question before I start (and probably some more):

I found out that you can create a `Merit::Order` with `Merit::Order.new`. Which is nice. Than I started to click around and read and found out that there's an example file called:

https://github.com/quintel/merit/blob/master/examples/stub.rb

Which made things a little confusing:

How do I know if a technology is a `MustRunProducer`, `VolatileProducer`, `DispatchableProducer`?

**Comment by ChaelKruip** [comment]
> I found out that you can create a Merit::Order with Merit::Order.new

I think that already happens in ETMoses. The new Merit object is created with the scaled production park and given the effective load on the HV network of the topology as demand curve. 
The Merit module runs and returns a price curve which can be used as a tariff for financial transactions.

What I'm trying to say is that I think that you don't have to initialise and run the MO but rather figure out how to hook into the existing one. The two download options needed are identical to those on [this page](http://et-engine.com/data/latest/merit)

**Comment by dennisschoenmakers** [comment]
> How do I know if a technology is a MustRunProducer, VolatileProducer, DispatchableProducer?

That is already taken into account in [**Market::MeritBuilder**](https://github.com/quintel/etmoses/blob/66860411ccd6293ade1008f309548f800da9530a/app/models/market/merit_builder.rb#L43-L45) and defined in the technology's *type*.

**Comment by antw** [comment]
> That is already taken into account in Market::MeritBuilder and defined in the technology's type.

:+1:

The ETEngine API will include the technology `type` if you really need it:

```js
// GET http://etengine.dev/api/v3/scenarios/425000/merit

{
  "participants": [
    // ...
    {
      "profile": "wind_inland",
      "type": "volatile",  // <-- !!!
      "key": "energy_power_wind_turbine_inland",
      "marginal_costs": 0,
      "output_capacity_per_unit": 3,
      "number_of_units": 0.06448469374401514,
      "availability": 0.95,
      "fixed_costs_per_unit": 531768.45,
      "fixed_om_costs_per_unit": 147579.9,
      "full_load_hours": 1700
    },
    // ...
  ]
}
```

*However*, the Market namespace already includes MeritBuilder which creates a fully-formed `Merit::Order` instance in order to compute the price curve. It should be possible to use that without much modification.

**Comment by grdw** [comment]
> It should be possible to use that without much modification.

Ok, I see. Didn't notice that there was already a class built for it. :no_mouth: 

Also found: https://github.com/quintel/etmoses/blob/master/app/models/market/from_market_model_builder.rb#L61-L74

Which looks exactly like the thing that is needed! :+1: 

I think I can figure out

**Comment by grdw** [comment]
I committed: bd83c03. However, there are no specs. The reason is that I don't really know yet what happens in between the input and output. I'll have to validate with somebody if the numbers are correct.
