### ISSUE TITLE
Is it possible to assign a negative anual use to baseload profiles

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#572]
Hans Verberne asks me if its possible to 'abuse' baseloadprofiles to represent production of central production plants. He wants to assign a negative annual use to baseload profiles.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt please assign a team member to ensure that your issue is noticed and that someone feels responsible for it. 

Assigning to @antw

**Comment by antw** [comment]
> [is] it possible to 'abuse' baseloadprofiles to represent production of central production plants

This is not possible as the base load profiles are split into two components – flexible and inflexible. The behaviour would almost certainly be incorrect if you assigned a negative demand, especially if you were to turn on the base load-specific features like "saving" and "postponing".

What you *can* do, is upload a new profile of your own which describes the production of these plants, set the technology type to "Other", and give it a negative demand.

<img width="1130" alt="screen shot 2015-10-28 at 09 51 21" src="https://cloud.githubusercontent.com/assets/4383/10785071/7ca44680-7d59-11e5-904c-e685d76d1669.png">

This will only work on [the beta server](http://beta.moses.et-model.com/) at the moment.
