### ISSUE TITLE
When an end-point contains a gas technology, the end-point should get a gas connection

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#576]
I think 'automatic' assignment of gas connections is more user-friendly than the alternatives (requiring the user to edit the topology file or abusing the technology matrix for this purpose). I'm not yet clear on the following question:

How are we going to determine the 'units' of the end-points gas connection? 

Options include:
1 use the 'units' of the base_load
2 use the 'units' of gas technologies (this gives to many connections if the user actually plans to use several gas-technologies per 'household'
3 the 'units' that was specified in the topology for the number of expected connections for the end-point

@dennisschoenmakers @antw @jorisberkhout @AlexanderWirtz any preference?

**Comment by antw** [comment]
> Options include: [...]

Currently implemented is option 1. The number of gas connections will be equal the number of base loads on the endpoint.
