### ISSUE TITLE
Demand profiles for hot water and space heating should behave analogous to base_load

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#577]
After discussion with @antw and @jorisberkhout, I think it is more natural to express the heat and hot water demand in terms of a profile that is scaled to match the total yearly demand for these quantities.

This is similar to how base_load profiles are scaled with the yearly electricity demand.

**Comment by ChaelKruip** [comment]
This will also require demand for space heating and hot water to be imported from the scaled ETM scenario. I think we can use the following queries to get the demand (in MJ):
```
V(households_useful_demand_for_space_heating_after_insulation, demand)
```
and 
```
V(households_useful_demand_hot_water, demand)
```
These demands have to be converted to kWh (divide the mj by 3.6 to get kWh) before the curves can be scaled right @antw?

**Comment by antw** [comment]
> These demands have to be converted to kWh (divide the mj by 3.6 to get kWh) before the curves can be scaled right @antw?

:+1:
