### ISSUE TITLE
Adding gas-chart

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#580]
We came up with two designs.

One is where we plot the gas chart above the load chart.
````
GAS
|
|
|
|
|_______________________________
0                               100

LOAD
|
|
|
|
|_______________________________
0                               100

BRUSH
|
|_______________________________
0                               100
````

*Pro's*
- Everything in one overview

*Con's*
- Brush needs to update two charts which is not supported in nvd3 library. 

The other is in separate tabs:

````
LOAD | GAS | TECHNOLOGIES

LOAD
|
|
|
|
|_______________________________
0                               100

BRUSH
|
|_______________________________
0                               100
````

*Pro's*
- Easy to implement

*Con's*
- Will probably be even slower on some machines due to the rendering of two charts instead of one. Chael told me that some people have trouble with rendering the charts because of slowness.

My personal preference is to put everything in one overview + getting rid of the nvd3 library and use something custom to update two charts with one brush.

**Comment by grdw** [comment]
> My personal preference is to put everything in one overview + getting rid of the nvd3 library and use something custom to update two charts with one brush.

@ChaelKruip 

I made some time calculations and investigated into the options with the focus on the first option. But I hit a brick wall concerning the first option. Getting rid of the nvd3 library is going to be one hell of a job. Mainly because there is A LOT of code to sift through (nvd3 is build up with models which are intertwined and branched into each-other pretty badly). And it's not feasable to do so unless we have at least two weeks (which might be an exaggeration but I guess it would be). I would have to do a lot of reading on d3 and all it's advanced features, because it's such an extensive library. Implement the exact same focus chart with d3 instead of nvd3 and extend it with another chart. 

To put it bluntly: option 1 is off the table unless we're going to do some really ugly nvd3-code-hackary or just write the thing with d3 which we don't have any time for. 

So option 2 it is.

**Comment by dennisschoenmakers** [comment]
In the end, I think we really need to have a solution where you can inspect and explore the electricity *and* the gas load chart simultaneously since all of the 'added value' is in the synergy of the two. It would be very unfortunate if you have to switch tabs for that.

What about putting the two series (elec + gas) in **one** chart?

**Comment by grdw** [comment]
> What about putting the two series (elec + gas) in one chart?

Chael and I discussed that option aswell. But it might get too messy. Than again, you can toggle them on and off with the legend.

**Comment by dennisschoenmakers** [comment]
> [...] Than again, you can toggle them on and off with the legend.

Exactly, and I think it's much better than switching tabs.

**Comment by dennisschoenmakers** [comment]
How easy/hard will it be, @grdw ? :smile:

**Comment by grdw** [comment]
I do have a question now about 'the synergy of the two'. The thing is that there is an `altLoad` attribute which contains the load when the strategies are applied (the data for the green line). Would there be a separate one for gas (like `gasAltLoad`) or would the strategies apply to both gas and normal load and would the green line show the 'sum' of both strategies? (Maybe @antw has an answer for this).

> How easy/hard will it be

Easy, considering the question above. Which makes it still easy. It's just adding a line with the data for gas load attached to it, which is 5 minutes of work. But it might be two lines which makes it 6 minutes of work.

**Comment by dennisschoenmakers** [comment]
> The thing is that there is an altLoad attribute which contains the load when the strategies are applied (the data for the green line). Would there be a separate one for gas (like gasAltLoad) 

I guess so.

> or would the strategies apply to both gas and normal load and would the green line show the 'sum' of both strategies?

No that would be weird! I guess we need four lines: 
* one for electricity, 
* one for gas, 
* one for electricity with strategies applied and 
* one for gas with strategies applied.

**Comment by antw** [comment]
> Would there be a separate one for gas (like gasAltLoad) or would the strategies apply to both gas and normal load and would the green line show the 'sum' of both strategies? (Maybe @antw has an answer for this).

I think there will be need for separate "basic" and "feature" gas loads; the gas load may be affected by the user's choice of strategies.

> What about putting the two series (elec + gas) in one chart?

I agree with @grdw that this could get messy, but it should be quite straightforward to implement (compared with the other options, anyway). It think it might be worth trying.

**Comment by dennisschoenmakers** [comment]
and since you can toggle them all, user can choose what to inspect, right? :)

**Comment by dennisschoenmakers** [comment]
> I agree with @grdw that this could get messy

If you mean with 'messy' a lot of information all crammed up in the same spot on your screen, I am not so worried. Up to the user to show gas/elec with/without strategies.

**Comment by ChaelKruip** [comment]
Agree!

**Comment by grdw** [comment]
![screen shot 2015-10-29 at 2 07 06 pm](https://cloud.githubusercontent.com/assets/2676542/10819057/5d44549a-7e46-11e5-9397-6aaa141e1f7e.png)

Something like this? :smile:

**Comment by ChaelKruip** [comment]
:+1:

**Comment by dennisschoenmakers** [comment]
Excellent!
