### ISSUE TITLE
Remember original URL when you need to log in

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#587]
Now it's annoying when you follow a link, and you log in, you are redirected to the home page, in stead of your url.

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by dennisschoenmakers** [comment]
I am still not redirected after signing in on beta. 

1. Sign out
2. Go to http://beta.moses.et-model.com/testing_grounds/383
3. You're redirected to the login
4. You log in
5. You end up in the welcome page, while I would expect page under 2 above.

**Comment by grdw** [comment]
That's weird, I would expect the url from `2.` to be in the session variable declared at: [here](https://github.com/quintel/etmoses/commit/47f0d352cc3d8e540c348c48ca16534247d44254#diff-55c5b7aecfb519d0e4880eaf2788eb6eR35). 

Hmm, I'll take a look! :+1:
