### ISSUE TITLE
Download of curves is broken

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#588]
<img width="503" alt="screen_shot_2015-11-03_at_13_39_50_png" src="https://cloud.githubusercontent.com/assets/1303760/10908215/715f35e2-8230-11e5-94c1-cbd6c9c713d7.png">

**Comment by grdw** [comment]
Which curves?

**Comment by ChaelKruip** [comment]
> Which curves?

The 'load' curve (first in the list). Nothing happens when I push the button
