### ISSUE TITLE
Business case should reflect transactions based on flex

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#589]
No flexibility measures in [this LES](http://beta.moses.et-model.com/testing_grounds/355)

<img width="1199" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/10910760/846c256c-8241-11e5-88ad-5cb72222eaef.png">

**Comment by grdw** [comment]
Can you maybe explain the details of this problem? Is it just the fact that these values are empty or should they be filled?

**Comment by ChaelKruip** [comment]
> Can you maybe explain the details of this problem? 

In the LES mentioned, there is a transaction based on the flexibility realised by the customer. The Aggregator should pay for it. Because the green and blue curves are different for end-points that belong to the customer I'd expect the Aggregator to pay a non-zero amount to the customer and thus have expenses.

> Is it just the fact that these values are empty or should they be filled?

I expect that the Customer should get money and the Aggregator should be paying.

The cells are empty because there is no transaction defined that gives them any value right?

**Comment by ChaelKruip** [comment]
@grdw what is the status of this?

**Comment by grdw** [comment]
@ChaelKruip I merged it and deployed it.
