### ISSUE TITLE
No business case calculation for complex LES

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#592]
Hello,

Hans and I are trying to simulate the average Liander grid. The loadcalculations seems to be okay but after ET Moses is finished still no BC is available. I looked at the market model and topology but it seems that all the stakeholders are taken care of. Its about this LES at Hans Verberne's account.

"Hierbij de link naar Liander 2014

http://beta.moses.et-model.com/testing_grounds/247"

**Comment by antw** [comment]
This was an old LES, created before current market model system was deployed, and therefore lacked a BusinessCase object of its own. I have added one manually. You should find that the financial outcomes now show up.

**Comment by JeroenvdLogt** [comment]
Thank you, load calculations & business case are performed now. Regardless it takes longer than 1 minute simulation time. Only it seams aggragtion of load is not good now. see: https://github.com/quintel/etmoses/issues/643
