### ISSUE TITLE
Concurrency with buffers

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#594]
The only issue that stands between the new profile layout with buffers is the concurrency.

The concurrency now looks at the end-points - and the unique profiles per technology.

Let's say this is the LES and all technologies have 2 profiles for simplicity.

```` 
     LV#1 - [ Tech 1 -> Profile #1 ] 
    / 
HV -
    \
     LV#2 - [ Tech 2 -> Profile #1 ]
````

With minimized concurrency it will look like:

```` 
          [ Tech -> Profile #1 ]
        /
     LV#1 - [ Tech -> Profile #2 ]
    /      
HV -
    \
     LV#2 - [ Tech 2 -> Profile #1 ]
         \
          [ Tech 2 -> Profile #2 ]
````

Nothing new here, this is just how it functions.

----

With a buffer it looks like:

````  
                   [ Heat pump #1 ]
                  /
     LV#1 - [ Buffer 1 -> Profile #1 ] -  [ Heat Pump #2 ]
    /                                                                         
HV -
    \
     LV#2 - ....
````

Minimezed concurrency looks like:

````  
                                          [ Heat Pump #1 ]
                                         /
               [ Buffer 1 -> Profile #1 ]
             /                           \
            /                             [ Heat Pump #2 ]
           /
          /                                   [ Heat Pump #1 ]
         /                                   /
        LV#1 - - - [ Buffer 2 -> Profile #2 ]
      /                                      \
     /                                        [ Heat Pump #2 ]
    /
HV -
    \
     LV#2 - ....
````

At least that's what I think it looks like. @ChaelKruip maybe you could say whether or not this way of thinking is correct?

**Comment by antw** [comment]
I can't speak for @ChaelKruip, but that's not *quite* what I was expecting. In the example, you have two heat pumps (`#1` and `#2`), and they seem to *both* be connected to Buffer 1 and Buffer 2. This is what I was anticipating:

Max concurrency:

```
     LV#1 - [ Composite 1 -> Profile #1 ]  ---  [ Heat Pump #1 ] (2 units)
    /                    
HV
    \
     LV#2 - ....
```

Min concurrency:

```
                             [ Heat Pump #1 ] (1 unit)
                               /
     LV#1 - [ Composite 1 -> Profile #1 ]
    /                          \
HV                           [ Heat Pump #2 ] (1 unit)
    \
     LV#2 - ....
```

That is... changing the concurrency settings would change the number of discrete technologies, but the number of composites ("buffers") would remain the same.

I suppose if @ChaelKruip meant that a change in concurrency *should* change the number of composites, we'd end up with:

```
           
        [ Composite 1 -> Profile #1 ] - [ Heat Pump #1 ] (1 unit)
         /
     LV#1 - [ Composite 2 -> Profile #2 ] - [ Heat Pump #2 ] (1 unit)
    /
HV                           
    \
     LV#2 - ....
```

--

In fairness to you, I think the specification for this task is unclear:

* **Can a composite have a number of units?** (to act as a multiplier for the demand profile) – *I hope so.*

* **What does it *mean* to specify a number of units on a composite**, and how does that affect the (sub)-technologies it uses?

  i.e. if a composite has "2" units and itself contains a heat pump with "2" units, how many heat pumps are there in total? 2 or 4?

**Comment by ChaelKruip** [comment]
> I suppose if @ChaelKruip meant that a change in concurrency should change the number of composites, we'd end up with:

As discussed with @grdw this is indeed what I meant. The concurrency works on the thing that carries the profile. It makes little sense to treat multiple units separately if they are all using the same profile right?

> Can a composite have a number of units? (to act as a multiplier for the demand profile) – I hope so.

I hope so too :fearful: 

> What does it mean to specify a number of units on a composite, and how does that affect the (sub)-technologies it uses?

> i.e. if a composite has "2" units and itself contains a heat pump with "2" units, how many heat pumps are there in total? 2 or 4?

2. This is in line with how topologies behave: a 'units' on one level does not influence the lower levels.

**Comment by grdw** [comment]
This is part of pull request https://github.com/quintel/etmoses/pull/605
