### ISSUE TITLE
uploading technology.csv

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#595]
I'm trying rebuild the LES of Hans Verberne. Its a private one so to keep it that way Hans send me the topology, technology.csv and the market model. I am able to reproduce the topology and market model. But when I try to rebuild the technology table something goes wrong. I succeed in uploading but all the names and profiles are gone. Result is that all the loads are zero.

On the live server I am using Hans Liander Topology (name of both topology, market modell and LES). I included the technology table in this issue as xlsx because I cannot upload csv files here.

http://moses.et-model.com/testing_grounds/
[technology_profile (1).xlsx](https://github.com/quintel/etmoses/files/27827/technology_profile.1.xlsx)
352/edit

**Comment by grdw** [comment]
I see that `Productie edsn_3d` is being used as a profile after converting [technology_profile (1).xlsx](https://github.com/quintel/etmoses/files/27827/technology_profile.1.xlsx) to a csv in excel.

This is not a valid `profile_key`. I would suggest removing the `Productie ` prefix (mind the whitespace). After that it should work just fine.

Including #568

**Comment by grdw** [comment]
It would also be nice to add validations for this though. To check if the `profile_key` actually exists in Et-moses. Might be better than throwing an error. :smile: There are no validations right now due to the dropdown boxes but since a CSV is pretty freeform we might consider adding one. 

Including @ChaelKruip

**Comment by JeroenvdLogt** [comment]
Actualy I renamed a load_profile to the correct name at the beta-server and tried again. But even than it didn't work properly. For now I am bussy with other things. Maybe when I meet Chael or if I am in Amsterdam I can show.

**Comment by grdw** [comment]
Is there a specific error message you receive? Like:

![screen shot 2015-11-17 at 10 14 13 am](https://cloud.githubusercontent.com/assets/2676542/11207189/f76f3086-8d13-11e5-89f4-17ea63a70920.png)

Or do you get redirected to the '[something went wrong](http://beta.moses.et-model.com/500.html)' page?

**Comment by ChaelKruip** [comment]
@grdw please refer to the person whom you are asking the question to trigger them getting an email notification. Including @JeroenvdLogt

**Comment by grdw** [comment]
I already found a problem. The first CSV converter assumed the profiles were filled from a `profile` csv header. Right now the `profile_key` header is used. This triggers some strange behaviour (namely technologies without profiles). I'll look closer into the CSV -> Technologies conversion.

**Comment by antw** [comment]
>  please refer to the person whom you are asking the question to trigger them getting an email notification

The author of an issue will get a notification for each update unless they explicitly opt out by clicking "Unsubscribe" (top-right, beneath the assignee).

--

The technologies CSV looks to me to be lagging behind the rest of the application in that it is missing many of the newly added attributes (coefficient of performance, costs, etc). Maybe this is partly to blame?

However, I don't think we can *guarantee* that a beta CSV will work on production: profile names may be different (or absent), technologies may have changed, and features that exist on beta won't be there on production.

**Comment by grdw** [comment]
I did fix the `profile_key` issue. https://github.com/quintel/etmoses/commit/644c681ca251c16089260ab27807d7e51e744916

> The technologies CSV looks to me to be lagging behind the rest of the application in that it is missing many of the newly added attributes (coefficient of performance, costs, etc). Maybe this is partly to blame?

Could be, but is not described in the original issue.

**Comment by ChaelKruip** [comment]
> The author of an issue will get a notification for each update unless they explicitly opt out by clicking "Unsubscribe" (top-right, beneath the assignee).

Cool. Thanks for pointing that out.

**Comment by ChaelKruip** [comment]
> Could be, but is not described in the original issue.

Let's close this one and open a new issue then :smile:
