### ISSUE TITLE
Are cost included in upscaling from ET-Moses to ETM

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#597]
I was wondering wether with upscaling from ET-Moses to ETM simulationresults for costs are empoyed  in ETM or not. It seems as nothing was changed in energyproduction and -consumption but the market model changed however that systemcost still unchanged.

![image](https://cloud.githubusercontent.com/assets/7781037/10995346/5b4367b2-847c-11e5-9af2-b3ab699c76f4.png)

![image](https://cloud.githubusercontent.com/assets/7781037/10995356/736ee0fa-847c-11e5-8508-0cf9a0f0a4b6.png)

**Comment by ChaelKruip** [comment]
Only the effects of updated slider-settings affect the scaled back ETM scenario.
