### ISSUE TITLE
Show advanced button should say 'hide advanced' when clicked once

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#598]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/10995400/cb15e786-847c-11e5-9aaf-e823dcda2fab.png)

**Comment by grdw** [comment]
I could also call it 'toggle advanced' ?

**Comment by ChaelKruip** [comment]
> I could also call it 'toggle advanced' ?

:+1:
