### ISSUE TITLE
Add Netbeheer NL en Gasunie logos to footer

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#602]

**Comment by ChaelKruip** [comment]
Assigned to @grdw

**Comment by ChaelKruip** [comment]
I think we want this to be similar to the ETM: 
* leading partner: Alliander
* partners: Gasunie, Netbeheer Nederland (roulerend)

![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/11029845/100eeeba-86ca-11e5-9a44-2f4c83512e88.png)

**Comment by dennisschoenmakers** [comment]
As discussed with @ChaelKruip: Just place the logos on the right of the current logo.

**Comment by grdw** [comment]
Something like this:

![screen shot 2015-11-30 at 2 55 59 pm](https://cloud.githubusercontent.com/assets/2676542/11473412/83a4a474-9772-11e5-8004-d4d446ab14f3.png)

**Comment by ChaelKruip** [comment]
> Something like this:

Perhaps a bit more spacing? Otherwise :+1:

**Comment by grdw** [comment]
> Perhaps a bit more spacing

![screen shot 2015-11-30 at 3 06 29 pm](https://cloud.githubusercontent.com/assets/2676542/11473672/f6d502b2-9773-11e5-9c90-5809d3e4c29a.png)

**Comment by dennisschoenmakers** [comment]
:+1:
