### ISSUE TITLE
User request: high res PNG dump for large topologies

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#604]
One of our clients builds large topologies and is frustrated with the relatively small window in the front-end. He would like to be able to print the topology to a high res (PNG) image for the purpose of putting it in presentations etc.

**Comment by grdw** [comment]
Personal note: https://gist.github.com/gustavohenke/9073132

**Comment by grdw** [comment]
https://github.com/quintel/etmoses/pull/617

**Comment by grdw** [comment]
I got it to work in IE9 aswell. But there's still a problem; the top of the image is getting cut off. This has to do with svg and scaling in IE9.

**Comment by grdw** [comment]
![blbdgfdfjfdoigd](https://cloud.githubusercontent.com/assets/2676542/11301364/d3359cf2-8f96-11e5-9231-4a853a1c464e.png)

The topology is extremely small compared to the Firefox and Chrome version.

**Comment by grdw** [comment]
I read alot about not using dynamic heights/widths in combination with svg's, last friday. I tried to fix the height problem but couldn't really find a direct solution. @antw do you know what might be the problem here?

**Comment by antw** [comment]
Sorry to say I have no idea why this would happen or what the `viewport` attribute does, so your guess is as good as mine. Perhaps the D3.js docs will have some information on scaling-to-fit?

**Comment by grdw** [comment]
Fixed the topology preview problems in IE9. :sweat_drops: 

Still haven't fixed the dump as PNG problem.

This is what it looks like in Firefox:
![310](https://cloud.githubusercontent.com/assets/2676542/11335123/08d7126a-91da-11e5-9f4d-386a2ba4d9a3.png)

This what it looks like in IE9:
![310](https://cloud.githubusercontent.com/assets/2676542/11335147/27869172-91da-11e5-83ef-d9d580663e0b.png)

I am sort of trying to check if there are any differences between the svg send by IE9 and Firefox to detect any 'weirdness' but I'll keep searching.

**Comment by ChaelKruip** [comment]
> Fixed the topology preview problems in IE9.

:+1:

**Comment by grdw** [comment]
I tried to figure out what this may cause.

Upon drawing a small topology (id=340) the following svg is produced in Firefox:

````html
<svg viewBox=\"0 0 1140 400\" height=\"400\" width=\"1140\" class=\"overlay\" id=\"topology-graph-full\">
<g transform=\"translate(100,15)\">
<path d=\"M470,200C470,250 470,250 470,300\" stroke-width=\"2px\" stroke=\"#ccc\" fill=\"none\" class=\"link\"></path>
<path d=\"M470,100C470,150 470,150 470,200\" stroke-width=\"2px\" stroke=\"#ccc\" fill=\"none\" class=\"link\"></path>
<path d=\"M470,0C470,50 470,50 470,100\" stroke-width=\"2px\" stroke=\"#ccc\" fill=\"none\" class=\"link\"></path>
<g transform=\"translate(470,300)\" class=\"node\">
<circle style=\"fill: rgb(255, 255, 255); stroke: steelblue; stroke-width: 2px;\" r=\"8\"></circle>
<text style=\"fill-opacity: 1; font: 12px sans-serif;\" text-anchor=\"start\" dy=\".35em\" x=\"13\">installatie 1a</text>
</g>
<g transform=\"translate(470,200)\" class=\"node\">
<circle style=\"fill: rgb(255, 255, 255); stroke: steelblue; stroke-width: 2px;\" r=\"8\"></circle>
<text style=\"fill-opacity: 1; font: 12px sans-serif;\" text-anchor=\"end\" dy=\".35em\" x=\"-13\">MSR 1</text>
</g>
<g transform=\"translate(470,100)\" class=\"node\">
<circle style=\"fill: rgb(255, 255, 255); stroke: steelblue; stroke-width: 2px;\" r=\"8\"></circle>
<text style=\"fill-opacity: 1; font: 12px sans-serif;\" text-anchor=\"end\" dy=\".35em\" x=\"-13\">MV Network</text>
</g>
<g transform=\"translate(470,0)\" class=\"node\">
<circle style=\"fill: rgb(255, 255, 255); stroke: steelblue; stroke-width: 2px;\" r=\"8\"></circle>
<text style=\"fill-opacity: 1; font: 12px sans-serif;\" text-anchor=\"end\" dy=\".35em\" x=\"-13\">HV Network</text>
</g>
</g>
</svg>
````

In Internet Explorer 9 this happens:
````html
<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"overlay\" id=\"topology-graph-full\" viewBox=\"0 0 1140 400\" width=\"1140\" height=\"400\">
<g transform=\"translate(100 15)\">
<path class=\"link\" fill=\"none\" stroke=\"#ccc\" stroke-width=\"2px\" d=\"M 470 200 C 470 250 470 250 470 300\" />
<path class=\"link\" fill=\"none\" stroke=\"#ccc\" stroke-width=\"2px\" d=\"M 470 100 C 470 150 470 150 470 200\" />
<path class=\"link\" fill=\"none\" stroke=\"#ccc\" stroke-width=\"2px\" d=\"M 470 0 C 470 50 470 50 470 100\" />
<g class=\"node\" transform=\"translate(470 300)\">
<circle style=\"fill: #fff; stroke: steelblue; stroke-width: 2px;\" r=\"8\" />
<text style=\"font: 12px/normal sans-serif; font-size-adjust: none; font-stretch: normal; fill-opacity: 1;\" text-anchor=\"start\" x=\"13\" dy=\"0.35em\">installatie 1a</text>
</g>
<g class=\"node\" transform=\"translate(470 200)\">
<circle style=\"fill: #fff; stroke: steelblue; stroke-width: 2px;\" r=\"8\" />
<text style=\"font: 12px/normal sans-serif; font-size-adjust: none; font-stretch: normal; fill-opacity: 1;\" text-anchor=\"end\" x=\"-13\" dy=\"0.35em\">MSR 1</text>
</g>
<g class=\"node\" transform=\"translate(470 100)\">
<circle style=\"fill: #fff; stroke: steelblue; stroke-width: 2px;\" r=\"8\" />
<text style=\"font: 12px/normal sans-serif; font-size-adjust: none; font-stretch: normal; fill-opacity: 1;\" text-anchor=\"end\" x=\"-13\" dy=\"0.35em\">MV Network</text>
</g>
<g class=\"node\" transform=\"translate(470)\">
<circle style=\"fill: #fff; stroke: steelblue; stroke-width: 2px;\" r=\"8\" />
<text style=\"font: 12px/normal sans-serif; font-size-adjust: none; font-stretch: normal; fill-opacity: 1;\" text-anchor=\"end\" x=\"-13\" dy=\"0.35em\">HV Network</text>
</g>
</g>
</svg>
````

**Comment by grdw** [comment]
> No comma between translate

Turns out this was the issue.

Note for future IE9 troubles:

When cloning an object. Don't use `attr` upon any sub-html node of that cloned object. For that attribute will not change. Instead use `replace` and use a regex to replace the attribute you want to change.
