### ISSUE TITLE
How to deal with output temperatures of technologies (specifically hybrid heat pumps)?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#606]
# Background

Space heating and domestic hot water require different temperatures. Say 45 and 60 degrees respectively. In ETMoses we model these two uses of heat by using two distinct buffers. Each buffer has the following attributes:

* physical_volume [liter]: how many liters of water the buffer contains (this water is always there, the consumed water is heated by passing it through a heat-exchange unit which extracts heat from the buffer).
* max temperature [degrees Celsius]: the maximum temperature the water in the buffer can have. If heat is extracted from the buffer, this temperature will drop.
* a demand profile [kW]: for every 15 minutes, how many kWh is extracted from the buffer.

# Problem description

Currently, heating technologies just produce heat (in kWh) without any regard for the temperature that they are producing this heat at. The heat stored in water is a product of the liters of water and the temperature difference between the 'outside' and the water:
```
kWh_heat = liters * delta_T * heat_capacity_of_water
```
So, if a heat pump produces 1 kWh of heat is could either be (the heat capacity of water being roughly 0.0011626 kWh / (liter * K)):

1. 860 liter of water heated one degree
2. one liter of water heated 860 degrees (as if!)
3. any other combination of liters and temperatures that represent 1 kWh of heat

This leads to the following problem: 

*In ETMoses a heat pump may heat a buffer to 100 degrees by adding more kWh's of heat to the buffer. In reality a heat pump may only heat the buffer to 45 degrees because it simply cannot make water hotter than 45 degrees.*

In ETMoses, the heat pump part of a hybrid heat pump may provide all the heat for domestic hot water use, whereas in real life the gas boiler needs to provide the 'last step' from 45 to 60 degrees.

NOTE: This issue is mainly about domestic hot water demand as it requires water at temperatures higher than what the heat pump can produce.

# Possible solution direction

We could think about the interaction of buffer and hybrid heat pump as follows:

1. The 100 liter buffer for hot water consumption starts out 'empty' at a temperature of say 15 degrees (outside temperature)
* The heat pump part of the HHP starts heating the 100 liter to 45 degrees. This requires that the heat pump 'knows' that it can only produce heat at 45 degrees.
* Whenever the use profile demands hot water (of 60 degrees), the gas part of the HHP will heat the water from the buffer 'ad-hoc' to 60 degrees.
* The temperature in the buffer will decrease because of the use of heat and the heat pump will refill the buffer whenever the temperature drops below a threshold temperature, say, 35 degrees (unless some strategy commands otherwise).

NOTE: It does not make sense to have the gas part of the HHP heat the buffer to 60 degrees because this would result in the heat pump sitting idle unless the temperature of the buffer becomes lower than 45 degrees again.

**Comment by ChaelKruip** [comment]
@antw @dennisschoenmakers @AlexanderWirtz @jorisberkhout sorry for the wall of text again but I'd really like your opinion on the solution direction described above.

**Comment by dennisschoenmakers** [comment]
:+1: for the proposed direction.
