### ISSUE TITLE
technology CSV should be updated to deal with new attributes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#612]
See https://github.com/quintel/etmoses/issues/595

**Comment by grdw** [comment]
Quick question though; should the user be able to specifiy these attrbiutes by hand in their csv or does this need to be filled automatically from EtMoses or both (depending on the fact if the columns in question are empty or not?)

**Comment by ChaelKruip** [comment]
> Quick question though; should the user be able to specifiy these attrbiutes by hand in their csv or does this need to be filled automatically from EtMoses or both (depending on the fact if the columns in question are empty or not?)

Both. ETMoses should fill in the values that are in the interface, whether the user created those or not (when they are the default values). The user should be able to edit the CSV though (otherwise there would be little use for it).

**Comment by grdw** [comment]
This is already fixed
![screen shot 2016-01-12 at 2 17 50 pm](https://cloud.githubusercontent.com/assets/2676542/12264454/4847827a-b937-11e5-8d85-95d75b208d62.png)
