### ISSUE TITLE
P2H should be possible using a heat pump instead of an electric heater

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#626]
Currently, our P2H setup is a buffer tank with an electric resistive heater. If you have a heat pump at your disposal, however, it is much more energetically efficient to use the electricity in the HP. We should add this option as a strategy...

Including @antw @dennisschoenmakers

**Comment by ChaelKruip** [comment]
Assigning @antw. Not highest priority but I'd like to hear your opinion on how difficult this would be:

* When a heat-pump is connected to a buffer, use the heat pump to heat the buffer if there is excess solar production

**Comment by ChaelKruip** [comment]
> We should add this option as a strategy...

P2H should become **only** a strategy and nothing more IMO. When people have electric (buffering) technologies coupled to their buffers, P2H should just be a way to use excess electricity to heat the buffers using those technologies.

**Comment by ChaelKruip** [comment]
More specifically, I propose to do the following:
* If the P2H strategy is selected, all **buffering** technologies are used to fill up the buffers to the max (also see https://github.com/quintel/etmoses/issues/670). 
* It would be nice if we could prioritise buffering technologies with higher efficiency/COP. So, if a buffer has a heat pump and a resistive electric heater, the heat pump should be used to the max before the heater is used to consume the rest of the excess electricity.

**Comment by antw** [comment]
Another issue caused me to take a second reading of this, and something caught my attention:

> If the P2H strategy is selected, all electric buffering technologies are used to fill up the buffers to the max (also see #670).

I'm not clear on the significance of #670 when it comes to electric technologies on endpoints. The *central* heat network buffer has two volumes: one which may be filled by all central technologies – must runs and dispatchables – and a second (which represents a higher temperature) which may be filled only by must-runs.

Endpoint buffers have only one volume: the one specified by the user.

**Comment by ChaelKruip** [comment]
> Endpoint buffers have only one volume: the one specified by the user.

Exactly, but #670 is a suggestion to give them two volumes (just like the central ones). Unless this is a lot of work I think we should try to make that improvement.
