### ISSUE TITLE
New interface should 'show' the difference between a boosting or buffering technology

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#627]
Stage:

- [x] Design
- [x] Feedback
- [x] Implementation
- [x] Feedback
- [x] Fixing feedback + bugs
- [x] Pull request

**Comment by grdw** [comment]
First design idea:

![20151125-profile-matrix-buffer-booster-v3](https://cloud.githubusercontent.com/assets/2676542/11401150/6a676abc-9391-11e5-8fd7-5900b8d03cf4.png)

- Changed the remove button to a simple trash bin
- Did some alignment things to the inputs
- Indent the block of 'technology' that's attached to a certain buffer.
- Adding a pair of radio buttons to determine the position of the technology relative to the buffer

Including @ChaelKruip @antw 

Shoot.

**Comment by antw** [comment]
Looks good to me. :+1:

It would be nice to have a small `(?)` button to explain what "Boosting" and "Buffering" mean.

**Comment by grdw** [comment]
> It would be nice to have a small (?) button to explain what "Boosting" and "Buffering" mean.

Yes :+1:

**Comment by ChaelKruip** [comment]
I like it but could you maybe make the technology areas more "cellular" (clearly separated from each other). Now I have the feeling of reading a very long list instead of a 'chain of separate entities'. Sorry to be so vague @grdw I'll talk to you in person now :smile:

**Comment by grdw** [comment]
Something like this? Taking into account above mentioned points.

![screen shot 2015-11-26 at 4 31 22 pm](https://cloud.githubusercontent.com/assets/2676542/11426274/2a98fe8a-945b-11e5-92ac-390d44847fa4.png)

**Comment by ChaelKruip** [comment]
> Something like this? 

I like how the different shading makes clear that several lines of information all belong to the same technology. Unfortunately, for technologies that are are connected to the same buffer, I feel that different shading undermines the sense of 'connectedness' of the technologies and the buffer.

I know what I'm saying here may sound like a paradox but IMO info about one technology should clearly belong together. At the same time it should be clear that technologies connected to a buffer belong to that buffer.

**Comment by ChaelKruip** [comment]
@dennisschoenmakers please let us know what you think as well!

**Comment by dennisschoenmakers** [comment]
Looking good @grdw! Wondering: what is *demand* for a buffer?

Could we use an icon for the buffer to set it more 'apart' from the other stuff?

And perhaps a thinker line around a group of buffers plus the heating technologies?

**Comment by grdw** [comment]
>  I feel that different shading undermines the sense of 'connectedness' of the technologies and the buffer.

Yes. I still don't fully how to make something more 'cellular'. 

Other option would be without the 'even' 'uneven'

![screen shot 2015-11-26 at 5 16 41 pm](https://cloud.githubusercontent.com/assets/2676542/11427204/8433e670-9461-11e5-90f6-6b13a6ba9b44.png)
