### ISSUE TITLE
Uploading technology csv results in name: other

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#629]
When I try to upload a technology csvfile this results in a table with all the name cells as other. I will snet the csv file to Chael by e-mail. The topology I use is USEF: waardebepaling flex (Lochem doorrekening) at the beta server.

**Comment by JeroenvdLogt** [comment]
Another thing I encounter, when I change name: other in name: electric car f.e. all the previous settings of capacity-storage-annual usage are set to default automatically. It cost a lot of time to reset everything to the previous values. Is it possible to cancel default values?

**Comment by dennisschoenmakers** [comment]
Due to the holiday of @ChaelKruip assigned this to @grdw
