### ISSUE TITLE
No load calcuations

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#630]
I try to do load calculations on a LES. ET-Moses doesn't return errors but no calculations are performed though. I see the following after I clicked on save and view LES.

![no load calculation usef](https://cloud.githubusercontent.com/assets/7781037/11439409/78829dd6-94fb-11e5-9aaa-182a1ce3278c.JPG)

**Comment by antw** [comment]
It's a large LES which is hitting to 60s timeout. Tried increasing the limit in Nginx but it had no effect. It's likely Unicorn is killing the Rails process [after 60 seconds](https://github.com/quintel/etmoses/blob/e213e4693b0859d942a93aa6facc1ae5b508f084/config/unicorn/production.rb#L11).

Assigning to me.

**Comment by ChaelKruip** [comment]
@antw does this still happen with the new background loader?

**Comment by antw** [comment]
>  does this still happen with the new background loader?

Nope; closing!
