### ISSUE TITLE
Adding heat-demand to interface of et-moses

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#636]
Either:

- adding the graph as a loose tab, 

![screen shot 2015-11-30 at 4 08 21 pm](https://cloud.githubusercontent.com/assets/2676542/11475896/1e4963c2-9780-11e5-9412-33630e96bd98.png)

(Don't mind the content)

- solve the problem the same way the gas-chart is now solved. By adding a new color to the legend of the current chart. 

Including @ChaelKruip

**Comment by ChaelKruip** [comment]
The important message to take away from the heat chart is the possible mismatch between supply and demand of heat. Although both supply and demand of heat can be expressed in kW (and thus would fit naturally in the load chart) I feel that they convey information that is different from a 'load on the network'.

I would, therefore, opt for a separate tab. Another advantage of a separate tab could be performance (right @grdw ?)

**Comment by grdw** [comment]
> Another advantage of a separate tab could be performance 

Well it's a possible disadvantage. It will be another D3 chart that needs to be loaded into the DOM. We could also load it as soon as somebody clicks the tab instead of 'loading everything' -> 'hide irrelevant content' -> 'show content whenever somebody clicks on it'.

**Comment by grdw** [comment]
> Another advantage of a separate tab could be performance  

Right now the performance is not much of a problem. Yes, the calculation itself can still be slow at times but the front-end is now faster since the resolution changes.

**Comment by grdw** [comment]
How is the heat demand profile going to be calculated? I now fill it with a set of random numbers (would be wrong right?).
