### ISSUE TITLE
Building P2H should be equivalent to adding a resistive heater to a buffer

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#640]
Before we had buffers, we modelled P2H as a resistive heater + a buffer. Now that we have both buffers and resistive heaters in the technology matrix, we should model P2H as such. 

Essentially, we could remove P2H from the technologies.

@jorisberkhout @antw @dennisschoenmakers do you agree with my reasoning?

**Comment by jorisberkhout** [comment]
I like it!

One question though, how are we going to link this to the ETM?

**Comment by ChaelKruip** [comment]
> One question though, how are we going to link this to the ETM?

Good question. If someone builds a P2H unit in the ETM, that is equivalent to buying a buffer tank and a cheap resistive heater. In ETMoses every household has two buffers (which can be given a zero volume). I think that all P2H units from the ETM should be translated into `households_space_heater_electricity` units that are coupled to the hot water buffer.

Also see https://github.com/quintel/etmoses/issues/626
