### ISSUE TITLE
Name does not show up correctly in warning

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#642]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11500262/4d50c37a-982c-11e5-9cd4-18c5060c3456.png)

**Comment by grdw** [comment]
It's because most users don't have a name... They should be able to edit that though or a simpler fix would be to display an email address and remove the name column.

**Comment by ChaelKruip** [comment]
> a simpler fix would be to display an email address and remove the name column

Or display the email address only if there is no name

**Comment by antw** [comment]
There are privacy implications to displaying an e-mail address publicly, and [our privacy policy](http://et-model.com/privacy) is quite explicit that they're only used to associate users with their scenarios.

I would suggest adopting the name "Anonymous" if a user does not have a name, or perhaps display a different version of the warning message: "You are now editing someone else's LES".

**Comment by ChaelKruip** [comment]
> There are privacy implications to displaying an e-mail address publicly, and our privacy policy is quite explicit that they're only used to associate users with their scenarios.

Good point!

> I would suggest adopting the name "Anonymous" if a user does not have a name

I like!

**Comment by grdw** [comment]
> display a different version of the warning message: "You are now editing someone else's LES".

This has my preference :+1:
