### ISSUE TITLE
What to do with the capacity constraints of the network when cancelling excess and storage potential?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#65]
Say we have the following situation: the neighbours (they share a connection) have enough storage potential (5) to store their excess (5) but the node that connects them to each other **and** the rest of the network has too small a capacity:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7064815/ff1f270c-deb1-11e4-922a-b6b8a80ce085.png)

There a two ways to go about this:
1. Interpret the connecting node (which is likely a transformer of some kind) as the literal connection that is portrays in the network. In that case, we must limit the amount of excess that can travel between neighbours with the capacity of the node
2. Interpret the connecting node as the connection to the rest of the network but not as the connection between neighbours. This is more realistic in a sense as the neighbours are in reality often connected to a single cable which is, in turn, connected to the rest of the network through the transformer:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/7065393/94324266-deb7-11e4-82b8-890d4cf54428.png)
In that case, the cables between neighbours are what will possibly restrict the flow of excess. We can build such a topology in Ivy:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7065548/3510d64c-deb9-11e4-9d7f-9b721c0ee3c7.png)
but I don't think we will use such **serial** topologies often but I also think that we should allow for them to be used. The expected behaviour for serial topologies (at the connection level) will be described in https://github.com/quintel/etloader/issues/64

I feel that 1. is more consistent (we take the topology literally) and also provides a worst-case scenario as the transformer are usually dimensioned to be of lower capacity than cables.
If the user wants to study the behaviour of 'serial' topologies he/she should build them explicitly (see #64).

For 1. the expected behaviour is that only the excess that 'fits' through the connecting node (3) is stored. Letting the excess flow maximally, the connecting node has 0 capacity left, the battery stores 3 and has 2 left:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7065786/a31a257e-debb-11e4-9897-4c9c763c9e45.png)

**Comment by ChaelKruip** [comment]
@dennisschoenmakers @antw does the above make sense to you as well?

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers @antw does the above make sense to you as well?

I would also go for **1)** for the time being.
