### ISSUE TITLE
Progress bars should indicate what the user is waiting for

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#650]
There are a lot of Javascript solutions for this. 
Point being, to track things happening in Javascript.

- So I could determine that it's currently fetching the current load-chart (yes / no).
- Than if it's fetching the load-chart with strategies. (yes / no).

I can't determine which node it is currently calculating or really specific details, without losing a lot of time on the requests that would actually determine that (which in my eyes - defeats the purpose of a progress bar).

I am going to look if the background processor in question `delayed_job` has a method or extension that allows to determine the 'progress' . 

##### Delayed Job and an actual progress bar

I took some time investigating if `delayed_job` had some way to determine progress. There's `progress_job` but you have to specify manually (in steps of x) how far you are to a 100. And I don't think that can be easily said (for example: does pull consumption equal 10% of the time, 20% of the time?).
So an actual bar which goes like the sketch below, is going to be off the table unless somebody's going to say something really smart right now?

````
0% [##############                                ] 100%
````

The reason for that is that it's hard to determine when you are at 50% or 56%. You can maybe describe it in bytes or guess how long previous calculations took etc. etc. But it's all relative and takes more time to implement than that there will actually be any signficant information coming from that progress bar.

##### Or just plain status updates

Something simpler would be to say 'the server is currently calculating load' and 'the server is currently calculating the load with strategies'. That would be do-able in short time. It would also be possible to determine if the data is being fetched directly from the cache or if it's actually calculated.

**Comment by ChaelKruip** [comment]
> Or just plain status updates

I think this is fine for now. Given the time, I would go for a very simple (half day) approach @grdw

**Comment by grdw** [comment]
![screen shot 2015-12-08 at 4 22 16 pm](https://cloud.githubusercontent.com/assets/2676542/11659308/e3e07380-9dc7-11e5-9c22-974d5682eb7b.png)

Right now it's something like this.

**Comment by ChaelKruip** [comment]
:+1:
