### ISSUE TITLE
Difference between 'save' / 'save all and view less' button is unclear

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#652]
As reported by @JeroenvdLogt

**Comment by ChaelKruip** [comment]
Assigning to @grdw

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can you explain what you find confusing about the current situation?

![etmoses](https://cloud.githubusercontent.com/assets/1303760/11952020/bc31408e-a895-11e5-9483-b6584daeb57c.png)

**Comment by JeroenvdLogt** [comment]
Saves save mean that only the market model is saved (if you were working on that) or is the complete LES saved. And does this mean that the original marketmodel will be overwritten?

**Comment by ChaelKruip** [comment]
> Saves save mean that only the market model is saved (if you were working on that) or is the complete LES saved. 

* 'save' means that the current tab which you are editing is saved
* 'save all and view LES' means that all tabs are saved and you are taken to the 'view' page

> And does this mean that the original marketmodel will be overwritten?

What do you mean by 'original' here? 

* If you have edited the market model, 'save' will save your changes if you are on the market model tab. 
* If you have edited the market model, 'save all and view LES' will save your market model regardless of the tab you are currently viewing
* if you have not edited the market model it will not be saved (there is no need to save it) and it will stay unchanged
