### ISSUE TITLE
Are Investment costs rightly calculated?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#653]
As reported by @JeroenvdLogt. 

@JeroenvdLogt can you post your validation numbers here?

It is about this LES: http://beta.moses.et-model.com/testing_grounds/383

**Comment by dennisschoenmakers** [comment]
Apparently, the business case on beta is not recalculated, after you have updated the topology.

**Comment by dennisschoenmakers** [comment]
@grdw can you check this out?

**Comment by antw** [comment]
The DelayedJob workers have stopped running (again). I'm not sure why, but I'll start them up again shortly and will make a note to look into it.

**Comment by antw** [comment]
I retract my previous statement. :grimacing: A `delayed_job` process is present; I thought there would be more than one worker, but perhaps it isn't configured like that? Either way, I guess DelayedJob is not the culprit.

**Comment by JeroenvdLogt** [comment]
![image](https://cloud.githubusercontent.com/assets/7781037/11660991/fcced118-9dcf-11e5-884c-ac9a03047efe.png)

**Comment by dennisschoenmakers** [comment]
We'll try to resolve this asap tomorrow, @JeroenvdLogt

**Comment by grdw** [comment]
Hmm, changing the name of the market model triggers a recalculation (added a whitespace).

**Comment by grdw** [comment]
Allright what I can see. These are the nodes that contain valid information for the initial investment costs (being nodes that contain `investment_cost`, `stakeholder` and `economic_lifetime` / `technical_lifetime` attributes):

````yaml
- - MSR veld B
  - system operator
  - :liftime: 1
  - :investment_cost: 126900.0
  - :yearly_o_and_m_costs: 0.0
- - LS cable veld B
  - system operator
  - :liftime: 1
  - :investment_cost: 117450.0
  - :yearly_o_and_m_costs: 0.0
- - MS cable veld stresstest
  - system operator
  - :liftime: 1
  - :investment_cost: 110000.0
  - :yearly_o_and_m_costs: 0.0
- - Overige MSR stresstest
  - system operator
  - :liftime: 1
  - :investment_cost: 103400.0
  - :yearly_o_and_m_costs: 0.0
- - LS cable overige MSR stresstest
  - system operator
  - :liftime: 1
  - :investment_cost: 95700.0
  - :yearly_o_and_m_costs: 0.0
- - MSR stresstest
  - system operator
  - :liftime: 1
  - :investment_cost: 9500.0
  - :yearly_o_and_m_costs: 0.0
- - LV veld 1
  - system operator
  - :liftime: 1
  - :investment_cost: 2170.0
  - :yearly_o_and_m_costs: 0.0
- - LV veld 2
  - system operator
  - :liftime: 1
  - :investment_cost: 2170.0
  - :yearly_o_and_m_costs: 0.0
- - LV veld 5
  - system operator
  - :liftime: 1
  - :investment_cost: 1835.0
  - :yearly_o_and_m_costs: 0.0
- - LV veld 6 stresstest
  - system operator
  - :liftime: 40
  - :investment_cost: 2637.0
  - :yearly_o_and_m_costs: 0.0
- - MSR veld J
  - system operator
  - :liftime: 1
  - :investment_cost: 89300.0
  - :yearly_o_and_m_costs: 0.0
- - MSR veld L
  - system operator
  - :liftime: 1
  - :investment_cost: 117800.0
  - :yearly_o_and_m_costs: 0.0
````

This is when completly ignoring all the technologies that are attached to this (so calculations for `Customer Ac1a` are left out of this example).

Which results in:

````ruby
{"system operator"=>776290.925}
````

**Comment by JeroenvdLogt** [comment]
Does this mean the problem is solved?

**Comment by grdw** [comment]
@JeroenvdLogt I didn't change the lifetime (from 40 to 1) yet, for that specific node of the topology in your LES. I was more trying to ask if that could be the reason why the investment costs were calculated wrongly?

**Comment by JeroenvdLogt** [comment]
@grdw I cannot pinpoint the problem. Yesterday I tried at least 10 different configuration that din't seem to had any effect at all on the business case (investment cost especially). For now it looks like everything works allright.
