### ISSUE TITLE
Gasinfrastructure cost

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#654]
Hereby a gist of average gasnetwork cost in Gist. The cost of refrubishing will follow soon
<script src="https://gist.github.com/JeroenvdLogt/bb6331ea52a0a386c6fc.js"></script>

**Comment by JeroenvdLogt** [comment]
<script src="https://gist.github.com/JeroenvdLogt/bb6331ea52a0a386c6fc.js"></script>

**Comment by JeroenvdLogt** [comment]
<script src="https://gist.github.com/JeroenvdLogt/bb6331ea52a0a386c6fc.js"></script>

**Comment by JeroenvdLogt** [comment]
Mmm cannot upload a gist. I will send it to Chael
https://gist.github.com/bb6331ea52a0a386c6fc.git

**Comment by JeroenvdLogt** [comment]
https://gist.github.com/JeroenvdLogt/bb6331ea52a0a386c6fc

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can you put this is a table please?
This works basically as follows:

|Connection type|Tariff|
|---|---|
|bla|bla|

And could you translate all text into English as well?

**Comment by JeroenvdLogt** [comment]
I changed it to table form. I still have to add cost of refurbishing.
https://gist.github.com/JeroenvdLogt/bb6331ea52a0a386c6fc

**Comment by JeroenvdLogt** [comment]
Can I upload excel files or csv. I made the tables manually now but this takes a lot of time.

**Comment by ChaelKruip** [comment]
@JeroenvdLogt I have corrected some errors in the syntax of the Markdown (you can check how your Markdown document formats by using a dedicated editor such as [http://markdownpad.com/](http://markdownpad.com/). 

Can you check that I did not introduce any mistakes? [The updated file](https://github.com/quintel/documentation/blob/master/etmoses/average_cost_of_gas_infrastructure.md)

**Comment by ChaelKruip** [comment]
@JeroenvdLogt what is the status of this ticket?

**Comment by JeroenvdLogt** [comment]
Only the headers of the first table is in dutch. The rest of the gist is okay.

**Comment by ChaelKruip** [comment]
OK, thanks @JeroenvdLogt. Closing.
