### ISSUE TITLE
Issues with the new technology editor

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#661]
I have merged the new technology editor and gas network into master (*not* deployed to staging), but there are some minor "niggles" still occurring. I'll note them here, but I can split this into separate issues if preferred.

* **I can't add certain technologies to an existing LES.** I can *delete* and edit technologies successfully. Strangely, some technologies *can* be added: 

  Can be added:
  * Battery
  * Power-to-gas

  Cannot be added:
  * Buffer space-heating
  * Buffer hot water
  * Household
  * Building
  * Electric vehicle
  * Other
  * Residential PV panel 

  It seems that I *can* import a new LES with these technologies, but I cannot add them manually to an existing LES.

* **Adding a household technology shows two profile select boxes:**

  ![screen shot 2015-12-09 at 18 06 21](https://cloud.githubusercontent.com/assets/4383/11695009/edbeb96a-9ea4-11e5-80de-c66b3129ac0f.png)

* **Using the default topology, if I add a battery or power-to-gas to the "Households 2" endpoint, the technology is instead added to "Households 1"**. This only seems to affect existing testing grounds; technologies are assigned to Households 2 and 3 *and successfully saved* when importing a *new* LES.

**Comment by grdw** [comment]
>  Adding a household technology shows two profile select boxes:

You should change the `units` field for some duplication fun:

![screen shot 2015-12-10 at 8 57 10 am](https://cloud.githubusercontent.com/assets/2676542/11709959/05b0f124-9f1c-11e5-8c31-766c98b0dcbe.png)

:sweat_smile: 

I'll look into the issues though.

**Comment by grdw** [comment]
> I can't add certain technologies to an existing LES. 

"but I cannot add them manually to an existing LES."

Do you have an exmample LES?
Or what do you mean by 'added'. Does that mean, that the template does pop-up but it doesn't add it to the `technology_profile` in the database?

> Adding a household technology shows two profile select boxes: -> fixed

> Using the default topology, if I add a battery or power-to-gas to the "Households 2" endpoint, the technology is instead added to "Households 1"

I still need to look into this one.

**Comment by antw** [comment]
> You should change the units field for some duplication fun:

:laughing:

> Does that mean, that the template does pop-up but it doesn't add it to the `technology_profile` in the database?

Yes exactly. The UI works fine, the data is sent to the Rails app correctly, but the TestingGround doesn't get saved.

I have found the reason: it appears the load profile key is being duplicated before it is sent from the browser to the Rails app. The TestingGround validation fails with a message such as:

```
"has an unknown load profile: ev_availability_profile_1_3.7_kwev_availability_profile_1_3.7_kw"
```

> Eh, maybe you could give an example LES here aswell? I'm trying really hard to break it though.

1. Grab a copy of the staging database, import it locally, and run the migrations.
2. Visit http://MOSES_URL/testing_grounds/372/edit
3. Add a Battery to "Households 2" and press "Save".
4. Refresh the page. The battery has appeared on "Households 1".

**Comment by grdw** [comment]
Thanks!

**Comment by grdw** [comment]
> "has an unknown load profile: ev_availability_profile_1_3.7_kwev_availability_profile_1_3.7_kw"

I found it. Wrong jQuery selector,, again.
