### ISSUE TITLE
Questions about the hybrid heat-pump

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#667]
@ChaelKruip Time permitting, can you provide a short description of the expected behaviour of the hybrid heat pumps? I cannot find any documentation on GitHub that describes them (maybe there's some elsewhere I missed?), and I'm having some difficulties. :anguished: 

I understand the basics: demand is satisfied by the electrical component until the network becomes congested, at which point the gas component becomes active.

However, the following questions have emerged during my work so far:

* Does each component have a separate `capacity`? For example, if the HHP has a capacity of 5kW and the electrical component is using 2kW, does that mean that the gas component may run at up to 3kW? Or do the separate components have their own, independent capacities?

  So far I have assumed the former, but the latter might be substantially simpler to implement. The Node files only define a single `input_capacity`, although I suppose we could derive the capacity of each component fairly easily:

  ```ruby
  V(
    households_space_heater_hybrid_heatpump_air_water_electricity,
    "input_capacity * (electricity_input_conversion + ambient_heat_input_conversion)"
  )

  V(
    households_space_heater_hybrid_heatpump_air_water_electricity,
    "input_capacity * network_gas_input_conversion"
  )
  ```

  I think this is a horribly hacky solution, but *needs must when the devil drives*.

* ETEngine reports the COP of the hybrid heat-pump as as 2.647. The COP is calculated as `1 / 1 - ambient_heat_input_conversion`, which does not account for the fact that only the electrical component uses ambient heat.

  Should the gas component have a hard-coded COP of 1? If that is true, does that mean the COP reported by ETEngine needs adjusting prior to being used by the electrical component?

**Comment by ChaelKruip** [comment]
> I cannot find any documentation on GitHub that describes them (maybe there's some elsewhere I missed?)

Sorry about that. I wrote some [here](https://github.com/quintel/documentation/blob/master/etmoses/hybrid_heat_pump.md) but that needs to be updated to the non-temperature modelling we have chosen for now.

> I understand the basics: demand is satisfied by the electrical component until the network becomes congested, at which point the gas component becomes active.

* The HHP is imported into ETMoses as **two** distinct technologies (the gas-part and the heat pump-part)
* The HP-part is a 'buffering' technology that fills the buffer just like other heat pumps. It does so without regard for possible network congestion unless a special "switch HHPs to gas if congested"-strategy is selected
* The gas-part is a 'boosting' technology which fulfils (part of) the demand if one of the following things happen:
  * The content of the buffer (kWh) plus the production of the heat pump-part (Cap_HP * 0.25 hours) is insufficient to satisfy demand
  * The **capacity** of the buffer is insufficient to provide the heat (even if there is enough kWh stored in the buffer)
  * The network (on or more higher up nodes) is congested and the strategy "switch HHPs to gas if congested" is active
  * The temperature of the LES drops below 4 degrees Celsius (which would in real-life make the COP of the HP go down too much to be economically viable)

> Does each component have a separate capacity?

Yes. The HP-part has a heat (output) capacity of 4.9 kW, the gas-part of 15.0 kW

> I think this is a horribly hacky solution, but needs must when the devil drives.

Sorry you had to demean yourself to this :wink: 

> The COP is calculated as 1 / 1 - ambient_heat_input_conversion

The hybrid heat pump in ETE is modeled as one converter which complicates this a bit. The COP can be calculated reliably as:
```
COP = (ambient_heat_input_conversion / electricity_input_conversion + 1)
```

The efficiency of the gas component is 106.7 % (```output.useable_heat = 1.067```)

Hope that helps!

**Comment by ChaelKruip** [comment]
I think we can close this. Re-open if not.
