### ISSUE TITLE
Question: is it possible to have multiple strategies per technology?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#669]
I think it's now possible to give a `behavior` in the technologies table. But does that result in a single strategy or how sould I interpret this?

**Comment by antw** [comment]
The `behaviour` [maps the InstalledTechnology to the Network class](https://github.com/quintel/etmoses/blob/master/app/models/network/technologies.rb#L16-L25) used to calculate its load. It's not quite the same thing as a `strategy`.

It's a one-to-one map (each technology has one `behaviour` and maps to one Network class), *except* in the case of base loads where the two load profile components – "flexible" and "inflexible" – result in the base load splitting into two technologies. In that case, the `behavior` column in the `technology_component_behaviors` table defines how each part works. 

The Network class may do different things depending on the strategies chosen by the user; for example, the [ElectricVehicle](https://github.com/quintel/etmoses/blob/fcc6d6a131a242c36865f5eac75d956995e7718a/app/models/network/technologies/electric_vehicle.rb#L13-L14) cares about both the `buffering_electric_car` and `solar_storage` strategies, and will behave slightly differently depending on which of those are enabled.

**Out of interest**, what prompted this question? Something to do with the hybrid heat-pump, or...?

**Comment by grdw** [comment]
> Out of interest, what prompted this question? Something to do with the hybrid heat-pump

Yes. :+1:  We (@ChaelKruip and I) wanted to know what the default behavior would be.

**Comment by antw** [comment]
I'm adding new Network classes to model the hybrid heat-pump, so the two Technology records (one for gas, one for electricity) will have to have a new `behaviour`. Maybe "hhp_electricity" and "hhp_gas"?
