### ISSUE TITLE
Buffer should have two volumes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#670]
The following distinction should be made at some point:

* How much energy we can store in the buffer before the buffering technology switches off: this is equivalent to ```liters_of_water_in_buffer * thermostate_temperature_of_buffer * heat_capacity_of_water```
* How much energy can be in the buffer physically: this is equivalent to ```liters_of_water_in_buffer * max_temperature_of_water * heat_capacity_of_water```

This distinction needs to be made because excess electricity (P2H) should be stored in the buffer up to the point that the buffer doesn't explode. This could lead to much higher temperatures than normally desired when buffering with a heat pump for instance.

**Comment by grdw** [comment]
![screen shot 2015-12-17 at 10 47 29 am](https://cloud.githubusercontent.com/assets/2676542/11866462/95df4cac-a4ab-11e5-9de8-d3bc07dd66db.png)

Let's assume there's a `volume_in_liters` attribute. What would the default be? 
Also how does one go from `volume_in_liters` to `volume` (in kWh)?

**Comment by ChaelKruip** [comment]
This become more important now that we buffer as much as possible by default. Successful buffering would lead to a buffer which is 'full' rendering P2H useless.
