### ISSUE TITLE
Behaviour of buffers could be improved

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#671]
Talking to @grdw I realised that we can make the workings of buffers a bit more transparent for the user if we change the interface somewhat.

Currently, we assign a storage volume to a buffer (kWh). This is not very intuitive to most users who would rather think about a buffer-size in liters. Instead of asking the user for kWh, we could ask for liters and given a (currently fixed) temperature for the buffer, translate liters into kWh.

Do you think this is feasible/a good idea @antw?

**Comment by ChaelKruip** [comment]
Also see https://github.com/quintel/etmoses/issues/670

**Comment by grdw** [comment]
![screen shot 2015-12-17 at 3 02 35 pm](https://cloud.githubusercontent.com/assets/2676542/11871344/42ad40a6-a4cf-11e5-8e05-daf6884dadd9.png)

**Comment by antw** [comment]
> Currently, we assign a storage volume to a buffer (kWh). This is not very intuitive to most users who would rather think about a buffer-size in liters. Instead of asking the user for kWh, we could ask for liters and given a (currently fixed) temperature for the buffer, translate liters into kWh.
>
> Do you think this is feasible/a good idea @antw?

I think this makes sense for space and water heating. Does it also make sense for buffers in the gas and electricity networks? We don't have gas buffers yet – but probably will soon – and electricity buffers are standalone technologies (P2P/EV), but it would be nice if we had a system flexible enough to choose the correct volume *unit* depending on the technology.

**Comment by ChaelKruip** [comment]
> Does it also make sense for buffers in the gas and electricity networks?

For electricity not. For gas maybe. 

> but it would be nice if we had a system flexible enough to choose the correct volume unit depending on the technology

After discussing this with @grdw we feel that `volume` should be reserved for energy [kWh]. This is a relevant unit for heat, gas and electricity. The 'size' of the buffer could depend on the carrier. For electricity I think kWh is the only relevant measure but for heat `liters` makes sense. For gas it might be that `cubic_meters` is a relevant measure of `size`.
