### ISSUE TITLE
Heat demand and hot water profiles should only have a use profile

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#672]
They currently have availability as well:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11742216/44ddb9a8-9ffe-11e5-878c-9637a9eba7a7.png)

**Comment by antw** [comment]
This is the case for the old heat pump profiles. A migration has already been written which will deprecate these profiles, and the new "use" profiles can then be uploaded. I think this can be closed.
