### ISSUE TITLE
Profile database should include demand profiles for hot water and space heating 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#673]
Instead of 'heat pumps':
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11742237/796f607c-9ffe-11e5-823c-94da3d652379.png)

**Comment by antw** [comment]
[Already done](https://github.com/quintel/etmoses/blob/c1493d8c16a203f9f39005dfb998c302c6f915db/db/migrate/20151209171445_add_load_profile_categories_for_composites.rb) :smiley:

**Comment by ChaelKruip** [comment]
:+1:
