### ISSUE TITLE
Question: switching hybrid heat pump to gas by temperature or a more general profile?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#675]
We want to have HHPs switching from electricity to gas if the outside temperature drops below a threshold value (say 4 degrees).

We could upload a temperature curve and set a threshold in ETMoses but I am asking myself if we should not make this behaviour more general (and simpler to implement) by allowing the user to upload and choose a profile with 0's and 1's for when the HHP should switch. That way, the behaviour can be anything (including temperature) but ETMoses does not have to 'know' this.

@antw @grdw what do you think?

**Comment by antw** [comment]
0's and 1's is a nice idea since it could be described as "this technology is turned off" and "this technology is turned on". This could be applied to *any* technology, not just the HHP.

**Comment by ChaelKruip** [comment]
> This could be applied to any technology, not just the HHP.

Yes! For now we can focus on the HHP but I very much like the suggestion.

**Comment by ChaelKruip** [comment]
Closing this as we have decided to use 1s and 0s.
