### ISSUE TITLE
Rename " Electrical capacity [kW]" to " Output capacity [kW]"

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#677]
Electrical capacity doesn't make sense for gas technologies. Moreover the output capacity is what's more intuitive 

Also for the sake of lines: https://github.com/quintel/etmoses/blob/master/app/assets/javascripts/les/profile_select_box.js#L38-L40

**Comment by antw** [comment]
> Moreover the output capacity is what's more intuitive

I think it's the other way around: the electricity or gas capacity is an *input* capacity. The *output* capacity is what we currently simply call `capacity`: that is the input/electrical/gas capacity multiplied by the `performance_coefficient`.

I think to avoid confusion we could call it `carrier_capacity`. There is a new `carrier` attribute which defines the type of energy used by the technology (electricity or gas), so I think this would fit quite nicely.
