### ISSUE TITLE
capacity, input_capacity, output_capacity, electrical_capacity and other confusion

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#680]
Currently, the front-end shows something called the "electrical capacity" [kW]:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11744742/675d701c-a013-11e5-9ee3-ecf33ddb5193.png)

This made sense when the only thing we cared about was electricity but now we also have gas and heat.

A technology has in input capacity (one per input carrier) and an output capacity and one output capacity (we don't have multiple outputs for the same technology yet, but beware of CHPs). Input capacity, C_in, and output capacity, C_out, are related by efficiency (for normal technologies) or COP (for heat pumps):

```
C_out = eff * C_in
```
or, for heat pumps,
```
C_out = COP * C_in
```
where C_in in the latter case is the input capacity of electricity.

I think it makes sense to show the user the **output capacity** in the front-end (and make him/her edit that, and optionally the efficiency or COP). This is the 'name plate' capacity of the technology and is what people usually refer to when talking about it.

## Proposal

* Rename "electrical capacity [kW]" into "output capacity [kW]"
* Rename "Coefficient of performance" to "COP/efficiency" to be more general

@antw @dennisschoenmakers @jorisberkhout I'd like to know what you think about this suggestion!

**Comment by antw** [comment]
> Rename "electrical capacity [kW]" into "output capacity [kW]"

[Said it here](https://github.com/quintel/etmoses/issues/677#issuecomment-163937493), but I'm not sure I understand the choice of *output* capacity: a consumption technology takes electricity as *input* and then multiplies it by the COP to get the output.

It *does* make sense to me in the context of production technologies (solar PV), so I think the choice of name is not clear cut.

Since each technology has a carrier (currently "electricity" or "gas"), couldn't the UI adapt to this, and show "Electrical capacity" and "Gas capacity" as appropriate? In the backend we could just call it "carrier_efficiency".

> Rename "Coefficient of performance" to "COP/efficiency" to be more general

:+1:

**Comment by grdw** [comment]
> couldn't the UI adapt to this, and show "Electrical capacity" and "Gas capacity" as appropriate? 

What I said to Chael in person. ;) 

> In the backend we could just call it "carrier_efficiency".

Sound good to me! :+1:

**Comment by jorisberkhout** [comment]
> I think it makes sense to show the user the output capacity in the front-end (and make him/her edit that, and optionally the efficiency or COP). This is the 'name plate' capacity of the technology and is what people usually refer to when talking about it.

I agree with @ChaelKruip here. When selecting a heating system for your house, the output capacity is the most relevant parameter as you this needs to be high enough to be able to meet your heating demand.

In addition, specifying the output capacity makes it easier to compare different heating technologies.

**Comment by dennisschoenmakers** [comment]
> @antw @dennisschoenmakers @jorisberkhout I'd like to know what you think about this suggestion!

I agree with @ChaelKruip as well. If you buy a gas heater for hot water, you also buy a 30kW thing. That is output capacity, and let's keep everything equal. :smiley:

**Comment by antw** [comment]
> In addition, specifying the output capacity makes it easier to compare different heating technologies.

That's fine, and I agree, but what I mean is that what we currently call `electrical_capacity` is actually an input capacity. The proposal is to rename this to "output capacity" which doesn't seem accurate to me. We take the electrical capacity, multiply it by the performance coefficient (to factor in the useable heat which isn't modelled in Moses) and then produce an output.

* `electrical_capacity` → `electrical_input_capacity` / `carrier_capacity`
* `capacity` → `output_capacity`

I approve of showing the output capacity to the user; but the output capacity of a heat pump is what we currently call `capacity`, not `electrical_capacity`.

**Comment by ChaelKruip** [comment]
> I approve of showing the output capacity to the user; but the output capacity of a heat pump is what we currently call capacity, not electrical_capacity.

Thanks for clarifying @antw. I think we all agree then!
