### ISSUE TITLE
Interface does not allow me to create new technologies for some end-points

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#681]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11745039/703484bc-a015-11e5-9e23-7387d17ccd18.png)

[This LES](http://beta.moses.et-model.com/testing_grounds/388/edit)

There are no 'add' buttons! Am I doing something wrong?

**Comment by antw** [comment]
The screenshot is cut off at the bottom so it's hard to tell, but there should be a drop-down like this:

![screen shot 2015-12-11 at 13 43 48](https://cloud.githubusercontent.com/assets/4383/11745071/3dce91d2-a00d-11e5-9e6e-cc4a80d283dc.png)

**Comment by antw** [comment]
Maybe it could be made to stand out more?

![screen shot 2015-12-11 at 13 46 46](https://cloud.githubusercontent.com/assets/4383/11745126/a7041122-a00d-11e5-8ea0-7a7b547fec0e.png)

**Comment by ChaelKruip** [comment]
Oh, right! You have to scroll down to add a new technology! Hm... we'll think about that later :smile:
