### ISSUE TITLE
Changing the number of heat pumps changes their electrical capacity and results in zero load

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#685]
As observed in http://beta.moses.et-model.com/testing_grounds/389.

Every time I change the number of `heat pumps for space heating (air)` connected `buffer space heating #1` in this LES, the `Electrical capacity [kW]` is changed from `4.4 kW` to `2.22222 kW` and the corresponding load chart did not show any load at all. Manually changing the capacity back to `4.4 kW` resolved this issue.

I see similar behaviour for the `Heat pump for space heating (ground)` in which case the electrical capacity is changed to `2.08333 kW`. Changing it back to `4.4 kW` resolves the issue.

The heat pumps for hot water (air and ground) follow similar behaviour. In both of these cases the electrical capacity is changed from `4.4 kW` to `3.3 kW`.

Assigning @ChaelKruip. Please re-assign if necessary.

**Comment by ChaelKruip** [comment]
Assigning to @grdw 

Could it be that the 'update-action' is still linked to electrical_capacity.

**Comment by grdw** [comment]
> Could it be that the 'update-action' is still linked to electrical_capacity.

No, because that's not merged yet. I'll look into it.

**Comment by grdw** [comment]
@jorisberkhout 

How would I do this exactly?

1. I have an existing LES with no technologies. 
2. I add a buffer and a heat pump.
3. I change the units of the heat pump

But nothing much happens to the electrical capacity. Is this when you import an existing scenario and than fiddle with the units?

**Comment by ChaelKruip** [comment]
This happened on Chrome. Perhaps the browser matters?

**Comment by grdw** [comment]
Maybe it could be related to the "Save all and view LES" bug? Since that button didn't save any changes to the technologies form before https://github.com/quintel/etmoses/commit/a2fc62eabf39fe373a6f8cd8a1e3d10906d5faec.

**Comment by ChaelKruip** [comment]
> Maybe it could be related to the "Save all and view LES" bug? Since that button didn't save any changes to the technologies form before a2fc62e.

Could be. Can you check that @grdw?

**Comment by grdw** [comment]
Oh crap. I think I know what this is. 

https://github.com/quintel/etmoses/pull/682/files#diff-24aa26b990635ba72f69c523f7da6f2bR53

It has to do with this line. It's still in the pull request. I'll cherry-pick the commit out of the PR.

**Comment by grdw** [comment]
*Allow me to explain:*

Everytime you change the select-box of a technology, a 'hidden' piece of HTML get's updated. The only problem being that it didn't clear out the old values. So the default select-box state was "Battery" . The capacity of a Battery is 4.4. If you changed to 'Baseload', your capacity would still be 4.4. This is because it didn't clear the hidden peice of HTML before changing the values. It now does, so I think [that](https://github.com/quintel/etmoses/commit/f7561abe86a3a2dc1bff2a4941e36ee013ed78b1) resolved this problem. 

@jorisberkhout can you confirm?

**Comment by jorisberkhout** [comment]
Thanks for the explanation, @grdw . This seems to be the solution to part of the problem. Each time I add a new heat pump it capacity is set to `4.4 kW` (which is the wrong capacity). If I then change the number of units, the capacity is set to the correct capacity (`2.2 kW`, `2.0833 kW` or `3.3 kW` depending on the type of heat pump).

**But** once the capacity is changed to the correct value, the load is no longer calculated (resulting in zero electrical load on node Households 1). Is this resolved with your fix, @grdw ?

**Comment by grdw** [comment]
I did notice some capacity issue. This had to with `electrical_capacity` and `electrical-capacity` notice the `-` and `_`. I saw that after importing a scenario and saving it, all my capacities where blanked. This fixed that problem and maybe also your capacity issue.

**Comment by grdw** [comment]
@jorisberkhout could you maybe check again if the loads are correct (they are calculated though but I don't know if they're correct)?

**Comment by jorisberkhout** [comment]
Looks correct to me, @grdw ! Thanks for resolving this. Closing this issue.
