### ISSUE TITLE
Removed technologies keep re-appearing when I edit the LES

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#686]
As observed in http://beta.moses.et-model.com/testing_grounds/390 which I created from scenario 452533 on beta.pro.et-model.com.

I removed all technologies connected to node `Households 3` and saved the LES by hitting the `Save all and view LES` button. There is, however, still load on node `Households 3`. When I edit the LES, the technologies connected on Households 3 are back again.

Assigning @ChaelKruip . Re-assign as you see fit.

**Comment by ChaelKruip** [comment]
Assigning @grdw.

Perhaps this is related to the (sometimes) failing 'save all' button?

**Comment by grdw** [comment]
Yep, this one I can reproduce! :) I'm guessing it has to do with the failing.
