### ISSUE TITLE
`Om costs` sounds a little cryptic to me

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#687]
As observed in the `Toggle advanced` menu for technologies when editing a LES.

<img width="814" alt="screen shot 2015-12-12 at 17 47 13" src="https://cloud.githubusercontent.com/assets/4669028/11762964/c1663fea-a0f8-11e5-8786-e5814471b665.png">

`Om costs` sounds a little cryptic to me. I would say `O&M costs` would be better.

Assigning @ChaelKruip to decide if this is important enough to fix.

**Comment by ChaelKruip** [comment]
Assigning @grdw to change "Om" into "O&M"
