### ISSUE TITLE
Buffering strategy re-appears after editing a LES

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#690]
In the following LES http://beta.moses.et-model.com/testing_grounds/389, I noticed that the strategy `Buffering of heat in heat pumps` keeps being switched back on after I edited the LES. Here what I do, step-by-step:

- I open http://beta.moses.et-model.com/testing_grounds/389
- I switch the `Buffering of heat in heat pumps` strategy off (it is on by default)
- I edit the LES, hit `Save` followed by `Save all and view LES`
- When viewing the LES, the `Buffering of heat in heat pumps` is switched on again

The previous behaviour is only there for this particular strategy. If I switch on or off any of the other strategies, they stay switched on or off.

After discussing with @ChaelKruip  assiging @grdw.

**Comment by grdw** [comment]
The strategies are not saved. Don't know why. But I'll look into it tomorrow.

**Comment by grdw** [comment]
On a related note: #660

**Comment by grdw** [comment]
He now does remember the selected strategies. So I'll close this for now :)
