### ISSUE TITLE
The whole broad behavior profile issue

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#691]
The front-end is now ready.

*The way it is:*
The new page of the testing ground (after import) doesn't show you the behavior profile. It's not necessary to make a user already pick something which he might not even need. Instead it's available at the edit page under general after creating the testing ground.

There's still nothing done with the profile itself. It's uploaded to the `profiles` table which is a rename of the `price_curves` table + an extra `type` column for STI.

This is in the now 2 pull requests #682 and #689. 

---

Todo:

- [x] Actually doing something with the behavior profile
- [x] Toggling between gas and electricty `(1/0)` for the behavior profiles

As explained by @ChaelKruip over the phone. 1 means 'gas is on' and 0 means electricity is on except if there's a strategy which says otherwise.

Also including @antw.

**Comment by antw** [comment]
> Actually doing something with the behavior profile
> Toggling between gas and electricty (1/0) for the behavior profiles

Both of those have been implemented. :smiley: Handy to know that 1 means gas and 0 means electricity. I had it the other way around. Will fix.

**Comment by ChaelKruip** [comment]
@antw just to be sure: 

* 1 means gas regardless
* 0 means electricity **unless a strategy says that it should be gas because of congestion**

Right?

**Comment by antw** [comment]
Yes. The gas component can run at all times; the electricity component runs when the value in the profile is `0`.

> unless a strategy says that it should be gas because of congestion

Question: If there is **2kW of available network capacity**, and the **electrical component is rated at 4.9kW**, should the component run at 2kW, or be turned off completely? Currently, the former is true; but swapping to the latter would be a one-line change if you want that instead.

**Comment by ChaelKruip** [comment]
> Currently, the former is true; but swapping to the latter would be a one-line change if you want that instead.

Perfect!
