### ISSUE TITLE
Neighbourhood battery

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#701]
This ticket summarises the changes to be made to add the neighbourhood battery. 

## Front-end

- [x] A new technology must be selectable called 'neighbourhood battery'
- [x] The user should be able to set the % (between 0 and 100) of the battery which is reserved for congestion management. 20% is a good default I think. A slider (integrated in the technology interface) would be a nice-to-have:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11870922/1c35a6e6-a4cc-11e5-95b0-6bb5fde8a8f3.png)
- [ ] Preliminary default values for other properties: capacity = 10kW, volume = 100kWh, investment_cost = 30000 EUR, technical_lifetime = 15 years

## behaviour

[This document](https://github.com/quintel/documentation/blob/master/etmoses/buurtbatterij.md) describes the expected behaviour of the battery.

**Comment by grdw** [comment]
I'm busy with the front-end part for this, though I stumble upon a bootstrap-slider issue. The slider is initialized but the slider can't be dragged (it's just stuck)(tried stripping of a lot of javascript to get it working to no success). I can remember I had a similar problem with the `solar_capping` slider but I can't really remember how I fixed it. :thought_balloon: I'll look into it in a bit more detail tomorrow.

**Comment by grdw** [comment]
I fixed the slider problems :)

> % (between 0 and 100) of the battery which is reserved for congestion management. 20% is a good default I think

How would you call this attribute in one word? `congestion_management_percentage` sounds a bit too 'vague'.

**Comment by ChaelKruip** [comment]
> How would you call this attribute in one word? congestion_management_percentage sounds a bit too 'vague'.

`congestion_reserve_percentage` perhaps?

**Comment by grdw** [comment]
`congestion_reserve_percentage` sound good I guess.

**Comment by grdw** [comment]
Preview:

![screen shot 2015-12-22 at 11 13 36 am](https://cloud.githubusercontent.com/assets/2676542/11953012/111eadaa-a89d-11e5-9dab-ca36836d9a61.png)

**Comment by antw** [comment]
Looking good! :+1:

**Comment by ChaelKruip** [comment]
Nice work @grdw! 

I think we should add an information tooltip right of the slider that explains in more detail what this all means.
