### ISSUE TITLE
Business case does not appear 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#730]
Not when editing but also not in the overview page:

![etmoses](https://cloud.githubusercontent.com/assets/1303760/12418922/ffb00c54-beb2-11e5-8d14-368d9e9ea733.png)

**Comment by grdw** [comment]
![screen shot 2016-01-19 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/2676542/12421197/530fae78-bec1-11e5-9999-525fe7628448.png)

Related database line. The background calculator crashes. Related: https://github.com/quintel/etmoses/issues/706

**Comment by antw** [comment]
There doesn't seem to be any such method on MeritCurveBuilder. It dates back to [this commit](https://github.com/quintel/etmoses/commit/ba041ca4e4a718e711f0f7f57165e022d5825bbb); perhaps it was meant to be `MeritCurveBuilder.new(...).price_curve`?

**Comment by grdw** [comment]
I guess it would be `MeritCurveBuilder.new(...).merit.price_curve`
But I'll change it. :+1: I was a bit confused with another issue that looked quite similar.

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/5941e9af0aa0895f19a0ee45980f69dcf914dbb0
