### ISSUE TITLE
Importing 'set' attributes that are statically defined in ETmoses from ETengine

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#735]
Certain attributes from the ETMoses `technologies` table are static and they should be fetched from ETengine to keep a good separation between the application and the actual data.

Attributes that are defined in ETMoses are:

- volume 
- size (volume in liters)
- demand
- capacity
- (max_bufferable_temperature (for buffers))( ? @ChaelKruip )

--

There are some implications when removing those 3(4) columns and using ETengine instead. The main thing I can think of are the defaults that are set in the front-end. That can be removed aswell. 

--

General overview of things todo:

- [ ] #737
- [ ] Maybe include: https://github.com/quintel/etmoses/issues/700

**Comment by ChaelKruip** [comment]
>  to keep a good separation between the application and the actual data.

What do you mean @grdw?
I think that the main reason is to keep consistency between ETM and ETModel...

> volume (volume in liters)

I think it is good to keep our terms clear: 
* size (liters) is the physical size of a buffer
* volume (kWh) is the storage size of a buffer

> demand
> capacity

I think that these are taken from ETE but please correct me if I'm wrong...

**Comment by grdw** [comment]
> I think that the main reason is to keep consistency between ETM and ETModel...

I think we mean the same. But what I'm trying to say: data / numbers / attributes of carriers is not something which belongs in etmoses.

> I think that these are taken from ETE but please correct me if I'm wrong...

Yes and no. It depends if they're defined (and I'm not sure about those specific attributes). If not it takes a default from the technologies table.

**Comment by ChaelKruip** [comment]
> It depends if they're defined

They should be defined I think. If not, we need to look at why and not simply use a default from the database.

**Comment by grdw** [comment]
> They should be defined I think. If not, we need to look at why and not simply use a default from the database.

Hmm.. I just found out that they are :+1:  only when adding a new technology the attributes for which there are no defaults are ignored. I think I know why.

**Comment by grdw** [comment]
````
+---------------------------------------------------------------------------+------------------+----------------+--------------------------+----------------+
| key                                                                       | default_capacity | default_volume | default_volume_in_liters | default_demand |
+---------------------------------------------------------------------------+------------------+----------------+--------------------------+----------------+
| households_space_heater_heatpump_air_water_electricity                    | 2.22222          |                |                          |                |
| households_space_heater_heatpump_ground_water_electricity                 | 2.08333          |                |                          |                |
| households_water_heater_heatpump_air_water_electricity                    | 3.33333          |                |                          |                |
| households_water_heater_heatpump_ground_water_electricity                 | 3.33333          |                |                          |                |
| households_flexibility_p2p_electricity                                    | 4.4              |                |                          |                |
| households_flexibility_p2h_electricity                                    | 2.0              |                |                          |                |
| buffer_space_heating                                                      | 10.0             |                | 100.0                    |                |
| buffer_water_heating                                                      | 10.0             |                | 100.0                    |                |
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity | 4.9              |                |                          |                |
| households_space_heater_hybrid_heatpump_air_water_electricity_gas         | 15.0             |                |                          |                |
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity | 4.9              |                |                          |                |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas         | 15.0             |                |                          |                |
| congestion_battery                                                        | 10.0             | 100.0          |                          |                |
+---------------------------------------------------------------------------+------------------+----------------+--------------------------+----------------+
````

I'm trying to fetch the numbers from `et-engine` however there are some catches.

- `heat_pumps` capacity are the 'capacity' divided by the cop (as @jorisberkhout managed to tell me)
The number I receive from et-engine is the 'capacity' (so 10) and not the number that's in the table.
- the `congestion_battery`,`buffer_space_heating`,`bufffer_water_heating`,`hybrid_heatpump_*` does not exist in et-engine (or the key is incorrect) - I think Hybrid heatpumps are a special case.

*Incorrect numbers*
- `households_flexibility_p2p_electricity ` capacity is not 4.4 but 1.26 (is this `input_capacity` and `output_capacity` again).
- `households_flexibility_p2h_electricity` capacity is 2 but I receive 1.5789473684210529.

**Comment by grdw** [comment]
I wrote it in a little more detail here: https://github.com/quintel/etmoses/issues/740

I'm closing this issue therefor.
