### ISSUE TITLE
Exporting revised: a look at the technologies and attributes that are exported to ETModel

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#736]
An export takes all technologies that are defined in a LES which are 'exportable' (which means that the `export_to` column must not be blank).

Which in this case are (`<etmoses-key> -> <etmodel-export-to>`):

- `households_solar_pv_solar_radiation -> households_solar_pv_solar_radiation_market_penetration`
- `households_space_heater_heatpump_air_water_electricity -> households_space_heater_heatpump_air_water_electricity_share`
- `households_space_heater_heatpump_ground_water_electricity -> households_space_heater_heatpump_ground_water_electricity_share`
- `households_water_heater_heatpump_air_water_electricity -> households_water_heater_heatpump_air_water_electricity_share`
- `households_water_heater_heatpump_ground_water_electricity -> households_water_heater_heatpump_ground_water_electricity_share`
- `transport_car_using_electricity -> transport_car_using_electricity_share`
- `households_flexibility_p2p_electricity -> households_flexibility_p2p_electricity_market_penetration`
- `energy_flexibility_p2g_electricity -> number_of_energy_flexibility_p2g_electricity`
- `households_flexibility_p2h_electricity -> households_flexibility_p2h_electricity_market_penetration`

**Comment by jorisberkhout** [comment]
Removing milestone as this is not deploy-critical.

**Comment by grdw** [comment]
The following technologies don't have an `export_to` value:

````
["households_collective_chp_biogas",
 "households_collective_chp_network_gas",
 "households_collective_chp_wood_pellets",
 "households_collective_geothermal",
-- [ DOWN HERE ] -------------------------------
 "households_space_heater_combined_network_gas",
 "households_space_heater_district_heating_steam_hot_water",
 "households_space_heater_electricity",
 "households_space_heater_hybrid_heatpump_air_water_electricity",
 "households_space_heater_network_gas",
 "households_water_heater_combined_network_gas",
 "households_water_heater_district_heating_steam_hot_water",
 "households_water_heater_fuel_cell_chp_network_gas",
 "households_water_heater_hybrid_heatpump_air_water_electricity",
 "households_water_heater_network_gas",
 "households_water_heater_resistive_electricity"]
````

**Comment by grdw** [comment]
The fuel cell CHP is currently not enabled in the technology matrix. Should we add an `export_to` attribute anyway or should we leave it blank for now and when we make it visible, add the `export_to` attribute?

@ChaelKruip

**Comment by ChaelKruip** [comment]
> The fuel cell CHP is currently not enabled in the technology matrix. Should we add an export_to attribute anyway or should we leave it blank for now and when we make it visible, add the export_to attribute?

Whatever you think will give us least problems later on. Adding it now will lessen the chance of forgetting to add it later. I don't know if that has some unwanted side-effects though.

**Comment by grdw** [comment]
> Whatever you think will give us least problems later on. Adding it now will lessen the chance of forgetting to add it later.

Yes it does. And stating that it's already rejected from importing and invisible in the front-end I think adding the `export_to` attribute won't do any harm for now 👍
