### ISSUE TITLE
BUG: Date seems to be incorrect?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#738]
![image](https://cloud.githubusercontent.com/assets/104830/12808954/3b8a2b50-cb1b-11e5-8035-d677922f66f4.png)

July or January?

**Comment by ChaelKruip** [comment]
Assigning to @grdw

**Comment by ChaelKruip** [comment]
@grdw was is the status of this?

**Comment by grdw** [comment]
It's in a pull request.
