### ISSUE TITLE
Volume of P2H should be zero (it is connected to a buffer)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#742]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12921063/c9bff358-cf4b-11e5-94b9-3c52c2ed5fd5.png)

**Comment by ChaelKruip** [comment]
@grdw what is the status of this?

**Comment by grdw** [comment]
Not fixed yet. Still need to look into it. It's probably a case of removing `storage.volume` from the `importable_attributes` table.

**Comment by grdw** [comment]
I blanked the `default_volume` field and set it from 9.3 to `NULL`. This causes the volume to be `nil`, not zero. We could explicitly make it zero (if you'd want that) and maybe disable the field from being edited? (Because changing that value doesn't make any sense).

**Comment by antw** [comment]
I think `nil`/`NULL` is the correct choice. The P2H tech itself doesn't have, or need, a volume attribute; only the buffer/composite to which it belongs has a volume.

**Comment by ChaelKruip** [comment]
So, can we close this @grdw?

**Comment by grdw** [comment]
Yes, we can. Just tested to see if production/staging/development acted the same way.
