### ISSUE TITLE
Importing batteries should not give them a warning colour

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#743]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12921113/f29f831a-cf4b-11e5-8f3d-6e5a0f677548.png)

See [this LES](http://beta.moses.et-model.com/testing_grounds/415)

Why are they red BTW?

**Comment by ChaelKruip** [comment]
Once I created the LES I got the following message:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12921171/2d0bc6f8-cf4c-11e5-99d0-52e9f71b6bc3.png)

Batteries shouldn't have a profile anyway right?

**Comment by grdw** [comment]
Hmm.. This has to do with the neighborhood battery. I think we exclude the neighborhood battery from that check but we should also exclude the normal battery.
