### ISSUE TITLE
The business case of my LES only shows up after I edit it

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#745]
But if it was calculable all along... Y U NO SHOW?!
![yuno](https://cloud.githubusercontent.com/assets/1303760/12921562/25d27ea2-cf4e-11e5-8016-83481dcf5e79.png)

**Comment by grdw** [comment]
Y U NO PATIENCE!

**Comment by grdw** [comment]
Hmm.. I'll try to see what I can do. But you expect the *initial calculation* to directly show the business case and not upon refresh, am I right?

**Comment by ChaelKruip** [comment]
> But you expect the initial calculation to directly show the business case and not upon refresh, am I right?

Yes. Don't you? :wink:

**Comment by grdw** [comment]
Well yes. :+1:  but just checking to make sure I understand the issue properly.
