### ISSUE TITLE
When opening scenario 493815 on BETA in ETMoses, it complains

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#746]
The ETM interface tells me that this is a scaled scenario:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/12921944/ca2e4de0-cf4f-11e5-8ea9-c16386674a75.png)

But ETMoses is not convinced:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12921914/a522d962-cf4f-11e5-9566-04537a3e0144.png)

**Comment by antw** [comment]
An ETEngine database migration went awry and I had to re-run it locally and reimport the ETE database.

Your (scaled) scenario was probably created in the 5 minute window when this occurred and was lost when the database was uploaded. The new 493815 scenario is *not* scaled, so Moses is correct.
