### ISSUE TITLE
Solar PV capacity default incorrect

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#750]
When importing directly from et-engine it's -1.6
When adding a new technology it's -1.5

It has to do with the database default but also with the fact that the capacity is ignored in the template parsing.

**Comment by ChaelKruip** [comment]
This exactly the type of problems we hope to remedy with https://github.com/quintel/etmoses/issues/740

**Comment by grdw** [comment]
I've added capacity, demand and volume to be fetched from et-engine if the technology 'allows' it. Which means that the attribute has to be whitelisted. This sounds a little double and probably is something which can be refactored ;) I'm checking to see if it is.

**Comment by ChaelKruip** [comment]
How much time do you need to close this issue @grdw?

**Comment by grdw** [comment]
The simple fix here would be to update the database capacity...., but that's what we are trying to prevent.

**Comment by grdw** [comment]
Fixed with: #814 - temporarily
