### ISSUE TITLE
EV volume is off by a factor of 10000

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#752]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12973466/d2e009ca-d0ac-11e5-8c13-2379a67b3533.png)

**Comment by grdw** [comment]
Hmm, saw this happening yesterday aswell. The value we get from ETEngine is `0.0000096`

This is the literal value from et-engine:

````ruby
"storage"=>{"present"=>{"volume"=>0.02, "decay"=>4.4e-05}, "future"=>{"volume"=>0.02, "decay"=>4.4e-05}}
````

And in our builder we divide that number by 1000 to switch from Wh to kWh according to a comment.

**Comment by antw** [comment]
The ETEngine value was changed from Wh to MWh (for consistency with the rest of the dataset), so to get kWh we now need to multiply by 1000.

**Comment by grdw** [comment]
>  to get kWh we now need to multiply by 1000.

:+1:
