### ISSUE TITLE
It is unclear which capacity is shown in overview page of selected node

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#754]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12973852/ed6fde52-d0af-11e5-9800-3871bb057891.png)

**Comment by grdw** [comment]
Well right now we named all of it `Output capacity`:

![screen shot 2016-02-11 at 11 16 08 am](https://cloud.githubusercontent.com/assets/2676542/12973987/e169a394-d0b0-11e5-9cbc-f3bcb7c2ab81.png)

I already know that that's not the way to go in some special cases and there's already an [issue](https://github.com/quintel/etmoses/issues/737) for it to clean that up. The quick and cheap way to solve this is to be consistent and also call that column `Output capacity`.

**Comment by ChaelKruip** [comment]
> The quick and cheap way to solve this is to be consistent and also call that column Output capacity.

Let's do that for now. Also please round these numbers to fewer digits in the interface (not in the back-end!)

**Comment by grdw** [comment]
![screen shot 2016-03-01 at 11 22 43 am](https://cloud.githubusercontent.com/assets/2676542/13424273/ef57b236-df9f-11e5-9355-da5340351140.png)

Input and output capacity are now shown as two separate fields in the technologies tab.
