### ISSUE TITLE
When changing the concurency it switches from et-engine values to database defaults

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#763]
It sounds a little duplicate to the ears but it will be forgotten.

Part of #740

**Comment by ChaelKruip** [comment]
@grdw can you make an estimate of the time needed for this ticket?

**Comment by grdw** [comment]
Are we talking about this ticket specifically or the global issue #740? This is a little harder than it sounds though, but I can explain in person.

**Comment by grdw** [comment]
All technologies have been moved to yml files. Also when changing concurrency it initializes a new set of `InstalledTechnology` objects. It doesn't guess the values from pre-existing html inputs like the old Javascript version was trying to do. So therefor closing this issue.
