### ISSUE TITLE
Save as name pop-up should only show if no new name is given

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#764]
When you save a LES with a new name, you get a pop up which asks you to provide a new name. This should only happen if you try to save without changing the name in the first place.

**Comment by grdw** [comment]
I get the problem. To rephrase it:

If a LES is named "1 Car" and you rename it "2 Cars" and hit the "Save as" button, don't show the pop-up but name the cloned LES "2 Cars".

**Comment by ChaelKruip** [comment]
> If a LES is named "1 Car" and you rename it "2 Cars" and hit the "Save as" button, don't show the pop-up but name the cloned LES "2 Cars".

:+1:
