### ISSUE TITLE
"Save all and view LES"-button does not save technology table

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#766]
It just show the old LES...

**Comment by grdw** [comment]
Can I get some more info on this; i.e. are you doing something special (or is this only the case for cloned LES's aswell - or something completely unrelated which you did differently). I need a little more. I'm really sorry to keep on repeating that I don't know how to reproduce it. :disappointed:

**Comment by ChaelKruip** [comment]
I get this anytime I use that button after editing a LES in Chrome. Also if just importing a new scenario from ETE. Not only with cloned ones.

**Comment by grdw** [comment]
I can reproduce it on beta but not locally. I can also only reproduce it on beta as follows:

1. Import a scenario
2. Remove all technologies
3. Add one EV to one end-point
4. Save it
5. Hit the edit button
6. Change units to whatever number
7. Kaput

If I however repeat step 5 and 6 it works.

**Comment by grdw** [comment]
I know it's not the most appropriate tag here but I can't "destroy it" locally.

**Comment by grdw** [comment]
Chael could you maybe find the time to test this on some of your LES's? 

I do find that when you remove all technologies and hit "Save all and view LES" button breaks.

**Comment by grdw** [comment]
I found out that the technologies matrix was sometimes not correctly marked as 'editing' which is something the "Save all" button is scanning for. The only odd form was the technology matrix, so I think this should kill off all the issues with the save all and view LES buttons.

If not, please re-open this issue.
