### ISSUE TITLE
Editing the market model or business case should not trigger a new load calculation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#768]
Perhaps the cache is invalidated too conservatively?

**Comment by grdw** [comment]
Linked: https://github.com/quintel/etmoses/issues/695

**Comment by ChaelKruip** [comment]
Putting this on-hold as it is not urgent

**Comment by ChaelKruip** [comment]
Putting this on-hold as it is not urgent

**Comment by grdw** [comment]
I just tested this but it doesn't really work that well.. whenever the `markt_model_id` changes (for instance, you make a change to a market model that isn't yours and it starts cloning) than it still triggers a recalculation.

Also the `save all and view Les` button triggers a save action on the LES itself which causes the cache to flush.

**Comment by grdw** [comment]
Closing, just tested on beta and this is fixed.
