### ISSUE TITLE
Business case compare table colors

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#770]
![screen shot 2016-02-11 at 2 58 42 pm](https://cloud.githubusercontent.com/assets/2676542/12978262/333e8efe-d0d0-11e5-981a-59f4fc15c59a.png)

I think there should be some color to directly detect the differences in the business case compare table. Either between the fact if there's a difference or not or everything above or below €0,00 is colored red/green implying something good/bad. Yet I don't know if paying less/more for something should be perceived to be something good or bad.

**Comment by ChaelKruip** [comment]
> I think there should be some color to directly detect the differences in the business case compare table. 

:+1: 

> I think there should be some color to directly detect the differences in the business case compare table. 

This is the problem. Sometimes more is good, sometimes not. So, I would not do that.
