### ISSUE TITLE
Wrong profile is shown in node overview

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#773]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12978833/c3c86f78-d0d3-11e5-9380-1a2b708f3dd4.png)

but this is a group of 100 houses:

![etmoses](https://cloud.githubusercontent.com/assets/1303760/12978852/d46bd96e-d0d3-11e5-92dd-77540bca7bda.png)

**Comment by ChaelKruip** [comment]
Actually, this the profile which is actually used! The EDSN profile shown in the technology table is never used!

**Comment by ChaelKruip** [comment]
Including @antw

**Comment by antw** [comment]
I can reproduce this by creating a scenario with 300 households, importing into Moses and deleting all technologies except the base load. The drop-down says "edsn_1a", but instead "anonimous_base_load_1" is saved.

If instead, when importing, I change the profile to "edsn_e1b" before saving, that profile *is* saved correctly. When I then try to edit the LES, "edsn_e1**a**" (the default) is selected in the profile `<select>`.

I suspect a bug in the technology editor table.
