### ISSUE TITLE
"Stroring PV in EV" strategy should not lead to bigger peaks

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#775]
This happens in [this LES](http://beta.moses.et-model.com/testing_grounds/424)

![etmoses](https://cloud.githubusercontent.com/assets/1303760/12979147/98961bdc-d0d5-11e5-829c-93df57a50056.png)

**Comment by ChaelKruip** [comment]
I spotted a potential origin for the issue. More EV profiles have been added to the database. Some of these have very high capacities... The cars still appear to have 3.7kW as capacity but perhaps the 'profile default' overwrites this in the calculation?

**Comment by antw** [comment]
This has been fixed. The high-capacity profiles are no longer automatically selected when changing concurrency.
