### ISSUE TITLE
Inconsistent attribute volume for 'transport_car_using_electricity'

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#785]
Was 25 kW is now 20 kW.

Was changed in quintel/etsource@c89c78ceba433afac0dc8ae2d6d8d1a8b0864876

**Comment by ChaelKruip** [comment]
@jorisberkhout I did not realise that this value was updated. Please note that the profiles for EV depend on both capacity and volume of EV need to be updated if such a change is made in ETSource. If you are convinced that this a necessary update, I'll upload new profiles to ETMoses.

**Comment by ChaelKruip** [comment]
This has been resolved right @jorisberkhout?

**Comment by jorisberkhout** [comment]
> This has been resolved right @jorisberkhout?

Correct, the storage volume has been changed back to `25 kWh` in quintel/etsource@8d65405d97ef280b91ea41e60638e96e2041d167.

Closing this issue.
