### ISSUE TITLE
'energy_flexibility_p2g_electricity' capacity inconsistent 

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#788]
Old capacity was 135
And now it is 739.5833

**Comment by ChaelKruip** [comment]
@jorisberkhout can you shed some light on these changes?

**Comment by jorisberkhout** [comment]
The source for the 'old' capacity (i.e. `135 kW`) is described in https://github.com/quintel/etdataset/issues/598#issuecomment-99492739. Subsequent research by @RobTerwel proved that units with larger capacity are currently available and we decided to increase the capacity to `739.5833 kW`.

So, I would say that the capacity is not inconsistent, but has been updated :;):. Closing this issue.
