### ISSUE TITLE
Validate capacities of inidividual parts of hybrid heat pumps

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#789]
The capacities for the indvidual parts of the hybrid heatpumps are:

| Part                                                                                                                       | Capacity |
| -------------------------------------------------------------------------------------------------------- |  ---- | 
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity	| 4.9	| 
| households_space_heater_hybrid_heatpump_air_water_electricity_gas	        | 15	| 
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity	| 4.9 |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas	        | 15  |

**Comment by ChaelKruip** [comment]
Assigned to @RobTerwel

**Comment by RobTerwel** [comment]
Should be

| Part                                                                                                                       | Capacity |
| -------------------------------------------------------------------------------------------------------- |  ---- | 
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity	| 4.9	| 
| households_space_heater_hybrid_heatpump_air_water_electricity_gas	        | **22**	| 
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity	| 4.9 |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas	        | **22**  |

which makes the gas part consistent with `households_space_heater_combined_network_gas` and `households_water_heater_combined_network_gas`.

For more info, see etmoses_number_validation excel file.

Closing this one.
