### ISSUE TITLE
Workflow for testing grounds should be more intuitive

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#79]
I think this is rather important in order to give users more structure:

IMO it should be a form view with:

### Meta-information:

* Owner (user_id) (defaults to current_user)

### National scenario:
* National scenario: (Select box with all presets from ETengine) or scenario ID

### Local scenario:
* Local scenario: (Select box with all presets from ETengine) or scenario ID
* Scaled down to number of residences:

### Topology used:
* Topology

### Technologies used:

* Option: let algorithm deal with this?

# Questions:
* This scenario_id fill in thing is rather complicated. It's not so obvious what it is, and it's hard to know which ID your scenario has as an ETM user. What should be the best way to deal with this @ChaelKruip and @grdw ?

**Comment by grdw** [comment]
> This scenario_id fill in thing is rather complicated. It's not so obvious what it is, and it's hard to know which ID your scenario has as an ETM user. What should be the best way to deal with this @ChaelKruip and @grdw ?

Discussing this very problem at: #95

**Comment by dennisschoenmakers** [comment]
Could we also add the latest 10 scenarios to the list? I know, they can be anybody's...

**Comment by dennisschoenmakers** [comment]
Do we also need to specify from which server the national/local scenario comes from, @ChaelKruip ?

![image](https://cloud.githubusercontent.com/assets/104830/7518307/767f0a90-f4da-11e4-988e-13e5b73cf2b5.png)

**Comment by antw** [comment]
> Do we also need to specify from which server the national/local scenario comes from, @ChaelKruip ?

I think not. The server is currently [hardcoded to use ETE beta](https://github.com/quintel/etloader/blob/master/config/environments/staging.rb#L13). Perhaps we can extract that into a YAML config file like ETModel does, but I don't think we should support multiple ETEngine servers.

That being the case, the server used should be implied:

* `beta.ivy` → `beta.et-engine`
* `ivy` → `et-engine`

**Comment by ChaelKruip** [comment]
> I think not.

I agree.

**Comment by ChaelKruip** [comment]
> Topology used

I think we can close this issue if the the topology is added to the overview @grdw
