### ISSUE TITLE
Distinguish between automatically selectable profiles

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#794]
As mentioned in https://github.com/quintel/etmoses/issues/784, only profiles that are 'approved' should be eligible for selection by ETMoses.

**Comment by grdw** [comment]
I disagree with the term 'approved' here. It almost sounds if every load profile that's been uploaded is wrong by default. Also who can set the 'approved' checkbox? Only admins I would guess. 

You don't want the profile to take part in the concurrency process. So I would guess it's something like `can_concur` or `included_in_concurrency`. Or will we use the `approved` boolean in the future for something else besides the fact that it can or cannot be selected while minimizing the concurrency?

**Comment by ChaelKruip** [comment]
> included_in_concurrency

Fine by me!
