### ISSUE TITLE
Incosistent font-size neighbourhood battery congestion reserve slider

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#798]
![screen shot 2016-02-17 at 4 00 12 pm](https://cloud.githubusercontent.com/assets/2676542/13113504/996d4bd4-d58f-11e5-8e67-7052bb15a184.png)

It annoys me a litle that the two aren't the same size.

**Comment by antw** [comment]
Maybe just get rid of the 0%/100% labels entirely? ETModel does this and I think it works fine there:

![screen shot 2016-02-17 at 15 48 07](https://cloud.githubusercontent.com/assets/4383/13114997/e89b6b0c-d58d-11e5-86b7-723facd0a865.png)
