### ISSUE TITLE
Design: showing parts of load in the chart

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#800]
The original idea is to hover over a virtual line upward from the x-axis of the load and gas chart and show a pop-up which shows the percentages of how the loads are split up.

A small hit-area:
![design etmoses - chart - parts of load - hit area](https://cloud.githubusercontent.com/assets/2676542/13140110/6ab1785a-d630-11e5-9218-40fc68ee32c5.png)

When you are with your mouse in the yellow part it should show the the percentages of load for Electricity (which is right now 100% EV) and when you are with your mouse in the red part it should show the percentages of load for Gas.

*The existing "pop-over"*
![design etmoses - chart - existing popover](https://cloud.githubusercontent.com/assets/2676542/13140228/0b24038e-d631-11e5-81a9-d716e510798d.png)

The existing pop-over is automatically generated by nvd3 which is going to be a bit of a hurdle. Maybe it's possible to reuse this existing pop-over but I'm not sure yet about how this will be implemented technically (it seems to me that there will be an additional attribute next to X and Y called something in the lines of `consists_of`/`parts_of_load` which has to be shown in the pop-over). 

The usbility of the current pop-over is pretty 'crappy' since you have to hover your mouse at the exact spot on the load-chart where you want to inspect what's on the current point. That has to change as well.

---

*Technical questions:*

@antw :

- Since we already did some minor modifications to the existing nv.d3 library (for enabling and disabling a specific type of chart accross multiple, already rendered charts), would it be legitimate to do it again in light of this feature?

---

Relevant: https://bl.ocks.org/mbostock/3902569

**Comment by ChaelKruip** [comment]
In addition to the feature described above, after talking to @dennisschoenmakers, I feel that we also should support drawing lines to represent the load of individual technologies. This should be turned off by default IMO.

I don't think the chart itself needs much modification (it would just require sending extra data-arrays to the same chart). It will likely require a more flexible/user friendly legend though because showing all technologies as coloured balls in the current legend will lead to clutter.

**Comment by grdw** [comment]
> It will likely require a more flexible/user friendly legend though because showing all technologies as coloured balls in the current legend will lead to clutter.

Yes. Even in full-width that will become a problem if somebody renders the default imported technologies.. :sweat_smile: Let me draw up something.

**Comment by ChaelKruip** [comment]
> Let me draw up something.

Perhaps the ETM can be an inspiration?

![screen shot 2016-02-18 at 12 22 44](https://cloud.githubusercontent.com/assets/1303760/13142007/8b0ec06c-d63a-11e5-9268-22918188eb36.png)

**Comment by grdw** [comment]
> Perhaps the ETM can be an inspiration?

Yes and it's probably going to become something very similar to that.

**Comment by grdw** [comment]
Related: #801

**Comment by dennisschoenmakers** [comment]
I also think the loads of different technologies should be stacked on top of each other, a bit like Frauenhofer does:

![image](https://cloud.githubusercontent.com/assets/104830/13145134/f1b0f2a4-d64e-11e5-950a-a2bbeb7e754b.png)

Stacking makes each share a lot more clear IMO.

**Comment by grdw** [comment]
> I also think the loads of different technologies should be stacked on top of each other, a bit like Frauenhofer does:

Looks very nice!

**Comment by grdw** [comment]
Status: there's a branch on my local machine which is capable of showing the parts of the load (obviously while faking the data). I'm waiting for the pull requests for the NVD3 -> D3 to merge. After that it's waiting for @antw to fetch the calculation in parts. And I would still have to do some tweaking after that.

**Comment by antw** [comment]
I think @dennisschoenmakers' idea above is solid, but I have two questions/concerns:

1. How do we deal with the strategies on/off? I find the *current* chart hard-to-read with just four series present (electricity on/off, gas on/off). Needless to say the chart would be unreadable if we were to plot each technology load twice. We will have to decide:

  * Do we show the "strategies on" loads (except when no strategies are chosen, in which case we show "strategies off").
  * Do we give the user a choice as to which set of loads they want to view?
  * Is there a third option in which we *can* display strategies on and off without the chart becoming a mess?

2. Are we going to show the technology loads only on endpoints, or will higher-level nodes be expected to aggregate the loads of their children? For example, if you click on the "HV Network", would you expect to see the loads of all technologies in the network?

**Comment by grdw** [comment]
> How do we deal with the strategies on/off? 

Moreover there also needs to be a toggle between stacked and 'normal' view.

**Comment by ChaelKruip** [comment]
> Do we give the user a choice as to which set of loads they want to view?

We already do this (right?) and I would keep doing that as I share @antw's concern of readability.

> Is there a third option in which we can display strategies on and off without the chart becoming a mess?

I can imagine the following being useful: if strategies are selected, show the stack of the curves-with-strategies (the current green line) and **in addition** show the blue line without the stacked sub-division. I think that a stack and a line might be still manageable.

**Comment by ChaelKruip** [comment]
> Are we going to show the technology loads only on endpoints, or will higher-level nodes be expected to aggregate the loads of their children? For example, if you click on the "HV Network", would you expect to see the loads of all technologies in the network?

I think we need to show the load per technology for higher level nodes too. That's why this is a challenging feature :grimacing:

**Comment by grdw** [comment]
> I think that a stack and a line might be still manageable.

I'm going to be honest here and say that this is probably going to look really chaotic. I'm fine with including it in the chart as a line but I would hide it by default to prevent the initial chaos a little.

**Comment by antw** [comment]
I pushed to the `local-preference` branch the load calculation changes required to show the loads of individual technologies. I'm sure it will need further testing from me to ensure everything is behaving correctly, but hopefully there is enough to help with the charts.

Presently, the data is delivered to the browser with the load data (`data.json`), but I'm perfectly happy to reconsider that and do something closer to the description in #869. 

```js
{
  "networks": { ... },
  "technologies": { ... },
  "tech_loads": {
    "electricity": {
      "node_key": {
        "tech_key_one": [0.0, 0.0, ...],
        "tech_key_two": [0.0, 0.0, ...]
      }
    }
  }
}

```
