### ISSUE TITLE
Buffering of heat does not work on beta

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etmoses#809]
I am trying out the "buffering of heat" solution on the beta server (Household 3 in http://beta.moses.et-model.com/testing_grounds/439). See specifications below. Network does have a capacity of 150 kW.

![image](https://cloud.githubusercontent.com/assets/4319656/13174022/4bc4a7a6-d701-11e5-942d-16aa57ef9a77.png)

@antw When I apply the "buffering of heat" I do not see any result.

![image](https://cloud.githubusercontent.com/assets/4319656/13173997/15702bf8-d701-11e5-848b-9091080ad4cd.png)

![image](https://cloud.githubusercontent.com/assets/4319656/13174019/3eef3140-d701-11e5-8a1a-c2a84d6910ea.png)

**Comment by ChaelKruip** [comment]
@antw what is the status of this ticket?

**Comment by antw** [comment]
Looking into it along with some other HP issues. Buffering does work locally, so perhaps something specific to this scenario...

Hopefully I'll have it figured out today.

**Comment by antw** [comment]
Fixed by 5bce92bb.

![screen shot 2016-02-22 at 20 17 11](https://cloud.githubusercontent.com/assets/4383/13231346/5de2bc14-d9a1-11e5-8859-ab2455eeb4d2.png)

![screen shot 2016-02-22 at 20 17 21](https://cloud.githubusercontent.com/assets/4383/13231349/618be746-d9a1-11e5-866b-a101734c2789.png)

**Comment by wouterterlouw** [comment]
Thanks @antw 
![image](https://cloud.githubusercontent.com/assets/4319656/13249785/9af1eb90-da26-11e5-84aa-4b8e9bf58040.png)
