### ISSUE TITLE
Flexibility should be accounted for in business case

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#812]
I have made a [LES](http://beta.moses.et-model.com/testing_grounds/425) where the aggregator pays the customer for realised flex:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13245961/f6fc8ce4-da10-11e5-8104-a7bce18e144d.png)

The LES shows a lot of flexibility (differences between blue and green curves:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13245980/0bbb485a-da11-11e5-8b8b-243b7c32c1f5.png)

But the business case does not reflect this:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13245992/1f1d320a-da11-11e5-82ab-f78cb63e9c0e.png)

**Comment by grdw** [comment]
Staging is up and running again :+1: so I'll look into this problem.

**Comment by grdw** [comment]
Is this still a problem?
