### ISSUE TITLE
Validated DB technology capacities [Version 1.0]

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmoses#814]
This issue is about how capacities are defined in ETMoses. It supersedes #789 and will be replaced (longer term) by #805 . It can best be seen as a WIP capacity definition before moving on to implement the more 'physical' capacities, losses and efficiencies of #805 .

The capacities in the DB should be updated as follows in the table below. For these capacities we use the following definitions:

- for an **electricity or gas consuming** technology we put the **input** capacity
- for an **electricity producing technology** we put the **output** capacity

we also have some technologies which cannot be captured by the two definitions above so we also say:

- for **storage** technologies we put the **input** capacity (limiting factor)

in this way we find the most accurate network load given current limitations. Further information on how these numbers were determined can be found in the etmoses_number_validation sheet.

| Part                                                                                                                       | Capacity |
| -------------------------------------------------------------------------------------------------------- |  ---- | 
| households_solar_pv_radiation	| - 1.6 | 
|households_space_heater_heatpump_air_water_electricity | 2.2222222 |
|households_space_heater_heatpump_ground_water_electricity | 2.0833333 |
|households_water_heater_heatpump_air_water_electricity | 3.3333333|
|households_water_heater_heatpump_ground_water_electricity|3.3333333|
|households_space_heater_network_gas | **27.5**|
|households_space_heater_combined_network_gas|**20.6185567**|
|households_water_heater_network_gas |**35.8208955**|
|households_water_heater_combined_network_gas|**24.4444444**|
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity	| **1.0888889**| 
| households_space_heater_hybrid_heatpump_air_water_electricity_gas	        | **20.6185567**	| 
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity	| **1.6333333** |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas	        | **24.4444444**  |
| buffer_space_heating	| 10|
| buffer_water_heating    | 10  |
| energy_flexibility_p2g_electricity | **739.5833333** |
| households_flexibility_p2h_electricity	| 2|
| households_flexibility_p2p_electricity    | 4.4|
| transport_car_using_electricity	| 3.7|

Numbers in bold represent capacities which have **changed**.

**Comment by ChaelKruip** [comment]
:+1:

**Comment by ChaelKruip** [comment]
@grdw can you pick this up this week? I think this can be done quite quickly

**Comment by grdw** [comment]
If I understand correctly. What you want me to do here; is that I replace the **bold** capacities with the capacities in the database eventhough some of those don't currently exist?

**Comment by RobTerwel** [comment]
Bold capacities are capacities that are new or should replace existing capacities. So if a value is bold, it should be entered in the database (and replace the existing value if there is one already).

**Comment by grdw** [comment]
After migrating it looks like:


| Part                                                                                                                       | Capacity |
| -------------------------------------------------------------------------------------------------------- |  ---- | 
| households_solar_pv_solar_radiation | -1.6 |
| households_space_heater_heatpump_air_water_electricity |  2.22222 |
| households_space_heater_heatpump_ground_water_electricity | 2.08333 |
| households_water_heater_heatpump_air_water_electricity |  3.33333 |
| households_water_heater_heatpump_ground_water_electricity | 3.33333 |
| transport_car_using_electricity | 3.7 |
| households_flexibility_p2p_electricity |  4.4 |
| energy_flexibility_p2g_electricity |  739.583 |
| households_flexibility_p2h_electricity |  2 |
| base_load | NULL |
| generic | NULL |
| base_load_buildings | NULL |
| base_load_edsn |  NULL |
| households_space_heater_network_gas | 27.5 |
| households_space_heater_combined_network_gas |  20.6186 |
| households_space_heater_micro_chp_network_gas | NULL |
| households_water_heater_network_gas | 35.8209 |
| households_water_heater_combined_network_gas |  24.4444 |
| households_water_heater_micro_chp_network_gas | NULL |
| households_water_heater_fuel_cell_chp_network_gas | NULL |
| buffer_space_heating  | 10 |
| buffer_water_heating  | 10 |
| households_space_heater_hybrid_heatpump_air_water_electricity | NULL |
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity | 1.08889 |
| households_space_heater_hybrid_heatpump_air_water_electricity_gas | 20.6186 |
| households_water_heater_hybrid_heatpump_air_water_electricity | NULL |
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity | 1.63333 |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas | 24.4444 |
| congestion_battery  | 10 |

**Comment by RobTerwel** [comment]
Looks good to me for now, @grdw ! :+1: 

Closing.
