### ISSUE TITLE
How can we include gas (and later, heat) in the network topology

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#832]
In sprint 2, we will add load calculations on the gas network. This requires that the user can specify the gas-infrastructure similar to the electricity infrastructure.

## Requirements

* end-points need to be consistent (should coincide) across different infra-structures: I think it makes sense to limit the freedom of users to combine any electricity-topology with any gas-topology with any heat-topology regardless of scale and number of end-points.
* higher level nodes need not coincide: it would be too restrictive to force the infrastructure for different carriers to follow the same topology
* information bundling: If end-points need to overlap between infrastructures for different carrier but for the same region, it makes sense to keep the code describing those infrastructures (YAML?) together somewhere 
* visual editing of topologies: managing multiple topologies (carriers) with the constraint of coinciding end-points is going to even more difficult than editing the current topology YAMLs. This suggest a layer of user-friendliness such as a simple graphical user interface (but feel free to disagree).

## Solution components/directions

* bottom-up topology building: In order to guarantee consistency between end-points, it would perhaps be logical to start with specifying how many end-points the topology should have
* check-boxes for carriers per end-point: which carriers are supported for each of those end-points can be shown with check-boxes and colour-coding (blue=electricity, grey=gas, red=heat)
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/13495976/fc243106-e14d-11e5-88a8-138569907b0a.png)
* drag-and drop cables, pipes and transformers: still thinking about a way to keep this simple and yet useful

**Comment by ChaelKruip** [comment]
@dennisschoenmakers @jorisberkhout @antw @grdw @JeroenvdLogt @AlexanderWirtz @RobTerwel feel free to criticise the above ideas. I'm just trying to get the creativity flowing here :smile:

**Comment by grdw** [comment]
> This suggest a layer of user-friendliness such as a simple graphical user interface

On a related note: https://github.com/quintel/etmoses/issues/596

**Comment by grdw** [comment]
I'm still convinced that we should use some D3 type solution for creating a topology. Here comes a really ugly drawing:

When you start creating you'll see one node where the title is an input field and two buttons + and -.
![screen shot 2016-03-03 at 15 29 08](https://cloud.githubusercontent.com/assets/2676542/13497418/7a391d5c-e155-11e5-91e7-42e557943f35.png)

After adding two nodes you'll get:
![screen shot 2016-03-03 at 15 34 33](https://cloud.githubusercontent.com/assets/2676542/13497437/8bc26e98-e155-11e5-9ca2-72c4e5371a7a.png)

Etc. etc. In order to get the gas/heat/load selection in here - I'm not really sure but I'm guessing when you click the node a form should render below the topology to change the settings of that node. Like stakeholder, capacity, units, etc.

**Comment by antw** [comment]
I haven't much to add at this stage, except to agree with everything above.

> end-points need to be consistent (should coincide) across different infra-structures: I think it makes sense to limit the freedom of users to combine any electricity-topology with any gas-topology with any heat-topology regardless of scale and number of end-points.

On a technical note, we currently implement the electricity and gas networks as completely separate data structures. I would like to explore an approach closer to that of ETEngine: a single graph where the edges between nodes have a carrier. This wasn't attempted during the previous gas sprint due to time constraints, but with the prospect of adding a third carrier (heat), I think it should be revisited.

**Comment by ChaelKruip** [comment]
> On a technical note, we currently implement the electricity and gas networks as completely separate data structures. I would like to explore an approach closer to that of ETEngine: a single graph where the edges between nodes have a carrier. This wasn't attempted during the previous gas sprint due to time constraints, but with the prospect of adding a third carrier (heat), I think it should be revisited.

Sounds good! :+1:

**Comment by ChaelKruip** [comment]
> I'm still convinced that we should use some D3 type solution for creating a topology. 

I am not against that if it fits our requirements

> When you start creating you'll see one node where the title is an input field and two buttons + and -.

This is the 'normal' way to build an hierarchical network: starting with the highest level and working your way down to the 'leaf nodes' or end-points. The conceptual issue I'm having with this in combination with different carriers is that the leaf-nodes should be the same/coincide (although not all carriers need to be available in each end-point) whereas the top node does not need to coincide and neither do any intermediate nodes.
See for example this topology of electricity (green) and heat (red) drawn by @jorisberkhout:
![img_5138_jpg](https://cloud.githubusercontent.com/assets/1303760/13498591/f35ea882-e15a-11e5-8d0c-2e6e9459e585.png)
There are six end-points which both have electricity and heat as carriers. IMO it would be difficult to built these two topologies starting from a top-node and working your way down. Starting bottom-up seems a lot more intuitive to me as the end-nodes are most restricted and the top-nodes need not even coincide for different carriers.

**Comment by ChaelKruip** [comment]
Some network-drawing tools to play with:

* [https://www.draw.io/](https://www.draw.io/)
* [https://www.gliffy.com/](https://www.gliffy.com/)

What do you like? What don't you like? What could/should we copy?

**Comment by grdw** [comment]
> There are six end-points which both have electricity and heat as carriers.

eh... okay. But up from there it could be that they are joined or are they always separate from each other?

Like:
````
A -> B -> C
       ↗
D -> E
````

Where C is both a heat and electricity carrier?

**Comment by ChaelKruip** [comment]
> Where C is both a heat and electricity carrier.

Do you mean that node C uses both electricity and heat as carriers than yes. It is not likely that the highest node for electricity (HV network) and the highest node for the heat network coincide in location or function.

**Comment by ChaelKruip** [comment]
We decided to make something a 'gas' connection, if one or more gas-technologies are attached to it.
