### ISSUE TITLE
Load calculation on gas infrastructure: what does it do?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#833]
This ticket is to explore and specify what a load calculation for gas could look like and what is technically feasible. Thanks @jorisberkhout for the initial brainstorming on this.

## Certainties

There are a few things that we already know with 99% certainty that are going to be in there:

* low-, medium- and high pressure levels separated by pressure stations (similar to voltage levels for electricity)
* capacities [kW] for pressure stations (similar to transformer)
* costs for pressure stations (similar to transformer)
* technical lifetime for pressure stations
* load/flow measures in kW (already available on end-points)
* volume measures in kWh (already available on end-points)

## Likely features

* losses for pressure stations
* capacities for pipes
* width and length for pipes
* technical lifetime for pipes
* costs for gas-infrastructure placement (green field)
* costs for gas-infrastructure replacement
* costs for gas-infrastructure refurbishing
* costs for pipes depending on width and length

### Possibly complex features

If we want to fully support the feeding-in of P2G-produced hydrogen into the network, ETMoses needs to keep track of the storage volume of the local network (the part of the topology to which the current end-point is connected). This would immediately imply some extra complexity:

* need to keep track of volume and pressure of gas in connected parts of the network
* pressure ranges which trigger action: if pressure is too low => feed in more gas from next pressure level. If pressure too high => pump gas from lower to higher pressure level.
* need to keep track of the amounts of hydrogen and network gas (as they have different energy density)

I think that the need for these complex features depends on the potential for feed-in of hydrogen in the network. If the current network can accommodate (much) more feed-in than can be realistically expected from any future scenario, this is not a useful extension of ETMoses. So, we have to so some calculations to see in which regime we are.

**Comment by ChaelKruip** [comment]
After discussions with @JeroenvdLogt @antw @jorisberkhout @dennisschoenmakers and others, the following pictures has emerged.

## Questions we want to answer

The following questions are likely to be relevant in the discussions about gas-infrastructure:

* Building a new neighbourhood: should we invest in gas infrastructure?
* For existing neighbourhoods: should we refurbish existing infrastructure?
* How big are the investments in the electricity network that we can prevent if we keep the current gas network operational? And what would that cost?
* What is the capacity for feeding locally produced gas (hydrogen, biogas) back into the network? 
* How big is the storage volume for different levels of the gas network?
* What losses are associated with feeding in locally produced gas?

## Levels rather than topology

The gas-network is very much circular/meshed (vermaasd): 
![et-moses__voorbereiding_sparringsessie_ontwikkeling_gasinfra_-_chael_kruip_quintel_com_-_quintel_intelligence_mail](https://cloud.githubusercontent.com/assets/1303760/13667067/0bfba1b0-e6b5-11e5-8f8d-08b131a2ba1f.png)

Many routes can be taken from one point in the network to another. This suggests the following simplification: we describe the gas network primarily by its different pressure-levels. Consumers/producers can be connected at different levels.

## Calculator: flow trough levels

In order to calculate the potential for storing gas and the losses associated with feeding-in of locally produced gas, the following attributes have to be known for each pressure level:

* storage volume [kWh or, equivalently, m^3]
* capacity for extraction (consumption) [kW]
* capacity for feed-in [kW]
* losses for for feed-in [kW] (due to need for compression)

In order to calculate effects of asset management choices, the following attributes may be relevant:

* investment cost of relevant types of pipes [EUR/m]
* removal cost of relevant types of pipes [EUR/m]
* refurbishing cost of relevant types of pipes [EUR/m]
* cost of GOS [EUR/kW]
* variable O&M cost for GOS [EUR/kWh]
* cost of DSR [EUR/kW]
* variable O&M cost for DSR [EUR/kWh]
* lifetimes for all relevant components

**Comment by ChaelKruip** [comment]
@JeroenvdLogt @dennisschoenmakers @antw am I missing anything?

**Comment by Sanne512** [comment]
- Feedback on the questions we want to answer: keep in mind that these questions are relevant for all the stakeholders. 
•How big are the investments in the electricity network that we can prevent if we keep the current gas network operational? And what would that cost? --> the question is more relevant the other way around: what are the financial consequences for the electric and gas infrastructure if an area goes full-electric?
•What is the capacity for feeding locally produced gas (hydrogen, biogas) back into the network? --> both capacity and costs are relevant. 

- Feedback on the certainties: costs of the pipelines are missing. 

- Feedback on the quality of the gas: this is too complicated to model in this sprint, besides that it does not happen in reality often, so far only once or twice. It is important to include in the documentation on why we left this out.
