### ISSUE TITLE
Profile listing should become more structured and should support 'hiding' and 'types'

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#84]
When adding more load profiles and profiles that describe other aspects of technologies (availability, flexibility etc.), the current [list of profiles](http://ivy.et-engine.com/load_profiles) is going to very long and confusing. 

I propose to use something of a 'tree'-view:
![code_rant__rendering_a_tree_view_using_the_mvc_framework](https://cloud.githubusercontent.com/assets/1303760/7271163/e9015776-e8e1-11e4-96a1-6870adf73226.png)
Which I took from [this website](http://mikehadlow.blogspot.nl/2008/10/rendering-tree-view-using-mvc-framework.html)

At the highest level I think that we want to distinguish between types of profiles:
* base-load profiles: for houses, e.g, EDSN
* consumption profiles: for EV (if not in 'storage mode'), heat pumps etc.
* production profiles: for solar PV
* flexibility profiles: for EV (if in 'storage mode') and P2H

Perhaps the following nesting is useful for the types listed above:
* technology (key of technology)
  * capacity of technology (if relevant, for heat pumps it is)
    * time-resolution

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @antw.

**Comment by ChaelKruip** [comment]
Thanks for making this possible @grdw. It seems that we still need the possibility of assigning/choosing categories when creating a profile though to make this useful...

**Comment by grdw** [comment]
As discussed; this is already in the current setup. Though there aren't that many categories to pick from at the moment. If someone could add some categories to the database. :smiley_cat:
