### ISSUE TITLE
Profiles are not displayed when initialising a LES with a technology matrix in CSV format

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#840]
[This LES](https://moses.energytransitionmodel.com/testing_grounds/418/edit#) does not show profiles. 

For this LES, the tariffs are blank as well:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13664920/1c872b90-e6aa-11e5-8949-7196443e8cf7.png)

**Comment by grdw** [comment]
I see that the Buffers are blanked for this LES. It does have profiles attached or did you do that manually afterwards? Also stating that this issue is old, can this still be reproduced?

**Comment by ChaelKruip** [comment]
If I try to update any LES by using a CSV dump of the technologies, it crashes.

**Comment by grdw** [comment]
>  it crashes.

As in Airbrake 500 internal server error?

Maybe we should revisit the CSV import ...

**Comment by ChaelKruip** [comment]
> Maybe we should revisit the CSV import ...

👍

**Comment by ChaelKruip** [comment]
Assigning @antw

**Comment by antw** [comment]
> If I try to update any LES by using a CSV dump of the technologies, it crashes.

I fixed that a couple of days ago in 5eb7e893 and 9715ea85.

**Comment by antw** [comment]
Profiles do seem to be imported correctly from the CSV; I'll close this.
