### ISSUE TITLE
Difference between blue and green curve disappears when zooming in on the week

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#841]
There are differences in [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/479):
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13669012/dbc2c922-e6c0-11e5-8319-88ee6bb0954c.png)
but in the week-view the curves are the same:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13669033/07679454-e6c1-11e5-9f61-bd67df7e7fe3.png)

**Comment by grdw** [comment]
I know which line of code this is doing, moment please...
