### ISSUE TITLE
When are the Merit curves greyed out?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#844]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13671786/49d4486c-e6d2-11e5-8c05-1250ce413dda.png)

**Comment by grdw** [comment]
Related: https://github.com/quintel/etmoses/issues/765

**Comment by grdw** [comment]
I think the correct answer is: always, which is the same answer to when they are functional. I already created an issue for this bug.
