### ISSUE TITLE
Why is there no gas use in this LES?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#845]
In [LES 479](https://beta-moses.energytransitionmodel.com/testing_grounds/479), there are hybrid heat pumps which should switch to gas if the network is congested. This requirement is met but no gas consumption is seen:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13671983/2024dc7e-e6d3-11e5-9b6b-9d6ebea8c8eb.png)
Am I missing something? Or is the calculator/chart broken?

**Comment by antw** [comment]
The gas component is "boosting" and there are two criteria – either being true – which will cause the technology to become active:

* Demand for heat has not been satisfied by the other heating technologies by the time the gas component is calculated, or
* Demand for energy is greater than the capacity of the buffer.

I checked out all the time steps in January 13, and neither criteria are met.

* In all steps demand has been satisfied by other technologies prior to computing the gas component.
* Capacity of the buffer is greater than demand.

**Comment by ChaelKruip** [comment]
Thanks @antw! :relieved:
