### ISSUE TITLE
A new resistive (electric) heater should be added when I press 'add' for P2H

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#846]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13672808/96ca6706-e6d6-11e5-8add-ab81aa63d263.png)

Now nothing happens...

**Comment by grdw** [comment]
Isn't P2H added to a Buffer water heating?

**Comment by ChaelKruip** [comment]
Oh, I see, it literally appears beneath the hot water buffer! 

It works but is quite ghastly from a users perspective because nothing happens on your screen to indicate that the P2H unit has actually been added to your technologies.
