### ISSUE TITLE
How to connect gas technologies to the gas network?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#851]
In the light of https://github.com/quintel/etmoses/issues/833, we still have to decide how to connect technologies and consumers to the various levels of the gas network.

TO BE EXPANDED!

**Comment by ChaelKruip** [comment]
After discussion with @dennisschoenmakers I concluded that we should make the connection-level an attribute of the technology. Default to the lowest level for all technologies for now. If we have time, we can make the connection level an 'advanced attribute' and let the user change this in the technology overview page.

**Comment by Sanne512** [comment]
We totally agree!

**Comment by ChaelKruip** [comment]
> If we have time, we can make the connection level an 'advanced attribute' and let the user change this in the technology overview page.

I think we should make time for this in this sprint and give the user the choice for each technology to which pressure level it is connected.

**Comment by ChaelKruip** [comment]
I thought about how the number of gas connections can be specified in ETMoses. First we must distinguish between the number of gas **connections** and the number of end-points of the electrical topology which 'have' gas.

So far, we have used the technology interface to define whether an end-point 'has' gas or not. If the user (or ETMoses) has connected at least one gas-technology to an end-point of the topology, that end-point 'has' gas. I propose to keep this the way it is because it:
* is backward compatible with existing LESs
* allows ETMoses to quantify how *many* gas connections an end-point has: it can use the 'number_of_connections' attribute in the topology YAML. So, if end-point 'A' has 100 connections, it is counted as 100 electricity connections if no gas technology is connected, and 100 electricity connections plus 100 gas connections if a gas technology is connected to that end-point
* requires very little changes to the current code

Including @dennisschoenmakers @Sanne512 @antw @grdw

**Comment by ChaelKruip** [comment]
BTW: the number of gas connections already is a 'measure' to be used in market models. @antw isn't the above how ETMoses currently 'measures' the number of gas connections?

**Comment by antw** [comment]
> allows ETMoses to quantify how many gas connections an end-point has: it can use the 'number_of_connections' attribute in the topology YAML.

This attribute is new to me. The number of connections is determined by [how many base load techs are installed on an endpoint](https://github.com/quintel/etmoses/blob/14882b8f12e6ff1fcabde0a6caf3edfb1ff3a93d/app/models/market/measures/number_of_connections.rb#L5). For gas, the number of connections will be zero if there are no gas techs attached to the endpoint.

**Comment by ChaelKruip** [comment]
> This attribute is new to me.

It only existed in my head! :smile: 

> The number of connections is determined by how many base load techs are installed on an endpoint.

:+1: 

> For gas, the number of connections will be zero if there are no gas techs attached to the endpoint.

Right! But *if* there are gas technologies connected, the number of connections is the same as the number of base-loads right?

**Comment by antw** [comment]
> But if there are gas technologies connected, the number of connections is the same as the number of base-loads right?

Yes, exactly. If there are no gas technologies installed, the number of **gas** connections is zero. If an endpoint does have one or more gas technologies, the number of gas connections is equal to the number of electricity connections.
