### ISSUE TITLE
How/where should the user select the gas-level for inspection of its load and capacity?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#852]
For electricity, the nodes are clickable:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13771916/825fa736-ea91-11e5-8e18-671e3275730b.png)

For gas, we will not use a full-fledged topology though...

TO BE EXPANDED

**Comment by ChaelKruip** [comment]
After discussion with @dennisschoenmakers I decided that the following output would be interesting in order of priority:
* yearly/weekly load on the highest node of the gas-network. It would be nice if this can be split up per technology (similar to electricity load)
* yearly consumption, production and losses for all levels in a stacked bar chart
* a table showing, capacity (up), capacity (down), pressure range and passive storage volume [kWh] for all levels

**Comment by ChaelKruip** [comment]
> yearly/weekly load on the highest node of the gas-network.

![etmoses](https://cloud.githubusercontent.com/assets/1303760/13807252/95d7daac-eb60-11e5-915b-69776280ce2e.png)

> yearly consumption, production and losses for all levels in a stacked bar chart

![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/13807918/f4eb1100-eb63-11e5-9ae8-8cd105134a0a.png)

(sorry that the values are a bit nonsensical, in reality the consumption_1 - production_1 + loss_1 = consumption_2 - production_2 etc. for the different levels).

> a table showing, capacity (up), capacity (down), pressure range and passive storage volume [kWh] for all levels

No surprises there...

**Comment by Sanne512** [comment]
Could the yearly and weekly load be shown for all the nodes and not just the top node?

**Comment by ChaelKruip** [comment]
> Could the yearly and weekly load be shown for all the nodes and not just the top node?

I think we could add the different levels either as differently coloured curves (as with technologies) or have a select box for which level the load chart should display the data.
