### ISSUE TITLE
[Airbrake] [Production] undefined method `reject' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#853]
**Airbrake error:** [#1543](https://quintel.airbrake.io/projects/111227/groups/1642101202104071543)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `undefined method `reject' for nil:NilClass`
**Occurred at:** Mar 15, 2016 16:01:57 UTC
**First seen at:** Mar 15, 2016 16:01:57 UTC
**Occurrences:** 1 (1 since last deploy on Mar 15, 2016 14:31:50 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/424/business_cases/188/render_summary](https://moses.energytransitionmodel.com/testing_grounds/424/business_cases/188/render_summary)
**File:** `[PROJECT_ROOT]/app/services/finance/business_case_summary.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/finance/business_case_summary.rb:30:in financials_without_freeform
[PROJECT_ROOT]/app/services/finance/business_case_summary.rb:10:in summarize
[PROJECT_ROOT]/app/controllers/business_cases_controller.rb:28:in render_summary
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in send_action
```

**Comment by grdw** [comment]
Related to -> https://github.com/quintel/etmoses/issues/570

**Comment by grdw** [comment]
Closing due to issue related being closed.
