### ISSUE TITLE
Business case sometimes(!) gives different outcomes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#854]
It seems like it happens after you have edited the market model, and the new business case is calculated for the first time it gives different results than after you recalculate by turning a strategy on and off again (triggering calculations each time).

After changing concurrency of EV to 'minimal' in [this LES](https://moses.energytransitionmodel.com/testing_grounds/427), the business case read:
<img width="1019" alt="screen_shot_2016-03-15_at_21_31_45_png" src="https://cloud.githubusercontent.com/assets/1303760/13793248/46eca806-eaf6-11e5-9a8c-04a36eb4c4c2.png">

After turning the solar capping strategy off:
<img width="1003" alt="screen_shot_2016-03-15_at_21_33_11_png" src="https://cloud.githubusercontent.com/assets/1303760/13793357/d15c9082-eaf6-11e5-8ddb-2fb93c6289da.png">

And after turning it on again (should give the original situation):
<img width="1007" alt="screen_shot_2016-03-15_at_21_33_54_png" src="https://cloud.githubusercontent.com/assets/1303760/13793403/03e0f958-eaf7-11e5-9f86-7d50d9c2b2a2.png">

The last two numbers can be retrieved reliably by switching the strategy 'on' and 'off'.

**Comment by ChaelKruip** [comment]
I was able to reproduce the problem today. 

I'm just guessing here but could it be that the business case calculation takes an 'old' load calculation or uses the 'blue' instead of the 'green' curve as a basis?

**Comment by antw** [comment]
Closed by 08ebfef2.
