### ISSUE TITLE
No options to log in if you have forgotten your password

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#855]
Is there an option to reset your password in case you have forgotten it?

**Comment by ChaelKruip** [comment]
@dennisschoenmakers can you pick this up?

**Comment by Sanne512** [comment]
What's the status? Because I forgot the password to my own Alliander account (sanne.preso@alliander.com) and I can't access it now..

**Comment by antw** [comment]
You can now reset your password if you forgot it:

| Sign in page | Forgotten password page |
| --- | --- |
| ![screen shot 2016-05-25 at 10 05 24](https://cloud.githubusercontent.com/assets/4383/15534398/866705b6-2260-11e6-8a18-3ae88a26e8ef.png) | ![screen shot 2016-05-25 at 10 08 53](https://cloud.githubusercontent.com/assets/4383/15534450/cc35f6ba-2260-11e6-920f-1ef940a2d0b2.png) |

After asking for it to be reset, you'll be send back to the sign-in page, and an e-mail with instructions should arrive within a minute or two.
