### ISSUE TITLE
OVERVIEW TICKET sprint 2

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#857]
This ticket summarises the main features we want to implement in sprint 2. It includes links to important issues where more details can be found.

After discussion with @JeroenvdLogt @Sanne512 @MarjoleinSchwachofer @antw @dennisschoenmakers @AlexanderWirtz and @jorisberkhout we have decided to model the gas network as a number of communicating pressure levels.

## Load calculation for gas

A summary of the discussion leading to this can be found in https://github.com/quintel/etmoses/issues/833#issuecomment-194873890 

## Visualisation of the calculation

In https://github.com/quintel/etmoses/issues/852 three output elements (two charts and a table) are described.

## Connecting technologies to the levels of the gas network

In https://github.com/quintel/etmoses/issues/851 the following suggestion is made: make the level of connection an attribute of the technology (similar to its lifetime, capacity etc.). By default, we connect all technologies to the lowest (0.1 bar) level. This can be changed in the future to be changeable by the user in the technology interface.

## Cost of the gas infrastructure and other asset data

In https://github.com/quintel/etmoses/issues/850, the design for an 'asset-page for the gas infrastructure' is discussed. 

For the necessary values on asset components see https://github.com/quintel/etmoses/issues/870

In https://github.com/quintel/etmoses/issues/889, the link between the 'scale' of the LES and the national assets is described.

## Connection between assets and load calculation

The number of 'connectors' (GOSs, DRSs, 'overslagstations' etc.) between the levels chosen in the 'asset-page for the gas infrastructure' are used to determine the capacity between the pressure levels.

The length (and type) of pipe chosen in the 'asset-page for the gas infrastructure' are used to determine the (passive) storage volume of the pressure levels. 

See https://github.com/quintel/etmoses/issues/861 for details of the load calculation itself.

**Comment by ChaelKruip** [comment]
I don't think your commit closes this issue @dennisschoenmakers :smile:

**Comment by dennisschoenmakers** [comment]
> I don't think your commit closes this issue @dennisschoenmakers :smile:

That would be way too easy :grinning:

**Comment by Sanne512** [comment]
Overall, it looks really good. Due to different holidays Jeroen and I are meeting the gas experts on March 25th to check the design of the gas modelling with them and make a start with collecting the necessary values. I still have some questions for Chael for which I will call him tomorrow, but the first remarks you can find in the different sections.

**Comment by ChaelKruip** [comment]
Closing.
