### ISSUE TITLE
GasTerra logo should be added to ETMoses

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#858]
I think this should be done ASAP as GasTerra is currently sponsoring development of ETMoses as well.

**Comment by ChaelKruip** [comment]
I think the logo should not be clipped (bottom!) and better aligned with the others:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13815151/b7b83242-eb89-11e5-8c4e-6cce4645fce8.png)

**Comment by dennisschoenmakers** [comment]
Agree. working on it :smile:

**Comment by dennisschoenmakers** [comment]
Fixed with 3d4944359cddb9d66bd0995b6175a22515de08fb
