### ISSUE TITLE
[Airbrake] [Staging] 301 Moved Permanently

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#866]
**Airbrake error:** [#8988](https://quintel.airbrake.io/projects/111227/groups/1647672921694908988)
**Airbrake project:** ETMoses

**Error type:** `RestClient::MovedPermanently`
**Error message:** `301 Moved Permanently`
**Occurred at:** Mar 23, 2016 08:31:58 UTC
**First seen at:** Mar 23, 2016 08:31:58 UTC
**Occurrences:** 1 (1 since last deploy on Mar 16, 2016 15:07:41 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/import](https://beta-moses.energytransitionmodel.com/testing_grounds/import)
**File:** `[GEM_ROOT]/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:39:in return!
[GEM_ROOT]/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in process_result
[GEM_ROOT]/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in block in transmit
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in start
```

**Comment by grdw** [comment]
Import is broken on beta environment.
