### ISSUE TITLE
Heat network topology: make the user draw it on a map

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#871]
## Background

The topology of heat networks is expected to be very different at different scales. For a city, the main infrastructure might resemble a ring, for a street it could be more like a branching tree, for a block of houses it could be more like a single pipe. 
The cost of a heat network (per connection) will likely be strongly correlated with the length of pipe needed and the density of the buildings.

Moreover, the topology will depend strongly on available sources for heat and their location.

## Spatial approach

The above suggests that spatial information is going to be of paramount importance. The current YAML format used for electricity networks is ill equipped to deal with spatial information. The same goes for the ['aggregated level' approach](https://github.com/quintel/etmoses/issues/833#issuecomment-194873890) used for gas.

The idea is to combine a map of the region in question with a simple drawing tool to characterise the shape of the heat network and the location of the heat source(s). 

The user can look up the relevant area and select the region of interest (draw a rectangular selection for instance). A source, can be added which will feed the network. Next, the user can draw a polygon or tree structure connecting source and houses/connections. 

## Anticipation of other features

We are looking for ways to initialise ETMoses with open source spatial data such as BAG and the Enexis open asset data. Also, we are planning to use Open Street Map and/or Google maps to visualise the results of our calculations. The above would be a first exploration in this direction. 

## Open questions

There are still many open questions such as: 

* how do we 'characterise' connections to households?
* how to deal with 'open networks' containing multiple decentralised sources
* ...

**Comment by ChaelKruip** [comment]
To inspire some debate and ideas here is a very crude mock-up of a possible interface:
![openstreetmap](https://cloud.githubusercontent.com/assets/1303760/14112554/625d6c2c-f5cf-11e5-82a2-ee3bb5b6c9aa.png)

The user can drag new elements into the map from the legend on the right. Right-clicking will reveal a dialog window where attributes can be edited.

**Comment by AlexanderWirtz** [comment]
Seems ambitious. I hope we can get some representative numbers for heat network investment costs. One condition this depends on quite strongly is the kind of soil or underground the network is layed into or onto. This is also true for gas networks, by the way.

The only way to get a good feel for this si to go and talk to some people, I suppose. Wouter Meyers has a contact in Amsterdam (Peter Simoës of AEB, interviewed in 2011).

_________

Quoting email from Wouter Meyers:

From: Wouter Meyers 
Sent: Tuesday, April 12, 2011 15:14
To: Wouter van Lelyveld
Cc: Alexander Wirtz
Subject: Kosten warmtenetten
 
Hi Wouter,          cc. Alex
 
Uit mijn interview met Peter Simoës van het Afvalenergiebedrijf in Amsterdam heb ik wat gegevens over de investeringskosten van warmtenetten zoals zij die hanteren in hun planningen. Zie jij een manier om deze data mee te nemen in het model? Ik weet niet wat de huidige schattingen zijn van de kosten voor het warmtenet, maar dit zijn wel de kosten waarmee gerekend wordt in echte projecten (in Amsterdam) ;-)
 
Er zijn drie onderdelen waarin geïnvesteerd moet worden:
-        Bronnen – warmtebronnen (afvalverbranding, geothermische bronnen, etc) – ca. 10% van totale investering
-        Primaire netwerk – leidingen van bron tot aan distributiepunten – ca. 30-40% van totale investering
-        Secundaire netwerk – leidingen van primaire netwerk naar huizen en gebouwen – ca. 50-60% van totale investering
 
Per huishouden wordt zo’n € 3.500 tot € 4.000 gerekend voor het secundaire netwerk. Als je uitgaat van € 3.500 en 50% van totale investeringen kom je dan op een kostenplaatje van:
-        Bronnen: € 350
-        Primaire net: € 3.150
-        Secundaire net: € 3.500
-        Totaal: € 7.000 per huishouden
 
Eigenlijk kun je de investeringen in de bronnen en het primaire net natuurlijk niet splitsen per huishouden, maar op zich kun je dat als aanname wel doen.
 
Onderhoud en beheer wordt als volgt berekend voor het secundaire netwerk:
Woningen
-        € 80 per jaar onderhoud
-        € 40 per jaar beheer
 
Bedrijven
-        € 3 / kWth / jaar onderhoud
-        € 1 / kWth / jaar beheer
 
Voor bronnen en primaire netwerk wordt onderhoud en beheer berekend als 1% van de totale investeringskosten.
 
Overigens treedt bij het transport van warmte zo’n 25% verlies op, die vooral in het secundaire netwerk zit, waar de leidingen steeds dunner worden en contactoppervlakte met de buitenwereld dus steeds groter.
 
Ik zal deze data trouwens ook nog een keer valideren in een interview met Nuon aan het einde van de maand.

Groeten,
Wouter

**Comment by AlexanderWirtz** [comment]
Another possible source is Albert Blom from Nuon / Vattenfall. @jorisberkhout has been in touch with him about waste incinerator CHPs

**Comment by ChaelKruip** [comment]
> @jorisberkhout has been in touch with him about waste incinerator CHPs

@jorisberkhout Could you see if he is available for an interview?

**Comment by ChaelKruip** [comment]
Closing this issue as our plans have changed with respect to how to model the infrastructure.
