### ISSUE TITLE
Buttons disappear behind new footer

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#873]
Only when selected (save button) do they come to the foreground:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14108983/2cff5a7c-f5c0-11e5-908e-d09a265bb9cc.png)

**Comment by grdw** [comment]
Possible duplicate: https://github.com/quintel/etmoses/issues/860

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/a31829bf66cd5c4dfa5c0730efecf056fc87d660
