### ISSUE TITLE
Concurrency buttons can be drastically reduced

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#874]
The buttons with a line through it can be removed:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14136778/e3305040-f664-11e5-836d-d6af9b31b230.png)

**Comment by grdw** [comment]
![screen shot 2016-03-31 at 11 35 00](https://cloud.githubusercontent.com/assets/2676542/14171706/9e23c376-f734-11e5-858e-840f8184c84e.png)

That will leave us with this :+1: 
There are boolean's called 'expandable' in the `technologies` table. I set them manually on the beta environment to false for the technologies specified in the image above.

**Comment by ChaelKruip** [comment]
:+1: nice changes @grdw!

One last request: can you make all names plural? "Households" instead of "Household" etc.

**Comment by grdw** [comment]
> One last request: can you make all names plural?

Yes. I could. I do consider this somewhat low-prio so I'll probably change this tomorrow.

**Comment by ChaelKruip** [comment]
> Yes. 

:+1: 

> I could. 

:+1: 

> I do consider this somewhat low-prio so I'll probably change this tomorrow.

:+1:  :+1:

**Comment by grdw** [comment]
<img src="https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif"/>
