### ISSUE TITLE
Space heating demand and hot water demand should be refined

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#875]
Currently, the space heating demand which is used to scale the space heating profiles with is taken as the demand of the converter in the red box:
![https___beta-engine_energytransitionmodel_com_data_latest_layout](https://cloud.githubusercontent.com/assets/1303760/14137347/b7d528c8-f667-11e5-9631-1c08825822aa.png)

The issue with this is that this demand represents the total demand for space heating (after insulation and solar collectors). Some of this demand can be satisfied by technologies which are *not included* in ETMoses such as the wood-pellet stove, district heating or coal heater. So, the technologies in ETMoses are asked to fulfil the total demand, although a (possibly big) portion of that is already taken care of by technologies outside of the scope of ETMoses.

To correct for this, we should subtract the demand already supplied by technologies outside of the scope of ETMoses and use the resulting demand to scale the profiles.

The same argument goes for hot water.

**Comment by ChaelKruip** [comment]
@antw @grdw are these demands passed from ETE to ETMoses by means of gqueries? In that case I assign myself to produce the relevant queries for these demands.

**Comment by antw** [comment]
The demands are read directly from the converter and made available to Moses [through a JSON API](https://github.com/quintel/etengine/blob/master/app/models/api/v3/converter_stats_presenter.rb). No Gqueries involved.

Gqueries would be a far better solution, but would take some effort to implement.

**Comment by ChaelKruip** [comment]
> Gqueries would be a far better solution, but would take some effort to implement.

I'll try to give that a place in the next sprint.

**Comment by ChaelKruip** [comment]
> No Gqueries involved.

What about these lines:

https://github.com/quintel/etmoses/blob/master/app/models/import/composite_builder.rb#L8-L9 ?

Don't they refer to these queries:

https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_hot_water_buffer_demand.gql and https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_space_heating_buffer_demand.gql?

**Comment by antw** [comment]
Yes. I was having a senile moment. :blush: 

*Most* technology demands are read from the converter directly; composites (space heating, hot water) and base loads are special cases which use gqueries. For those technologies, it is only the demand which is read this way.

**Comment by ChaelKruip** [comment]
> composites (space heating, hot water) and base loads are special cases which use gqueries. 

:tada: :dancers: those are exactly the ones I need to improve the queries for :tada: :dancers:

**Comment by ChaelKruip** [comment]
These queries have been refined in https://github.com/quintel/etsource/pull/1105
