### ISSUE TITLE
Find out if we use the correct base load demand

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#876]
In the light of https://github.com/quintel/etmoses/issues/875, I am concerned if we need to refine the base-load demand as well. 

@grdw @antw can you point me to the place where this demand is defined in ETMoses?

**Comment by antw** [comment]
Maybe [DemandAttribute](https://github.com/quintel/etmoses/blob/master/app/models/import/demand_attribute.rb)? That's what we use to import the demand from ETEngine (and convert it to kWh).

**Comment by ChaelKruip** [comment]
In [this line](https://github.com/quintel/etmoses/blob/master/app/models/import/house_builder.rb#L28) the total final demand of electricity is used to scale the base load. This should be replaced with a gquery which only returns electricity for appliances, lighting and cooking.
