### ISSUE TITLE
Storing grey electricity in neighbourhood battery

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#877]
When modelling a neighbourhood battery in the LES Showcase buurtbatterij (link to LES added below), it only stores the energy from the PV panels to prevent congestion and not the grey electricity from the net. 

https://moses.energytransitionmodel.com/testing_grounds/436

**Comment by antw** [comment]
@ChaelKruip I do believe I can fix this, although I will have to test it manually to be sure that the fix doesn't inadvertently break some other aspect of the NB. Unfortunately the local preference ("subnet awareness" / "bottom-up calculation" / whatever else you might call it) features which come with #872 will immediately break it again (in fact, #872 will require it to be reverted).

We could push the fix straight to production, but I can see it remaining broken on beta for some time.

**Comment by ChaelKruip** [comment]
> We could push the fix straight to production, but I can see it remaining broken on beta for some time.

I think that's fine. It is important that @Sanne512 can work with the battery on LIVE. If we can fix it on beta (with the bottom-up calculator) in this sprint, things work out fine. There is no *fundamental* reason for the battery to not work with the bottom-up calculator right?

**Comment by antw** [comment]
> There is no fundamental reason for the battery to not work with the bottom-up calculator right?

Indeed, there is not.

A fix has been pushed to production; the neighbourhood should now take energy from the grid in all situations, provided there is sufficient network capacity. Sorry for the inconvenience @Sanne512.

**Comment by Sanne512** [comment]
Thanks for fixing it!
