### ISSUE TITLE
Add pressure levels asset sheet in front-end

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#878]
There's only one gas topology 'shape' available. The only thing the user can determine is what the attributes of this topology are. The user can determine the volume, capacity (high, low) and loss of every pressure level. The way to do this is through the asset-sheet.

**Comment by ChaelKruip** [comment]
See https://github.com/quintel/etmoses/issues/861#issuecomment-199861250 for the relation between the chosen assets and the volume/capacities.
