### ISSUE TITLE
Some weeks do not show loads with weekly calculations

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#881]
[This LES] shows no loads for the second week of January:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14179516/a7077a02-f75f-11e5-9db7-e7206f85b209.png)

**Comment by grdw** [comment]
Hmm,, I see.. crap. I'm looking into it as we speak.

**Comment by grdw** [comment]
Well I figured out it's a caching problem.. (ofcourse). It turns out it cuts out a piece of 673 array items at the range of 673..1346 . which ofcourse is not possible. It should only do that when it has a full year in cache.
