### ISSUE TITLE
Costs of heat infrastructure: what numbers can we find?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#886]
Quoting email from Wouter Meyers:

From: Wouter Meyers 
Sent: Tuesday, April 12, 2011 15:14
To: Wouter van Lelyveld
Cc: Alexander Wirtz
Subject: Kosten warmtenetten
 
Hi Wouter,          cc. Alex
 
Uit mijn interview met Peter Simoës van het Afvalenergiebedrijf in Amsterdam heb ik wat gegevens over de investeringskosten van warmtenetten zoals zij die hanteren in hun planningen. Zie jij een manier om deze data mee te nemen in het model? Ik weet niet wat de huidige schattingen zijn van de kosten voor het warmtenet, maar dit zijn wel de kosten waarmee gerekend wordt in echte projecten (in Amsterdam) ;-)
 
Er zijn drie onderdelen waarin geïnvesteerd moet worden:
-        Bronnen – warmtebronnen (afvalverbranding, geothermische bronnen, etc) – ca. 10% van totale investering
-        Primaire netwerk – leidingen van bron tot aan distributiepunten – ca. 30-40% van totale investering
-        Secundaire netwerk – leidingen van primaire netwerk naar huizen en gebouwen – ca. 50-60% van totale investering
 
Per huishouden wordt zo’n € 3.500 tot € 4.000 gerekend voor het secundaire netwerk. Als je uitgaat van € 3.500 en 50% van totale investeringen kom je dan op een kostenplaatje van:
-        Bronnen: € 350
-        Primaire net: € 3.150
-        Secundaire net: € 3.500
-        Totaal: € 7.000 per huishouden
 
Eigenlijk kun je de investeringen in de bronnen en het primaire net natuurlijk niet splitsen per huishouden, maar op zich kun je dat als aanname wel doen.
 
Onderhoud en beheer wordt als volgt berekend voor het secundaire netwerk:
Woningen
-        € 80 per jaar onderhoud
-        € 40 per jaar beheer
 
Bedrijven
-        € 3 / kWth / jaar onderhoud
-        € 1 / kWth / jaar beheer
 
Voor bronnen en primaire netwerk wordt onderhoud en beheer berekend als 1% van de totale investeringskosten.
 
Overigens treedt bij het transport van warmte zo’n 25% verlies op, die vooral in het secundaire netwerk zit, waar de leidingen steeds dunner worden en contactoppervlakte met de buitenwereld dus steeds groter.
 
Ik zal deze data trouwens ook nog een keer valideren in een interview met Nuon aan het einde van de maand.

Groeten,
Wouter

**Comment by ChaelKruip** [comment]
@Sanne512 perhaps you can use these numbers as a starting point for your expert meetings?

**Comment by Sanne512** [comment]
The investment costs of heat  networks are strongly dependent on the type of houses or industry connected to the heat network and the area where the heat network is situated: is it a rural, city or semirural area. The costs of the heat network will be clustered in a value per type of house and type of area per meter pipe, we expect it to consist of 3 main types. Besides the investments in the heat network another investment per house is needed to connect the house to the heat network. 

The O&M costs for the pipes are 1% of the investment costs and the O&M costs of the heat exchangers are 2% of the investment costs. This goes for the total heat network: transport and distribution. 

For modelling the business case, the distance from the heat source to the end point is important. To include all costs the chosen end point is the connection to the heat network with the furthest distance to the heat source. 

The deprecation periods of heat networks are determined similar to the depreciation periods of gas infrastructure: for calculating the economic values the financial depreciation periods are used, while the technical depreciation periods are much longer. So in practice the infrastructure is being used after the financial depreciation period has ended. 

The heat experts of Alliander are retreiving these numbers and recalculating them in this format we can use. They expect to deliver this in week 22.
