### ISSUE TITLE
Replace electricity demand for base-load with  gquery

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#888]
As described in [this issue](https://github.com/quintel/etmoses/issues/876), the electricity demand to scale base load with needs to be refined. 

The new query in question lives here: [etsource/gqueries/modules/etmoses/etmoses_electricity_base_load_demand.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/etmoses/etmoses_electricity_base_load_demand.gql)

The demand used to scale base-load with needs to be made dependent on a gquery similar to the demand for space heating and hot water (see https://github.com/quintel/etmoses/blob/master/app/models/import/composite_builder.rb#L8-L9)

**Comment by ChaelKruip** [comment]
What is the status of this @grdw ?

**Comment by grdw** [comment]
This is for any base-load (including buildings?) or just for the technology called `base_load`? I'm asking because they're both build by a separate class in etmoses.

**Comment by ChaelKruip** [comment]
> This is for any base-load (including buildings?)

Good question @grdw!
For buildings, the queries should be different indeed. Please make an issue and assign me to create the queries for the buildings sector (hot water, space heating and electricity).

**Comment by grdw** [comment]
Related: 

- https://github.com/quintel/etmoses/issues/944
- https://github.com/quintel/etmoses/pull/943
