### ISSUE TITLE
The national quantity of each asset needs to be researched

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#889]
If the user opens a new LES, the gas-asset page should  be initialised with the fraction of the national assets which are relevant for this LES.

So, if the LES contains 50% of the connections in the Netherlands, the asset-page of the LES should list half of all assets per pressure level in the Netherlands.

**Comment by Sanne512** [comment]
Just to check if I understand this correctly: the first page of the new LES is a standard topology for gas? Can the user still adjust these figures afterwards, similar to the way technologies are being determined in the LES now?

**Comment by ChaelKruip** [comment]
> Just to check if I understand this correctly: the first page of the new LES is a standard topology for gas? Can the user still adjust these figures afterwards, similar to the way technologies are being determined in the LES now?

Yes. The national average is presented as a default (scaled to the number of connections) but can be adjusted by the user.

**Comment by ChaelKruip** [comment]
@Sanne512 what is the status of this? We are close to the deadline with this.

**Comment by jorisberkhout** [comment]
See https://github.com/quintel/etmoses/issues/870#issuecomment-218094181

**Comment by ChaelKruip** [comment]
Can we close this @jorisberkhout @Sanne512 ?

**Comment by Sanne512** [comment]
Yes, this can be closed
