### ISSUE TITLE
No buffer volume in heat pumps while set to buffering

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#890]
The heat pumps in the LES showcase buurtbatterij are set to buffer instead of boost, but they show no buffer volume. A link to the LES is provided below. Could you explain why? 

https://moses.energytransitionmodel.com/testing_grounds/436

**Comment by ChaelKruip** [comment]
@Sanne512 please assign someone to your ticket so they feel responsible for solving it :smile:

**Comment by Sanne512** [comment]
@ChaelKruip I will do, but who can I choose from?

**Comment by ChaelKruip** [comment]
> @ChaelKruip I will do, but who can I choose from?

<img width="481" alt="screen shot 2016-04-11 at 10 35 24" src="https://cloud.githubusercontent.com/assets/1303760/14421661/235d2fa4-ffd3-11e5-96d1-52fee4670055.png">

For technical bugs: @grdw 
For documentation: @jorisberkhout 
For the rest: @chaelkruip

**Comment by ChaelKruip** [comment]
The buffer volume of the heat pump is given by the volume of the buffer to which it is connected. I know this sentence is confusing so here is an image:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14458578/7e034314-00b2-11e6-9bad-aa644be9aa82.png)

I think we should remove the 'volume' indicator for heat pumps to limit this confusion.

**Comment by ChaelKruip** [comment]
Closing. Please re-open if this does not answer your question.
