### ISSUE TITLE
EDSN profiles

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#891]
There seems to be something wrong with the EDSN profiles: in the LES test EDSN (link included below) at node "Households 2" there are 100 households with 1 kWh yearly use. However the amount of energy use in the LES seems to differ from the amount of energy use in the profiles on which they are based. Could you explain what is happening here? You can clearly see the difference by comparing the Y-axes of the two graphs attached.  

https://moses.energytransitionmodel.com/testing_grounds/439 

![edsn 1a profile in database](https://cloud.githubusercontent.com/assets/17741822/14382042/0d8d21ce-fd8b-11e5-99af-4823b9feabad.png)
![edsn at node households 2](https://cloud.githubusercontent.com/assets/17741822/14382040/0b74e82c-fd8b-11e5-9db4-7200d7be25c2.png)

**Comment by ChaelKruip** [comment]
@Sanne512, the curves shown in the first plot are normalised to have **unity surface area**. So, when you assign 100 units with 1 kWh, the EDSN profile is scaled to have 100 kWh surface area for the whole year. This amounts to a load of 0.01141 kW on average. Although the profile is fluctuating, the average of  0.012 kW seems to be quite in line with the results I see in the LES.

NOTE: 1 kW of load for the whole year corresponds to 8760 kWh (there are 8760 hours in a year).

**Comment by ChaelKruip** [comment]
please re-open if this does not answer your question adequately.
