### ISSUE TITLE
Add a direct link from ETMoses front-end to ETmoses Wiki

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#894]
As discussed in https://github.com/quintel/etmoses/issues/893, a direct link from the ETMoses app to the documentation on the ETMoses Wiki would be very helpful. @MarjoleinSchwachofer and I came up with the suggestion of adding an 'Information' item to the menu bar like we have in the ETM front-end.

<img width="1176" alt="screen shot 2016-04-12 at 12 05 41" src="https://cloud.githubusercontent.com/assets/4669028/14456963/00304248-00a8-11e6-8f66-6554e4b6d7a2.png">

As @ChaelKruip rightfully commented on this suggestion, it would be more in line with the style of the other menu items to turn the 'Information' item into a menu as well. I propose to start with the following menu items:

- Information
  - About Quintel Intelligence (linking to quintel.com)
  - Documentation (linking to github.com/quintel/etmoses/wiki)

We can expand the menu later with things like partners, etc.

What do you think of this idea, @MarjoleinSchwachofer , @dennisschoenmakers , @antw, @AlexanderWirtz and @ChaelKruip ?

**Comment by MarjoleinSchwachofer** [comment]
Good idea. In my view an important item under information is a direct link to how to use section. I think this should be a specific item, as documentation  can also be viewed as background information. What do you think?

**Comment by jorisberkhout** [comment]
> What do you think?

I like it. The Information menu item would then look like this (I also re-arranged the menu items).

- Information
  - How to use (linking to https://github.com/quintel/etmoses/wiki/How-to-use)
  - Documentation (linking to github.com/quintel/etmoses/wiki)
  - About Quintel Intelligence (linking to quintel.com)

Any objections?

**Comment by dennisschoenmakers** [comment]
> Any objections?

No, great idea!

**Comment by jorisberkhout** [comment]
Assigning @grdw as he can implement this a million time quicker than I can ;)

**Comment by jorisberkhout** [comment]
This has been implemented on the Beta-server. Thanks, @grdw !
