### ISSUE TITLE
Should we redirect `How to` item under `Local Energy Solutions` menu to ETMoses Wiki?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmoses#895]
Currently the menu item in the red box below redirects to a separate webpage. The information on that page is now also available on the ETMoses Wiki, where it can be maintained more easily. I would suggest to make the `How to` item redirect to https://github.com/quintel/etmoses/wiki/LES. In addition, I would suggest changing its name to `More information` and make the Wiki page it refers to open in a new tab. Do you agree,  @MarjoleinSchwachofer , @ChaelKruip , @dennisschoenmakers , @antw and @AlexanderWirtz ?

<img width="1187" alt="screen shot 2016-04-12 at 17 57 51" src="https://cloud.githubusercontent.com/assets/4669028/14467106/12fad230-00da-11e6-9561-7097ccd00aba.png">

**Comment by jorisberkhout** [comment]
Part of https://github.com/quintel/etmoses/issues/893.

**Comment by MarjoleinSchwachofer** [comment]
Wouldn't  https://github.com/quintel/etmoses/wiki/LES-overview be a better link to redirect to and in step 1 add a link to the link mentioned above? Or the new items how-to-use/Quick start pages.

**Comment by ChaelKruip** [comment]
> Wouldn't https://github.com/quintel/etmoses/wiki/LES-overview be a better link to redirect to and in step 1 add a link to the link mentioned above? Or the new items how-to-use/Quick start pages.

I think both are good suggestions. [LES]( https://github.com/quintel/etmoses/wiki/LES) is not the most intuitive place to start (mostly my fault).

**Comment by jorisberkhout** [comment]
> Wouldn't https://github.com/quintel/etmoses/wiki/LES-overview be a better link to redirect to and in step 1 add a link to the link mentioned above? Or the new items how-to-use/Quick start pages.

Good point. I think it would be even better to have a close look at the content of the Quick start / LES and LES-overview pages and combine the information that is on these pages. I will do so and come back to this issue once I have done that.

**Comment by jorisberkhout** [comment]
I have merged the old `LES` and `LES-overview` pages into a single page. This page can be found on https://github.com/quintel/etmoses/wiki/Local-Energy-Solutions and I suggest to link the How To menu item to that page.

**Comment by jorisberkhout** [comment]
Assigning @grdw to implement this.

**Comment by jorisberkhout** [comment]
This has been implemented on the Beta-server. Thanks, @grdw !
