### ISSUE TITLE
Colours should not change when toggling in stacked chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#903]
Toggling between 'basic' and 'strategies', the technologies change and so do the colours assigned to them. This should not happen as it is terribly confusing.
Basic:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14491784/2bcb0d1a-017b-11e6-878e-f1654430ea01.png)
Strategies:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14491792/36d400d6-017b-11e6-8124-94270aefadee.png)

**Comment by ChaelKruip** [comment]
This is the LES: https://beta-moses.energytransitionmodel.com/testing_grounds/479

**Comment by grdw** [comment]
It's not really LES specific this issue. This is more that the colours are assigned in the order that the technologies arrive in the front-end. I'll assign a color per technology to avoid further confusion.

**Comment by ChaelKruip** [comment]
> depending in which order they arrive in the front-end

I think you should also fix the order somehow.

**Comment by antw** [comment]
> I think you should also fix the order somehow.

I think @grdw has the right idea: assign a specific colour to each technology. The order in which the technologies appear in the response shouldn't matter.

**Comment by ChaelKruip** [comment]
> The order in which the technologies appear in the response shouldn't matter.

I agree, but now they also take different positions in the legend :cry:

**Comment by antw** [comment]
> I agree, but now they also take different positions in the legend :cry:

A colour *and* a sort order can be defined (perhaps sort the legends alphanumerically?).

All I'm saying is that the order in which things appear in an HTTP response – the order in which they arrive in the front-end – shouldn't matter as this isn't guaranteed to be constant (it can depend on the order in which `Technology` records are saved in the database, the order in which a visitor added techs to an LES, the order in which they're calculated, etc).
