### ISSUE TITLE
Load of full year is not shown if I re-calculate the year while in 'individual' mode

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#905]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/14493720/13b9c5f2-0187-11e6-9a41-14bc41c3aa74.png)

Is this a feature?

**Comment by ChaelKruip** [comment]
This LES: https://beta-moses.energytransitionmodel.com/testing_grounds/479

**Comment by ChaelKruip** [comment]
Also, the selection button for the chart is non-responsive after calculating the full year (it cannot be changed from 'total' back to 'individual' or 'stacked') even if I switch to weekly view...

**Comment by grdw** [comment]
I just tried it locally, the problem I saw was that the resolution is incorrect (I'm getting the charts back in high resolution for the full year when switching to "Full year" from "Individual mode"). 

Did your browser froze by accident or?

**Comment by grdw** [comment]
Upon further investigation I found out that the cache for loads per technology is correctly written but it does not fetch correctly... I'm now seeing to it to fix it.

**Comment by grdw** [comment]
Okay, I found it :sweat_smile: moment please.
