### ISSUE TITLE
[Airbrake] [Production] undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#914]
**Airbrake error:** [#9995](https://quintel.airbrake.io/projects/111227/groups/1666507774947209995)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `downcase' for nil:NilClass ``
**Where:** `market_models#show`
**Occurred at:** Apr 18, 2016 08:13:27 UTC
**First seen at:** Apr 18, 2016 08:13:27 UTC
**Occurrences:** 1 (1 since last deploy on Apr 04, 2016 09:57:19 UTC)

**URL:** [https://moses.energytransitionmodel.com/market_models/190](https://moses.energytransitionmodel.com/market_models/190)
**File:** `[PROJECT_ROOT]/app/helpers/market_models_helper.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/helpers/market_models_helper.rb:29:in format_interaction_foundation
[PROJECT_ROOT]/app/views/market_models/show.html.haml:19:in public_send
[PROJECT_ROOT]/app/views/market_models/show.html.haml:19:in block (2 levels) in _app_views_market_models_show_html_haml___13768061355553179_70327427919640
[PROJECT_ROOT]/app/views/market_models/show.html.haml:13:in each
```

**Comment by grdw** [comment]
Whenever you try to create a market model and submit it empty. It will give this error.
