### ISSUE TITLE
Cumulative investment chart does not show any curve

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#915]
In Chrome:
![screen shot 2016-04-18 at 10 11 23](https://cloud.githubusercontent.com/assets/1303760/14597629/436631ee-054e-11e6-987a-cf0c9c56a7bb.png)

[Link to the LES](http://etmoses.dev/testing_grounds/358/edit)

**Comment by grdw** [comment]
That's logical considering all your building years to be 1960. There's only one total 'dot' and that's on point 'February'. However, it looks a bit odd though.

**Comment by ChaelKruip** [comment]
> That's logical considering all your building years to be 1960. There's only one total 'dot' and that's on point 'February'. However, it looks a bit odd though.

I see! So this will change once we have different build years and lifetimes 👍 

Closing.
