### ISSUE TITLE
Buttons to reset and rescale the assets should move up (between the table and the charts)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#916]
![screen shot 2016-04-18 at 10 20 18](https://cloud.githubusercontent.com/assets/1303760/14597798/49a31e18-054f-11e6-9624-dd87b5374aed.png)

**Comment by ChaelKruip** [comment]
Also, there should be a question mark with extra information about what these buttons do

**Comment by grdw** [comment]
I think the only weird button, that actually needs some explanation is the green one. Also the color green for that button is a bit weird. I think red would be better considering you're destroying your old gas asset list.

**Comment by ChaelKruip** [comment]
> I think the only weird button, that actually needs some explanation is the green one.

I disagree. I find the text 'update gas asset list' of the blue button very confusing. I just updated the list myself, why should I press a button now?
Isn't this button to update the charts instead? If that is its function, why not change the text to "Update gas asset charts"?

**Comment by ChaelKruip** [comment]
Perhaps it makes it less confusing if we would also include the usual 'save' and 'save all and view les' buttons?

@antw @dennisschoenmakers what do you think?

**Comment by grdw** [comment]
> I just updated the list myself, why should I press a button now

Fair enough. The most ideal situation would be ofcourse that it automatically saves (there's already an issue for that). I think renaming it to 'Save' would probably cause less confusion. 

'Save all and  view LES' is a bit weird, because you don't want to visit the 'load' page after you click that button. You want to go to the gas load page - because that makes much more sense.

**Comment by ChaelKruip** [comment]
>  I think renaming it to 'Save' would probably cause less confusion.

👍 

> You want to go to the gas load page - because that makes much more sense.

Perhaps we could add a "Save and view gas-load" button then?

**Comment by grdw** [comment]
> Perhaps we could add a "Save and view gas-load" button then?

Yes. Same functionality - different redirect.

**Comment by grdw** [comment]
I moved the buttons inbetween the table and the charts but I don't think it looks that pretty:

![screen shot 2016-04-18 at 14 27 45](https://cloud.githubusercontent.com/assets/2676542/14604022/be6ae074-0571-11e6-9f53-4e380ba01f6f.png)

**Comment by ChaelKruip** [comment]
> I moved the buttons inbetween the table and the charts but I don't think it looks that pretty:

I think it is fine for now.

Can you rename the green button to: "Save and view gas-load" as well?

Also, I think "Reload gas asset list" should be renamed too. Perhaps "Scale gas assets to number of connections" is a better name? I still think an information item (question mark) would be useful here.

**Comment by grdw** [comment]
> Can you rename the green button to: "Save and view gas-load" as well?

I would if it actually did just that.

> Scale gas assets to number of connections

Yes. Maybe 'Rescale assets to gas connections' .. Because you wipe out all the old data and than create a new asset list.

**Comment by ChaelKruip** [comment]
> I would if it actually did just that.

It doesn't?

> Maybe 'Rescale assets to gas connections'

👍

**Comment by grdw** [comment]
> It doesn't?

Not yet. It doesn't take to much time to fix that though.
