### ISSUE TITLE
[Airbrake] [Staging] No such file or directory @ rb_file_s_mtime - /var/www/etmoses/releases/20160418082917/tmp/networks/staging/490/feature/electricity/49a08c0e397826d795e50f9a6a16b08f35708bd965875a2b22d9bb1db5e25bc6.load.current_week.tmp

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#919]
**Airbrake error:** [#8684](https://quintel.airbrake.io/projects/111227/groups/1666617828971098684)
**Airbrake project:** ETMoses

**Error type:** `Errno::ENOENT`
**Error message:** `` No such file or directory @ rb_file_s_mtime - /var/www/etmoses/releases/20160418082917/tmp/networks/staging/490/feature/electricity/49a08c0e397826d795e50f9a6a16b08f35708bd965875a2b22d9bb1db5e25bc6.load.current_week.tmp ``
**Where:** `testing_grounds#data`
**Occurred at:** Apr 18, 2016 11:52:07 UTC
**First seen at:** Apr 18, 2016 11:52:07 UTC
**Occurrences:** 1 (1 since last deploy on Apr 18, 2016 08:29:35 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/490/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/490/data.json)
**File:** `[PROJECT_ROOT]/app/services/network_cache/validator.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/network_cache/validator.rb:43:in mtime
[PROJECT_ROOT]/app/services/network_cache/validator.rb:43:in block (2 levels) in cache_time
[PROJECT_ROOT]/app/services/network_cache/validator.rb:42:in map
[PROJECT_ROOT]/app/services/network_cache/validator.rb:42:in block in cache_time
```

**Comment by grdw** [comment]
Closing due to duplicate: #1028
