### ISSUE TITLE
Shouldn't different end-points show the same load?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#920]
I thought that the new bottom-up calculator would produce equal load results for equal end-points. For [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/490) the results are quite different for the first and second end-point.

Also, it fails to calculate... 😢

**Comment by antw** [comment]
> Also, it fails to calculate... 

Related to #919. Will look into it shortly.

**Comment by antw** [comment]
> Also, it fails to calculate... 😢

I'll get the core issue resolved, but until then you can temporarily work around this by selecting a different week. 

> I thought that the new bottom-up calculator would produce equal load results for equal end-points. For this LES the results are quite different for the first and second end-point.

None of the three endpoints are identical. They have differing numbers of buildings and heat-pumps. [Check out LES491](https://beta-moses.energytransitionmodel.com/testing_grounds/491) which corrects the differences; the loads are the same on all three endpoints.

**Comment by ChaelKruip** [comment]
>  None of the three endpoints are identical. 

Sorry about that! I think the app broke while I was changing them to be identical...
