### ISSUE TITLE
Better number formatting needed for gas-chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#924]
<img width="272" alt="screen shot 2016-04-19 at 14 10 48" src="https://cloud.githubusercontent.com/assets/1303760/14638654/8e323ad4-0638-11e6-9d16-0dc926efd21a.png">

**Comment by ChaelKruip** [comment]
The numbers being cut off in the above images is not due to cropping 😄

**Comment by grdw** [comment]
No, it's a bad margin. I already fixed it [here](https://github.com/quintel/etmoses/pull/923/files#diff-7205be044d8febf8e4e45168d601bfe7R7)
