### ISSUE TITLE
Weird behaviour of gas-load when P2G is used

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#926]
Sorry to be vague but several things seem to wrong at the same time. 

In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/493) I have built a P2G facility and selected the P2G strategy. In the week of 18 to 24 June, the gas-load on end-point "Households 2" looks different with and without strategies:
<img width="606" alt="screen shot 2016-04-19 at 14 27 31" src="https://cloud.githubusercontent.com/assets/1303760/14639158/40ea5c68-063b-11e6-9adb-615cd92dee9f.png">
This implies/suggests that gas is fed into the network. The stacked chart does not show any feed-in, however:
<img width="1009" alt="screen shot 2016-04-19 at 14 30 56" src="https://cloud.githubusercontent.com/assets/1303760/14639179/6de6ef06-063b-11e6-87d6-686c87931d68.png">

When switching back to the normal load view page, the gas-load for the same end-point looks very(!) different:
<img width="637" alt="screen shot 2016-04-19 at 14 32 19" src="https://cloud.githubusercontent.com/assets/1303760/14639219/a879ae6a-063b-11e6-9277-f6b7877e7b38.png">

including @antw

**Comment by antw** [comment]
> This implies/suggests that gas is fed into the network. The stacked chart does not show any feed-in, however:

P2G is not fed into the new gas network. I'll make that a priority.

**Comment by grdw** [comment]
I still see exactly the same loads. When I switch between gas load and load. Do I have to do it prematurely? Like; not wait until the gas load page is finished?
