### ISSUE TITLE
[Airbrake] [Staging] No route matches {:action=>"gas_load", :controller=>"gas_asset_lists", :id=>nil, :testing_ground_id=>"495"} missing required keys: [:id]

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#934]
**Airbrake error:** [#2102](https://quintel.airbrake.io/projects/111227/groups/1668143265685682102)
**Airbrake project:** ETMoses

**Error type:** `ActionController::UrlGenerationError`
**Error message:** `` No route matches {:action=>"gas_load", :controller=>"gas_asset_lists", :id=>nil, :testing_ground_id=>"495"} missing required keys: [:id] ``
**Where:** `testing_grounds#gas_load`
**Occurred at:** Apr 20, 2016 14:22:54 UTC
**First seen at:** Apr 20, 2016 14:22:53 UTC
**Occurrences:** 2 (2 since last deploy on Apr 20, 2016 14:19:26 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/495/gas_load](https://beta-moses.energytransitionmodel.com/testing_grounds/495/gas_load)
**File:** `[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:219:in raise_generation_error
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:192:in optimized_helper
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:178:in call
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:270:in block (2 levels) in define_url_helper
```

**Comment by antw** [comment]
Closed by 4c44942a.
