### ISSUE TITLE
Rename 'Applied to stakeholder' to .... 

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#935]
We once decided to rename 'Applied to stakeholder' to something a little more convenient. But to be honest I forgot what it was. @ChaelKruip do you remember? Or could maybe explain what that select box says about a market model measure?

Including: @jorisberkhout

**Comment by jorisberkhout** [comment]
Now that @ChaelKruip explained me what is meant by 'Applied to stakeholder' (i.e. it allows you to select at which stakeholder the measure is actually measured), I think that 'Measured at stakeholder' would be better way to describe this. What do you think, @ChaelKruip and @grdw ?

**Comment by ChaelKruip** [comment]
Assigned to @grdw
