### ISSUE TITLE
User profiles for gas

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#937]
What will be the input for the profiles of the natural gas use? Can the user adjust the profiles just as for electricity?

**Comment by ChaelKruip** [comment]
> What will be the input for the profiles of the natural gas use? Can the user adjust the profiles just as for electricity?

Right now. The use of natural gas is implicitly defined by the hot water and space heating profiles. The gas-fired heaters (combi-boilers, hybrid heat pumps etc.) connected to buffers wit these profiles will consume gas. 

Please re-open if this does not answer your question.
