### ISSUE TITLE
Order of series in chart should be based on peak/volume ratio

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#938]
The lowest ratios comprise the 'base loads': they go on the bottom of the chart. The more peaky series go on the top of the chart. 

### Example.

I guess this is also the logic behind the other of technologies from Frauenhofer:

![image](https://cloud.githubusercontent.com/assets/104830/14777288/623adfb0-0acc-11e6-95a0-d989a192a694.png)

As suggested by **Sybren** on our meeting at April 20th 2016.

### Complication
The ratio could vary between scenario's, strategies or in time: so question is: do we want to keep this fixed (so based on average ratios?)

**Comment by ChaelKruip** [comment]
Assigning to @grdw and putting on-hold for now.

**Comment by ChaelKruip** [comment]
Can this be closed @grdw?

**Comment by grdw** [comment]
Yes it can
