### ISSUE TITLE
[Airbrake] [Staging] Cannot interpolate a curve with 673 values to 8760

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#939]
**Airbrake error:** [#5914](https://quintel.airbrake.io/projects/111227/groups/1676764212198095914)
**Airbrake project:** ETMoses

**Error type:** `Market::InvalidInterpolationError`
**Error message:** `` Cannot interpolate a curve with 673 values to 8760 ``
**Where:** `data#price_curve`
**Occurred at:** May 02, 2016 11:51:10 UTC
**First seen at:** May 02, 2016 11:51:10 UTC
**Occurrences:** 1 (1 since last deploy on Apr 21, 2016 14:44:59 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/499/data/price_curve.csv](https://beta-moses.energytransitionmodel.com/testing_grounds/499/data/price_curve.csv)
**File:** `[PROJECT_ROOT]/app/models/market/interpolated_curve.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/market/interpolated_curve.rb:14:in new
[PROJECT_ROOT]/app/models/market/merit_builder.rb:32:in price_curve
[PROJECT_ROOT]/app/controllers/data_controller.rb:10:in price_curve
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in send_action
```

**Comment by grdw** [comment]
My bad (I clicked the download merit order load curves button). But I have no idea how or why this error happened though ...

**Comment by antw** [comment]
I'll take a look into this shortly, but "673 values" suggests to me that something tried to run the market model with weekly – instead of annual – load data.
