### ISSUE TITLE
For buildings we use a gquery to determine the demand. Is this still the correct one?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#944]
See line: https://github.com/quintel/etmoses/blob/master/app/models/import/buildings_builder.rb#L31

The gquery that we use right now is `present_demand_in_source_of_electricity_in_buildings.gql` in [etsource](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_74_source_of_electricity_in_buildings/present_demand_in_source_of_electricity_in_buildings.gql). 

Is this correct for ETMoses?

**Comment by ChaelKruip** [comment]
> Is this correct for ETMoses?

No, because it includes electricity from heating which is explicitly modelled in ETMoses. 

I have pushed a [dedicated gquery](https://github.com/quintel/etsource/commit/692a78e9237a9000e06d7dab490c64e65615b616) to improve this.

Assigning @grdw to use this query.
