### ISSUE TITLE
Neighbourhood battery doesn't distribute electricity

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#945]
The neighbourhood battery does store grey electricity, but it doesn't distribute it afterwards during the winter, which it should. This can be clearly seen in the following LES: 

https://moses.energytransitionmodel.com/testing_grounds/436 

This also happens on the beta server.

**Comment by Sanne512** [comment]
I was wondering if you could give me an indication about how long it takes to fix this? Because I need to finish my LES of the neighbourhood battery this week.

**Comment by antw** [comment]
@Sanne512 Could you describe what you would *expect* to see in this network? It would be especially helpful if you could point to specific times, days, or weeks where the load is different to what you expected.

The battery does appear to discharge in winter – albeit not very much – in response to congestion problems on "MSR1 buurtbatterij en heatpumps". My guess is that the rest of the time, there is sufficient capacity in the network to fulfil the demand of all technologies without needing to discharge the battery (there wouldn't be any point to discharging the battery if it were going to immediately recharge from the HV network).

<img width="555" alt="screen shot 2016-05-04 at 13 16 15" src="https://cloud.githubusercontent.com/assets/4383/15013901/6a66f31a-11fa-11e6-8bfe-eb325dd21974.png">

Perhaps I am misunderstanding the problem?

**Comment by Sanne512** [comment]
@JeroenvdLogt mentioned that I should try reloading the LES, because sometimes the LEsses do not automatically update after something has changed in the programming of ETMoses. So I did that and that led to the above picture you posted, which indeed resembles more what I expected. So that question is solved. 

But now I have another one: I expect the battery to charge when there is congestion. I entered the following specs: 4 neighboorhoud batteries with a volume of 100 kW and reserving 50% for congestion. I expect in the first week they would have 200 kW available for preventing congestion. But in the graph below it shows that on the first day the battery discharges a lot of load causing more congestion instead of preventing it and I don't understand why it does this. Could you explain this? 

![image](https://cloud.githubusercontent.com/assets/17741822/15107247/f4ce46de-15ce-11e6-9dde-2f2548dceddf.png)

**Comment by antw** [comment]
> Could you explain this?

I can't; that seems like a bug. I'm looking into it and will get back to you ASAP.

**Comment by antw** [comment]
@Sanne512 This should now be fixed.

<img width="568" alt="screen shot 2016-05-09 at 14 46 11" src="https://cloud.githubusercontent.com/assets/4383/15115044/d4bde14e-15f4-11e6-87be-1a42922ca026.png">

**Comment by Sanne512** [comment]
It looks good! Thanks for fixing it :)
