### ISSUE TITLE
"Save and view LES button" does not save the changes made

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#946]
After editing the specifications of the technologies in the LES, to save them I clicked the "Save and view LES button" but it did not save the changes made in the technologies. 

This happened while editing the following LES: 

https://moses.energytransitionmodel.com/testing_grounds/436/edit

**Comment by ChaelKruip** [comment]
Possible duplicate of https://github.com/quintel/etmoses/issues/766

**Comment by grdw** [comment]
Is a duplicate of #766 I'll close this issue and all further communication goes there. There's also already an idea to get rid of those two buttons here: https://github.com/quintel/etmoses/issues/776
