### ISSUE TITLE
Residential PV panel has an input capacity

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#948]
The residential PV panels in the LES below show an input capacity of 5 kW that cannot be changed. Why do they have an input capacity? 

https://moses.energytransitionmodel.com/testing_grounds/436/edit 

![pv input capacity](https://cloud.githubusercontent.com/assets/17741822/14982538/5bce5ab4-1137-11e6-9990-981cc0c062e4.PNG)

**Comment by ChaelKruip** [comment]
> Why do they have an input capacity?

The input capacity is shown to inform the user of the possible ration between input and output capacities (efficiency or COP). In the case of solar PV, this attribute is not very informative and could be omitted. We are considering more technology-specific display rules. Hiding the input capacity for PV would be a good idea IMO.

Including @grdw

**Comment by Sanne512** [comment]
@JeroenvdLogt  FYI
