### ISSUE TITLE
Gas storage/LNG

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#951]
I was wondering if gas storage/LNG is included as one of the technologies in ETMoses?

**Comment by ChaelKruip** [comment]
It is possible to store gas in the network by feed-in from the lowest pressure level. 

LNG is not explicitly modelled at the moment. What would you expect an 'LNG technology' to do? Isn't LNG storage (just) compression to even higher pressures?

**Comment by Sanne512** [comment]
LNG is a method to buffer natural gas, but with different efficiencies and costs. So when it's possible to buffer natural gas and edit these specifics LNG is included in ETMoses :)

**Comment by ChaelKruip** [comment]
>  but with different efficiencies and costs

Can you provide these numbers? I think we could include a new type of compressor with the correct efficiency and costs as an alternative for the default compressors.

> and edit these specifics

At the moment, the user cannot edit the specifics of the technologies in the gas-asset matrix.

**Comment by Sanne512** [comment]
@JeroenvdLogt Do you think we have these numbers available at Alliander? Because if we don't have these I would consider it a nice to have and would like to focus my time on other more urgent tasks.

**Comment by ChaelKruip** [comment]
Closing this for the moment. Re-open if relevant again.
