### ISSUE TITLE
[Airbrake] [Staging] No route matches {:action=>"show", :controller=>"business_cases", :id=>nil, :testing_ground_id=>"123"} missing required keys: [:id]

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#954]
**Airbrake error:** [#0996](https://quintel.airbrake.io/projects/111227/groups/1509247091701430996)
**Airbrake project:** ETMoses

**Error type:** `ActionController::UrlGenerationError`
**Error message:** `` No route matches {:action=>"show", :controller=>"business_cases", :id=>nil, :testing_ground_id=>"123"} missing required keys: [:id] ``
**Where:** `testing_grounds#show`
**Occurred at:** May 09, 2016 17:03:41 UTC
**First seen at:** Sep 14, 2015 08:44:33 UTC
**Occurrences:** 2 (1 since last deploy on May 09, 2016 16:13:33 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/123](https://beta-moses.energytransitionmodel.com/testing_grounds/123)
**File:** `[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:219:in raise_generation_error
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:192:in optimized_helper
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:178:in call
[GEM_ROOT]/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:270:in block (2 levels) in define_url_helper
```

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/a271d5e494ace7a03ee51bf8b133675c30c8b31c
