### ISSUE TITLE
For the whole LES, the demand for heat and the different forms of supply need to be shown per time-step 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#964]
A chart similar to gas and electricity would be nice. A stack of production combined with a line for demand would be very useful here:
<img width="641" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://cloud.githubusercontent.com/assets/1303760/15248766/302379f2-191c-11e6-9a66-e8ca085bae9f.png">

The main categories would be:
* Demand (total demand)
* Production: 
  * Heat network (excess heat)
  * Heat network (dispatchable)
  * Decentral production

The decentral production would include all technologies in the households. If possible it would be nice to differentiate between those as well.

**Comment by grdw** [comment]
I have some questions. How would somebody be able to view these charts? Just by clicking on and end-point? Or is this not connected to an end-point at all and does this need to be in a different chart?

**Comment by antw** [comment]
I'll wait for @ChaelKruip to clarify, but at the moment I don't think there is enough data available to the front-end to be able to make this chart possible. The network calculation is going to have to do more book-keeping to properly record exactly which producers were running when, and how much energy was output.

I'd like to know the answers to @grdw's questions too

**Comment by ChaelKruip** [comment]
>  Or is this not connected to an end-point at all and does this need to be on a different page?

Yes. Just like with the gas 'tab', I'd like to have a tab with heat demand/production overview for the whole LES.

> The network calculation is going to have to do more book-keeping to properly record exactly which producers were running when, and how much energy was output.

I think we would like to have access to the following curves:
* total space heating demand (adding all scaled profiles for space heating)
* total hot water demand (adding all scaled profiles for space heating)
* the net load of the buffers (can be positive or negative)
* the production of heat by decentralised technologies (heat pumps, combi boilers etc.)
* the production of heat by the must-run part of the heat network
* the production of heat by the dispatchable part of the heat network
* the deficit of heat (if buffers + production does not match demand)

**Comment by ChaelKruip** [comment]
I present to you probably the ugliest mock-up chart ever:
![20160613_chart_v01_pptx](https://cloud.githubusercontent.com/assets/1303760/16012228/da967d88-3188-11e6-8175-e78e4b28d682.png)
I hope a few things are clear from it though:
* Demand = positive load and stacked
* Supply = negative load and also stacked
* The mismatch between supply and demand is drawn as a production deficit
* Buffers can have positive and negative loads depending on the moment
* We show this in a weekly time-frame

**Comment by antw** [comment]
I'll work on getting this data out of the network calculation. I'll aim to expose it via a Rails action which responds with JSON something like:

```js
{
    "demand": {
      "hot_water": [1, 2, 3, ..., 672],
      "space_heating": [1, 2, 3, ..., 672]
    }
    "supply": {
      "must_run": [1, 2, 3, ..., 672],
      "dispatchable": [1, 2, 3, ..., 672],
      "decentral": [1, 2, 3, ..., 672]
    }
    // positive = charging, negative = discharging
    "buffer_load": [1, 2, -3, -4, ..., 672]
}
```

I *think* that covers all the bases...

**Comment by ChaelKruip** [comment]
> I think that covers all the bases...

Sounds good!

Thinking about it a bit more, I think it would be great if we could show the sources of the heat network separately if possible:
* central heat network (must-run)
* central heat network (dipatchable)
* heat network (geothermal)
* heat network (gas CHP)
* heat network (biogas CHP)
* heat network (biomass CHP)

**Comment by antw** [comment]
> Thinking about it a bit more, I think it would be great if we could show the sources of the heat network separately if possible:

In which case, instead of `must_run` and `dispatchable` "supply" series', we can separate out each technology.

```js
{
    "demand": {
      "hot_water": [1, 2, 3, ..., 672],
      "space_heating": [1, 2, 3, ..., 672]
    }
    "supply": {
      // we can show which are must-run and which are dispatchable using the
      // the legend, labels, and chart colours
      "heat_source_1": [1, 2, 3, ..., 672],
      "heat_source_2": [1, 2, 3, ..., 672],
      "heat_source_3": [1, 2, 3, ..., 672],

      // local = from endpoints, aka "decentral"
      "local": [1, 2, 3, ..., 672]
    }
    // positive = charging, negative = discharging
    "buffer_load": [1, 2, -3, -4, ..., 672]
}
```

**Comment by ChaelKruip** [comment]
Closing as this chart has been merged. Some improvements are listed in https://github.com/quintel/etmoses/issues/1161
