### ISSUE TITLE
Importing the sources from ETE

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#967]
* The user sets a certain percentage of heat-network use in the ETM:
<img width="456" alt="energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://cloud.githubusercontent.com/assets/1303760/15249660/06582c6c-1921-11e6-8d36-a60458eb1288.png">
and
<img width="472" alt="energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://cloud.githubusercontent.com/assets/1303760/15249673/1ed4eb72-1921-11e6-9d42-90f4aae22ee5.png">

* Now, the use must specify how the number of heat exchangers (connections to the heat network) are coupled to buffers.
* Next the user chooses how the heat net is supplied:
<img width="459" alt="energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://cloud.githubusercontent.com/assets/1303760/15249700/3be05c92-1921-11e6-9b9a-c2e152b2b633.png">
 
Note that the heat network can also be supplied with heat from excesses in agriculture, industry and central production! 
* When the user opens the (scaled) ETM scenario in ETMoses, the number of connections is imported as a number of heat-exchangers for space heating and a(nother) number for hot water.

**Comment by ChaelKruip** [comment]
The following technologies need to be imported:

* households_collective_chp_network_gas
* households_collective_chp_wood_pellets
* households_collective_chp_biogas
* households_collective_geothermal
* households_heat_network_connection_steam_hot_water (excess heat/must-run)
* households_heat_network_connection_steam_hot_water (dispatchable)

The subdivision of the latter category (the central heat network) is needed as there are many technologies feeding the central network, some of them must-run (from a heat perspective meaning that they primarily produce electricity and have heat as a by-product), others dispatchable (dedicated to follow the heating demand).

I propose to give a *flat* production profile to the "excess heat/must-run" category. In principle, we can do better because we know the hourly profiles from Merit and could make a weighted average curve but this will be a lot of work with little payoff IMO.

**Comment by ChaelKruip** [comment]
Also, the buildings can be heated with a heat-network so the following additional converters need to be imported:

* buildings_collective_chp_network_gas
* buildings_collective_chp_wood_pellets
* buildings_collective_geothermal
* buildings_chp_engine_biogas

**Comment by ChaelKruip** [comment]
What is the status of this @grdw?

**Comment by grdw** [comment]
> households_heat_network_connection_steam_hot_water (excess heat/must-run)
> households_heat_network_connection_steam_hot_water (dispatchable)

Are not imported. There are two gql's which determine the needed production and capacity and the financial numbers are specified as defaults in ETMoses. It's merged and on beta. Do we still need to use that technology to extract values from it or?

**Comment by ChaelKruip** [comment]
> Do we still need to use that technology to extract values from it or?

No, but they need to become technologies in the technology matrix (heat exchangers) as in:
![20150609_etmoses_sprint3_v11_pptx](https://cloud.githubusercontent.com/assets/1303760/15934422/c98934b8-2e63-11e6-8399-fd819c6a5ebe.png)

**Comment by grdw** [comment]
Are they not the same as https://github.com/quintel/etmoses/issues/973#issuecomment-224853904 ?

**Comment by ChaelKruip** [comment]
> Are you not confusing them with #973 (comment) ?

Yes 😄
