### ISSUE TITLE
Double-counting of hot water and space heating needs to be explained in documentation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#969]
This leads to too high costs for owners of end-points.

**Comment by ChaelKruip** [comment]
@jorisberkhout what is the status of this?

**Comment by ChaelKruip** [comment]
Has this been done @jorisberkhout?

**Comment by jorisberkhout** [comment]
Done with https://github.com/quintel/etmoses/wiki/Technologies/734bfac5c4e18eb0cce7037bce090ac5600c1bfc and https://github.com/quintel/etmoses/wiki/Business-cases/f1789cc91f2ed7f3c6af3216565ef2522c2e9f2e.

Closing.
