### ISSUE TITLE
How should the number of connections to the heat network be determined?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#970]
From the settings in the (scaled) ETM scenario, the number of heat network connections for space heating and hot water are extracted. As with all other heating technologies in the household sector, they are counted twice while in real life, the same connection to the heat network would suffice for both space heating and hot water.

For connections to the heat network, this double counting is even more problematic than for the normal technologies because the `number_of_heat_connections` is one of the 'measures' in the market models. How to deal with this?

Perhaps we can take a maximum of the hot water and space heating connections?

@dennisschoenmakers @jorisberkhout @antw any fresh ideas are welcome here!

**Comment by ChaelKruip** [comment]
> Perhaps we can take a maximum of the hot water and space heating connections?

We decided to do this the same way as with all other heating technologies. We separately take the following 'technologies' into account from ETE:
* households_space_heater_district_heating_steam_hot_water
* households_water_heater_district_heating_steam_hot_water

**Comment by ChaelKruip** [comment]
Although the above works fine for the technology matrix, the `number_of_heat_connections` measure in the Market Model transactions should not be the sum of `households_space_heater_district_heating_steam_hot_water` and `households_water_heater_district_heating_steam_hot_water` because houses typically only pay once for their connection to the heat network.

I propose to take the maximum of heat/hot water connections as the `number_of_heat_connections`.

@Sanne512 @antw @dennisschoenmakers @grdw @jorisberkhout @AlexanderWirtz does that make sense to you as well?

**Comment by antw** [comment]
> Perhaps we can take a maximum of the hot water and space heating connections? [...] I propose to take the maximum of heat/hot water connections as the number_of_heat_connections.

Agreed. I think this makes more sense than using the number of base loads. If you have ten base loads, but only three "Buffer water heating" and five "Buffer space heating" techs, it seems reasonable to say that you have five heat connections, not ten.

**Comment by ChaelKruip** [comment]
>  If you have ten base loads, but only three "Buffer water heating" and five "Buffer space heating" techs, it seems reasonable to say that you have five heat connections, not ten.

I assume you mean `households_space_heater_district_heating_steam_hot_water` instead of ""Buffer space heating" techs" right?
We are talking about the number of connection *to the heat network*. The number of buffers (connected to local heat pumps etc.) might be larger than the number of buffers connected to the network.

**Comment by AlexanderWirtz** [comment]
makes sense to me

**Comment by antw** [comment]
> We are talking about the number of connection to the heat network. The number of buffers (connected to local heat pumps etc.) might be larger than the number of buffers connected to the network.

My bad; I did not realise that. I'll fix this.
