### ISSUE TITLE
[Airbrake] [Staging] no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#975]
**Airbrake error:** [#6726](https://quintel.airbrake.io/projects/111227/groups/1688978065694636726)
**Airbrake project:** ETMoses

**Error type:** `TypeError`
**Error message:** `` no implicit conversion from nil to integer ``
**Where:** `gas_asset_lists#load_summary`
**Occurred at:** May 19, 2016 08:17:12 UTC
**First seen at:** May 19, 2016 08:17:12 UTC
**Occurrences:** 1 (1 since last deploy on May 18, 2016 15:38:56 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/502/gas_asset_lists/11/load_summary](https://beta-moses.energytransitionmodel.com/testing_grounds/502/gas_asset_lists/11/load_summary)
**File:** `[PROJECT_ROOT]/app/models/installed_gas_asset.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:33:in []
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:33:in pressure_level
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:40:in pressure_level_name
[PROJECT_ROOT]/app/models/network/builders/gas_chain/slots.rb:22:in block in initialize
```

**Comment by grdw** [comment]
Closing due to duplicate #976
