### ISSUE TITLE
[Airbrake] [Staging] no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#976]
**Airbrake error:** [#3499](https://quintel.airbrake.io/projects/111227/groups/1688978074452343499)
**Airbrake project:** ETMoses

**Error type:** `TypeError`
**Error message:** `` no implicit conversion from nil to integer ``
**Where:** `gas_asset_lists#gas_load`
**Occurred at:** May 19, 2016 08:17:05 UTC
**First seen at:** May 19, 2016 08:17:05 UTC
**Occurrences:** 1 (1 since last deploy on May 18, 2016 15:38:56 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/502/gas_asset_lists/11/gas_load](https://beta-moses.energytransitionmodel.com/testing_grounds/502/gas_asset_lists/11/gas_load)
**File:** `[PROJECT_ROOT]/app/models/installed_gas_asset.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:33:in []
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:33:in pressure_level
[PROJECT_ROOT]/app/models/installed_gas_asset.rb:40:in pressure_level_name
[PROJECT_ROOT]/app/models/network/builders/gas_chain/slots.rb:22:in block in initialize
```

**Comment by antw** [comment]
I modified the gas asset lists for the affected LESes (see #980). The problem is that a number of assets were assigned `pressure_level_index: null`. I can't seem to recreate this myself.
