### ISSUE TITLE
[Airbrake] [Staging] can't iterate from NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#982]
**Airbrake error:** [#2147](https://quintel.airbrake.io/projects/111227/groups/1689116246763092147)
**Airbrake project:** ETMoses

**Error type:** `TypeError`
**Error message:** `` can't iterate from NilClass ``
**Where:** `gas_asset_lists#calculate_net_present_value`
**Occurred at:** May 19, 2016 12:51:43 UTC
**First seen at:** May 19, 2016 12:51:42 UTC
**Occurrences:** 1 (1 since last deploy on May 18, 2016 15:38:56 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/495/gas_asset_lists/4/calculate_net_present_value](https://beta-moses.energytransitionmodel.com/testing_grounds/495/gas_asset_lists/4/calculate_net_present_value)
**File:** `[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in each
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in each_with_time_with_zone
[PROJECT_ROOT]/app/services/gas_asset_lists/net_present_value_calculator.rb:4:in map
[PROJECT_ROOT]/app/services/gas_asset_lists/net_present_value_calculator.rb:4:in each_with_object
```

**Comment by antw** [comment]
Closed by be89fe21.
