### ISSUE TITLE
Specifying stakeholders gas assets

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#983]
The stakeholders for gas assets can be determined by a dropdown menu. This can differ from the stakeholders that are specified in the electricity topology. In practice this can be the same stakeholder, is this taken into account in the business case?

**Comment by ChaelKruip** [comment]
> In practice this can be the same stakeholder, is this taken into account in the business case?

The cost of a piece of infrastructure is assigned in the business case to the stakeholder selected in the gas-asset list. This cost is added to the other costs for that stakeholder. 

Does that answer your question @Sanne512?

**Comment by Sanne512** [comment]
Yes it does and I have a follow up question: in the market model you can add additional stakeholders that aren't included in the topology. Is it possible to assign gas assets to these new stakeholders?

**Comment by ChaelKruip** [comment]
> Is it possible to assign gas assets to these new stakeholders?

Yes. The only thing which is restricted by not including a stakeholder in the electricity topology is the use of a 'measure' for that stakeholder.
