### ISSUE TITLE
Hide gas cost charts when no assets are installed

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#985]
If the user removes all the gas assets from their LES, it would be nice to hide the blank charts and instead show a message to the effect of "Your LES has no assets!"

![screen shot 2016-05-19 at 14 17 14](https://cloud.githubusercontent.com/assets/4383/15394710/6dcab194-1dcc-11e6-978e-8acd9937c73f.png) ![screen shot 2016-05-19 at 14 17 47](https://cloud.githubusercontent.com/assets/4383/15394720/7a962f3e-1dcc-11e6-8b27-6775ab3f6e25.png)

**Comment by grdw** [comment]
I agree, the same if all the assets are from the same year. Than there's no 'line' only a dot.

**Comment by ChaelKruip** [comment]
This issue is superseded by https://github.com/quintel/etmoses/issues/1319
