### ISSUE TITLE
[Airbrake] [Production] Duplicate entry 'test' for key 'index_load_profiles_on_key'

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#987]
**Airbrake error:** [#2571](https://quintel.airbrake.io/projects/111227/groups/1689902854428932571)
**Airbrake project:** ETMoses

**Error type:** `Mysql2::Error`
**Error message:** `` Duplicate entry 'test' for key 'index_load_profiles_on_key' ``
**Where:** `load_profiles#create`
**Occurred at:** May 20, 2016 14:54:24 UTC
**First seen at:** May 20, 2016 14:54:24 UTC
**Occurrences:** 1 (1 since last deploy on May 09, 2016 13:44:09 UTC)

**URL:** [https://moses.energytransitionmodel.com/load_profiles](https://moses.energytransitionmodel.com/load_profiles)
**File:** `[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in query
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in block in execute
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in block in log
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in instrument
```

**Comment by grdw** [comment]
@antw I think you fixed this one right?

**Comment by antw** [comment]
Oh MySQL, are you kidding me?

```sql
SELECT "test" = "Test"
# => 1
```

Theres a load profile with the key `Test`. Ruby *quite sensibly* recognises that `"test" != "Test"`, hence the uniqueness validation passes. MySQL on the other hand...

![16or0](https://cloud.githubusercontent.com/assets/4383/15535886/19c0d16a-2267-11e6-8264-4e13afc3debf.gif)

**Comment by grdw** [comment]
>  MySQL on the other hand...

Says "peace among worlds"?
