### ISSUE TITLE
[Airbrake] [Staging] undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#988]
**Airbrake error:** [#5565](https://quintel.airbrake.io/projects/111227/groups/1691871607668585565)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `length' for nil:NilClass ``
**Where:** `testing_grounds#data`
**Occurred at:** May 23, 2016 08:05:53 UTC
**First seen at:** May 23, 2016 08:05:53 UTC
**Occurrences:** 1 (1 since last deploy on May 20, 2016 07:33:19 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/504/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/504/data.json)
**File:** `[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/services/testing_ground/tree_sampler.rb:18:in downsample
[PROJECT_ROOT]/app/services/testing_ground/calculator.rb:51:in block (3 levels) in tech_loads
[PROJECT_ROOT]/app/services/testing_ground/calculator.rb:50:in each
[PROJECT_ROOT]/app/services/testing_ground/calculator.rb:50:in map
```

**Comment by grdw** [comment]
I'm closing this one aswell on the basis that it only occurred on one day. Also if I understand correctly, this error implies that there were no loads present to downsample. But as of right now the LES is correctly loading.
