### ISSUE TITLE
Problems with toggling concurrency

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#994]
When was building the following LES: Testen_HvT_topology_buildings_profiles

I had some troubles with toggling concurrency. First I adjust settings of the technology table and after that toggled minimal concurrency for heat buffers. 
1) After that the technology table was much longer than necessary. Many heating technologies had zero units assigned.
2) My previous adjusted settings for buildings and so on where gone.

**Comment by JeroenvdLogt** [comment]
![bug etmoses](https://cloud.githubusercontent.com/assets/7781037/15503914/ab7d4580-21bc-11e6-95b9-b429c549f9c6.JPG)

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by JeroenvdLogt** [comment]
https://moses.energytransitionmodel.com/testing_grounds/478
