### ISSUE TITLE
Names of buildingprofiles in technology table is not displayed correctly

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#995]
In this LES: testing buidingprofiles I am using self uploaded baseload profiles. Although it seems the right profiles are used when looking at the dashboard, the technology table shows EDSN2a profiles to be used.

**Comment by ChaelKruip** [comment]
Please include a link to your LES @JeroenvdLogt

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by JeroenvdLogt** [comment]
https://moses.energytransitionmodel.com/testing_grounds/479
